### ISSUE TITLE
Document need to check for xrandr dependency

### ISSUE THREAD

**Issue by Sovhan** [MultiMC/Launcher#4245]
### Role

I play modded minecraft on Fedora

### Suggestion

Flesh out tar install procedure

### Benefit

Other players will be able to play if X11 is not installed

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I'm running a distro that has no X server installed so xrandr was not installed. this lead to my games not launching with the following stack

```
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:213]: Failed to start Minecraft:
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:245]: java.lang.reflect.InvocationTargetException
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: Caused by: java.lang.ExceptionInInitializerError
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.lang.Class.newInstance(Class.java:442)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:243)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at $wrapper.com.therandomlabs.randompatches.core.RPTransformer.<init>(Unknown Source)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.lang.Class.newInstance(Class.java:442)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:132)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:27:40] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	... 8 more
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: Caused by: net.minecraft.util.ReportedException: Failed to reload configuration category
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at com.therandomlabs.randompatches.repackage.com.therandomlabs.randomlib.TRLUtils.crashReport(TRLUtils.java:183)
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at com.therandomlabs.randompatches.repackage.com.therandomlabs.randomlib.config.TRLCategory.onReload(TRLCategory.java:42)
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at com.therandomlabs.randompatches.repackage.com.therandomlabs.randomlib.config.ConfigManager.writeToDisk(ConfigManager.java:160)
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at com.therandomlabs.randompatches.repackage.com.therandomlabs.randomlib.config.ConfigManager.reloadFromConfig(ConfigManager.java:144)
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at com.therandomlabs.randompatches.repackage.com.therandomlabs.randomlib.config.ConfigManager.reloadFromDisk(ConfigManager.java:93)
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at com.therandomlabs.randompatches.repackage.com.therandomlabs.randomlib.config.ConfigManager.register(ConfigManager.java:86)
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at com.therandomlabs.randompatches.core.RPTransformer.<clinit>(RPTransformer.java:18)
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	... 24 more
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: Caused by: java.lang.reflect.InvocationTargetException
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 	at com.therandomlabs.randompatches.repackage.com.therandomlabs.randomlib.config.TRLCategory.onReload(TRLCategory.java:40)
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 	... 29 more
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: Caused by: java.lang.ExceptionInInitializerError
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at com.therandomlabs.randompatches.config.RPConfig$Window.onReloadClient(RPConfig.java:396)
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	... 34 more
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:951)
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
[18:27:40] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	... 35 more
[18:27:40] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[18:27:40] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[18:27:40] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[18:27:40] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[18:27:40] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[18:27:40] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:973)
[18:27:40] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
```

the "org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes" line gave me the key to be able to lauch the game after installing xrandr, and verifying that xrandr -q was outputing something; a SO post had the same problem on a code snipet ^^: https://stackoverflow.com/questions/58939641/lwjgl-crashing-at-startup

adding a line in the dependencies like you did for qt should suffice to avoid this problem.

**Comment by kb-1000** [comment]
Fedora does have Xorg preinstalled, unless that changed with the 35 release (which I believe I'd have heard of). Selected by default is Wayland though, with Xwayland.
It just doesn't have the xrandr tool preinstalled.
There's an RPM package in the sourcetree, but unfortunately it's not published on [multimc.org](https://multimc.org/#Download) at the moment.
I have an unofficial release of that package [on copr]( https://copr.fedorainfracloud.org/coprs/kb1000/multimc/) though.
The RPM solves that problem by simply depending on xrandr.

**Comment by JJTech0130** [comment]
However, it might be nice to specify this somewhere. There are other platforms on which I have used MultiMC that don't have `xrandr` installed, and it took me a while to figure out what was wrong. (That error message isn't very helpful 😆).

**Comment by Sovhan** [comment]
oh I missed your packages on copr, I only found those under ve srakitnican, which have the 3.6 version of multimc I think. Thanks for the unofficial repo!
