### ISSUE TITLE
Fails to launch mods Manjaro Kde AMD64

### ISSUE THREAD

**Issue by SuddenPineapple** [MultiMC/Launcher#4258]
Bug report by user here, I could not decide the proper repo to put this in so here it is. I can't get any mods to work but normal versions of Minecraft work. I'm on 0.6.13 with the curse forge support from the AUR.  I've tried Forge 36.2.0 and Fabric 0.11.7 It's Minecraft 1.16.5 with the Forge Labs Kingdom of Daldar pack. Error log: https://paste.ee/p/xUlkJ

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by SuddenPineapple** [comment]
It happens with all mod packs
MultiMC version: 0.6.13-custom


Launched instance in online mode
Authentication server is online

authserver.mojang.com resolves to:
    [143.204.28.72]

session.minecraft.net resolves to:
    [34.206.109.4, 52.44.210.220, 34.192.50.106]

textures.minecraft.net resolves to:
    [65.8.236.66, 65.8.236.28, 65.8.236.19, 65.8.236.121]

api.mojang.com resolves to:
    [65.8.235.88]


Minecraft folder is:
/home/rileyj/.local/share/multimc/instances/FTB Ultimate/minecraft


Java path is:
/usr/lib/jvm/java-16-openjdk/bin/java


Checking Java version...
Java is version 16.0.2, using 64-bit architecture, from N/A.


AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
Advanced Micro Devices, Inc. [AMD/ATI] Picasso (rev c2)

Subsystem: Lenovo Device 3808

Kernel driver in use: amdgpu

OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.2.3

Main Class:
  

Native path:
  /home/rileyj/.local/share/multimc/instances/FTB Ultimate/natives

Traits:
traits legacyFML
traits texturepacks
traits legacyLaunch

Libraries:
  /home/rileyj/.local/share/multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/rileyj/.local/share/multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/rileyj/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/rileyj/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/rileyj/.local/share/multimc/instances/FTB Ultimate/minecraft/bin/minecraft.jar

Native libraries:
  /home/rileyj/.local/share/multimc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/rileyj/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar

Mods:
  [✔️] advancedmachines
  [✔️] advancedsolarpanel
  [✔️] appeng-rv9-i
  [✔️] BiblioCraft[v1.1.2]
  [✔️] buildcraft
  [✔️] ChargePads
  [✔️] ChickenChunks 1.3.1.2
  [✔️] CoFHCore
  [✔️] computercraft
  [✔️] ee3
  [✔️] EnderStorage
  [✔️] extrabees-1.5.0.6b
  [✔️] ExtrabiomesXL-universal-1.4.7-3.11.0
  [✔️] factorization
  [✔️] FlatBedrock
  [✔️] forestry
  [✔️] forgeirc
  [✔️] gravisuite
  [✔️] GravityGun1.4.7v2
  [✔️] GregTech
  [✔️] IC2
  [✔️] IC2NuclearControl
  [✔️] immibis-core-52.4.6
  [✔️] InvTweaks
  [✔️] IronChest
  [✔️] legacyjavafixer-1.0
  [✔️] MineFactoryReloaded
  [✔️] modularforcefieldsystem
  [✔️] ModularPowersuits
  [✔️] mystcraft-uni-1.4.7-0.10.1.00
  [✔️] MystNEI-Plugin-1.1
  [✔️] neiplugins
  [✔️] neipluginsredpower
  [✔️] NetherOres
  [✔️] obsidiplates-universal-1.2.0.3
  [✔️] omnitools
  [✔️] petrogen
  [✔️] PortalGun1.4.7v5
  [✔️] PowerConverters
  [✔️] railcraft
  [✔️] redpowercompat
  [✔️] redpowercore
  [✔️] redpowerdigital
  [✔️] redpowermechanical
  [✔️] secretroomsmod
  [✔️] soulshards
  [✔️] StevesCarts
  [✔️] Thaumcraft
  [✔️] thaumicbees
  [✔️] thermalexpansion
  [✔️] tubestuff
  [✔️] TwilightForest
  [✔️] voxelcommon
  [✔️] voxelMap
  [✔️] VoxelMenu
  [📁] VoxelModPack (folder)
  [✔️] voxelpacket
  [✔️] voxelplayer
  [✔️] wirelessredstoneaddons
  [✔️] wirelessredstonecore
  [✔️] wirelessredstoneredpower
  [✔️] XReliquary
  [✔️] xycraft

Core Mods:
  [✔️] CodeChickenCore
  [✔️] miscperipherals-3.1c
  [✔️] NotEnoughItems
  [✔️] PowerCrystalsCore
  [✔️] VanillaNeiFix_mc147_1.0

Jar Mods:
  forge-1.4.7-6.6.2.534-universal.jar
  liteloader (d03f885c-e9b2-441b-accd-72f22e456ad3.jar)

Params:
  

Window size: 854 x 480

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -Xms512m, -Xmx4024m, -Duser.language=en]


Minecraft process ID: 8763


Using onesix launcher.

Launching with applet wrapper...
Applet wrapper failed:
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')

Falling back to using main class.
	at cpw.mods.fml.relauncher.FMLRelauncher.<init>(FMLRelauncher.java:48)
	at cpw.mods.fml.relauncher.FMLRelauncher.instance(FMLRelauncher.java:40)
	at cpw.mods.fml.relauncher.FMLRelauncher.appletEntry(FMLRelauncher.java:212)
	at net.minecraft.client.MinecraftApplet.init(MinecraftApplet.java:25)
	at net.minecraft.Launcher.init(Launcher.java:109)
	at org.multimc.LegacyFrame.start(LegacyFrame.java:130)
	at org.multimc.onesix.OneSixLauncher.legacyLaunch(OneSixLauncher.java:131)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:240)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Failed to invoke the Minecraft main class:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.legacyLaunch(OneSixLauncher.java:146)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:240)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
Exiting with -1
	at cpw.mods.fml.relauncher.FMLRelauncher.<init>(FMLRelauncher.java:48)
	at cpw.mods.fml.relauncher.FMLRelauncher.instance(FMLRelauncher.java:40)
	at cpw.mods.fml.relauncher.FMLRelauncher.handleClientRelaunch(FMLRelauncher.java:26)
	at net.minecraft.client.Minecraft.main(Minecraft.java:2243)
	... 8 more
Process exited with code 255.
Clipboard copy at: 18 Nov 2021 13:11:12 -0700

**Comment by jotoho** [comment]
@SuddenPineapple 

Still not MultiMC's problem. You're trying to run a MC 1.4.7 modpack using a forge version that came out 9+ years ago and expect it to run on a JRE version from earlier this year. It is well known that modding MC versions older than 1.17 requires using Java 8 specifically.

P.S.: Use something like GitHub Gist or Pastebin for long logs in the future.
