### ISSUE TITLE
Minecraft not booting after Forge Installed

### ISSUE THREAD

**Issue by kdoub05** [MultiMC/Launcher#4263]
### Operating System

Windows, macOS, Linux

### Description of bug

Instance will not start after forge installed. I would expect for it to just boot.

### Steps to reproduce

Create a instance.
Add Forge (any version)
Then it may not boot

### Suspected cause

Forge may be the problem

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kb-1000** [comment]
Please reproduce the issue and provide the logs. We cannot diagnose anything without them.

**Comment by kdoub05** [comment]
Log: MultiMC version: 0.6.13-2517


Launched instance in online mode
Authentication server is online

authserver.mojang.com resolves to:
    [99.84.164.75]

session.minecraft.net resolves to:
    [54.144.25.180, 52.20.216.23, 54.80.155.214]

textures.minecraft.net resolves to:
    [99.84.160.74, 99.84.160.63, 99.84.160.11, 99.84.160.99]

api.mojang.com resolves to:
    [13.249.91.171]


Minecraft folder is:
C:/Users/kdoub/MultiMC/instances/forgenotwork/.minecraft


Java path is:
C:/Program Files/Eclipse Foundation/jdk-16.0.2.7-hotspot/bin/javaw.exe


Checking Java version...
Java is version 16.0.2, using 64-bit architecture, from Eclipse Foundation.


Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/kdoub/MultiMC/instances/forgenotwork/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/kdoub/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/kdoub/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/kdoub/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/kdoub/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/kdoub/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/kdoub/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/kdoub/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/kdoub/MultiMC/libraries/com/mojang/patchy/1.2.3/patchy-1.2.3.jar
  C:/Users/kdoub/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/kdoub/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/kdoub/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/kdoub/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/kdoub/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/kdoub/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/kdoub/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/kdoub/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/kdoub/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/kdoub/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/kdoub/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/kdoub/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/kdoub/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/kdoub/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/kdoub/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  C:/Users/kdoub/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/kdoub/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/kdoub/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/kdoub/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/kdoub/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/kdoub/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar
  C:/Users/kdoub/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.11.2/log4j-core-2.11.2.jar
  C:/Users/kdoub/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/kdoub/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/1.5.3/ForgeWrapper-1.5.3.jar
  C:/Users/kdoub/MultiMC/libraries/net/minecraftforge/forge/1.16.5-36.1.0/forge-1.16.5-36.1.0-launcher.jar
  C:/Users/kdoub/MultiMC/libraries/org/ow2/asm/asm/9.0/asm-9.0.jar
  C:/Users/kdoub/MultiMC/libraries/org/ow2/asm/asm-commons/9.0/asm-commons-9.0.jar
  C:/Users/kdoub/MultiMC/libraries/org/ow2/asm/asm-tree/9.0/asm-tree-9.0.jar
  C:/Users/kdoub/MultiMC/libraries/org/ow2/asm/asm-util/9.0/asm-util-9.0.jar
  C:/Users/kdoub/MultiMC/libraries/org/ow2/asm/asm-analysis/9.0/asm-analysis-9.0.jar
  C:/Users/kdoub/MultiMC/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar
  C:/Users/kdoub/MultiMC/libraries/cpw/mods/grossjava9hacks/1.3.0/grossjava9hacks-1.3.0.jar
  C:/Users/kdoub/MultiMC/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  C:/Users/kdoub/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/kdoub/MultiMC/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  C:/Users/kdoub/MultiMC/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  C:/Users/kdoub/MultiMC/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar
  C:/Users/kdoub/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/kdoub/MultiMC/libraries/com/electronwill/night-config/core/3.6.3/core-3.6.3.jar
  C:/Users/kdoub/MultiMC/libraries/com/electronwill/night-config/toml/3.6.3/toml-3.6.3.jar
  C:/Users/kdoub/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  C:/Users/kdoub/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  C:/Users/kdoub/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/kdoub/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/kdoub/MultiMC/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar
  C:/Users/kdoub/MultiMC/libraries/net/minecraftforge/nashorn-core-compat/15.1.1.1/nashorn-core-compat-15.1.1.1.jar
  C:/Users/kdoub/MultiMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  C:/Users/kdoub/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/kdoub/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/kdoub/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/kdoub/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/kdoub/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/kdoub/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/kdoub/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/kdoub/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/Users/kdoub/MultiMC/instances/forgenotwork/.minecraft --assetsDir C:/Users/kdoub/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 36.1.0 --fml.mcVersion 1.16.5 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20210115.111550

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms409m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 16712


Using onesix launcher.

2021-11-21 06:24:24,814 main WARN Advanced terminal features are not available in this environment
[06:24:25] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Teyg456, --version, MultiMC5, --gameDir, C:/Users/kdoub/MultiMC/instances/forgenotwork/.minecraft, --assetsDir, C:/Users/kdoub/MultiMC/assets, --assetIndex, 1.16, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.1.0, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --width, 854, --height, 480]
[06:24:25] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 16.0.2 by Eclipse Foundation
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	... 8 more
Caused by: java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x23529fee) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x23529fee
	at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:41)
	at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
	at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:41)
	at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
	at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
	at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
	at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	... 13 more
Exiting with -1
Process exited with code -1.
Clipboard copy at: 21 Nov 2021 06:24:32 -0600

**Comment by kdoub05** [comment]
Video: https://youtu.be/NaAi1uJoXVI

**Comment by phit** [comment]
use java 8 for anything older than 1.17
