### ISSUE TITLE
The versions crashed while trying to download a new version

### ISSUE THREAD

**Issue by PrierMC** [MultiMC/Launcher#4267]
### Description of bug

When I Tried to download the new versions multimc crashed . I tried it with different kinds of java like 1.8 and 1.16 but with all of these things , it crashed again . That is funny that i could download all versions i wanted but from few days ago , it crashed and it didnt download any versions and said in the last of the log :Failed to find Minecraft main class:
java.lang.ClassNotFoundException: io.github.zekerzhayard.forgewrapper.installer.Main
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:185)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with code -1.

### Steps to reproduce

![Screenshot (254)](https://user-images.githubusercontent.com/94781443/142756605-265ff02d-61c4-4494-a5cd-8be16ee41b09.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
Could you provide some reproduction steps?

**Comment by phit** [comment]
update MultiMC to the latest dev version, this has been fixed
