### ISSUE TITLE
Game Crashes When Starting Game

### ISSUE THREAD

**Issue by StereoMadnessss** [MultiMC/Launcher#4287]
### Operating System

macOS

### Description of bug

What was expected: game would launch normally

What happened: This:
[17:19:48] [Render thread/INFO]: [STDERR]: Failed to start Minecraft:
[17:19:48] [Render thread/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
[17:19:48] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:19:48] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[17:19:48] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:19:48] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[17:19:48] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[17:19:48] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[17:19:48] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[17:19:48] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[17:19:48] [Render thread/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[17:19:48] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:236)
[17:19:48] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
[17:19:48] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
[17:19:48] [Render thread/INFO]: [STDERR]: 	... 8 more
[17:19:48] [Render thread/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[17:19:48] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:19:48] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[17:19:48] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:19:48] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[17:19:48] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
[17:19:48] [Render thread/INFO]: [STDERR]: 	... 10 more
[17:19:48] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.glfw.GLFW
[17:19:48] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.platform.GLX.getOpenGLVersionString(GLX.java:38)
[17:19:48] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.getApiDescription(RenderSystem.java:600)
[17:19:48] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_6396.method_37123(class_6396.java:65)
[17:19:48] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_37274(class_310.java:2418)
[17:19:48] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_22681(class_310.java:2412)
[17:19:48] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:187)
[17:19:48] [Render thread/INFO]: [STDERR]: 	... 15 more
[17:19:48] [Render thread/INFO]: [STDOUT]: Exiting with -1
Process exited with code 255.

### Steps to reproduce

Make a new instance on build 2929 of mmc and launch it on MacOS.

### Suspected cause

The developer build broke. That I was using.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by StereoMadnessss** [comment]
this is 1.17.1

**Comment by StereoMadnessss** [comment]
with optifabric

**Comment by StereoMadnessss** [comment]
it worked before but now does not. a fact is that all of my instances do not work.

**Comment by StereoMadnessss** [comment]
confirmed that it is mmc's issue because I launched the exact same instance on the Minecraft launcher by porting 1.17.1-fabric 0.11.7 and it launched normally.

**Comment by peterix** [comment]
Did you enable this?
![image](https://user-images.githubusercontent.com/203326/143796237-e08649f9-3d1a-4169-8654-4ec81c656b61.png)

This is only doable on Linux, really. Or if you know exactly what you are doing.

**Comment by StereoMadnessss** [comment]
oops

**Comment by StereoMadnessss** [comment]
I thought it would work better

**Comment by StereoMadnessss** [comment]
mistakes

**Comment by peterix** [comment]
Ah well. It's there to work around some bugs in the GLFW shipped by Mojang, IF you have a version of it installed as part of your system.

macOS and Windows generally don't ship GLFW.

**Comment by peterix** [comment]
You could still install it manually, somehow. But yeah, that's more of an advanced thing :)
