### ISSUE TITLE
MultiMC doesn't download natives

### ISSUE THREAD

**Issue by SorestForest** [MultiMC/Launcher#4289]
### Operating System

Windows

### Description of bug

Just starting minecraft and it crashes because some natives aren't downloaded.

Crash log:
[11:51:35] [Render thread/INFO]: Failed to find module info for D:\Рабочий Стол\portables\MultiMC\instances\1.18-rc4\natives\jemalloc.dll
com.sun.jna.platform.win32.Win32Exception: Указанный тип ресурса в файле образа отсутствует.
	at aiz.a(SourceFile:62) ~[minecraft-1.18-rc4-client.jar:?]
	at aiz.a(SourceFile:48) ~[minecraft-1.18-rc4-client.jar:?]
	at aiz.b(SourceFile:132) ~[minecraft-1.18-rc4-client.jar:?]
	at r.a(SourceFile:84) [minecraft-1.18-rc4-client.jar:?]
	at aiz.a(SourceFile:131) [minecraft-1.18-rc4-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:205) [minecraft-1.18-rc4-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

### Steps to reproduce

1. Start minecraft

### Suspected cause

MultiMC doesn't downloaded natives for minecraft and it can't start.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
please provide the full log

**Comment by SorestForest** [comment]
re-installed multimc and it worked. srry for distrubticing
