### ISSUE TITLE
Uploading screenshot to imgur crashes multimc without error in log

### ISSUE THREAD

**Issue by ImperatorStorm** [MultiMC/Launcher#4299]
### Operating System

Linux

### Description of bug

Attempting to [upload a screenshot to imgur via the "Screenshots" menu](https://user-images.githubusercontent.com/30777770/144520590-0777e8a3-3f20-46f8-9115-9b7adc134753.png) causes multimc to crash without any obvious errors.

[MultiMC-0.log](https://github.com/MultiMC/Launcher/files/7645780/MultiMC-0.log)

Using dev branch on [`multimc-bin`](https://aur.archlinux.org/packages/multimc-bin) on the AUR.

### Steps to reproduce

instance settings -> "Screenshots" -> select screenshot -> "Upload" -> silently crashes

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by NewoIsTaken** [comment]
I have some more information [here](https://paste.ee/p/FygcO#5lvqXv2tgxc4ohE00mF9QKlASaLCU3aS).
Specifically:
```
terminate called after throwing an instance of 'QString'
/usr/bin/multimc: line 23: 31517 Aborted                 (core dumped) ./MultiMC "$@"
```

**Comment by ImperatorStorm** [comment]
stacktrace from `gdb`:

```
(gdb) backtrace
#0  0x00007ffff5d2cd22 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff5d16862 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff60b6802 in __gnu_cxx::__verbose_terminate_handler () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff60c2c8a in __cxxabiv1::__terminate (handler=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00007ffff60c2cf7 in std::terminate () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x00007ffff60c2f8e in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0xc89790 <typeinfo for QString>, dest=0x521570 <QString::~QString()>)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x000000000057aaba in NetJob::start() ()
#7  0x000000000059f519 in ProgressDialog::execWithTask(Task*) ()
#8  0x000000000079a72d in ScreenshotsPage::on_actionUpload_triggered() ()
#9  0x00000000005d3dd5 in ScreenshotsPage::qt_metacall(QMetaObject::Call, int, void**) ()
#10 0x00007ffff6523517 in ?? () from /usr/lib/libQt5Core.so.5
#11 0x00007ffff7369203 in QAction::triggered(bool) () from /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff736bf18 in QAction::activate(QAction::ActionEvent) () from /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff65237cb in ?? () from /usr/lib/libQt5Core.so.5
#14 0x00007ffff74675e3 in QAbstractButton::clicked(bool) () from /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff746786c in ?? () from /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff7469474 in ?? () from /usr/lib/libQt5Widgets.so.5
#17 0x00007ffff7469695 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
#18 0x00007ffff756761b in QToolButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
#19 0x00007ffff73b30be in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#20 0x00007ffff736fd62 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#21 0x00007ffff7377ac9 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#22 0x00007ffff64ec41a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#23 0x00007ffff737657b in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/libQt5Widgets.so.5
#24 0x00007ffff73cca84 in ?? () from /usr/lib/libQt5Widgets.so.5
#25 0x00007ffff73cfdb5 in ?? () from /usr/lib/libQt5Widgets.so.5
#26 0x00007ffff736fd62 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#27 0x00007ffff64ec41a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#28 0x00007ffff68c51f0 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#29 0x00007ffff689a7d5 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#30 0x00007ffff2752fcc in ?? () from /usr/lib/libQt5XcbQpa.so.5
#31 0x00007ffff4efe4dc in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#32 0x00007ffff4f52799 in ?? () from /usr/lib/libglib-2.0.so.0
#33 0x00007ffff4efbbc1 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#34 0x00007ffff6545046 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#35 0x00007ffff64ead8c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#36 0x00007ffff64f32f4 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#37 0x0000000000512292 in main ()
```
