### ISSUE TITLE
java won't work

### ISSUE THREAD

**Issue by tofjapon** [MultiMC/Launcher#4313]
Hi i can play Minecraft from the Minecraft launcher but when i try with the MultiMc launcher i get this error : 

Java path is:
/usr/bin/java

Checking Java version...
Could not start java:
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.IllegalArgumentException: Error decoding percent encoded characters
	at java.base/sun.net.www.ParseUtil.decode(ParseUtil.java:218)
	at java.base/jdk.internal.loader.FileURLMapper.getPath(FileURLMapper.java:64)
	at java.base/jdk.internal.loader.FileURLMapper.exists(FileURLMapper.java:73)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.getJarFile(URLClassPath.java:821)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:769)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:762)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:761)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.<init>(URLClassPath.java:735)
	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:499)
	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:482)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:481)
	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:449)
	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:318)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:757)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:780)
	at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:675)

Check your MultiMC Java settings.

Thanks a lot for any help. 
Kind of beginner here

**Comment by phit** [comment]
please provide the full log using the Upload button in MultiMC https://github.com/MultiMC/Launcher/wiki/Minecraft-Logs#usage

**Comment by tofjapon** [comment]
Hi and thank you for your help ! 

https://paste.ee/p/vbTja

Thanks ! 

Chris

**Comment by phit** [comment]
remove the special characters from the path you keep MultiMC in, Java does not like them

**Comment by tofjapon** [comment]
﻿
﻿
Good morning ! 

Thank you so much. I did it and it’s working now. 

Awesome application. And awesome service. 

Have a nice day 

Best regards, 
Chris

**Comment by tofjapon** [comment]
Thank you so much it worked 

Chris
