### ISSUE TITLE
Switching between JDK 17 and JRE 1.8

### ISSUE THREAD

**Issue by CasperOng** [MultiMC/Launcher#4319]
### Operating System

Windows

### Description of bug

Nah, IDK how to write this thing but my Minecraft just won't work
Basically, when I want to play Minecraft 1.18 I will need to change the java version to Java JDK 17 but if I use java 17 to play 1.8.9 this error popped up

`Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1.
`

elif I use jre or jdk 1.8.0. I can start Minecraft 1.8.9 normally. However, the 1.18 Minecraft just needs to have a newer version of JRE or JDK.

So HOW CAN I FUCKING FIX THIS SHIT BY USING JUST ONE VERSION OF JRE OR JDK I WON'T CARE ABOUT THE JDK 17 OR JRE 1.8. I JUST DONT WANT TO SWITCH BETWEEN DIFFERENT VERSION OF JAVA

### Steps to reproduce

/

### Suspected cause

/

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you need both, you can configure java versions in the instance settings so you don't need to switch around all the time
java 8 for anything older than 1.16, java 17 for anything newer

https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#set-instance-java-installation

**Comment by CasperOng** [comment]
Holy JESUS DAMN OK I WILL TAKE IT
