### ISSUE TITLE
Failed to run Forge 1.16.5 caused by ForgeWrapper 1.5.4

### ISSUE THREAD

**Issue by Nesquate** [MultiMC/Launcher#4335]
### Operating System

Linux

### Description of bug

Hello MultiMC Team,

Recently my friend want to play Cave Factory (Forge modpack), but he can't run any more.

I tried to solve his problem and I found even I install forge 1.16.5 only and no any other mods, I still can't open Minecraft.

Logs : 
```
MultiMC version: 0.6.14-develop-3011


Launched instance in online mode

authserver.mojang.com resolves to:
    [13.227.55.75]

session.minecraft.net resolves to:
    [52.70.238.65, 3.211.245.5, 23.23.220.104]

textures.minecraft.net resolves to:
    [13.227.66.60, 13.227.66.6, 13.227.66.93, 13.227.66.69]

api.mojang.com resolves to:
    [54.192.16.140]


Minecraft folder is:
/home/nesquate/.local/share/multimc/instances/1.16.5/.minecraft


Java path is:
/usr/lib64/jvm/java-17-openjdk/bin/java


Checking Java version...
Java is version 17.0.1, using 64-bit architecture, from N/A.


AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx
Advanced Micro Devices, Inc. [AMD/ATI] Picasso (rev c1)

Subsystem: ASUSTeK Computer Inc. Device 18f1

Kernel driver in use: amdgpu

OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.2.5

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  /home/nesquate/.local/share/multimc/instances/1.16.5/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  /home/nesquate/.local/share/multimc/libraries/com/mojang/patchy/1.2.3/patchy-1.2.3.jar
  /home/nesquate/.local/share/multimc/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /home/nesquate/.local/share/multimc/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /home/nesquate/.local/share/multimc/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /home/nesquate/.local/share/multimc/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  /home/nesquate/.local/share/multimc/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  /home/nesquate/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/nesquate/.local/share/multimc/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  /home/nesquate/.local/share/multimc/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /home/nesquate/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /home/nesquate/.local/share/multimc/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /home/nesquate/.local/share/multimc/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /home/nesquate/.local/share/multimc/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  /home/nesquate/.local/share/multimc/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  /home/nesquate/.local/share/multimc/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /home/nesquate/.local/share/multimc/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  /home/nesquate/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/nesquate/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/nesquate/.local/share/multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/nesquate/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/nesquate/.local/share/multimc/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  /home/nesquate/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.15.0/log4j-api-2.15.0.jar
  /home/nesquate/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.15.0/log4j-core-2.15.0.jar
  /home/nesquate/.local/share/multimc/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  /home/nesquate/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  /home/nesquate/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  /home/nesquate/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  /home/nesquate/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  /home/nesquate/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  /home/nesquate/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  /home/nesquate/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  /home/nesquate/.local/share/multimc/libraries/io/github/zekerzhayard/ForgeWrapper/1.5.4/ForgeWrapper-1.5.4.jar
  /home/nesquate/.local/share/multimc/libraries/net/minecraftforge/forge/1.16.5-36.2.20/forge-1.16.5-36.2.20-launcher.jar
  /home/nesquate/.local/share/multimc/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  /home/nesquate/.local/share/multimc/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  /home/nesquate/.local/share/multimc/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  /home/nesquate/.local/share/multimc/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  /home/nesquate/.local/share/multimc/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  /home/nesquate/.local/share/multimc/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar
  /home/nesquate/.local/share/multimc/libraries/cpw/mods/grossjava9hacks/1.3.3/grossjava9hacks-1.3.3.jar
  /home/nesquate/.local/share/multimc/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  /home/nesquate/.local/share/multimc/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  /home/nesquate/.local/share/multimc/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  /home/nesquate/.local/share/multimc/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  /home/nesquate/.local/share/multimc/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar
  /home/nesquate/.local/share/multimc/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  /home/nesquate/.local/share/multimc/libraries/com/electronwill/night-config/core/3.6.3/core-3.6.3.jar
  /home/nesquate/.local/share/multimc/libraries/com/electronwill/night-config/toml/3.6.3/toml-3.6.3.jar
  /home/nesquate/.local/share/multimc/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  /home/nesquate/.local/share/multimc/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  /home/nesquate/.local/share/multimc/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  /home/nesquate/.local/share/multimc/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  /home/nesquate/.local/share/multimc/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar
  /home/nesquate/.local/share/multimc/libraries/net/minecraftforge/nashorn-core-compat/15.1.1.1/nashorn-core-compat-15.1.1.1.jar
  /home/nesquate/.local/share/multimc/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  /home/nesquate/.local/share/multimc/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-linux.jar
  /home/nesquate/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar
  /home/nesquate/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-linux.jar
  /home/nesquate/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-linux.jar
  /home/nesquate/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-linux.jar
  /home/nesquate/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-linux.jar
  /home/nesquate/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-linux.jar
  /home/nesquate/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-linux.jar

Params:
  --username  --version MultiMC5 --gameDir /home/nesquate/.local/share/multimc/instances/1.16.5/.minecraft --assetsDir /home/nesquate/.local/share/multimc/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 36.2.20 --fml.mcVersion 1.16.5 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20210115.111550

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx8192m, -Duser.language=en]


Minecraft process ID: 26125


Using onesix launcher.

Missing: /home/nesquate/.local/share/multimc/libraries/net/minecraftforge/forge/1.16.5-36.2.20/forge-1.16.5-36.2.20-client.jar
Some extra libraries are missing! Running the installer to generate them now.
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50)
	... 8 more
Caused by: java.lang.NoSuchMethodError: 'net.minecraftforge.installer.json.Install net.minecraftforge.installer.json.Util.loadInstallProfile()'
	at io.github.zekerzhayard.forgewrapper.installer.util.InstallerV0.loadInstallProfile(InstallerV0.java:14)
	at io.github.zekerzhayard.forgewrapper.installer.Installer.install(Installer.java:15)
	... 13 more
Exiting with -1
```

I found ` java.lang.NoSuchMethodError: 'net.minecraftforge.installer.json.Install net.minecraftforge.installer.json.Util.loadInstallProfile()'` so I tried to change ForgeWrapper version.

Original in `net.minecraftforge.json`
```json
"downloads": {
                "artifact": {
                    "sha1": "e97805af76d4c1cebb753132eadbabd92e67a17b",
                    "size": 34299,
                    "url": "https://files.multimc.org/maven/io/github/zekerzhayard/ForgeWrapper/1.5.4/ForgeWrapper-1.5.4.jar"
                }
            },
            "name": "io.github.zekerzhayard:ForgeWrapper:1.5.4"
```

After I changed : 
```json
"downloads": {
                "artifact": {
                    "sha1": "2b0e06937349a209dbb90dca6381258daa456ad7",
                    "size": 30486,
                    "url": "https://files.multimc.org/maven/io/github/zekerzhayard/ForgeWrapper/1.5.3/ForgeWrapper-1.5.3.jar"
                }
            },
            "name": "io.github.zekerzhayard:ForgeWrapper:1.5.3"
```

And my Forge 1.16.5 works now.

So I think the newest ForgeWrapper (1.5.4) has bug that let Minecraft Forge 1.16.5 can't run.
Maybe it should be fixed, please check this.

Thanks.

### Steps to reproduce

Just install any Forge version for Minecraft 1.16.5

### Suspected cause

Because log says : 
```
Caused by: java.lang.NoSuchMethodError: 'net.minecraftforge.installer.json.Install net.minecraftforge.installer.json.Util.loadInstallProfile()'
	at io.github.zekerzhayard.forgewrapper.installer.util.InstallerV0.loadInstallProfile(InstallerV0.java:14)
	at io.github.zekerzhayard.forgewrapper.installer.Installer.install(Installer.java:15)
	... 13 more
```

I think this problem caused by latest (1.5.4) ForgeWrapper, which doesn't have `net.minecraftforge.installer.json.Installnet.minecraftforge.installer.json.Util.loadInstallProfile()` method or this method is broken.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
should be fixed by https://github.com/MultiMC/meta-multimc/commit/5f4cc4d9ef5a27e2d16cdd0c0ab6bed0c550b59f
restart multimc and rollback the forge library by clicking revert and try again

**Comment by Nesquate** [comment]
After restart MultiMC and click revert, this problem is fixed.
I appreciate your help very much.
