### ISSUE TITLE
Crash exit code: -1

### ISSUE THREAD

**Issue by freezebladeJD** [MultiMC/Launcher#4376]
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1.

This happens on any and every 1.12 installation and have no idea what's causing it.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by Kaleeeeeeee** [comment]
> https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)
	... 13 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.core.lookup.StrLookup
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 28 more
Exiting with -1
Process exited with code -1.

sorry but that does not fucking work! did this 7 fucking times and it still throws the error!

**Comment by phit** [comment]
please post the full log

 ![](https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png)
