### ISSUE TITLE
MultiMC Crashes when I press launch

### ISSUE THREAD

**Issue by SouthernCow64** [MultiMC/Launcher#4417]
### Operating System

Windows

### Description of bug

I only have optifine/forge installed and it crashes when I click launch. I am playing 1.18.1 and have Java 17 installed and it is selected.

Here is my crash log:
https://paste.ee/p/birqg

### Steps to reproduce

Here is the crash log again if the link doesn't work. 

MultiMC version: 0.6.14-3001

Launched instance in online mode

authserver.mojang.com resolves to:
    [108.156.72.68]

session.minecraft.net resolves to:
    [34.205.58.168, 52.21.65.46, 3.213.200.53]

textures.minecraft.net resolves to:
    [18.65.229.70, 18.65.229.16, 18.65.229.19, 18.65.229.21]

api.mojang.com resolves to:
    [18.67.1.90]

Minecraft folder is:
C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/instances/1.18.1/.minecraft

Java path is:
C:/Program Files/Java/jdk-17.0.1/bin/javaw.exe

Checking Java version...
Java is version 17.0.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/instances/1.18.1/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/com/mojang/blocklist/1.0.6/blocklist-1.0.6.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/com/github/oshi/oshi-core/5.8.2/oshi-core-5.8.2.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/net/java/dev/jna/jna-platform/5.9.0/jna-platform-5.9.0.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/com/ibm/icu/icu4j/69.1/icu4j-69.1.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/com/google/code/gson/gson/2.8.8/gson-2.8.8.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/com/mojang/authlib/3.2.38/authlib-3.2.38.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/cpw/mods/securejarhandler/0.9.54/securejarhandler-0.9.54.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/net/minecraftforge/eventbus/5.0.3/eventbus-5.0.3.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/net/minecraftforge/forgespi/4.0.10/forgespi-4.0.10.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/cpw/mods/modlauncher/9.0.7/modlauncher-9.0.7.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/cpw/mods/bootstraplauncher/0.1.17/bootstraplauncher-0.1.17.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/net/minecraftforge/fmlloader/1.18.1-39.0.8/fmlloader-1.18.1-39.0.8.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/com/mojang/minecraft/1.18.1/minecraft-1.18.1-client.jar

Native libraries:
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] OptiFine_1.18.1_HD_U_H4 (1)

Params:
  --username  --version MultiMC5 --gameDir C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/instances/1.18.1/.minecraft --assetsDir C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/assets --assetIndex 1.18 --uuid  --accessToken  --userType  --versionType release --launchTarget forgeclient --fml.forgeVersion 39.0.8 --fml.mcVersion 1.18.1 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20211210.034407

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx2048m, -Duser.language=en]

Minecraft process ID: 14412

Using onesix launcher.

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2022-01-08 20:54:12,085 main WARN Advanced terminal features are not available in this environment
[20:54:12] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, silentwosperer, --version, MultiMC5, --gameDir, C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/instances/1.18.1/.minecraft, --assetsDir, C:/Users/lovey/OneDrive/Desktop/Desktop Junk/MultiMC/assets, --assetIndex, 1.18, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 39.0.8, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407, --width, 854, --height, 480]
[20:54:12] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.0.7+91+master.8569cdf starting: java version 17.0.1 by Oracle Corporation
[20:54:13] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[20:54:13] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file URL: union:/C:/Users/lovey/OneDrive/Desktop/Desktop%20Junk/MultiMC/instances/1.18.1/.minecraft/mods/OptiFine_1.18.1_HD_U_H4%20(1).jar%2352!
[20:54:13] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file: C:\Users\lovey\OneDrive\Desktop\Desktop Junk\MultiMC\instances\1.18.1\.minecraft\mods\OptiFine_1.18.1_HD_U_H4 (1).jar
[20:54:13] [main/INFO] [op.OptiFineTransformer/]: Target.PRE_CLASS is available
[20:54:13] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/lovey/OneDrive/Desktop/Desktop%20Junk/MultiMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2349! Service=ModLauncher Env=CLIENT
[20:54:13] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.initialize
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	... 8 more
Caused by: java.lang.RuntimeException: Failed to load FML config from C:\Users\lovey\OneDrive\Desktop\Desktop Junk\MultiMC\instances\1.18.1\.minecraft\config\fml.toml
	at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.8/net.minecraftforge.fml.loading.FMLConfig.loadFrom(FMLConfig.java:63)
	at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.8/net.minecraftforge.fml.loading.FMLConfig.load(FMLConfig.java:76)
	at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.8/net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:79)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:93)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:93)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:52)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:87)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)
	... 13 more
Caused by: com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.AbstractInput.readCharsUntil(AbstractInput.java:123)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:166)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.AutoreloadFileConfig.load(AutoreloadFileConfig.java:41)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85)
	at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.8/net.minecraftforge.fml.loading.FMLConfig.loadFrom(FMLConfig.java:59)
	... 25 more
Exiting with -1
Process exited with code -1.

### Suspected cause

I'm not sure what is causing this. Not a clue. Was working fine until today.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
