### ISSUE TITLE
Crashes in 1.16.5 forge

### ISSUE THREAD

**Issue by CamillaLee** [MultiMC/Launcher#4450]
### Operating System

Windows

### Description of bug

I cant start game with multiMC.. here's my latest log
someone please help me with this... Sorry for my bad English ;(
-----------------------------------------------------------------------------

MultiMC version: 0.6.14-3001

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.225.107.75]

session.minecraft.net resolves to:
    [18.210.95.126, 52.1.29.34, 34.231.157.213]

textures.minecraft.net resolves to:
    [13.226.237.106, 13.226.237.16, 13.226.237.116, 13.226.237.8]

api.mojang.com resolves to:
    [54.230.60.109]

Minecraft folder is:
C:/Users/user/Downloads/mmc-stable-win32/MultiMC/instances/1.16.5/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 1.8.0_321, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/instances/1.16.5/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forge/1.16.5-36.2.20/forge-1.16.5-36.2.20-launcher.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/cpw/mods/grossjava9hacks/1.3.3/grossjava9hacks-1.3.3.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/com/electronwill/night-config/core/3.6.3/core-3.6.3.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/com/electronwill/night-config/toml/3.6.3/toml-3.6.3.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/nashorn-core-compat/15.1.1.1/nashorn-core-compat-15.1.1.1.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] abnormals_core-1.16.5-3.3.0
  [✔️] AI-Improvements-1.16.5-0.4.0
  [✔️] architectury-1.27.46
  [✔️] astikorcarts-1.16.5-1.1.1
  [✔️] astralsorcery-1.16-1.16.5-1.13.12
  [✔️] atmospheric-1.16.5-3.1.1
  [✔️] AutoRegLib-1.6-49
  [✔️] autumnity-1.16.5-2.1.2
  [✔️] betteranimalsplus-1.16.5-11.0.0-forge
  [✔️] betterbiomeblend-1.16.4-1.2.9-forge
  [✔️] betterendforge-1.16.5-1.6.3
  [✔️] betternether_reforged-1.2
  [✔️] BetterPortals-1.16.4-0.3.9
  [✔️] BiomesOPlenty-1.16.5-13.1.0.484-universal
  [✔️] BlockDiversity-1.16.5-1.3.2
  [✔️] blocklayering-1.16.3-1.0.0
  [✔️] briflorist
  [✔️] buildersaddition-1.16.5-20210807a
  [✔️] byg-1.3.5
  [✔️] cfm-7.0.0pre22-1.16.3
  [✔️] charm-forge-1.16.5-2.3.2
  [✔️] chipped-1.16.5-1.2.0.1-forge
  [✔️] chiselsandbits-1.0.43
  [✔️] citadel-1.8.1-1.16.5
  [✔️] cloth-config-4.13.49-forge
  [✔️] CTM-MC1.16.1-1.1.2.6
  [✔️] curios-forge-1.16.5-4.0.6.8
  [✔️] decorative_blocks_abnormals-1.2
  [✔️] decorative_blocks-1.16.4-1.7.2
  [✔️] dungeons_1.10.3_mc1.16.5
  [✔️] embellishcraft-1.16.5-3.4.0.0
  [✔️] environmental-1.16.5-1.1.1
  [✔️] extlights-3.3
  [✔️] Feywild-1.16.5-2.0.7
  [✔️] FpsReducer-forge-1.24-mc1.16.5
  [✔️] FramedBlocks-2.11.3
  [✔️] ftb-library-forge-1605.3.4-build.90
  [✔️] ftb-ultimine-forge-1605.3.1-build.45
  [✔️] geckolib-forge-1.16.5-3.0.57
  [✔️] Goblins_Dungeons_1.0.4
  [✔️] greekfantasy-16.5.3
  [✔️] iceandfire-2.1.9-1.16.5
  [✔️] Inspirations-1.16.5-1.2.3.38
  [✔️] ironagefurniture+1.16.4-1.16.5+0.2.0.5
  [✔️] kotlinforforge-1.16.0-obf
  [✔️] LibX-1.16.3-1.0.76
  [✔️] LightingWand-1.16.4-1.8.1
  [✔️] Mantle-1.16.5-1.6.152
  [✔️] mapperbase-1.16.5-2.4.0.0
  [✔️] mcw-bridges-2.0.1-mc1.16.5
  [✔️] mcw-doors-1.0.2-mc1.16.5
  [✔️] mcw-fences-1.0.2-mc1.16.5
  [✔️] MedievalCraft-1.16.5-1.16.2
  [✔️] minecolonies-1.16.5-1.0.309-RELEASE
  [✔️] moblocks-v0.8.1b
  [✔️] NefsMedievalPub+v0.9(1.16.5)
  [✔️] nekoration-1.16.X-1.4.0
  [✔️] observerlib-1.16.5-1.5.3
  [✔️] Omni-1.16.5-1.2.2
  [✔️] OptiFine_1.16.5_HD_U_G8
  [✔️] ornamental-1.16.5-4.5
  [✔️] Patchouli-1.16.4-53.2
  [✔️] performant-1.16.2-5-3.81m
  [✔️] platforms-1.16-1.7.12
  [✔️] projectvibrantjourneys-1.16.5-3.2.11
  [✔️] Quark-r2.4-321
  [✔️] replaymod-1.16.4-forge-1.0.1
  [✔️] shetiphiancore-1.16-3.8.7
  [✔️] smallships-1.16.5-1.10.1
  [✔️] structurize-0.13.252-ALPHA-universal
  [✔️] terraqueous-1.16-1.7.18
  [✔️] undeco-1.1.0
  [✔️] upgrade_aquatic-1.16.5-3.1.2
  [✔️] valhelsia_core-16.0.14
  [✔️] valhelsia_structures-1.16.5-0.1.6
  [✔️] WallpaperCraft-1.16.3-1.4.6
  [✔️] Waystones_1.16.5-7.6.4
  [✔️] worldedit-mod-7.2.5-dist
  [✔️] Xaeros_Minimap_21.22.6_Forge_1.16.5
  [✔️] XaerosWorldMap_1.18.8_Forge_1.16.5
  [✔️] xkdeco_0.2.4
  [✔️] YungsApi-1.16.4-Forge-13

Params:
  --username  --version MultiMC5 --gameDir C:/Users/user/Downloads/mmc-stable-win32/MultiMC/instances/1.16.5/.minecraft --assetsDir C:/Users/user/Downloads/mmc-stable-win32/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 36.2.20 --fml.mcVersion 1.16.5 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20210115.111550

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms7552m, -Xmx8832m, -Duser.language=en]

Minecraft process ID: 5232

Using onesix launcher.

Checking: MC_SLIM
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: PATCHED
Checking: MC_SRG
2022-01-25 17:28:17,521 main WARN Advanced terminal features are not available in this environment
[17:28:17] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, SabrinaHF, --version, MultiMC5, --gameDir, C:/Users/user/Downloads/mmc-stable-win32/MultiMC/instances/1.16.5/.minecraft, --assetsDir, C:/Users/user/Downloads/mmc-stable-win32/MultiMC/assets, --assetIndex, 1.16, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.20, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[17:28:17] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_321 by Oracle Corporation
[17:28:17] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[17:28:17] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file: C:\Users\user\Downloads\mmc-stable-win32\MultiMC\instances\1.16.5\.minecraft\mods\OptiFine_1.16.5_HD_U_G8.jar
[17:28:17] [main/INFO] [op.OptiFineTransformer/]: Target.PRE_CLASS is available
[17:28:17] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[17:28:17] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/user/Downloads/mmc-stable-win32/MultiMC/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[17:28:17] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[17:28:19] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '~'
[17:28:19] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.transformers
[17:28:19] [main/INFO] [op.OptiFineTransformer/]: Targets: 311
[17:28:19] [main/INFO] [op.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
[17:28:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:213]: Failed to start Minecraft:
[17:28:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: java.lang.reflect.InvocationTargetException
[17:28:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:28:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:28:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:28:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17:28:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[17:28:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[17:28:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[17:28:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[17:28:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: Caused by: java.lang.reflect.InvocationTargetException
[17:28:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:28:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:28:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:28:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17:28:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
[17:28:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	... 8 more
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.forName0(Native Method)
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.forName(Unknown Source)
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:67)
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:70)
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:59)
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:196)
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.HashMap.forEach(Unknown Source)
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[17:28:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 13 more
[17:28:19] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1
마인크래프트가 종료 코드 -1와(과) 함께 종료했습니다.(It means minecraft ended with exit code -1)
Clipboard copy at: 25 Jan 2022 17:30:35 +0900
-------------------------------------------------------------------------------

### Steps to reproduce

[launcher_log.txt](https://github.com/MultiMC/Launcher/files/7931892/launcher_log.txt)

### Suspected cause

maybe I need to let some of my new mods go...? I'm not sure...

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Forge is broken with Java 8 Update 321 or newer
You need an older Java 8 version, e.g. 8u312 you can find downloads here https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk

**Comment by CamillaLee** [comment]
Thank you Phit!! I've solve this problem with your advice!!!

> Forge is broken with Java 8 Update 321 or newer You need an older Java 8 version, e.g. 8u312 you can find downloads here https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk
