### ISSUE TITLE
Techopolis unable to load!!

### ISSUE THREAD

**Issue by misshaptat** [MultiMC/Launcher#4451]
### Operating System

Windows

### Description of bug

MultiMC version: 0.6.14-3001

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.225.59.75]

session.minecraft.net resolves to:
    [52.1.29.34, 34.231.157.213, 18.210.95.126]

textures.minecraft.net resolves to:
    [99.84.42.80, 99.84.42.122, 99.84.42.69, 99.84.42.92]

api.mojang.com resolves to:
    [99.84.40.162]

Minecraft folder is:
G:/Data/MultiMc2/instances/Techopolis/minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 1.8.0_321, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  G:/Data/MultiMc2/instances/Techopolis/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  G:/Data/MultiMc2/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  G:/Data/MultiMc2/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  G:/Data/MultiMc2/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  G:/Data/MultiMc2/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  G:/Data/MultiMc2/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  G:/Data/MultiMc2/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  G:/Data/MultiMc2/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  G:/Data/MultiMc2/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  G:/Data/MultiMc2/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  G:/Data/MultiMc2/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  G:/Data/MultiMc2/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  G:/Data/MultiMc2/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  G:/Data/MultiMc2/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  G:/Data/MultiMc2/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  G:/Data/MultiMc2/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  G:/Data/MultiMc2/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  G:/Data/MultiMc2/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  G:/Data/MultiMc2/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  G:/Data/MultiMc2/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  G:/Data/MultiMc2/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  G:/Data/MultiMc2/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  G:/Data/MultiMc2/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  G:/Data/MultiMc2/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  G:/Data/MultiMc2/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  G:/Data/MultiMc2/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  G:/Data/MultiMc2/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  G:/Data/MultiMc2/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  G:/Data/MultiMc2/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  G:/Data/MultiMc2/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  G:/Data/MultiMc2/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  G:/Data/MultiMc2/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  G:/Data/MultiMc2/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  G:/Data/MultiMc2/libraries/net/minecraftforge/forge/1.16.5-36.2.22/forge-1.16.5-36.2.22-launcher.jar
  G:/Data/MultiMc2/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  G:/Data/MultiMc2/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  G:/Data/MultiMc2/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  G:/Data/MultiMc2/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  G:/Data/MultiMc2/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  G:/Data/MultiMc2/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar
  G:/Data/MultiMc2/libraries/cpw/mods/grossjava9hacks/1.3.3/grossjava9hacks-1.3.3.jar
  G:/Data/MultiMc2/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  G:/Data/MultiMc2/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  G:/Data/MultiMc2/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  G:/Data/MultiMc2/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  G:/Data/MultiMc2/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar
  G:/Data/MultiMc2/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  G:/Data/MultiMc2/libraries/com/electronwill/night-config/core/3.6.3/core-3.6.3.jar
  G:/Data/MultiMc2/libraries/com/electronwill/night-config/toml/3.6.3/toml-3.6.3.jar
  G:/Data/MultiMc2/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  G:/Data/MultiMc2/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  G:/Data/MultiMc2/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  G:/Data/MultiMc2/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  G:/Data/MultiMc2/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar
  G:/Data/MultiMc2/libraries/net/minecraftforge/nashorn-core-compat/15.1.1.1/nashorn-core-compat-15.1.1.1.jar
  G:/Data/MultiMc2/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  G:/Data/MultiMc2/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  G:/Data/MultiMc2/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  G:/Data/MultiMc2/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  G:/Data/MultiMc2/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  G:/Data/MultiMc2/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  G:/Data/MultiMc2/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  G:/Data/MultiMc2/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  G:/Data/MultiMc2/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] AdFinders-1.16.5-5.0.11.0-build.0206
  [✔️] ae2extras-1.3.1-1.16.5
  [✔️] ae2wtlib-0.3.2-1.16.5
  [✔️] appleskin-forge-mc1.16.x-2.2.0
  [✔️] appliedenergistics2-8.4.7
  [✔️] architectury-1.28.48
  [✔️] AutoRegLib-1.6-49
  [✔️] blockcarpentry-1.16-0.4.0
  [✔️] Blur-1.1.0-1
  [✔️] Bookshelf-Forge-1.16.5-10.4.31
  [✔️] buildinggadgets-1.16.5-3.8.2
  [✔️] cant-sleep-clowns-will-eat-me-1.16.4-1.0.0.1
  [✔️] catalogue-1.5.0-1.16.5
  [✔️] ceramicbucket-1.16.5-2.7.0.1
  [✔️] Chisel-MC1.16.5-2.0.1-alpha.4
  [✔️] christmasfestivity-1.4.7-1.16.5-forge
  [✔️] ChunkAnimator-1.16.5-1.2.4
  [✔️] CodeChickenLib-1.16.5-4.0.6.443-universal
  [✔️] cofh_core-1.16.5-1.4.1.8
  [✔️] CommonCapabilities-1.16.5-2.8.0
  [✔️] configured-1.5.1-1.16.5
  [✔️] constructionwand-1.16.5-2.6
  [✔️] Controlling-7.0.0.28
  [✔️] CraftingTweaks_1.16.5-12.2.1
  [✔️] CreativeCore_v2.2.1_mc1.16.5
  [✔️] CTM-MC1.16.1-1.1.2.6
  [✔️] Cucumber-1.16.5-4.1.12
  [✔️] curios-forge-1.16.5-4.0.8.0
  [✔️] custommachinery-1.16.5-0.5.5
  [✔️] CyclopsCore-1.16.5-1.12.1
  [✔️] dankstorage-3.19
  [✔️] DeLogger-3.0.4-build.20+mc1.16.5
  [✔️] desiredservers-1.16.4-1.0.1
  [✔️] elevatorid-1.16.5-1.7.13
  [✔️] EnderStorage-1.16.5-2.8.0.168-universal
  [✔️] endrem_forge-5.0.1-R-1.16.5
  [✔️] engineersdecor-1.16.5-1.1.16
  [✔️] EnigmaticGraves-1.7.2
  [✔️] ExtraStorage-1.16.5-1.6.0
  [✔️] extremeSoundMuffler-3.17_1.16.5
  [✔️] factory-forge-1.16.5-1.3.1
  [✔️] fancymenu_forge_2.5.2_MC_1.16.2-1.16.5
  [✔️] FarmersDelight-1.16.5-0.5.4
  [✔️] FarmingForBlockheads_1.16.5-7.3.1
  [✔️] FastLeafDecay-v25.2
  [✔️] ferritecore-2.1.0-forge
  [✔️] Flopper-1.16.5-1.1.1
  [✔️] fltpot-1.16.5-0.2.4
  [✔️] FluxNetworks-1.16.5-6.2.1.14
  [✔️] ForgeEndertech-1.16.5-7.2.2.0-build.0202
  [✔️] ForgivingVoid_1.16.5-5.2.1
  [✔️] framedcompactdrawers-1.16-2.2.1
  [✔️] ftb-backups-2.1.2.2
  [✔️] ftb-chunks-forge-1605.3.2-build.115
  [✔️] ftb-essentials-1605.1.5-build.32
  [✔️] ftb-library-forge-1605.3.4-build.90
  [✔️] ftb-quests-forge-1605.3.6-build.76
  [✔️] ftb-ranks-forge-1605.1.5-build.16
  [✔️] ftb-teams-forge-1605.2.3-build.40
  [✔️] ftb-ultimine-forge-1605.3.1-build.45
  [✔️] Geolosys-1.16.5-6.0.0_beta
  [✔️] gottaclimbfast-mc1.16-1.1-forge
  [📁] hats (folder)
  [✔️] Hats-1.16.5-10.3.3
  [✔️] hexlands-forge-1.16.5-1.1.2
  [✔️] iChunUtil-1.16.5-10.5.1
  [✔️] ImmersiveEngineering-1.16.5-5.0.7-143
  [✔️] immersiveposts-1.16.5-4.2.2
  [✔️] InsaneLib-1.4.2-mc1.16.5
  [✔️] IntegratedCrafting-1.16.5-1.0.20
  [✔️] IntegratedDynamics-1.16.5-1.10.6
  [✔️] IntegratedTerminals-1.16.5-1.2.11
  [✔️] IntegratedTunnels-1.16.5-1.8.9
  [✔️] invtweaks-1.16.4-1.0.1
  [✔️] ironchest-1.16.5-11.2.21
  [✔️] item-filters-forge-1605.2.5-build.9
  [✔️] ItemPhysic_v1.4.18_mc1.16.5
  [✔️] jeed-1.16.5-1.6
  [✔️] jei-1.16.5-7.7.1.145
  [✔️] jmi-1.16.5-0.7-37
  [✔️] journeymap-1.16.5-5.8.0beta11
  [✔️] jumbofurnace-1.16.4-2.2.0.1
  [✔️] JustEnoughCalculation-1.16.5-3.8.6
  [✔️] KleeSlabs_1.16.5-9.2.1
  [✔️] konkrete_forge_1.3.3_MC_1.16.2-1.16.5
  [✔️] kubejs-forge-1605.3.19-build.258
  [✔️] kubejs-immersive-engineering-1605.1.2-build.4
  [✔️] kubejs-mekanism-1605.1.2-build.2
  [✔️] kubejs-thermal-1605.1.4-build.4
  [✔️] LibX-1.16.3-1.0.76
  [✔️] Lollipop-1.16.5-3.2.9
  [✔️] Mantle-1.16.5-1.6.152
  [✔️] mcjtylib-1.16-5.1.3
  [✔️] mcw-bridges-2.0.1-mc1.16.5
  [✔️] mcw-doors-1.0.5-mc1.16.5
  [✔️] mcw-fences-1.0.2-mc1.16.5
  [✔️] mcw-furniture-2.0.1-mc1.16.5
  [✔️] mcw-lights-1.0.2-mc1.16.5
  [✔️] mcw-paintings-1.0.2-mc1.16.5
  [✔️] mcw-roofs-2.1.0-mc1.16.5
  [✔️] mcw-trapdoors-1.0.4-mc1.16.5
  [✔️] mcw-windows-2.0.2-mc1.16.5
  [✔️] Measurements-1.16.5-1.2
  [✔️] Mekanism-1.16.5-10.1.1.456
  [✔️] metalbarrels-1.16.2-3.3b
  [✔️] modnametooltip_1.16.2-1.15.0
  [✔️] moredragoneggs-2.4
  [✔️] MoreMekanismProcessing-1.16.5-1.1
  [✔️] moreminecarts-1.3.14
  [✔️] moreoverlays-1.18.17-mc1.16.5
  [✔️] Morpheus-1.16.5-4.2.70
  [✔️] Morph-o-Tool-1.4-27
  [✔️] MouseTweaks-2.14-mc1.16.2
  [✔️] MyServerIsCompatible-1.16.5-1.0
  [✔️] NaturesCompass-1.16.5-1.9.1-forge
  [✔️] oauth-1.1.9-1.16
  [✔️] Patchouli-1.16.4-53.2
  [✔️] polymorph-forge-1.16.5-0.39
  [✔️] Portable Nether-1.1
  [✔️] Powah-1.16.5-2.3.16
  [✔️] QuarkOddities-1.16.3
  [✔️] Quark-r2.4-321
  [✔️] recycler-1605.1.0-build.11
  [✔️] RefinedRelocation_1.16.5-8.2.3
  [✔️] refinedstorage-1.9.16
  [✔️] refinedstorageaddons-0.7.4
  [✔️] rftoolsbase-1.16-2.1.2
  [✔️] rhino-forge-1605.1.5-build.75
  [✔️] RoadRunner-mc1.16.5-1.4.0
  [✔️] rsgauges-1.16.5-1.2.13
  [✔️] RSInfinityBooster-1.16.5-1.1+13
  [✔️] RSLargePatterns-1.16.5-2.1.0.3
  [✔️] rsrequestify-1.16.5-2.1.6
  [✔️] shutupexperimentalsettings-1.0.3
  [✔️] simple-rpc-1.16.5-2.7.1
  [✔️] SkyblockBuilder-1.16.4-1.6.13
  [✔️] sleeping_bags-1.16.5-1.0.3
  [✔️] sneaky_tree_growing_v1.6.2 RELEASE-1.16.5
  [✔️] sophisticatedbackpacks-1.16.5-3.15.1.503
  [✔️] StorageDrawers-1.16.3-8.5.1
  [✔️] supermartijn642corelib-1.0.16-mc1.16.5
  [✔️] tconplanner-1.16.5-1.1.1
  [✔️] TConstruct-1.16.5-3.3.2.324
  [✔️] techopolis-1.16.5-1.7
  [✔️] TerraForged-1.16.5-0.2.15
  [✔️] theoneprobe-1.16-3.1.4
  [✔️] thermal_expansion-1.16.5-1.4.2.4
  [✔️] thermal_foundation-1.16.5-1.4.2.9
  [✔️] Tips-1.16.5-4.0.15
  [✔️] TipTheScales-1.16.5-3.0.0.15
  [✔️] torchmaster-2.3.8
  [✔️] trashcans-1.0.12-mc1.16
  [✔️] universalgrid-1.16.5-0.125
  [✔️] Uppers-0.3.2
  [✔️] Waystones_1.16.5-7.6.4
  [✔️] woodenhopper-1.16.5-1.2.0.0
  [✔️] xnet-1.16-3.0.16
  [✔️] XNetGases-1.16.5-2.3.9

Params:
  --username  --version MultiMC5 --gameDir G:/Data/MultiMc2/instances/Techopolis/minecraft --assetsDir G:/Data/MultiMc2/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 36.2.22 --fml.mcVersion 1.16.5 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20210115.111550

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms640m, -Xmx8320m, -Duser.language=en]

Minecraft process ID: 4168

Using onesix launcher.

Checking: MC_SLIM
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: PATCHED
Checking: MC_SRG
2022-01-25 09:46:13,435 main WARN Advanced terminal features are not available in this environment
[09:46:13] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, misshaptat, --version, MultiMC5, --gameDir, G:/Data/MultiMc2/instances/Techopolis/minecraft, --assetsDir, G:/Data/MultiMc2/assets, --assetIndex, 1.16, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.22, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --width, 854, --height, 480]
[09:46:13] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_321 by Oracle Corporation
[09:46:14] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[09:46:14] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/G:/Data/MultiMc2/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[09:46:18] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 13:0 token recognition error at: '`'
[09:46:18] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '~'
Init ItemPhysic coremods ...
Init CreativeCore coremods ...
[09:46:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:213]: Failed to start Minecraft:
[09:46:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: java.lang.reflect.InvocationTargetException
[09:46:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:46:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[09:46:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[09:46:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[09:46:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[09:46:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[09:46:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[09:46:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[09:46:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: Caused by: java.lang.reflect.InvocationTargetException
[09:46:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:46:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[09:46:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[09:46:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[09:46:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
[09:46:19] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	... 8 more
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.forName0(Native Method)
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.forName(Unknown Source)
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:67)
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:70)
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:59)
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:196)
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.HashMap.forEach(Unknown Source)
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[09:46:19] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 13 more
[09:46:19] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1
Process exited with code -1.
Clipboard copy at: 25 Jan 2022 09:46:24 -0500

### Steps to reproduce

just trying to load instant!!

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by GameFAQsRolo** [comment]
I'm having the same (similar?) error today. I'm guessing it's the java update I was prompted to install yesterday. Everything was working fine before the update.

Here's my log
https://paste.ee/p/Pryrf

**Comment by jotoho** [comment]
Java 8 update 321 is well known to have broken Forge. There are already lots of closed issues about that on this bugtracker. Downgrade your Java 8 version. Instructions can be found on other recent issues.

**Comment by jamierocks** [comment]
This isn't a bug with MultiMC, but rather game support.

This is a bug tracker for MultiMC, and therefor not the appropriate place for game support. There are many communities which may be able to provide game support for you - the MultiMC Discord being one, but also the Minecraft subreddit, Minecraft Forums, the #minecrafthelp IRC channel, and potentially many more.
