### ISSUE TITLE
MultiMC Launcher crash

### ISSUE THREAD

**Issue by Vlueyo** [MultiMC/Launcher#4454]
### Operating System

Windows

### Description of bug

I'm playing on a custom modpack with friends, and i've lost an item so my friends used a save so i can get it back, but the server bugged, so i've searched on internet what could we do to fix it, find something saying we had to delete quark-common.toml, that's what we did, then i've tried to reconnect, it "worked", it was loading, then it said "loading world" and then crashed, and since then everytime i try to launch the game, it load (with the forge loading screen) for 3-5 seconds and then crash, here's the bug logs :

MultiMC version: 0.6.14-3001

Launched instance in online mode

authserver.mojang.com resolves to:
    [52.222.173.68]

session.minecraft.net resolves to:
    [18.210.95.126, 34.231.157.213, 52.1.29.34]

textures.minecraft.net resolves to:
    [52.84.174.73, 52.84.174.77, 52.84.174.59, 52.84.174.23]

api.mojang.com resolves to:
    [52.222.149.199]

Minecraft folder is:
C:/Users/mario/Desktop/MultiMC/instances/Modpack/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 1.8.0_321, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/mario/Desktop/MultiMC/instances/Modpack/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/mario/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/mario/Desktop/MultiMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/mario/Desktop/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/mario/Desktop/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/mario/Desktop/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/mario/Desktop/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/mario/Desktop/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/mario/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/mario/Desktop/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/mario/Desktop/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/mario/Desktop/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/mario/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/mario/Desktop/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/mario/Desktop/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/mario/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/mario/Desktop/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/mario/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/mario/Desktop/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/mario/Desktop/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/mario/Desktop/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  C:/Users/mario/Desktop/MultiMC/libraries/net/minecraftforge/forge/1.16.5-36.2.20/forge-1.16.5-36.2.20-launcher.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  C:/Users/mario/Desktop/MultiMC/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar
  C:/Users/mario/Desktop/MultiMC/libraries/cpw/mods/grossjava9hacks/1.3.3/grossjava9hacks-1.3.3.jar
  C:/Users/mario/Desktop/MultiMC/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/mario/Desktop/MultiMC/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  C:/Users/mario/Desktop/MultiMC/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  C:/Users/mario/Desktop/MultiMC/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar
  C:/Users/mario/Desktop/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/mario/Desktop/MultiMC/libraries/com/electronwill/night-config/core/3.6.3/core-3.6.3.jar
  C:/Users/mario/Desktop/MultiMC/libraries/com/electronwill/night-config/toml/3.6.3/toml-3.6.3.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  C:/Users/mario/Desktop/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/mario/Desktop/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar
  C:/Users/mario/Desktop/MultiMC/libraries/net/minecraftforge/nashorn-core-compat/15.1.1.1/nashorn-core-compat-15.1.1.1.jar
  C:/Users/mario/Desktop/MultiMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  C:/Users/mario/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/mario/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/mario/Desktop/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] 3dSkinLayers-forge-1.1.0
  [✔️] abnormals_core-1.16.5-3.3.0
  [✔️] abnormals_delight-1.16.5-1.2.1
  [✔️] absentbydesign-1.16.5-1.5.0
  [✔️] Abundance-1.16.5-1.0.5
  [✔️] AdvancementPlaques-1.16.5-1.4.1
  [✔️] AI-Improvements-1.16.2-0.3.0
  [✔️] AkashicTome-1.4-16
  [✔️] alexsmobs-1.12.1
  [✔️] allurement-1.16.5-1.2.1
  [✔️] AmbientSounds_v3.1.11_mc1.16.5
  [✔️] appleskin-forge-mc1.16.x-2.1.0
  [✔️] appliedenergistics2-8.4.4
  [✔️] Aquaculture-1.16.5-2.1.20
  [✔️] archers_paradox-1.16.5-1.4.0.1
  [✔️] Architects-Palette-1.16.4-1.1.4
  [✔️] architectury-1.22.32-forge
  [✔️] ars_nouveau-1.16.5-1.24.7
  [✔️] Artifacts-1.16.5-2.10.0
  [✔️] astralsorcery-1.16-1.16.5-1.13.12
  [✔️] atmospheric-1.16.5-3.1.1
  [✔️] Atum-1.16.5-2.2.9
  [✔️] AutoRegLib-1.6-49
  [✔️] autumnity-1.16.5-2.1.2
  [✔️] bamboo_blocks-1.16.5-3.0.1
  [✔️] Bayou-Blues-1.16.5-1.0.5
  [✔️] BedBenefits-1.16.5-5.0.3
  [✔️] bedspreads-forge-1.16.5-5.1.0.2
  [✔️] berry_good-1.16.5-4.1.2
  [✔️] BetterAdvancements-1.16.5-0.1.0.108
  [✔️] Better-Badlands-1.16.5-2.0.3
  [✔️] betterbiomeblend-1.16.4-1.2.9-forge
  [✔️] BetterBurning-1.16.5-6.0.6
  [✔️] BetterCaves-Forge-1.16.4-1.1.2
  [✔️] BetterDungeons-1.16.4-1.2.1
  [✔️] BetterF3-1.1.3-forge-1.16.5
  [✔️] BetterMineshafts-Forge-1.16.4-2.0.4
  [✔️] BetterStrongholds-1.16.4-1.2.1
  [✔️] Blur-1.1.0-1
  [✔️] Bookshelf-Forge-1.16.5-10.2.27
  [✔️] Bountiful-1.16.4-3.3.1
  [✔️] buzzier_bees-1.16.5-3.0.2
  [✔️] byg-1.3.5
  [✔️] caelus-forge-1.16.5-2.1.3.1
  [✔️] carryon-1.16.5-1.15.5.15
  [✔️] Cataclysm-0.06
  [✔️] catalogue-1.3.0-1.16.5
  [✔️] catjammies-1.1.0
  [✔️] cavebiomeapi-1.16.5-1.4.2
  [✔️] cavesandcliffs-1.16.5-7.1.4
  [✔️] charm-forge-1.16.5-2.3.2
  [✔️] charmonium-forge-1.16.5-2.3.2
  [✔️] chocolate-1.3.0-1.16.4
  [✔️] Chunk+Pregenerator-V1.16-3.2.1
  [✔️] chunkloaders-1.1.7-mc1.16.5
  [✔️] citadel-1.8.1-1.16.5
  [✔️] ClientTweaks_1.16.3-5.3.0
  [✔️] cloth-config-4.11.26-forge
  [✔️] Clumps-6.0.0.27
  [✔️] CodeChickenLib-1.16.5-4.0.2.429-universal
  [✔️] cofh_core-1.16.5-1.4.0.3
  [✔️] comforts-forge-1.16.5-4.0.1.3
  [✔️] configured-1.5.1-1.16.5
  [✔️] Controlling-7.0.0.24
  [✔️] CosmeticArmorReworked-1.16.5-v4
  [✔️] CraftingTweaks_1.16.5-12.2.1
  [✔️] createaddition-1.16.5-20211202a
  [✔️] create-confectionery1.16.5_v1.0.2
  [✔️] create-mc1.16.5_v0.3.2g
  [✔️] create-stuff-additions1.16.5_v1.1.5
  [✔️] CreativeCore_v2.2.1_mc1.16.5
  [✔️] CTM-MC1.16.1-1.1.2.6
  [✔️] curioofundying-forge-1.16.5-5.2.0.0
  [✔️] curios-forge-1.16.5-4.0.5.2
  [✔️] CuriosQuarkOBP-1.16.5-1.0.2
  [✔️] Curious+Armor+Stands-1.16.5-2.1.2
  [✔️] curiouselytra-forge-1.16.5-4.0.2.3
  [✔️] curiousshulkerboxes-forge-1.16.5-4.0.1.0
  [✔️] dash-1.16.4-1.0.1
  [✔️] decorative_blocks_abnormals-1.2
  [✔️] decorative_blocks-1.16.4-1.7.2
  [✔️] differentiate-1.16.5-0.5.3
  [✔️] drawerfps-2.1
  [✔️] DrawersTooltip-1.16.2-2.1.0
  [✔️] DungeonCrawl-1.16.5-2.3.4
  [✔️] dusk-1.4
  [✔️] DustrialDecor-1.2.9
  [✔️] enchantedbookredesign-3.3-1.16.4
  [✔️] endergetic-1.16.4-3.0.0
  [✔️] Enhanced-Mushrooms-1.16.5-3.0.9
  [✔️] ensorcellation-1.16.5-1.4.0.1
  [✔️] entityculling-1.3.0
  [✔️] environmental-1.16.5-1.1.0
  [✔️] EquipmentCompare-1.16.5-1.2.7
  [✔️] expandability-2.0.1-forge
  [✔️] extlights-3.3
  [✔️] fairylights-4.0.5-1.16.5
  [✔️] FarmersDelight-1.16.5-0.4.6
  [✔️] farsight-1.7
  [✔️] farsightedmobs-forge-1.16-1.1
  [✔️] fastbenchminusreplacement-1.4
  [✔️] fastfurnaceminusreplacement-1.1-1.16.3
  [✔️] FastLeafDecay-v25
  [✔️] ferritecore-2.0.7-forge
  [✔️] flickerfix-1.0.1
  [✔️] flywheel-1.16-0.2.5
  [✔️] Fruitful-1.16.5-2.1.0
  [✔️] ftb-backups-2.1.1.6
  [✔️] ftb-library-forge-1605.3.2-build.64
  [✔️] GameMenuModOption-1.16.4-1.8
  [✔️] geckolib-forge-1.16.5-3.0.45
  [✔️] goblintraders-1.6.0-1.16.3
  [✔️] HealthOverlay-1.16.5-3.0.0
  [✔️] Iceberg-1.16.5-1.0.30
  [✔️] infernal-expansion-1.16.5-2.4.0
  [✔️] InventoryHud_[1.16.2-1.16.5].forge-3.4.0
  [✔️] InventoryHud_[1.16.2-1.16.5].forge-3.4.1
  [✔️] ironchest-1.16.5-11.2.13
  [✔️] itemzoom-1.16.4-2.3.0
  [✔️] Jade-1.16.4-2.7.4
  [✔️] jeed-1.16.5-1.1
  [✔️] jei-1.16.5-7.7.1.121
  [✔️] JEIEnchantmentInfo-1.16.4-1.2.1
  [✔️] jeiintegration_1.16.5-7.0.1.15
  [✔️] JustEnoughResources-1.16.3-0.12.0.100
  [✔️] Kiwi-1.16.5-3.5.2
  [✔️] KleeSlabs_1.16.5-9.2.1
  [✔️] kotlinforforge-1.16.0-obf
  [✔️] kubejs-create-1605.1.2-build.7
  [✔️] kubejs-forge-1605.3.15-build.106
  [✔️] kubejs-thermal-1605.1.4-build.2
  [✔️] lazydfu-0.1.3
  [✔️] leap-1.16.4-1.1.1
  [✔️] LegendaryTooltips-1.16.5-1.1.5
  [✔️] light-overlay-5.8.1
  [✔️] lootr-1.16.5-0.0.9.29
  [✔️] Mantle-1.16.5-1.6.147
  [✔️] Morpheus-1.16.5-4.2.70
  [✔️] MouseTweaks-2.14-mc1.16.2
  [✔️] mowziesmobs-1.5.19
  [✔️] neapolitan-1.16.5-2.2.0
  [✔️] Neat+1.7-27
  [✔️] nethers_delight-2.1
  [✔️] nomowanderer_MC1.16.5_1.2
  [✔️] observerlib-1.16.5-1.5.3
  [✔️] overloadedarmorbar-5.1.0
  [✔️] Patchouli-1.16.4-53.1
  [✔️] performant-1.16.2-5-3.72m
  [✔️] personality-1.16.5-1.0.3
  [✔️] Placebo-1.16.5-4.6.0
  [✔️] polymorph-forge-1.16.5-0.25
  [✔️] QuarkOddities-1.16.3
  [✔️] Quark-r2.4-316
  [✔️] randompatches-2.4.4-forge
  [✔️] ReAuth-1.16-Forge-3.9.3
  [✔️] refinedpipes-0.5
  [✔️] repurposed_structures_forge-3.4.6+1.16.5
  [✔️] rhino-forge-1605.1.3-build.54
  [✔️] savageandravage-1.16.5-3.1.0
  [✔️] SaveMyStronghold-1.16.4-1.0
  [✔️] seamless_loading_screen-1.16.5-1.1.6
  [✔️] secondchanceforge-1.2.0
  [✔️] selene-1.16.5-1.9.0
  [✔️] ServerTabInfo-1.16.4-1.3.3
  [✔️] smoothboot-forge-1.16.4-1.2.2
  [✔️] snowundertrees-1.16.5-v1.2
  [✔️] SoL-Carrot-1.16.5-1.10.1
  [✔️] sophisticatedbackpacks-1.16.5-3.12.2.422
  [✔️] sounddeviceoptions-1.4.3
  [✔️] StorageDrawers-1.16.3-8.3.0
  [✔️] structure_gel-1.16.5-1.7.7
  [✔️] supermartijn642configlib-1.0.9-mc1.16
  [✔️] supplementaries-1.16.5-0.17.12b
  [✔️] swingthroughgrass-1.16.4-1.5.3
  [✔️] TConstruct-1.16.5-3.3.0.308
  [✔️] TerraForged-1.16.5-0.2.15
  [✔️] the-conjurer-1.16.4-1.0.13
  [✔️] thermal_cultivation-1.16.5-1.4.1.3
  [✔️] thermal_expansion-1.16.5-1.4.1.2
  [✔️] thermal_foundation-1.16.5-1.4.1.6
  [✔️] thermal_innovation-1.16.5-1.4.1.3
  [✔️] thermal_locomotion-1.16.5-1.4.1.2
  [✔️] Toast-Control-1.16.4-4.3.1
  [✔️] tools_complement-1.16.5-1.0.0.1
  [✔️] ToolStats-1.16.5-6.0.1
  [✔️] toughnessbar-6.1
  [✔️] TrashSlot_1.16.3-12.2.1
  [✔️] tumbleweed-1.16-0.4.9
  [✔️] twilightforest-1.16.5-4.0.546-universal
  [✔️] upgrade_aquatic-1.16.5-3.1.1
  [✔️] Upgraded+Netherite+1.10.1
  [✔️] Waddles-1.16.5-0.8.13
  [✔️] Waystones_1.16.5-7.6.3
  [✔️] Xaeros_Minimap_21.22.3_Forge_1.16.5
  [✔️] XaerosWorldMap_1.18.6_Forge_1.16.5
  [✔️] YungsApi-1.16.4-Forge-12

Params:
  --username  --version MultiMC5 --gameDir C:/Users/mario/Desktop/MultiMC/instances/Modpack/.minecraft --assetsDir C:/Users/mario/Desktop/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 36.2.20 --fml.mcVersion 1.16.5 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20210115.111550

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms8000m, -Xmx8000m, -Duser.language=en]

Minecraft process ID: 25376

Using onesix launcher.

Checking: MC_SLIM
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: PATCHED
Checking: MC_SRG
2022-01-26 18:08:54,994 main WARN Advanced terminal features are not available in this environment
[18:08:55] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Vlueyo, --version, MultiMC5, --gameDir, C:/Users/mario/Desktop/MultiMC/instances/Modpack/.minecraft, --assetsDir, C:/Users/mario/Desktop/MultiMC/assets, --assetIndex, 1.16, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.20, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --width, 854, --height, 480]
[18:08:55] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_321 by Oracle Corporation
[18:08:55] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[18:08:55] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/mario/Desktop/MultiMC/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[18:08:59] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '~'
Init CreativeCore coremods ...
[18:09:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:213]: Failed to start Minecraft:
[18:09:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: java.lang.reflect.InvocationTargetException
[18:09:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:09:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:09:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:09:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[18:09:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[18:09:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[18:09:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[18:09:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[18:09:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: Caused by: java.lang.reflect.InvocationTargetException
[18:09:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:09:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:09:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:09:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[18:09:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
[18:09:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	... 8 more
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.forName0(Native Method)
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.forName(Unknown Source)
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:67)
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:70)
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:59)
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:196)
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.HashMap.forEach(Unknown Source)
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[18:09:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 13 more
[18:09:02] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1
Le processus s'est arrêté avec le code de sortie -1.
Clipboard copy at: 26 Jan 2022 18:09:41 +0100

### Steps to reproduce

Launch MultiMC
Launch the instance
And then it crashe 3-5 seconds later

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
nothing to do with the config changes you did
Forge is broken with Java 8 Update 321 or newer
You need an older Java 8 version, e.g. 8u312 you can find downloads here https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk
