### ISSUE TITLE
Error launching on Java latest

### ISSUE THREAD

**Issue by JordMonte512** [MultiMC/Launcher#4464]
### Operating System

Windows

### Description of bug

I am not 100% sure of the cause to this or where it came from as it worked fine for a while and then all of a sudden, launching provides this error:

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 33292

Using onesix launcher.

Checking: MC_SLIM
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: PATCHED
Checking: MC_SRG
2022-01-28 21:26:12,154 main WARN Advanced terminal features are not available in this environment
[21:26:12] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, ########, --version, MultiMC5, --gameDir, C:/JordNoSync/MultiMC/instances/Forge 1.16.5/minecraft, --assetsDir, C:/JordNoSync/MultiMC/assets, --assetIndex, 1.16, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.23, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --width, 854, --height, 480]
[21:26:12] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_321 by Oracle Corporation
[21:26:12] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[21:26:12] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file: C:\JordNoSync\MultiMC\instances\Forge 1.16.5\minecraft\mods\OptiFine_1.16.5_HD_U_G8.jar
[21:26:12] [main/INFO] [op.OptiFineTransformer/]: Target.PRE_CLASS is available
[21:26:13] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[21:26:13] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/JordNoSync/MultiMC/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[21:26:13] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[21:26:16] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.transformers
[21:26:16] [main/INFO] [op.OptiFineTransformer/]: Targets: 311
[21:26:17] [main/INFO] [op.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
[21:26:17] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, MultiMC5, --gameDir, C:\JordNoSync\MultiMC\instances\Forge 1.16.5\minecraft, --assetsDir, C:\JordNoSync\MultiMC\assets, --uuid, <PROFILE ID>, --username, ###########, --assetIndex, 1.16, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 854, --height, 480]
[21:26:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:213]: Failed to start Minecraft:
[21:26:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: java.lang.reflect.InvocationTargetException
[21:26:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:26:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:26:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:26:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:26:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[21:26:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[21:26:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[21:26:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[21:26:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: Caused by: java.lang.reflect.InvocationTargetException
[21:26:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:26:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:26:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:26:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:26:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
[21:26:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	... 8 more
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 13 more
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.reflect.InvocationTargetException
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 17 more
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: Caused by: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at net.minecraft.util.math.MathHelper.<clinit>(MathHelper.java:20)
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at net.minecraft.util.Util.func_240979_a_(Util.java:109)
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at net.minecraft.util.Util.<clinit>(Util.java:65)
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at net.minecraft.client.main.Main.main(Main.java:63)
[21:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	... 23 more
[21:26:17] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1
Process exited with code -1.

### Steps to reproduce

Running java latest should reproduce however if any issues are found reproducing, someone is more than welcome to ask for information / logs / screenshots and i would be happy to provide 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Forge is broken with Java 8 Update 321 or newer
You need an older Java 8 version, e.g. 8u312 you can find downloads here https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk
