### ISSUE TITLE
1.16.5 Modpacks Crashing Even When Using Java 8

### ISSUE THREAD

**Issue by Borph04** [MultiMC/Launcher#4474]
MultiMC version: 0.6.14-3001

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.35.76.76]

session.minecraft.net resolves to:
    [34.231.157.213, 18.210.95.126, 52.1.29.34]

textures.minecraft.net resolves to:
    [13.35.77.4, 13.35.77.97, 13.35.77.8, 13.35.77.88]

api.mojang.com resolves to:
    [65.8.195.210]

Minecraft folder is:
C:/Users/andyr/Desktop/MultiMC/instances/Create- Above and Beyond/minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_321/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_321, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/andyr/Desktop/MultiMC/instances/Create- Above and Beyond/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  C:/Users/andyr/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/net/minecraftforge/forge/1.16.5-36.2.20/forge-1.16.5-36.2.20-launcher.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/cpw/mods/grossjava9hacks/1.3.3/grossjava9hacks-1.3.3.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/com/electronwill/night-config/core/3.6.3/core-3.6.3.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/com/electronwill/night-config/toml/3.6.3/toml-3.6.3.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/net/minecraftforge/nashorn-core-compat/15.1.1.1/nashorn-core-compat-15.1.1.1.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  C:/Users/andyr/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/andyr/Desktop/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] abnormals_core-1.16.5-3.3.0
  [✔️] AdvancedRocketry-1.16.5-2.0.0-12-universal
  [✔️] AI-Improvements-1.16.2-0.3.0
  [✔️] antiqueatlas-6.0.1-forge-mc1.16.5
  [✔️] appleskin-forge-mc1.16.x-2.2.0
  [✔️] appliedenergistics2-8.4.4
  [✔️] Aquaculture-1.16.5-2.1.21
  [✔️] archers_paradox-1.16.5-1.4.0.1
  [✔️] Architects-Palette-1.16.4-1.1.4
  [✔️] architectury-1.24.35-forge
  [✔️] BackTools-1.16.5-10.1.0
  [✔️] BetterAdvancements-1.16.5-0.1.0.108
  [✔️] BetterBurning-1.16.5-6.0.6
  [✔️] BiomesOPlenty-1.16.5-13.1.0.482-universal
  [✔️] Buddycards-1.16.5-2.5.2
  [✔️] bwncr-1.16.5-3.10.16
  [✔️] catalogue-1.5.0-1.16.5
  [✔️] cavebiomeapi-1.16.5-1.3.7
  [✔️] CBMultipart-1.16.5-3.0.3.122-universal
  [✔️] cc-tweaked-1.16.5-1.99.1
  [✔️] Chisel-MC1.16.5-2.0.1-alpha.4
  [✔️] chiselsandbits-1.0.43
  [✔️] Chunk Pregenerator-V1.16-3.2.0
  [✔️] ChunkNoGoByeBye-1.16.5-1.3.0
  [✔️] cloth-config-4.12.41-forge
  [✔️] Clumps-6.0.0.27
  [✔️] cobblegenrandomizer-1.16-5.1.2
  [✔️] CodeChickenLib-1.16.5-4.0.5.438-universal
  [✔️] cofh_core-1.16.5-1.4.0.6
  [✔️] configured-1.5.1-1.16.5
  [✔️] connectivity-2.4-1.16.5
  [✔️] constructionwand-1.16.5-2.6
  [✔️] Controlling-7.0.0.28
  [✔️] cookiecore-1.16.5-3.3.0-12106d2
  [✔️] corpse-1.16.5-1.0.6
  [✔️] CosmeticArmorReworked-1.16.5-v4a
  [✔️] CraftingTweaks_1.16.5-12.2.1
  [✔️] crashutilities-3.12
  [✔️] create-mc1.16.5_v0.3.2g
  [✔️] CTM-MC1.16.1-1.1.2.6
  [✔️] culinaryconstruct-forge-1.16.5-4.0.0.6
  [✔️] curios-forge-1.16.5-4.0.5.3
  [✔️] darkerdepths-1.16.5-1.1.4
  [✔️] decorative_blocks_abnormals-1.2
  [✔️] decorative_blocks-1.16.4-1.7.2
  [✔️] DefaultOptions_1.16.5-12.2.1
  [✔️] Desolation 1.1.0-2 1.16.5
  [✔️] Dice-1.16.5-1.2.0
  [✔️] drinkbeer-1.16.5-2.3.5
  [✔️] DungeonCrawl-1.16.5-2.3.2
  [✔️] enchantedbookredesign-3.3-1.16.4
  [✔️] endergetic-1.16.4-3.0.0
  [✔️] EnderStorage-1.16.5-2.8.0.168-universal
  [✔️] Exchangers-1.16.5-3.0.2
  [✔️] exoticbirds-1.16.4-1.3.0
  [✔️] extcaves-2.4
  [✔️] fairylights-4.0.5-1.16.5
  [✔️] FarmersDelight-1.16.5-0.5.3
  [✔️] fastfurnaceminusreplacement-1.1-1.16.3
  [✔️] FastLeafDecay-v25
  [✔️] FastWorkbench-1.16.4-4.5.1
  [✔️] ferritecore-2.1.0-forge
  [✔️] flywheel-1.16-0.2.5
  [✔️] forbidden_arcanus-16.2.2
  [✔️] ftb-backups-2.1.2.2
  [✔️] ftb-chunks-forge-1605.3.2-build.83
  [✔️] ftb-library-forge-1605.3.4-build.90
  [✔️] ftb-quests-forge-1605.3.5-build.72
  [✔️] ftb-teams-forge-1605.2.3-build.40
  [✔️] grapplemod-1.16.5-v12
  [✔️] GunpowderLib-1.16.5-1.2.2
  [✔️] iChunUtil-1.16.5-10.5.0
  [✔️] ImprovedBackpacks-1.6.2.0
  [✔️] inventorysorter-1.16.1-18.1.0
  [✔️] item-filters-forge-1605.2.5-build.9
  [✔️] Jade-1.16.4-2.8.0
  [✔️] jei-1.16.5-7.7.1.137
  [✔️] kubejs-create-1605.1.2-build.7
  [✔️] kubejs-forge-1605.3.19-build.229
  [✔️] kubejs-thermal-1605.1.4-build.3
  [✔️] LibVulpes-1.16.5-1.0.2-25-universal
  [✔️] lootr-1.16.5-0.0.9.30
  [✔️] magicfeather-1.16.2-3.2.0
  [✔️] Mantle-1.16.5-1.6.147
  [✔️] metalbarrels-1.16.2-3.3b
  [✔️] mightyarchitect-mc1.16.3_v0.5
  [✔️] moreminecarts-1.3.12
  [✔️] MoreObservers-1.4.1-MC1.16-Forge
  [✔️] Morpheus-1.16.5-4.2.70
  [✔️] MouseTweaks-2.14-mc1.16.2
  [✔️] NaturesCompass-1.16.5-1.9.1-forge
  [✔️] nolakes-0.1-1.16.4
  [✔️] occultism-1.16.5-1.20.1
  [✔️] OpenLoader-1.16.5-9.0.3
  [✔️] orcinusscaves-1.3
  [✔️] OreTweaker-1.16.5-2.6.0
  [✔️] paintings-1.16.4-7.0.0.1
  [✔️] Patchouli-1.16.4-53.2
  [✔️] PathToDirt-1.2.0-mc1.16.x
  [✔️] pipez-1.16.5-1.2.13
  [✔️] Placebo-1.16.5-4.6.0
  [✔️] ponderjs-1.16.5-1.0.3d
  [✔️] portable_stonecutter-1.16.5-1.3.5
  [✔️] portality-1.16.5-3.2.5
  [✔️] PrettyPipes-1.9.5
  [✔️] ProjectRed-1.16.5-4.11.0-beta-6-core
  [✔️] ProjectRed-1.16.5-4.11.0-beta-6-illumination
  [✔️] ProjectRed-1.16.5-4.11.0-beta-6-integration
  [✔️] ProjectRed-1.16.5-4.11.0-beta-6-transmission
  [✔️] randomium-1.16.5-1.7
  [✔️] ravencoffee-1.16.5-beta_01
  [✔️] reliquary-1.16.5-1.3.5.1100
  [✔️] repurposed_structures_forge-3.4.4+1.16.5
  [✔️] rhino-forge-1605.1.5-build.75
  [✔️] Rubber_Duck-1.16.5-1.2.0
  [✔️] Scorge-3.1.3
  [✔️] selene-1.16.5-1.9.0
  [✔️] shutupexperimentalsettings-1.0.3
  [✔️] SoundFilters-0.14_for_1.16.2
  [✔️] spark-forge
  [✔️] SpawnerFix-1.16.2-1.0.0.2
  [✔️] StorageDrawers-1.16.3-8.3.0
  [✔️] strawgolem-1.16-1.9
  [✔️] structurescompass-1.16.5-1.2.0
  [✔️] supplementaries-1.16.5-0.17.12b
  [✔️] TConstruct-1.16.5-3.3.0.308
  [✔️] thermal_expansion-1.16.5-1.4.1.3
  [✔️] thermal_foundation-1.16.5-1.4.1.7
  [✔️] thermal_innovation-1.16.5-1.4.1.3
  [✔️] thermal_locomotion-1.16.5-1.4.1.2
  [✔️] titanium-1.16.5-3.2.8.7-22
  [✔️] torchmaster-2.3.8
  [✔️] valhelsia_core-16.0.13a
  [✔️] WaterStrainer-1.16.3-10.0.0
  [✔️] worldshape-1.0
  [✔️] xkdeco_0.2.4

Params:
  --username  --version MultiMC5 --gameDir C:/Users/andyr/Desktop/MultiMC/instances/Create- Above and Beyond/minecraft --assetsDir C:/Users/andyr/Desktop/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 36.2.20 --fml.mcVersion 1.16.5 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20210115.111550

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms8192m, -Xmx8192m, -Duser.language=en]

Minecraft process ID: 17780

Using onesix launcher.

Checking: MC_SLIM
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: PATCHED
Checking: MC_SRG
2022-01-30 18:47:08,836 main WARN Advanced terminal features are not available in this environment
[18:47:08] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, j9981, --version, MultiMC5, --gameDir, C:/Users/andyr/Desktop/MultiMC/instances/Create- Above and Beyond/minecraft, --assetsDir, C:/Users/andyr/Desktop/MultiMC/assets, --assetIndex, 1.16, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.20, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[18:47:08] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_321 by Oracle Corporation
[18:47:09] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[18:47:09] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/andyr/Desktop/MultiMC/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[18:47:11] [main/ERROR] [mixin/]: Mixin config antiqueatlas.mixins.json does not specify "minVersion" property
[18:47:11] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:213]: Failed to start Minecraft:
[18:47:11] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: java.lang.reflect.InvocationTargetException
[18:47:11] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:47:11] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:47:11] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:47:11] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[18:47:11] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[18:47:11] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[18:47:11] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[18:47:11] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[18:47:11] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: Caused by: java.lang.reflect.InvocationTargetException
[18:47:11] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:47:11] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:47:11] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:47:11] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[18:47:11] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
[18:47:11] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	... 8 more
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.forName0(Native Method)
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.forName(Unknown Source)
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:67)
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:70)
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:59)
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:196)
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.HashMap.forEach(Unknown Source)
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[18:47:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 13 more
[18:47:11] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1
Process exited with code -1.

### **Steps to reproduce:**

1. Download 1.16.5 modpack
2. Launch

### **Suspected Cause:**
   
I dunno man, I've:

1. reinstalled both java 8 and 17
2. tried changed the modpack instance java verison
3. reinstalled MultiMC
4. used different sources for java versions

### **This issue is semi-unique:**
1. I've seen this posted on Reddit only once before and the solution was to update graphics drivers, mine are up-to-date.

**Comment by phit** [comment]
Forge is broken with Java 8 Update 321 or newer
You need an older Java 8 version, e.g. 8u312 you can find downloads here https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk
