### ISSUE TITLE
Error Code 255

### ISSUE THREAD

**Issue by Hawk2811** [MultiMC/Launcher#4478]
Minecraft dont start with forge

OS: macOS 12 Monterrey

Minecraft Log

MultiMC version: 0.6.14-3000

Launched instance in online mode

authserver.mojang.com resolves to:
    [52.84.156.71]

session.minecraft.net resolves to:
    [18.210.95.126, 34.231.157.213, 52.1.29.34]

textures.minecraft.net resolves to:
    [13.35.118.20, 13.35.118.116, 13.35.118.34, 13.35.118.113]

api.mojang.com resolves to:
    [65.8.209.24]

Minecraft folder is:
/Volumes/Dados/Applications/MultiMC.app/Data/instances/Hawk/.minecraft

Java path is:
/usr/bin/java

Checking Java version...
Java is version 17.0.2, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  /Volumes/Dados/Applications/MultiMC.app/Data/instances/Hawk/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/net/minecraftforge/forge/1.16.5-36.2.23/forge-1.16.5-36.2.23-launcher.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/cpw/mods/grossjava9hacks/1.3.3/grossjava9hacks-1.3.3.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/com/electronwill/night-config/core/3.6.3/core-3.6.3.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/com/electronwill/night-config/toml/3.6.3/toml-3.6.3.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/net/minecraftforge/nashorn-core-compat/15.1.1.1/nashorn-core-compat-15.1.1.1.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-macos.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-macos.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-macos.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-macos.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-macos.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-macos.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-macos.jar
  /Volumes/Dados/Applications/MultiMC.app/Data/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar

Mods:
  [✔️] [1.16.5]+SecurityCraft+v1.9.0.1
  [✔️] architectury-1.26.39
  [✔️] backpacked-1.10.1-mc1.16.3
  [✔️] backpacker-1.3.1-mc1.16.3
  [❌] car-1.16.5-1.0.17.jar (disabled)
  [✔️] cc-tweaked-1.16.5-1.99.1
  [✔️] cfm-7.0.0-pre22-mc1.16.3
  [✔️] cgm-1.1.0-mc1.16.5
  [✔️] configured-1.5.1-1.16.5
  [✔️] dynamiclights-1.16.5.1
  [✔️] ExtremeReactors2-1.16.5-2.0.36
  [✔️] ftb-library-forge-1605.3.4-build.90
  [✔️] ftb-ultimine-forge-1605.3.1-build.45
  [❌] Futurepack-1.16.5-31.3.7000.jar (disabled)
  [✔️] geckolib-forge-1.16.5-3.0.57
  [✔️] goldenhopper-1.2.1-mc1.16.3
  [✔️] gravestone-1.16.5-1.0.6
  [✔️] guardvillagers-1.16.5.1.2.5
  [✔️] invtweaks-1.16.2-1.0.0
  [✔️] ironchest-1.16.5-11.2.21
  [✔️] ironfurnaces-1.16.5-2.7.7
  [✔️] jei-1.16.5-7.7.1.138
  [✔️] Mantle-1.16.5-1.6.152
  [✔️] mcw-bridges-2.0.1-mc1.16.5
  [✔️] mcw-fences-1.0.1-mc1.16.5
  [✔️] mcw-lights-1.0.0-mc1.16.5
  [✔️] Mekanism-1.16.5-10.0.24.453
  [✔️] nuclear_craft-1.16.5-0.9.3
  [✔️] obfuscate-0.6.2-1.16.3
  [✔️] OptiFine_1.16.5_HD_U_G8
  [✔️] OreTweaker-1.16.5-2.6.0
  [✔️] Patchouli-1.16.4-53.2
  [❌] plane-1.16.5-1.0.9.jar (disabled)
  [✔️] platos-1.5.1
  [✔️] potionsmaster-0.2.2-1.16.5-36.1.0
  [✔️] ResourcefulBees-1.16.5-0.10.1
  [✔️] simpleplanes-1.16.5-4.6.0
  [✔️] smallships-1.16.5-1.10.1
  [✔️] TConstruct-1.16.5-3.3.2.324
  [✔️] vehicle-0.45.1-mc1.16.3
  [✔️] vehicle-mod-0.45.2-1.16.3
  [✔️] WirelessRedstone-1.16.5-1.1.1
  [✔️] Xaeros_Minimap_21.22.5_Forge_1.16.5
  [✔️] XaerosWorldMap_1.18.7_Forge_1.16.5
  [✔️] ZeroCore2-1.16.5-2.1.9

Params:
  --username  --version MultiMC5 --gameDir /Volumes/Dados/Applications/MultiMC.app/Data/instances/Hawk/.minecraft --assetsDir /Volumes/Dados/Applications/MultiMC.app/Data/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 36.2.23 --fml.mcVersion 1.16.5 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20210115.111550

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: Hawk", -XstartOnFirstThread, -Xms4096m, -Xmx8192m, -Duser.language=en]

Minecraft process ID: 1251

Using onesix launcher.

Checking: MC_SLIM
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: PATCHED
Checking: MC_SRG
2022-02-01 14:48:28,543 main WARN Advanced terminal features are not available in this environment
[14:48:28] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Hawk084, --version, MultiMC5, --gameDir, /Volumes/Dados/Applications/MultiMC.app/Data/instances/Hawk/.minecraft, --assetsDir, /Volumes/Dados/Applications/MultiMC.app/Data/assets, --assetIndex, 1.16, --uuid, <ID DO PERFIL>, --accessToken, ❄❄❄❄❄❄❄❄, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.23, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --width, 854, --height, 480]
[14:48:28] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 17.0.2 by Oracle Corporation
[14:48:28] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[14:48:28] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file: /Volumes/Dados/Applications/MultiMC.app/Data/instances/Hawk/.minecraft/mods/OptiFine_1.16.5_HD_U_G8.jar
[14:48:28] [main/INFO] [op.OptiFineTransformer/]: Target.PRE_CLASS is available
[14:48:28] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[14:48:28] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/Volumes/Dados/Applications/MultiMC.app/Data/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[14:48:28] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[14:48:29] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.transformers
[14:48:29] [main/INFO] [op.OptiFineTransformer/]: Targets: 311
[14:48:30] [main/INFO] [op.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
[14:48:30] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:213]: Failed to start Minecraft:
[14:48:30] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: java.lang.reflect.InvocationTargetException
[14:48:30] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:48:30] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[14:48:30] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:48:30] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[14:48:30] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[14:48:30] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[14:48:30] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[14:48:30] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[14:48:30] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: Caused by: java.lang.reflect.InvocationTargetException
[14:48:30] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:48:30] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[14:48:30] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:48:30] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[14:48:30] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
[14:48:30] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	... 8 more
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: Caused by: java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at java.base/java.lang.Class.forName0(Native Method)
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at java.base/java.lang.Class.forName(Class.java:467)
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:67)
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:70)
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:59)
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:196)
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[14:48:30] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	... 13 more
[14:48:30] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1
O processo foi encerrado com o código 255.
Clipboard copy at: 01 Feb 2022 14:50:41 -0300

**Comment by phit** [comment]
Forge is broken with Java 8 Update 321 or newer
You need an older Java 8 version, e.g. 8u312 you can find downloads here https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk
