### ISSUE TITLE
a problem with 1.8.9

### ISSUE THREAD

**Issue by nyakeisi** [MultiMC/Launcher#4554]
### Operating System

Windows

### Description of bug

so, I'm trying to launch MC 1.8.9 without forge and it works fine, but when I'm trying to install forge (only forge, no mods at all) an error happens:
```
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi in java.library.path, C:\Users\\AppData\Local\Temp\jansi-64-756433856019784351.dll: Can't find dependent libraries]
	at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
	at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
	at org.fusesource.jansi.internal.Kernel32.<clinit>(Kernel32.java:37)
	at org.fusesource.jansi.WindowsAnsiOutputStream.<clinit>(WindowsAnsiOutputStream.java:52)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.logging.log4j.core.appender.ConsoleAppender.getOutputStream(ConsoleAppender.java:128)
	at org.apache.logging.log4j.core.appender.ConsoleAppender.getManager(ConsoleAppender.java:104)
	at org.apache.logging.log4j.core.appender.ConsoleAppender.createAppender(ConsoleAppender.java:99)
	at org.apache.logging.log4j.core.config.DefaultConfiguration.<init>(DefaultConfiguration.java:54)
	at org.apache.logging.log4j.core.LoggerContext.<init>(LoggerContext.java:63)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:217)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:114)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:81)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:83)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:34)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:387)
	at net.minecraft.launchwrapper.LogWrapper.configureLogging(LogWrapper.java:14)
	at net.minecraft.launchwrapper.LogWrapper.log(LogWrapper.java:28)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:94)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1.
```

with development build: 
```
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1.
```
currently, I've tried java versions 17, 17.0.2, 16, 16.0.2, 8 321 and many more, I haven't counted.
_ps. official launcher, lunar, labymod, and badlion crashing to._

### Steps to reproduce

just trying to launch Minecraft with Forge.

### Suspected cause

It's probably Forge (still no mods at all) because only after installing it happens.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
please provide a full log with Java 8

![grafik](https://user-images.githubusercontent.com/2097483/156392610-4cee5401-2514-4a91-b3f0-34d1cb69d54d.png)

**Comment by nyakeisi** [comment]
https://paste.ee/p/hPD32

**Comment by phit** [comment]
that's using java 17, you need to switch to java 8 https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#setting-up-java-in-multimc
