### ISSUE TITLE
SIGSEGV when launching MultiMC/DevLauncher

### ISSUE THREAD

**Issue by sp1ritCS** [MultiMC/Launcher#4588]
### Operating System

Linux

### Description of bug

This might be the same as https://github.com/MultiMC/Launcher/issues/2795, however given the time delta and the fact that MMC worked until recently I don't think so.

When launching the latest released MultiMC or the latest "DevLauncher" from git, it takes a few seconds but then it crashes with SIGSEGV.

OS: openSUSE Tumbleweed 20220316

Backtrace:
```
#0  malloc_consolidate (av=av@entry=0x7ffff5aedaa0 <main_arena>) at malloc.c:4732
4732	 unsorted_bin = unsorted_chunks(av);
[Current thread is 1 (Thread 0x7ffff6c07840 (LWP 8601))]
(gdb) bt
#0  malloc_consolidate (av=av@entry=0x7ffff5aedaa0 <main_arena>) at malloc.c:4732
#1  0x00007ffff5987bf8 in _int_malloc (av=av@entry=0x7ffff5aedaa0 <main_arena>, bytes=bytes@entry=32796) at malloc.c:3965
#2  0x00007ffff5989179 in __GI___libc_malloc (bytes=32796) at malloc.c:3329
#3  0x00007ffff5e1d211 in QArrayData::allocate (objectSize=objectSize@entry=2, alignment=alignment@entry=8, capacity=capacity@entry=16386, options=..., options@entry=...)
    at tools/qarraydata.cpp:218
#4  0x00007ffff5e92dd3 in QTypedArrayData<unsigned short>::allocate (options=..., capacity=16386) at ../../include/QtCore/../../src/corelib/tools/qarraydata.h:224
#5  QString::QString (this=this@entry=0x7fffff7ff1e8, size=size@entry=16385) at text/qstring.cpp:2163
#6  0x00007ffff6051ee7 in QUtf8::convertToUnicode (
    chars=0x7fffff7ff280 "61c000 r--p 00000000 00:25 12227793", ' ' <repeats 19 times>, "/usr/lib64/libxcb-render.so.0.0.0\n7ffff261c000-7ffff2621000 r-xp 00006000 00:25 12227793", ' ' <repeats 19 times>, "/usr/lib64/libxcb-render.so.0.0.0\n7ffff"..., len=16384, state=0xead678) at codecs/qutfcodec.cpp:561
#7  0x00007ffff6052776 in QUtf8Codec::convertToUnicode (this=<optimized out>, chars=<optimized out>, len=<optimized out>, state=<optimized out>) at codecs/qutfcodec.cpp:994
#8  0x00007ffff607f5c0 in QTextCodec::toUnicode (state=0xead678, length=16384, 
    in=0x7fffff7ff280 "61c000 r--p 00000000 00:25 12227793", ' ' <repeats 19 times>, "/usr/lib64/libxcb-render.so.0.0.0\n7ffff261c000-7ffff2621000 r-xp 00006000 00:25 12227793", ' ' <repeats 19 times>, "/usr/lib64/libxcb-render.so.0.0.0\n7ffff"..., this=<optimized out>) at ../../include/QtCore/../../src/corelib/codecs/qtextcodec.h:114
#9  QTextStreamPrivate::fillReadBuffer (this=0xead640, maxBytes=-1) at serialization/qtextstream.cpp:490
#10 0x00007ffff6082d54 in QTextStreamPrivate::scan (delimiter=QTextStreamPrivate::EndOfLine, maxlen=<optimized out>, length=<synthetic pointer>, ptr=<synthetic pointer>, 
    this=0xead640) at serialization/qtextstream.cpp:699
#11 QTextStream::readLineInto (this=<optimized out>, line=0x7fffff8033d8, maxlen=0) at serialization/qtextstream.cpp:1718
#12 0x00007ffff6082ff0 in QTextStream::readLine (this=this@entry=0x7fffff803420, maxlen=maxlen@entry=0) at serialization/qtextstream.cpp:1676
#13 0x00007ffff109020f in DPluginLoader::resolveFromPSM (moduleName=...) at ../../../src/dpluginloader.h:87
#14 DPluginLoader::pluginName (baseName=...) at ../../../src/dpluginloader.h:119
#15 DPluginLoader::load<QImageIOPlugin> (baseName=...) at ../../../src/dpluginloader.h:140
#16 0x00007ffff1090877 in QSvgPlugin::QSvgPlugin (this=<optimized out>, parent=<optimized out>, this=<optimized out>, parent=<optimized out>)
    at /usr/src/debug/qt5integration-5.5.17-1.1.x86_64/src/imageformats/svgchooser/main.cpp:45
#17 0x00007ffff1090957 in qt_plugin_instance () at /usr/src/debug/qt5integration-5.5.17-1.1.x86_64/src/imageformats/svgchooser/main.moc:121
#18 0x00007ffff5feced7 in QLibraryPrivate::pluginInstance (this=0xf578f0) at plugin/qlibrary.cpp:557
#19 0x00007ffff5fde2d3 in QPluginLoader::instance (this=this@entry=0x7fffff8035a0) at plugin/qpluginloader.cpp:199
#20 0x00007ffff108f228 in DPluginLoader::load<QImageIOPlugin> (baseName=...) at ../../../src/dpluginloader.h:142
[starts looping, starting with QSvgPlugin::QSvgPlugin]
```

Coredump:
[core.8601.gz](https://github.com/MultiMC/Launcher/files/8307665/core.8601.gz)

### Steps to reproduce

- Build DevLauncher from git
- launch DevLauncher

### Suspected cause

I suspect this to be some kind of memleak, because changing envvars changed where the error originated. I've seen staring with
- `malloc_consolidate` (like backtrace above)
- `_int_malloc`
- `calculateBlockSize` (called from QArrayData::allocate)
- `QString::QString`

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by peterix** [comment]
This doesn't appear to happen in MultiMC code and looks more like a Qt bug. Make sure all your Qt packages are fully updated.

**Comment by sp1ritCS** [comment]
Sorry, I reverted to an earlier snapshot and updated all packages incrementally.

It turns out that an update to [qt5integration](https://github.com/linuxdeepin/qt5integration) 5.5.17 has caused this, and it affects other Qt5 applications aswell. A fix is already in Factory and should make it's way to Tumbleweed soon.

Sorry for bothering you 😄
