### ISSUE TITLE
Forge and Fabric mods don't work and the game doesn't launch with the error code -1

### ISSUE THREAD

**Issue by Jares600** [MultiMC/Launcher#4623]
### Description of bug

so I recently installed MultiMC and used a 1.12.2 instance and added forge to it because I wanted to try mods in singleplayer,
so first I just added the mods which are just the pogo stick mod, optifine and toggle sneak and yes I did check their version and downloaded the 1.12.2 ones so its not about the mods, then launched it but it just didn't work and just exited with code -1 or whatever the hell that means, tried different versions such as 1.18.2 and the same issue occurred again, the game didn't launch with the mods but launched normally.

### Steps to reproduce

heres the error in the logs 

java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:110)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 5 more

### Suspected cause

I don't think its about the mods, I still haven't tried to launch it offline but anyways I don't really know anything that could cause this issue especially that it was running smoothly at the beginning.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DragonFire24424** [comment]
it was just to have used the java version 8 (311) 
link: [Download](https://drive.google.com/file/d/1fyEzHq3Agv2d98ptDlFBflWxh7g4cZtA/view?usp=sharing)
ops: the link is from my drive, so there is no virus

**Comment by Kneelawk** [comment]
Hi. The Java version you're using doesn't appear to be Java-8. `jdk.internal.loader.ClassLoaders$AppClassLoader` was added in Java-9, which is incompatible with many Minecraft versions prior to 1.17.

You can download an official Java-8 release from Adoptium at [https://adoptium.net/temurin/releases](https://adoptium.net/temurin/releases), by clicking the `Version` menu, selecting `8`, and clicking the download button for your OS (the first `.msi` download for Windows, the first `.pkg` download for Mac, etc.).

You will likely want to reboot after installing the Adoptium Java-8 so that everything will be set-up correctly. Then when you open MultiMC, you can click on the `Settings` button at the top, then the `Java` button on the left side of the new window, then the `Auto-detect...` button, and then your new Java-8 should be listed there and you can select it. It should be called something like `1.8.0_322`.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
