### ISSUE TITLE
Ubuntu budgie: "A required function is missing: glfwInitAllocator"

### ISSUE THREAD

**Issue by Fictitious-Rotor** [MultiMC/Launcher#4789]
### Operating System

Ubuntu Budgie 22.04 LTS

### Description of bug

Crash on launch of 1.19; does not occur with official minecraft launcher

```
[10:54:26] [main/INFO]: Building optimized datafixer
[10:54:34] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10:54:37] [Render thread/INFO]: Setting user: Rotor_
[10:54:38] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 build 7
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 22/06/2022, 10:54
Description: Initializing game

java.lang.ExceptionInInitializerError
	at org.lwjgl.glfw.GLFW.nglfwGetError(GLFW.java:1219)
	at org.lwjgl.glfw.GLFW.glfwGetError(GLFW.java:1248)
	at dyx.a(SourceFile:135)
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:58)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:826)
	at eev.<init>(SourceFile:465)
	at net.minecraft.client.main.Main.main(SourceFile:198)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NullPointerException: A required function is missing: glfwInitAllocator
	at org.lwjgl.system.APIUtil.requiredFunctionMissing(APIUtil.java:129)
	at org.lwjgl.system.APIUtil.apiGetFunctionAddress(APIUtil.java:122)
	at org.lwjgl.glfw.GLFW$Functions.<clinit>(GLFW.java:42)
	... 15 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.lwjgl.glfw.GLFW.nglfwGetError(GLFW.java:1219)
	at org.lwjgl.glfw.GLFW.glfwGetError(GLFW.java:1248)
	at dyx.a(SourceFile:135)
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:58)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:826)
	at eev.<init>(SourceFile:465)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:198)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Linux (amd64) version 5.15.0-39-generic
	Java Version: 17.0.3, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 2277364560 bytes (2171 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 2.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: HD Graphics 530
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x191b
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 7950.42
	Virtual memory used (MB): 5464.68
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms4096m -Xmx4096m
	Launched Version: 1.19
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /home/sam/Minecraft/MultiMC/instances/1.19/.minecraft/crash-reports/crash-2022-06-22_10.54.38-client.txt
Process exited with code 255 (0xff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
```

### Steps to reproduce

Ubuntu budgie -> launch 1.19 with LWJGL 3.3.1

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
did you enable system glfw in the launcher settings?

**Comment by Fictitious-Rotor** [comment]
> did you enable system glfw in the launcher settings?

I had, I've disabled it and tried again and the issue is resolved. Not sure why I have LWJGL on my system as I don't remember installing it but thank you for helping me :)
