### ISSUE TITLE
Minecraft isn't Launching.

### ISSUE THREAD

**Issue by roselessmc** [MultiMC/Launcher#4795]
Log:
MultiMC version: 0.6.16-3431

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.160.194.35, 18.160.194.44, 18.160.194.40, 18.160.194.57]

session.minecraft.net resolves to:
    [54.173.66.187, 54.164.34.185, 52.7.153.255]

textures.minecraft.net resolves to:
    [18.160.200.51, 18.160.200.107, 18.160.200.11, 18.160.200.72]

api.mojang.com resolves to:
    [18.160.200.10, 18.160.200.113, 18.160.200.51, 18.160.200.115]

Minecraft folder is:
C:/Users/dontshowmyuser/MultiMC/instances/1.16.5java8pack/.minecraft

Java path is:
C:/Program Files/Eclipse Adoptium/jdk-8.0.332.9-hotspot/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_332, using 64-bit architecture, from Temurin.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/dontshowmyuser/MultiMC/instances/1.16.5java8pack/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/dontshowmyuser/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/net/minecraftforge/forge/1.16.5-36.2.20/forge-1.16.5-36.2.20-launcher.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/cpw/mods/grossjava9hacks/1.3.3/grossjava9hacks-1.3.3.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/com/electronwill/night-config/core/3.6.3/core-3.6.3.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/com/electronwill/night-config/toml/3.6.3/toml-3.6.3.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/net/minecraftforge/nashorn-core-compat/15.1.1.1/nashorn-core-compat-15.1.1.1.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  C:/Users/dontshowmyuser/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/dontshowmyuser/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] BiomesOPlenty-1.16.5-13.1.0.487-universal
  [✔️] cfm-7.0.0-pre22-mc1.16.3
  [✔️] DynamicTrees-1.16.5-0.10.0-Beta33
  [✔️] DynamicTreesBOP-1.16.5-2.0.8
  [✔️] ImmersiveRailroading-1.16.5-forge-1.9.1
  [✔️] LandOfSignals-1.16.5-forge-0.0.4-HOTFIX-1
  [✔️] macawsbridgesbop-1.16.5-1.4
  [✔️] macawsroofsbop-1.16.5-1.2
  [✔️] mcw-bridges-2.0.3-mc1.16.5
  [✔️] mcw-doors-1.0.6-mc1.16.5
  [✔️] mcw-fences-1.0.5-mc1.16.5
  [✔️] mcwfencesbop-1.16.5-1.2
  [✔️] mcw-furniture-3.0.0-mc1.16.5
  [✔️] mcw-lights-1.0.3-mc1.16.5
  [✔️] mcw-paintings-1.0.3-mc1.16.5
  [✔️] mcw-paths-1.0.0-mc1.16.5
  [✔️] mcw-roofs-2.1.2-mc1.16.5
  [✔️] mcw-trapdoors-1.0.5-mc1.16.5
  [✔️] mcw-windows-2.0.3-mc1.16.5
  [✔️] morecfm-1.3.1-mc1.16.3
  [✔️] obfuscate-0.6.3-1.16.5
  [✔️] OptiFine_1.16.5_HD_U_G8
  [✔️] pamhc2crops-1.16.3-1.0.2
  [✔️] pamhc2foodcore-1.16.3-1.0.2
  [✔️] pamhc2foodextended-1.16.3-1.0.4
  [✔️] pamhc2trees-1.16.3-1.0.1
  [✔️] SereneSeasons-1.16.5-4.0.1.125-universal
  [✔️] TrackAPI-1.16.4-forge-1.2.1
  [✔️] UniversalModCore-1.16.5-forge-1.1.3
  [✔️] vehicle-0.45.1-mc1.16.3
  [✔️] worldedit-mod-7.2.5-dist

Params:
  --username  --version 1.16.5 --gameDir C:/Users/adoub/MultiMC/instances/1.16.5java8pack/.minecraft --assetsDir C:/Users/adoub/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 36.2.20 --fml.mcVersion 1.16.5 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20210115.111550

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx8192m, -Duser.language=en]

Minecraft process ID: 20468

Using onesix launcher.

Checking: MC_SLIM
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: PATCHED
Checking: MC_SRG
2022-06-26 08:10:49,556 main WARN Advanced terminal features are not available in this environment
[08:10:49] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, roseless_, --version, 1.16.5, --gameDir, C:/Users/adoub/MultiMC/instances/1.16.5java8pack/.minecraft, --assetsDir, C:/Users/adoub/MultiMC/assets, --assetIndex, 1.16, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.20, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --width, 854, --height, 480]
[08:10:49] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_332 by Temurin
[08:10:50] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[08:10:50] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file: C:\Users\dontshowmyuser\MultiMC\instances\1.16.5java8pack\.minecraft\mods\OptiFine_1.16.5_HD_U_G8.jar
[08:10:50] [main/INFO] [op.OptiFineTransformer/]: Target.PRE_CLASS is available
[08:10:50] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[08:10:51] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/dontshowmyuser/MultiMC/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[08:10:51] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[08:10:57] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.transformers
[08:10:57] [main/INFO] [op.OptiFineTransformer/]: Targets: 311
[08:10:58] [main/INFO] [op.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
[08:10:59] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.16.5, --gameDir, C:\Users\dontshowmyuser\MultiMC\instances\1.16.5java8pack\.minecraft, --assetsDir, C:\Users\dontshowmyuser\MultiMC\assets, --uuid, <PROFILE ID>, --username, roseless_, --assetIndex, 1.16, --accessToken, ????????, --userType, msa, --versionType, release, --width, 854, --height, 480]
[08:10:59] [main/ERROR] [mixin/]: Error loading companion plugin class [com.mrcrayfish.obfuscate.mixin.ObfuscateMixinPlugin] for mixin config [obfuscate.mixins.json]. The plugin may be out of date: NoSuchMethodError:sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_332] {}
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_332] {}
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_332] {}
	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:76) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.PluginHandle.<init>(PluginHandle.java:96) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:706) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.0.9.jar:8.0.9+86+master.3cf110c] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_332] {}
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_332] {}
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_332] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.20-launcher.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc3.jar:mmc3] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
[Serene Seasons Transformer]: Transforming func_228438_a_ in net/minecraft/client/renderer/WorldRenderer
[Serene Seasons Transformer]: Patched 1 calls
[Serene Seasons Transformer]: Transforming func_228436_a_ in net/minecraft/client/renderer/WorldRenderer
[Serene Seasons Transformer]: Patched 1 calls
[08:11:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:213]: Failed to start Minecraft:
[08:11:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: java.lang.reflect.InvocationTargetException
[08:11:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:11:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[08:11:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:11:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[08:11:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[08:11:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[08:11:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[08:11:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[08:11:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: Caused by: java.lang.reflect.InvocationTargetException
[08:11:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:11:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[08:11:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:11:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[08:11:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
[08:11:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	... 8 more
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	... 13 more
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: Caused by: java.lang.reflect.InvocationTargetException
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	... 17 more
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: Caused by: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at net.minecraft.util.math.MathHelper.<clinit>(MathHelper.java:20)
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at net.minecraft.util.Util.func_240979_a_(Util.java:109)
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at net.minecraft.util.Util.<clinit>(Util.java:65)
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at net.minecraft.client.main.Main.main(Main.java:63)
[08:11:02] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	... 23 more
[08:11:02] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 26 Jun 2022 08:11:19 -0500
Clipboard copy at: 26 Jun 2022 08:15:20 -0500

**Comment by phit** [comment]
Forge 34.1.27 to 36.2.24 (Minecraft 1.16.3-1.16.5) are broken with Java 8 Update 321 or newer.
If you are on 1.16.5 try upgrading your instances Forge version. If this isn't an option for you, you need an older Java 8 version, e.g. 8u312 you can find downloads here <https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk>

the crash will contain this
```
Caused by: java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
```
