### ISSUE TITLE
Failed to start Minecraft

### ISSUE THREAD

**Issue by xephrx** [MultiMC/Launcher#4800]
### Operating System

Windows

### Description of bug

Minecraft continuously fails to launch, hope the following data below is enough to help

### Steps to reproduce

1) Install the following custom modpack mods
2) Launch game

Log:
MultiMC version: 0.6.16-3431

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.224.4.35, 13.224.4.58, 13.224.4.54, 13.224.4.53]

session.minecraft.net resolves to:
    [34.202.22.53, 3.216.64.49, 52.204.38.144]

textures.minecraft.net resolves to:
    [13.224.2.19, 13.224.2.51, 13.224.2.89, 13.224.2.100]

api.mojang.com resolves to:
    [99.86.38.109, 99.86.38.43, 99.86.38.45, 99.86.38.128]

Minecraft folder is:
C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/instances/CustomMods/.minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 17.0.3.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/instances/CustomMods/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/datafixerupper/4.1.27/datafixerupper-4.1.27.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/3.3.39/authlib-3.3.39.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.12.4/text2speech-1.12.4.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/cpw/mods/securejarhandler/1.0.3/securejarhandler-1.0.3.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm/9.2/asm-9.2.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/eventbus/5.0.3/eventbus-5.0.3.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forgespi/4.0.10/forgespi-4.0.10.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/cpw/mods/modlauncher/9.1.3/modlauncher-9.1.3.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/cpw/mods/bootstraplauncher/1.0.0/bootstraplauncher-1.0.0.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/fmlloader/1.18.2-40.1.0/fmlloader-1.18.2-40.1.0.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.18.2/minecraft-1.18.2-client.jar

Native libraries:
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.12.4/text2speech-1.12.4-natives-windows.jar

Mods:
  [✔️] additionaladditions-4.0.5
  [✔️] alexsdelight-1.18.2-1.2.3
  [✔️] alexsmobs-1.18.6
  [✔️] ambientadditions-1.18.2-0.8.0
  [✔️] aqcaracal-1.18.2-1.0-forge
  [✔️] Aquaculture-1.18.2-2.3.7
  [✔️] architectury-4.5.75-forge
  [✔️] artifacts-1.18.2-4.1.0
  [✔️] asynclocator-1.18.2-1.0.1
  [✔️] AutoRegLib-1.7-53
  [✔️] betteranimalsplus-1.18.2-11.0.5-forge
  [✔️] BetterVillage-Forge-1.18.2-1.0.1
  [✔️] BiomesOPlenty-1.18.2-16.0.0.134
  [✔️] blockcarpentry-1.18-0.3.0
  [✔️] blue_skies-1.18.2-1.3.12
  [✔️] carryon-1.18.2-1.17.0.8
  [✔️] catalogue-1.6.2-1.18.2
  [✔️] cfm-7.0.0-pre29-1.18.2
  [✔️] chat_heads-0.6.1-forge-1.18.2
  [✔️] ChiselsBits-forge-1.18.2-1.2.101-universal
  [✔️] citadel-1.11.3-1.18.2
  [✔️] cloth-config-6.2.62-forge
  [✔️] cofh_core-1.18.2-1.6.4.21
  [✔️] collective-1.18.2-4.28
  [✔️] comforts-forge-1.18.2-5.0.0.4
  [✔️] configured-1.5.3-1.18.2
  [✔️] Craftable+Horse+Armour++Saddle-1.18-1.8-Forge
  [✔️] Croptopia-1.18.2-FORGE-2.0.5
  [✔️] culinaryconstruct-forge-1.18.2-4.3.1.0
  [✔️] culturaldelights-1.18.2-0.11
  [✔️] curios-forge-1.18.2-5.0.7.1
  [✔️] Decorative+Blocks-forge-1.18.2-2.1.0
  [✔️] DoggyTalents-1.18.2-2.5.0
  [✔️] dual_riders-1.18.2-1.1.1-forge
  [✔️] DungeonsArise-1.18.2-2.1.50d-beta
  [✔️] EarthMobs-1.18.2-1.1.2
  [✔️] EasyMagic-v3.3.0-1.18.2-Forge
  [✔️] ecologics-forge-1.18.2-1.7.1
  [✔️] enchantwithmob-quilt-1.0.1+1.18.2
  [✔️] Enlightened+End+BB+V1.5
  [✔️] ensorcellation-1.18.2-1.6.1.8
  [✔️] exoticbirds-1.18.2-1.7.0
  [✔️] expandability-6.0.0
  [✔️] FarmersDelight-1.18.2-1.1.2
  [✔️] feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2
  [✔️] friendsandfoes-forge-mc1.18.2-1.4.5
  [✔️] geckolib-1.18-forge-3.0.18
  [✔️] gemsnjewels-1.18.2-0.5.5
  [✔️] goblintraders-1.7.2-1.18.2
  [✔️] guardvillagers-1.18.2.1.4.3
  [✔️] HunterIllager-1.18.2-4.0.1
  [✔️] Incendium_v5.0.4
  [✔️] InventoryHud_[1.18].forge-3.4.4
  [✔️] jei-1.18.2-9.7.0.209
  [✔️] journeymap-1.18.2-5.8.5-forge
  [✔️] LibraryFerret-Forge-1.18.2-2.0.0
  [✔️] mcda-2.0.6
  [✔️] mcdar-1.4.8
  [✔️] mcdw-4.4.0
  [✔️] morevillagers-forge-1.18.2-3.3.2
  [✔️] naturalist-forge-1.0.4-1.18.2
  [✔️] NekosEnchantedBooks-1.18.2-1.7.0
  [✔️] NethersDelight-1.18.2-2.2.0
  [✔️] notenoughanimations-forge-1.6.0-mc1.18.2
  [✔️] NourishedNetherV12
  [✔️] Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.1
  [✔️] pamhc2foodcore-1.18.2-1.0.1
  [✔️] pamhc2foodextended-1.18.2-1.0.0
  [✔️] Patchouli-1.18.2-71.1
  [✔️] plushies-1.2-1.18.2-forge
  [✔️] PuzzlesLib-v3.3.5-1.18.2-Forge
  [✔️] Quark-3.2-358
  [✔️] QuarkOddities-1.18
  [✔️] repurposed_structures_forge-5.1.14+1.18.2
  [✔️] Rex's-AdditionalStructures-1.18.2-(v.3.1.0)
  [✔️] RoughlyEnoughItems-8.3.501
  [✔️] shutupexperimentalsettings-1.0.5
  [✔️] sit-1.18.2-1.3.2
  [✔️] stalwart-dungeons-1.18.2-1.2.2
  [✔️] structure_gel-1.18.2-2.4.4
  [✔️] TerraBlender-forge-1.18.2-1.1.0.102
  [✔️] terraincognita-1.18.2-2.0
  [✔️] Terralith_v2.2.1a
  [✔️] The_Wild_Update_Mod_V1.3_Minecraft_1.18
  [✔️] the-conjurer-1.18.2-1.1.1
  [✔️] Towns-and-Towers-1.18.2-1.6.0
  [✔️] UniversalEnchants-v3.0.6-1.18.2-Forge
  [✔️] untamedwilds-1.18.2-2.1.3
  [✔️] valhelsia_core-1.18.2-0.3.1
  [✔️] valhelsia_structures-forge-1.18.2-0.1.0
  [✔️] vanillacookbook-1.18.2-2.0.0
  [✔️] villagernames_1.18.2-3.5
  [✔️] VisualWorkbench-v3.3.0-1.18.2-Forge
  [✔️] Waddles-1.18.2-0.8.19
  [✔️] wearablebackpacks-1.18.2-0.1.0
  [✔️] YungsApi-1.18.2-Forge-2.0.8
  [✔️] YungsBetterDesertTemples-1.18.2-Forge-1.1.0
  [✔️] YungsBetterDungeons-1.18.2-Forge-2.1.0
  [✔️] YungsBetterMineshafts-1.18.2-Forge-2.1.4
  [✔️] YungsBetterStrongholds-1.18.2-Forge-2.1.1
  [✔️] YungsBetterWitchHuts-1.18.2-Forge-1.0
  [✔️] YungsBridges-1.18.2-Forge-2.1.0
  [✔️] YungsExtras-1.18.2-Forge-2.1.0

Params:
  --username  --version 1.18.2 --gameDir C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/instances/CustomMods/.minecraft --assetsDir C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/assets --assetIndex 1.18 --uuid  --accessToken  --userType  --versionType release --launchTarget forgeclient --fml.forgeVersion 40.1.0 --fml.mcVersion 1.18.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20220404.173914

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms5000m, -Xmx8072m, -Duser.language=en]

Minecraft process ID: 34424

Using onesix launcher.

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2022-06-29 17:53:14,780 main WARN Advanced terminal features are not available in this environment
[17:53:14] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, xephrx, --version, 1.18.2, --gameDir, C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/instances/CustomMods/.minecraft, --assetsDir, C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/assets, --assetIndex, 1.18, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 40.1.0, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914, --width, 854, --height, 480]
[17:53:14] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.3.1 by Oracle Corporation
[17:53:15] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/xerne/Downloads/mmc-stable-win32/MultiMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2348!/ Service=ModLauncher Env=CLIENT
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	... 8 more
Caused by: java.lang.module.ResolutionException: Modules roughlyenoughitems and jei export package mezz.jei.api.gui to module farmersdelight
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
	... 13 more
Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 29 Jun 2022 17:53:20 -0700

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
