### ISSUE TITLE
Exit code 255 1.19

### ISSUE THREAD

**Issue by DaltonSL** [MultiMC/Launcher#4813]
### Operating System

macOS

### Description of bug

MultiMC version: 0.6.16-3434

Launched instance in online mode

authserver.mojang.com resolves to:
    [108.138.89.64, 108.138.89.60, 108.138.89.63, 108.138.89.47]

session.minecraft.net resolves to:
    [3.229.83.86, 52.45.69.223, 52.7.214.17]

textures.minecraft.net resolves to:
    [13.224.2.89, 13.224.2.19, 13.224.2.51, 13.224.2.100]

api.mojang.com resolves to:
    [108.138.94.20, 108.138.94.107, 108.138.94.91, 108.138.94.37]

Minecraft folder is:
/Applications/MultiMC.app/Data/instances/1.19/.minecraft

Java path is:
/Users/daltonlanham/Downloads/jdk-18.0.1.1.jdk/Contents/Home/bin/java

Checking Java version...
Java is version 18.0.1.1, using 32-bit architecture, from Oracle Corporation.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  net.minecraft.client.main.Main

Native path:
  /Applications/MultiMC.app/Data/instances/1.19/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /Applications/MultiMC.app/Data/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  /Applications/MultiMC.app/Data/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  /Applications/MultiMC.app/Data/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  /Applications/MultiMC.app/Data/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-common/4.1.77.Final/netty-common-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-buffer/4.1.77.Final/netty-buffer-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-codec/4.1.77.Final/netty-codec-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-handler/4.1.77.Final/netty-handler-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-resolver/4.1.77.Final/netty-resolver-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport/4.1.77.Final/netty-transport-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport-native-unix-common/4.1.77.Final/netty-transport-native-unix-common-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport-classes-epoll/4.1.77.Final/netty-transport-classes-epoll-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /Applications/MultiMC.app/Data/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /Applications/MultiMC.app/Data/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /Applications/MultiMC.app/Data/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar
  /Applications/MultiMC.app/Data/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/authlib/3.5.41/authlib-3.5.41.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /Applications/MultiMC.app/Data/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  /Applications/MultiMC.app/Data/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/text2speech/1.13.9/text2speech-1.13.9.jar
  /Applications/MultiMC.app/Data/libraries/ca/weblite/java-objc-bridge/1.1/java-objc-bridge-1.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/minecraft/1.19/minecraft-1.19-client.jar

Native libraries:
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-macos.jar

Params:
  --username  --version 1.19 --gameDir /Applications/MultiMC.app/Data/instances/1.19/.minecraft --assetsDir /Applications/MultiMC.app/Data/assets --assetIndex 1.19 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: 1.19", -XstartOnFirstThread, -Xms512m, -Xmx3200m, -Duser.language=en]

Minecraft process ID: 1162

Using onesix launcher.

[14:07:29] [main/INFO]: Building optimized datafixer
[14:07:30] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[14:07:30] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[14:07:30] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[14:07:31] [Render thread/INFO]: [STDERR]: Failed to start Minecraft:
[14:07:31] [Render thread/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
[14:07:31] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
[14:07:31] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[14:07:31] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[14:07:31] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[14:07:31] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[14:07:31] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[14:07:31] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
[14:07:31] [Render thread/INFO]: [STDERR]: 	at ac.a(SourceFile:65)
[14:07:31] [Render thread/INFO]: [STDERR]: 	at eev.a(SourceFile:2306)
[14:07:31] [Render thread/INFO]: [STDERR]: 	at eev.a(SourceFile:2301)
[14:07:31] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:207)
[14:07:31] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[14:07:31] [Render thread/INFO]: [STDERR]: 	... 5 more
[14:07:31] [Render thread/INFO]: [STDERR]: Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.dylib [in thread "Render thread"]
[14:07:31] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:164)
[14:07:31] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:63)
[14:07:31] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.<clinit>(Library.java:51)
[14:07:31] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
[14:07:31] [Render thread/INFO]: [STDERR]: 	at dyq.<clinit>(SourceFile:8)
[14:07:31] [Render thread/INFO]: [STDERR]: 	at dzo.<init>(SourceFile:51)
[14:07:31] [Render thread/INFO]: [STDERR]: 	at dzv.<init>(SourceFile:19)
[14:07:31] [Render thread/INFO]: [STDERR]: 	at dzv.<init>(SourceFile:23)
[14:07:31] [Render thread/INFO]: [STDERR]: 	at dzv.<clinit>(SourceFile:11)
[14:07:31] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(SourceFile:46)
[14:07:31] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:195)
[14:07:31] [Render thread/INFO]: [STDERR]: 	... 6 more
[14:07:31] [Render thread/INFO]: [STDOUT]: Exiting with -1
Process exited with code 255 (0xff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

### Steps to reproduce

starting instance

### Suspected cause

no idea. need help

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
are you on M1 mac? you need to download x64 Java, ARM Java will not work

**Comment by DaltonSL** [comment]
I am. Perfect, that worked! Thanks so much
