### ISSUE TITLE
[Bug] Can't start 1.12.2 forge

### ISSUE THREAD

**Issue by agent-LuluDodo** [MultiMC/Launcher#4836]
### Operating System

Windows 11

### Description of bug

I am unable to start 1.12.2 forge.

[Log:](https://pastebin.com/5bKYrvhT)
```
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:110)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 5 more
Exiting with -1
```

### Steps to reproduce

1. Create a new 1.12.2 instance.
2. Install forge.
3. Start the instance.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by agent-LuluDodo** [comment]
I reinstalled Java 8 and now it works. (I had it installed before)
