### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TOTCAMUY** [MultiMC/Launcher#4839]
### Operating System

Windows

### Description of bug

Error "Could not decide minecarft version"

### Steps to reproduce

When I open instance I get the message "Update required", when I click "Upgrade the instance" I get the error "Could not decide minecarft version"
skr.sh/sF0Bw85kzsT
skr.sh/sF0i2kXEPq7
skr.sh/sF0rYKVDj3R

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
none of those screenshots works, that error means something messed up the instances, either a bad harddrive, full harddrive, antivirus or similar, you will need to restore your instances from a backup, or create new instances with the correct version and move the files over

**Comment by wsygd** [comment]
.He said it was a BUG .   What shoud I ？

  Version: 3.5.3
  Time: 2022-08-24 22:15:13
  Thread: Thread[ForkJoinPool.commonPool-worker-8,5,main]

  Content: 
    java.lang.InternalError: java.lang.InternalError: Should not get here
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
	at java.util.concurrent.ForkJoinTask.reportException(Unknown Source)
	at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(Unknown Source)
	at java.util.stream.DistinctOps$1.reduce(Unknown Source)
	at java.util.stream.DistinctOps$1.opEvaluateParallelLazy(Unknown Source)
	at java.util.stream.AbstractPipeline.sourceSpliterator(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.jackhuang.hmcl.util.platform.JavaVersion.lookupJavas(JavaVersion.java:294)
	at org.jackhuang.hmcl.util.platform.JavaVersion.initialize(JavaVersion.java:248)
	at org.jackhuang.hmcl.util.function.ExceptionalRunnable.lambda$toCallable$0(ExceptionalRunnable.java:32)
	at org.jackhuang.hmcl.task.Task$SimpleTask.execute(Task.java:1022)
	at org.jackhuang.hmcl.task.AsyncTaskExecutor.lambda$null$22(AsyncTaskExecutor.java:245)
	at org.jackhuang.hmcl.util.Lang.lambda$wrap$2(Lang.java:270)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.InternalError: Should not get here
	at sun.nio.fs.WindowsNativeDispatcher.GetFinalPathNameByHandle(Native Method)
	at sun.nio.fs.WindowsLinkSupport.getFinalPath(Unknown Source)
	at sun.nio.fs.WindowsLinkSupport.getRealPath(Unknown Source)
	at sun.nio.fs.WindowsPath.toRealPath(Unknown Source)
	at sun.nio.fs.WindowsPath.toRealPath(Unknown Source)
	at org.jackhuang.hmcl.util.platform.JavaVersion.lambda$lookupJavas$0(JavaVersion.java:272)
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source)
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
	at java.util.stream.AbstractTask.compute(Unknown Source)
	at java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(Unknown Source)
	... 3 more


-- System Details --
  Operating System: Windows 7 6.1.7601
  System Architecture: amd64
  Java Architecture: amd64
  Java Version: 1.8.0_341, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  JVM Max Memory: 1892155392
  JVM Total Memory: 71827456
  JVM Free Memory: 21917120
