### ISSUE TITLE
I can't open the game 

### ISSUE THREAD

**Issue by JihwanPark11** [MultiMC/Launcher#4856]
### Description of bug

I success on log into the account. But, I still can't open the game. 

### Steps to reproduce

![Uploading 스크린샷 2022-07-27 07.43.16.png…]()

### Suspected cause

Idk

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by JihwanPark11** [comment]
MultiMC version: 0.6.16-3434


Launched instance in online mode

authserver.mojang.com resolves to:
    [13.225.171.34, 13.225.171.56, 13.225.171.42, 13.225.171.40]

session.minecraft.net resolves to:
    [52.7.214.17, 52.45.69.223, 3.229.83.86]

textures.minecraft.net resolves to:
    [18.65.25.32, 18.65.25.8, 18.65.25.61, 18.65.25.14]

api.mojang.com resolves to:
    [65.9.42.112, 65.9.42.28, 65.9.42.111, 65.9.42.58]


Minecraft folder is:
/Applications/MultiMC.app/Data/instances/1.16.11/.minecraft


Java path is:
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java


Checking Java version...
Java is version 1.8.0_341, using 64-bit architecture, from Oracle Corporation.


Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  /Applications/MultiMC.app/Data/instances/1.16.11/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  /Applications/MultiMC.app/Data/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /Applications/MultiMC.app/Data/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  /Applications/MultiMC.app/Data/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  /Applications/MultiMC.app/Data/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /Applications/MultiMC.app/Data/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /Applications/MultiMC.app/Data/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/datafixerupper/3.0.25/datafixerupper-3.0.25.jar
  /Applications/MultiMC.app/Data/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/authlib/1.6.25/authlib-1.6.25.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /Applications/MultiMC.app/Data/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /Applications/MultiMC.app/Data/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  /Applications/MultiMC.app/Data/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/intermediary/1.16.1/intermediary-1.16.1.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/fabric-loader/0.14.8/fabric-loader-0.14.8.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/minecraft/1.16.1/minecraft-1.16.1-client.jar

Native libraries:
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar

Mods:
  [✔️] atum-1.1.1+1.16.1
  [✔️] fast-reset-1.16.1-v1.4.1
  [✔️] forceport-1.1.0
  [✔️] lazydfu-0.1.2
  [✔️] lithium-1.16.1-backport-fabric-0.6.6
  [✔️] sodium-1.16.1-backport-fabric-0.2.1+build.10
  [✔️] SpeedRunIGT-10.16+1.16.1
  [✔️] starlight-fabric-1.0.0-RC2-1.16.x
  [✔️] voyager-1.0.0
  [✔️] worldpreview-2.3.3+1.16.1

Params:
  --username  --version 1.16.1 --gameDir /Applications/MultiMC.app/Data/instances/1.16.11/.minecraft --assetsDir /Applications/MultiMC.app/Data/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: 1.16.1", -XstartOnFirstThread, -Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 11823


Using onesix launcher.

ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider jdk.nashorn.api.scripting.NashornScriptEngineFactory not found
[07:54:05] [main/INFO]: Loading Minecraft 1.16.1 with Fabric Loader 0.14.8
[07:54:06] [ForkJoinPool-1-worker-0/WARN]: Mod starlight uses the version fabric-1.0.0-RC2-82ae5ca which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:54:06] [main/INFO]: Loading 13 mods:
	- atum 1.1.1+1.16.1
	- fabricloader 0.14.8
	- fast_reset 1.4.1
	- forceport 1.1.0
	- java 8
	- lazydfu 0.1.2
	- lithium 0.6.6
	- minecraft 1.16.1
	- sodium 0.2.1+build.10
	- speedrunigt 10.16+1.16.1
	- starlight fabric-1.0.0-RC2-82ae5ca
	- voyager 1.0.0
	- worldpreview 2.3.3+1.16.1
[07:54:06] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/Applications/MultiMC.app/Data/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[07:54:06] [main/INFO]: Loaded configuration file for Lithium: 79 options available, 0 override(s) found
[07:54:06] [main/INFO]: Loaded configuration file for Sodium: 24 options available, 0 override(s) found
[07:54:12] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: net.minecraft.class_1550.<init>(class_1299,class_1937)void/newInvokeSpecial
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_341]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_341]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_341]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_341]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: net.minecraft.class_1550.<init>(class_1299,class_1937)void/newInvokeSpecial
	at net.minecraft.class_1299.<clinit>(class_1299.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_10252(class_2378.java:171) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_29110(class_2378.java:220) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:1.8.0_341]
	at net.minecraft.class_2378.<clinit>(class_2378.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:41) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) ~[minecraft-1.16.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 10 more
Caused by: java.lang.IllegalAccessError: no such constructor: net.minecraft.class_1550.<init>(class_1299,class_1937)void/newInvokeSpecial
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:483) ~[?:1.8.0_341]
	at net.minecraft.class_1299.<clinit>(class_1299.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_10252(class_2378.java:171) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_29110(class_2378.java:220) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:1.8.0_341]
	at net.minecraft.class_2378.<clinit>(class_2378.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:41) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) ~[minecraft-1.16.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 10 more
Caused by: java.lang.UnsupportedClassVersionError: net/minecraft/class_3222 has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_341]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_341]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_341]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:347) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_341]
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_341]
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_341]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_341]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_341]
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_341]
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_341]
	at net.minecraft.class_1299.<clinit>(class_1299.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_10252(class_2378.java:171) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_29110(class_2378.java:220) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:1.8.0_341]
	at net.minecraft.class_2378.<clinit>(class_2378.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:41) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) ~[minecraft-1.16.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 10 more
마인크래프트가 종료 코드 1 (0x1) 와(과) 함께 종료했습니다.
일반적으로 종료 코드나 종료 코드 설명만으로는 문제를 진단할 수 없습니다!
종료 코드뿐만 아니라 전체 로그를 항상 업로드합니다.
Clipboard copy at: 27 Jul 2022 07:56:37 +0800
Clipboard copy at: 27 Jul 2022 07:56:39 +0800

**Comment by JihwanPark11** [comment]
this is my log

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
