### ISSUE TITLE
Can't launch even vanilla 1.16.5 instances

### ISSUE THREAD

**Issue by cola98765** [MultiMC/Launcher#4888]
### Operating System

Windows

### Description of bug

Trying to launch **any** 1.16.5 instance (vanilla, forge, fabric) results in
```
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
```
(full log below)

issues like that apparently are related to Java version...
However 1.12 that also uses Java 8 works just fine

the java I had was
`Java is version 1.8.0_341, using 64-bit architecture, from Oracle Corporation.`
I read somewhere that there were issues past something like 320 so I launched the elder one I had as JDK
`Java is version 1.8.0_301, using 64-bit architecture, from Oracle Corporation.`
same issue... let's try some different... even older version
`Java is version 1.8.0_292, using 64-bit architecture, from AdoptOpenJDK.`
Same still

I didn't always had this issue, tho I didn't play 1.16 for quite a while and I think oracle java updated in the meantime.

```
MultiMC version: 0.6.16-3431


Launched instance in online mode

authserver.mojang.com resolves to:
    [52.84.199.41, 52.84.199.53, 52.84.199.46, 52.84.199.60]

session.minecraft.net resolves to:
    [52.72.238.122, 54.172.106.247, 107.20.118.247]

textures.minecraft.net resolves to:
    [54.192.231.57, 54.192.231.84, 54.192.231.107, 54.192.231.87]

api.mojang.com resolves to:
    [54.192.231.114, 54.192.231.23, 54.192.231.107, 54.192.231.100]


Minecraft folder is:
D:/gry/1minecraft/MultiMC/instances/vanilla 1.16.5/.minecraft


Java path is:
C:/Program Files/Java/jre1.8.0_341/bin/javaw.exe


Checking Java version...
Java is version 1.8.0_341, using 64-bit architecture, from Oracle Corporation.


Main Class:
  net.minecraft.client.main.Main

Native path:
  D:/gry/1minecraft/MultiMC/instances/vanilla 1.16.5/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  D:/gry/1minecraft/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  D:/gry/1minecraft/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  D:/gry/1minecraft/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  D:/gry/1minecraft/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  D:/gry/1minecraft/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  D:/gry/1minecraft/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  D:/gry/1minecraft/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  D:/gry/1minecraft/MultiMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  D:/gry/1minecraft/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  D:/gry/1minecraft/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  D:/gry/1minecraft/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  D:/gry/1minecraft/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  D:/gry/1minecraft/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  D:/gry/1minecraft/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  D:/gry/1minecraft/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  D:/gry/1minecraft/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  D:/gry/1minecraft/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  D:/gry/1minecraft/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  D:/gry/1minecraft/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  D:/gry/1minecraft/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  D:/gry/1minecraft/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  D:/gry/1minecraft/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  D:/gry/1minecraft/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  D:/gry/1minecraft/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  D:/gry/1minecraft/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  D:/gry/1minecraft/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  D:/gry/1minecraft/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  D:/gry/1minecraft/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  D:/gry/1minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  D:/gry/1minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  D:/gry/1minecraft/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  D:/gry/1minecraft/MultiMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  D:/gry/1minecraft/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  D:/gry/1minecraft/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  D:/gry/1minecraft/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  D:/gry/1minecraft/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  D:/gry/1minecraft/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  D:/gry/1minecraft/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  D:/gry/1minecraft/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  D:/gry/1minecraft/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Params:
  --username  --version 1.16.5 --gameDir D:/gry/1minecraft/MultiMC/instances/vanilla 1.16.5/.minecraft --assetsDir D:/gry/1minecraft/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx5900m, -Duser.language=en]


Minecraft process ID: 12124


Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/Hash$Strategy
	at net.minecraft.client.main.Main.main(SourceFile:64)
	... 8 more
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.Hash$Strategy
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 9 more
Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

```

### Steps to reproduce

* get MultiMC
* create new vanilla 1.16.5 instance
* select your Java 8 instance of choice in settings
* press Launch button

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
where did you get this Java version?

**Comment by cola98765** [comment]
> where did you get this Java version?
From Oracle website? It says right there in the logs

**Comment by phit** [comment]
can you try deleting `D:/gry/1minecraft/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar`

**Comment by cola98765** [comment]
that helped... I was wondering what was constant across overwriting MulitMC files and different java versions.
