### ISSUE TITLE
Don’t know what the error is here, any way to fix?

### ISSUE THREAD

**Issue by QiYiCubeguy** [MultiMC/Launcher#4904]
MultiMC version: 0.6.16-3431

Launched instance in online mode

authserver.mojang.com resolves to:
    [108.138.239.37, 108.138.239.63, 108.138.239.55, 108.138.239.36]

session.minecraft.net resolves to:
    [34.225.172.83, 44.199.38.182, 52.5.26.48]

textures.minecraft.net resolves to:
    [13.35.125.46, 13.35.125.99, 13.35.125.36, 13.35.125.78]

api.mojang.com resolves to:
    [108.139.1.102, 108.139.1.50, 108.139.1.51, 108.139.1.70]

Minecraft folder is:
C:/MultiMC/instances/1.19.2/.minecraft

Java path is:
C:/Program Files/Java/jdk18.0.1-win_i686 - 32/bin/java.exe

Checking Java version...
Java is version 18.0.1, using 32-bit architecture, from Azul Systems, Inc..

Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/MultiMC/instances/1.19.2/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  C:/MultiMC/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  C:/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/MultiMC/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  C:/MultiMC/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  C:/MultiMC/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  C:/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  C:/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  C:/MultiMC/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  C:/MultiMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  C:/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/MultiMC/libraries/io/netty/netty-common/4.1.77.Final/netty-common-4.1.77.Final.jar
  C:/MultiMC/libraries/io/netty/netty-buffer/4.1.77.Final/netty-buffer-4.1.77.Final.jar
  C:/MultiMC/libraries/io/netty/netty-codec/4.1.77.Final/netty-codec-4.1.77.Final.jar
  C:/MultiMC/libraries/io/netty/netty-handler/4.1.77.Final/netty-handler-4.1.77.Final.jar
  C:/MultiMC/libraries/io/netty/netty-resolver/4.1.77.Final/netty-resolver-4.1.77.Final.jar
  C:/MultiMC/libraries/io/netty/netty-transport/4.1.77.Final/netty-transport-4.1.77.Final.jar
  C:/MultiMC/libraries/io/netty/netty-transport-native-unix-common/4.1.77.Final/netty-transport-native-unix-common-4.1.77.Final.jar
  C:/MultiMC/libraries/io/netty/netty-transport-classes-epoll/4.1.77.Final/netty-transport-classes-epoll-4.1.77.Final.jar
  C:/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/MultiMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  C:/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  C:/MultiMC/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar
  C:/MultiMC/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  C:/MultiMC/libraries/com/mojang/authlib/3.11.49/authlib-3.11.49.jar
  C:/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  C:/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  C:/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/MultiMC/libraries/com/mojang/text2speech/1.13.9/text2speech-1.13.9.jar
  C:/MultiMC/libraries/com/mojang/minecraft/1.19.2/minecraft-1.19.2-client.jar

Native libraries:
  C:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-windows.jar

Params:
  --username  --version 1.19.2 --gameDir C:/MultiMC/instances/1.19.2/.minecraft --assetsDir C:/MultiMC/assets --assetIndex 1.19 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 3836

Using onesix launcher.

[13:35:58] [main/INFO]: Building optimized datafixer
[13:36:25] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[13:36:25] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[13:36:25] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[13:36:35] [Render thread/INFO]: [STDERR]: Failed to start Minecraft:
[13:36:35] [Render thread/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
[13:36:35] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
[13:36:35] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[13:36:35] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[13:36:35] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[13:36:35] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[13:36:35] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[13:36:35] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
[13:36:35] [Render thread/INFO]: [STDERR]: 	at ac.a(SourceFile:66)
[13:36:35] [Render thread/INFO]: [STDERR]: 	at efu.a(SourceFile:2359)
[13:36:35] [Render thread/INFO]: [STDERR]: 	at efu.a(SourceFile:2354)
[13:36:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.a(SourceFile:214)
[13:36:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:51)
[13:36:36] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[13:36:36] [Render thread/INFO]: [STDERR]: 	... 5 more
[13:36:36] [Render thread/INFO]: [STDERR]: Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll [in thread "Render thread"]
[13:36:36] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:164)
[13:36:36] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:63)
[13:36:36] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.<clinit>(Library.java:51)
[13:36:36] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
[13:36:36] [Render thread/INFO]: [STDERR]: 	at dzn.<clinit>(SourceFile:8)
[13:36:36] [Render thread/INFO]: [STDERR]: 	at eal.<init>(SourceFile:51)
[13:36:36] [Render thread/INFO]: [STDERR]: 	at eas.<init>(SourceFile:19)
[13:36:36] [Render thread/INFO]: [STDERR]: 	at eas.<init>(SourceFile:23)
[13:36:36] [Render thread/INFO]: [STDERR]: 	at eas.<clinit>(SourceFile:11)
[13:36:36] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(SourceFile:46)
[13:36:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.a(SourceFile:202)
[13:36:36] [Render thread/INFO]: [STDERR]: 	... 7 more
[13:36:36] [Render thread/INFO]: [STDOUT]: Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
MultiMC: Log upload triggered at: 05 Sep 2022 13:38:01 -0400

**Comment by StarXStone** [comment]
This is about the same error I am getting on all my instances in MultiMC. I am updating the driver just in case and also going to try to download an older version of Java toolkit to see if it is part of the issue.

**Comment by StarXStone** [comment]
Okay so far as I can tell... It is a client side issue. I updated drivers and Java to the latest JDK reset and still this error shows up on both MultiMC and Curseforge. (I do not want to use Curseforge for its ridiculous ToS and spyware but for this case I didn't have much choice. Still nothing. Maybe older versions of Java JDK? But that doesn't really make sense to me. This -1 Error is highly annoying and it only accures on my home PC not the laptop. The laptop can't handle bigger mods so unless I play a lite version of Vanilla Plus that's pretty much what I am limited to and YOU CAN'T MAKE ME GO BACK TO VANILLA!!!
I will try to look deeper into this if no one gets back to you.

**Comment by StarXStone** [comment]
Okay, so as far as I can tell this is a forge problem and when it is installed it gets thrown around with newer versions of JDK so I will look into version 8 being installed to see if that fixes the issue

**Comment by StarXStone** [comment]
Okay bro. Praise God I figured it out. So, turns out I did all that to find out MultiMC and forge reset where to find Javaw so what you need to do is go into your instance settings window (Left click menu or click on edit instance -> Settings -> Click the box for Java Installation to activate the menu features and click auto detect or browse if you know where to find the version installed manually). I think what happened is while updating your Java directory became hidden due to the changed version and so it created Error -1. You might need to do this for every instance and let me know how it works out.
