### ISSUE TITLE
multicm

### ISSUE THREAD

**Issue by lucanasi07** [MultiMC/Launcher#4906]
### Operating System

macOS

### Description of bug

minecraft does not open, it gives me problems: Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem.
tells me: The process has closed with code 255 (0xff). Please note that usually neither the exit code nor its description are sufficient to diagnose problems! Always upload the entire log and not just the exit code.

### Steps to reproduce

start

### Suspected cause

I do not know

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
1. Please write your issue in english, use a translator if you need to
2. Don't create multiple issue about the same thing
3. Provide a log file, otherwise we can't help you

![](https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png)

**Comment by KingTino104** [comment]
> 1. Please write your issue in english, use a translator if you need to
> 2. Don't create multiple issue about the same thing
> 3. Provide a log file, otherwise we can't help you
> 
> ![](https://camo.githubusercontent.com/a2d342eb358df2f907c3648d1ec53091ec43b739de4b5214147652a6865dfd4d/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3533313539383133373739303536323330352f3537353338313030303339383536393439332f756e6b6e6f776e2e706e67)

If you are trying to tell him to use english atleast say "Don't create multiple issues" not "Don't create multiple issue about the same thing"

**Comment by lucanasi07** [comment]
MultiMC version: 0.6.16-3434


Launched instance in online mode

authserver.mojang.com resolves to:
    [13.226.160.56, 13.226.160.47, 13.226.160.59, 13.226.160.49]

session.minecraft.net resolves to:
    [52.5.26.48, 34.225.172.83, 44.199.38.182]

textures.minecraft.net resolves to:
    [108.138.189.111, 108.138.189.89, 108.138.189.78, 108.138.189.125]

api.mojang.com resolves to:
    [108.138.199.126, 108.138.199.79, 108.138.199.5, 108.138.199.107]


Minecraft folder is:
/Applications/MultiMC.app/Data/instances/CreateCraft/.minecraft


Java path is:
/Library/Java/JavaVirtualMachines/jdk-17.0.4.1.jdk/Contents/Home/bin/java


Checking Java version...
Java is version 17.0.4.1, using 32-bit architecture, from Oracle Corporation.


Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.


Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  /Applications/MultiMC.app/Data/instances/CreateCraft/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Using system OpenAL.
Using system GLFW.

Libraries:
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /Applications/MultiMC.app/Data/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  /Applications/MultiMC.app/Data/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  /Applications/MultiMC.app/Data/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  /Applications/MultiMC.app/Data/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
  /Applications/MultiMC.app/Data/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /Applications/MultiMC.app/Data/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /Applications/MultiMC.app/Data/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /Applications/MultiMC.app/Data/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/datafixerupper/4.1.27/datafixerupper-4.1.27.jar
  /Applications/MultiMC.app/Data/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/authlib/3.3.39/authlib-3.3.39.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /Applications/MultiMC.app/Data/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  /Applications/MultiMC.app/Data/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/text2speech/1.12.4/text2speech-1.12.4.jar
  /Applications/MultiMC.app/Data/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar
  /Applications/MultiMC.app/Data/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  /Applications/MultiMC.app/Data/libraries/cpw/mods/securejarhandler/1.0.3/securejarhandler-1.0.3.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm/9.2/asm-9.2.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar
  /Applications/MultiMC.app/Data/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  /Applications/MultiMC.app/Data/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  /Applications/MultiMC.app/Data/libraries/net/minecraftforge/eventbus/5.0.3/eventbus-5.0.3.jar
  /Applications/MultiMC.app/Data/libraries/net/minecraftforge/forgespi/4.0.10/forgespi-4.0.10.jar
  /Applications/MultiMC.app/Data/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar
  /Applications/MultiMC.app/Data/libraries/cpw/mods/modlauncher/9.1.3/modlauncher-9.1.3.jar
  /Applications/MultiMC.app/Data/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  /Applications/MultiMC.app/Data/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  /Applications/MultiMC.app/Data/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  /Applications/MultiMC.app/Data/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  /Applications/MultiMC.app/Data/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  /Applications/MultiMC.app/Data/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  /Applications/MultiMC.app/Data/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  /Applications/MultiMC.app/Data/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  /Applications/MultiMC.app/Data/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  /Applications/MultiMC.app/Data/libraries/cpw/mods/bootstraplauncher/1.0.0/bootstraplauncher-1.0.0.jar
  /Applications/MultiMC.app/Data/libraries/net/minecraftforge/fmlloader/1.18.2-40.1.0/fmlloader-1.18.2-40.1.0.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/minecraft/1.18.2/minecraft-1.18.2-client.jar

Native libraries:
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar

Mods:
  [✔️] appleskin-forge-mc1.18.2-2.4.1
  [✔️] balm-3.2.0+0
  [✔️] car-1.18.2-1.0.3
  [✔️] carryon-1.18.2-1.17.0.8
  [✔️] catalogue-1.6.2-1.18.2
  [✔️] cfm-7.0.0-pre29-1.18.2
  [✔️] cgm-1.2.7-1.18.2
  [✔️] Chimes-1.1.1-1.18.2
  [✔️] collective-1.18.2-4.51
  [✔️] configured-1.5.4-1.18.2
  [✔️] create-1.18.2-0.5.0.d
  [✔️] createaddition-1.18.2-20220817a
  [✔️] Croptopia-1.18.2-FORGE-2.1.0
  [✔️] curios-forge-1.18.2-5.0.7.1
  [✔️] enderchests-1.18-1.9.6
  [✔️] entityculling-forge-mc1.18-1.5.1
  [✔️] flywheel-forge-1.18.2-0.6.5
  [✔️] forge-1.18.2-40.1.76-installer
  [✔️] framework-0.2.3-1.18.2
  [✔️] fullbrightnesstoggle_1.18.2-1.4
  [✔️] jei-1.18.2-9.7.2.264
  [✔️] Mantle-1.18.2-1.9.27
  [✔️] mcw-windows-2.0.3bfabric-mc1.18.2
  [✔️] notenoughcrashes-4.1.6+1.18.2-fabric
  [✔️] Patchouli-1.18.2-71.1
  [✔️] shetiphiancore-1.18-3.10.10
  [✔️] simpleplanes-1.18.2-4.15.0
  [✔️] SimpleStorageNetwork-1.18.2-1.6.2
  [✔️] sophisticatedbackpacks-1.18.2-3.18.24.704
  [✔️] sophisticatedcore-1.18.2-0.5.9.115
  [✔️] TConstruct-1.18.2-3.5.1.31
  [✔️] worldedit-mod-7.2.10
  [✔️] wraith-croptosis-1.5.0

Params:
  --username  --version 1.18.2 --gameDir /Applications/MultiMC.app/Data/instances/CreateCraft/.minecraft --assetsDir /Applications/MultiMC.app/Data/assets --assetIndex 1.18 --uuid  --accessToken  --userType  --versionType release --launchTarget forgeclient --fml.forgeVersion 40.1.0 --fml.mcVersion 1.18.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20220404.173914

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: CreateCraft", -XstartOnFirstThread, -Xms1500m, -Xmx2500m, -Duser.language=en]


Minecraft process ID: 15655


Using onesix launcher.

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2022-09-09 11:59:49,687 main WARN Advanced terminal features are not available in this environment
[11:59:49] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Jack_Sparrow_07, --version, 1.18.2, --gameDir, /Applications/MultiMC.app/Data/instances/CreateCraft/.minecraft, --assetsDir, /Applications/MultiMC.app/Data/assets, --assetIndex, 1.18, --uuid, <ID PROFILO>, --accessToken, ❄❄❄❄❄❄❄❄, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 40.1.0, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914, --width, 854, --height, 480]
[11:59:49] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.4.1 by Oracle Corporation
[11:59:49] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/Applications/MultiMC.app/Data/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2348!/ Service=ModLauncher Env=CLIENT
[11:59:50] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing mandatory dependencies: forge, forge, forge, forge
[11:59:50] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[11:59:50] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [de.maxhenkel.car.MixinConnector]
[11:59:50] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [shetiphian.core.mixins.MixinConnector]
[11:59:50] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.18.2, --gameDir, /Applications/MultiMC.app/Data/instances/CreateCraft/.minecraft, --assetsDir, /Applications/MultiMC.app/Data/assets, --uuid, <ID PROFILO>, --username, Jack_Sparrow_07, --assetIndex, 1.18, --accessToken, ❄❄❄❄❄❄❄❄, --userType, msa, --versionType, release, --width, 854, --height, 480]
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
Exiting with -1
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	... 8 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	... 20 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.SystemReport.m_143522_(SystemReport.java:65)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_167850_(Minecraft.java:2275)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_167872_(Minecraft.java:2268)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:178)
	... 26 more
Il processo si è chiuso con codice 255 (0xff).
Si prega di notare che di solito né il codice di uscita, né la sua descrizione sono sufficienti per diagnosticare problemi!
Carica sempre l'intero log e non solo il codice di uscita.
MultiMC: Log upload triggered at: 09 Sep 2022 11:59:56 +0200
MultiMC: Log uploaded to: https://paste.ee/p/I7bW3
MultiMC: Log upload triggered at: 09 Sep 2022 12:04:40 +0200

**Comment by phit** [comment]
> Using system OpenAL.
> Using system GLFW.

disable that, don't randomly enable settings you don't understand
