### ISSUE TITLE
Direwolf20 not working

### ISSUE THREAD

**Issue by Slimesoldier** [MultiMC/Launcher#4918]
### Operating System

Windows 11

### Description of bug

I imported Direwolf20 to multimc and want to play it and I'm using the right java but I keep getting this error code, the modpack works on the ftb launcher but not on multimc

MultiMC version: 0.6.16-3431

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.154.121.48, 18.154.121.49, 18.154.121.40, 18.154.121.35]

session.minecraft.net resolves to:
    [52.1.168.80, 44.194.242.94, 34.194.132.190]

textures.minecraft.net resolves to:
    [18.65.25.14, 18.65.25.61, 18.65.25.8, 18.65.25.32]

api.mojang.com resolves to:
    [18.154.132.115, 18.154.132.76, 18.154.132.18, 18.154.132.45]

Minecraft folder is:
C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/instances/FTB Presents Direwolf20 1.16/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_341/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_341, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/instances/FTB Presents Direwolf20 1.16/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/net/minecraftforge/forge/1.16.4-35.1.13/forge-1.16.4-35.1.13-launcher.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/ow2/asm/asm/7.2/asm-7.2.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/ow2/asm/asm-commons/7.2/asm-commons-7.2.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/ow2/asm/asm-tree/7.2/asm-tree-7.2.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/ow2/asm/asm-util/7.2/asm-util-7.2.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/ow2/asm/asm-analysis/7.2/asm-analysis-7.2.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/cpw/mods/modlauncher/8.0.6/modlauncher-8.0.6.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/cpw/mods/grossjava9hacks/1.3.0/grossjava9hacks-1.3.0.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/net/minecraftforge/accesstransformers/2.2.0-shadowed/accesstransformers-2.2.0-shadowed.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/net/minecraftforge/eventbus/3.0.5-service/eventbus-3.0.5-service.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/net/minecraftforge/coremods/3.0.0/coremods-3.0.0.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/com/electronwill/night-config/core/3.6.2/core-3.6.2.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/com/electronwill/night-config/toml/3.6.2/toml-3.6.2.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.0/maven-artifact-3.6.0.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/com/mojang/minecraft/1.16.4/minecraft-1.16.4-client.jar

Native libraries:
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] absentbydesign-1.16.4-1.2.0
  [✔️] AppleSkin-mc1.16.2-forge-1.0.14
  [✔️] appliedenergistics2-8.2.0-alpha.2
  [✔️] archers_paradox-1.16.3-1.0.0
  [✔️] architectury-1.1.55-forge
  [✔️] ars_nouveau-1.16.3-1.8.1
  [✔️] astralsorcery-1.16.4-1.13.6
  [✔️] BetterAdvancements-1.16.4-0.1.0.103
  [✔️] BloodMagic-1.16.3-3.0.2-7
  [✔️] Bookshelf-1.16.4-9.3.18
  [✔️] Botania-1.16.4-410
  [✔️] BotanyPots-1.16.4-6.0.7
  [✔️] BotanyTrees-1.16.4-2.0.4
  [✔️] buildinggadgets-3.7.2
  [✔️] bwncr-1.16.4-3.9.16
  [✔️] cc-tweaked-1.16.4-1.94.0
  [✔️] charginggadgets-1.3.0
  [✔️] chiselsandbits-0.2.8-RELEASE
  [✔️] citadel-1.5.3
  [✔️] cloth-config-forge-4.1.1
  [✔️] Clumps-6.0.0.13
  [✔️] CodeChickenLib-1.16.4-3.5.0.398-universal
  [✔️] cofh_core-1.16.3-1.0.4
  [✔️] comforts-forge-1.16.4-4.0.0.2
  [✔️] Controlling-7.0.0.11
  [✔️] CookingForBlockheads_1.16.3-9.2.2
  [✔️] culinaryconstruct-forge-1.16.3-4.0.0.1
  [✔️] curios-forge-1.16.4-4.0.3.0
  [✔️] Cyclic-1.16.4-0.10.1
  [✔️] DarkUtilities-1.16.4-7.0.3
  [✔️] DataFixerSlayer 1.0-2
  [✔️] DefaultOptions_1.16.3-12.2.0
  [✔️] DeLogger-1.16.4-1.0.5+mc-1.16.4
  [✔️] doomangelring-1.16.4-1.0.0
  [✔️] DungeonCrawl-1.16.3-2.2.2
  [✔️] elevatorid-1.16.4-1.7.8
  [✔️] emojiful-1.16.3-2.1.1
  [✔️] EnchantmentDescriptions-1.16.4-6.0.2
  [✔️] EnderStorage-1.16.4-2.7.0.159-universal
  [✔️] ensorcellation-1.16.3-1.0.3
  [✔️] entangled-1.2.9-mc1.16.4
  [✔️] entitydetectors-1.16.4-1.1.0.1
  [✔️] envirocore-1.16.4-3.0.4.1
  [✔️] envirotech-1.16.4-3.0.4.1
  [✔️] extcaves-2.4
  [✔️] ExtraStorage-1.16.4-1.2.1
  [✔️] ExtremeReactors2-1.16.4-2.0.16
  [✔️] extremeSoundMuffler-3.2_Forge-1.16.4
  [✔️] FastFurnace-1.16.3-4.3.0
  [✔️] FastLeafDecay-v25
  [✔️] FastWorkbench-1.16.3-4.4.1
  [✔️] findme-1.16.3-2.1.0.0
  [✔️] flatbedrock-1.16.4-1.1.6
  [✔️] FluxNetworks-1.16.4-6.1.5.10
  [✔️] forge-1.16.4-geckolib-3.0.0-beta.10
  [✔️] ftb-backups-2.1.1.6
  [✔️] ftb-chunks-1604.2.2.52
  [✔️] ftbessentials-1603.1.0.11
  [✔️] ftb-gui-library-1604.1.1.26
  [✔️] ftb-hide
  [✔️] ftb-janitor-1604.1.0.7
  [✔️] ftb-progress
  [✔️] ftb-ranks-1604.1.1.9
  [✔️] ftb-teams-1604.1.0.13
  [✔️] glassential-forge-1.16.4-1.1.5
  [✔️] gravestone-1.16.4-1.0.5
  [✔️] harvest-1.16.3-1.0.3
  [✔️] ice_ice_baby-1.16.4-3.0.1
  [✔️] ImmersiveEngineering-1.16.4-4.1.1-128
  [✔️] immersiveposts-1.16.3-3.0.0
  [✔️] industrial-foregoing-1.16.4-3.2.5-74675d6
  [✔️] inventorysorter-1.16.1-18.1.0
  [✔️] ironchest-1.16.4-11.2.10
  [✔️] itemcollectors-1.0.6-mc1.16.4
  [✔️] JAMD-1.1.4-beta+mc-1.16.4
  [✔️] JAVD-2.5.42+mc-1.16.4
  [✔️] jei-1.16.4-7.6.0.62
  [✔️] jeiintegration_1.16.4-6.1.1.11
  [✔️] JustEnoughProfessions-1.16.3-1.1
  [✔️] JustEnoughResources-1.16.4-0.12.0.103
  [✔️] Krate-1.16.4-0.1.2
  [✔️] kubejs-1604.3.2.119-forge
  [✔️] kubejs-blood-magic-1604.1.0.1
  [✔️] kubejs-immersive-engineering-1604.1.0.9
  [✔️] kubejs-mekanism-1604.1.1.5
  [✔️] kubejs-thermal-1604.1.0.5
  [✔️] kubejs-ui-1604.1.0.11
  [✔️] lanterncolors-1.16.3-2.1.1
  [✔️] LibX-1.16.3-1.0.5
  [✔️] light-overlay-5.5.4
  [✔️] Lollipop-1.16.4-3.2.3
  [✔️] mana-and-artifice-1.2.0.2
  [✔️] mcjtylib-1.16-5.0.15
  [✔️] mcw-bridges-1.0.4-mc1.16.4
  [✔️] mcw-doors-1.0.1fix-mc1.16.4
  [✔️] mcws-roofs-2.0.0-mc1.16.4
  [✔️] mcw-trapdors-1.0.0-mc1.16.4
  [✔️] mcw-windows-1.0.2-mc1.16.4
  [✔️] Mekanism-1.16.4-10.0.18.445
  [✔️] MekanismGenerators-1.16.4-10.0.18.445
  [✔️] MekanismTools-1.16.4-10.0.18.445
  [✔️] mgui-1.16.4-3.1.3
  [✔️] minecolonies-0.13.521-ALPHA-universal
  [✔️] MineTogether-1.16.4-4.1.6RC3
  [✔️] MiniCoal2-1.16.1-0.0.2-universal
  [✔️] mininggadgets-1.7.1
  [✔️] modnametooltip_1.16.2-1.15.0
  [✔️] modular-routers-1.16.3-7.2.0-39
  [✔️] moredragoneggs-1.4
  [✔️] Morpheus-1.16.4-4.2.68
  [✔️] MouseTweaks-2.13-mc1.16.2
  [✔️] movingelevators-1.2.29-mc1.16.4
  [✔️] MythicBotany-1.16.3-1.2.0
  [✔️] NaturesAura-33.1
  [✔️] NaturesCompass-1.16.4-1.8.6
  [✔️] observerlib-1.16.4-1.4.4
  [✔️] Patchouli-1.16.4-48
  [✔️] Placebo-1.16.3-4.3.3
  [✔️] pneumaticcraft-repressurized-1.16.4-2.7.2-86
  [✔️] pocketstorage-1.16.3-0.7.6
  [✔️] portality-1.16.4-3.2.0
  [✔️] Powah-1.16.4-2.3.6
  [✔️] PrettyPipes-1.9.0
  [✔️] Psi 1.16-88
  [✔️] QuantumStorage-1.16.4-5.3.0
  [✔️] quartz-chests-1603.1.0.8
  [✔️] rangedpumps-0.8.2
  [✔️] ratlantis-1.0.0-1.16.3
  [✔️] rats-7.0.1-1.16.3
  [✔️] refinedpipes-0.5
  [✔️] refinedstorage-1.9.9
  [✔️] refinedstorageaddons-0.7.2
  [✔️] reliquary-1.16.3-1.3.4.1061
  [✔️] restrictions-1.16-3.0.3
  [✔️] rftoolsbase-1.16-2.0.9
  [✔️] rftoolsbuilder-1.16-3.0.13
  [✔️] rftoolscontrol-1.16-4.0.6
  [✔️] rftoolspower-1.16-3.0.8
  [✔️] rftoolsstorage-1.16-2.0.7
  [✔️] rftoolsutility-1.16-3.0.19
  [✔️] rhino-1.7.13.9
  [✔️] rsgauges-1.16.4-1.2.6-b2
  [✔️] rsrequestify-1.16.3-2.0.1
  [✔️] Runelic-1.16.4-6.0.2
  [✔️] serverconfigupdater-1.3
  [✔️] Shrink-1.16.4-1.0.5
  [✔️] shutupexperimentalsettings-1.0.1
  [✔️] simplemagnets-1.0.8-mc1.16.4
  [✔️] simplybackpacks-1.16.3-1.4.13
  [✔️] SimplyJetpacks2-1.16.3-2.6.3.0
  [✔️] snad-1.0.2-1.16.3
  [✔️] Statues-1.16.3-0.1.6.3
  [✔️] StorageDrawers-1.16.3-8.2.1
  [✔️] structurize-0.13.104-ALPHA-universal
  [✔️] tetra-1.16.4-3.3.1
  [✔️] The_Undergarden-1.16.3-0.3.8
  [✔️] theoneprobe-1.16-3.0.6
  [✔️] thermal_cultivation-1.16.3-1.0.5
  [✔️] thermal_expansion-1.16.3-1.0.5
  [✔️] thermal_innovation-1.16.3-1.0.3
  [✔️] thermal_locomotion-1.16.3-1.0.3
  [✔️] thermal-1.16.3-1.0.5
  [✔️] TipTheScales-1.16.3-3.0.0.9
  [✔️] titanium-1.16.4-3.2.2
  [✔️] Toast-Control-1.16.3-4.3.0
  [✔️] torchmaster-2.3.5-alpha
  [✔️] trashcans-1.0.3-mc1.16.4
  [✔️] valkyrielib-1.16.4-3.0.4.3
  [✔️] Waystones_1.16.3-7.3.1
  [✔️] woot-1.16.4-1.0.2.2
  [✔️] wormhole-1.1.0-mc1.16.3
  [✔️] xnet-1.16-3.0.11
  [✔️] XNetGases-1.16.4-2.1.1
  [✔️] ZeroCore2-1.16.4-2.0.16

Params:
  --username  --version 1.16.4 --gameDir C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/instances/FTB Presents Direwolf20 1.16/.minecraft --assetsDir C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 35.1.13 --fml.mcVersion 1.16.4 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20201102.104115

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx8320m, -Duser.language=en]

Minecraft process ID: 3400

Using onesix launcher.

Checking: MC_SLIM
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: PATCHED
Checking: MC_SRG
2022-09-19 20:08:04,455 main WARN Advanced terminal features are not available in this environment
[20:08:04] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Slimesoldier, --version, 1.16.4, --gameDir, C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/instances/FTB Presents Direwolf20 1.16/.minecraft, --assetsDir, C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/assets, --assetIndex, 1.16, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 35.1.13, --fml.mcVersion, 1.16.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20201102.104115, --width, 854, --height, 480]
[20:08:04] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.6+85+master.325de55 starting: java version 1.8.0_341 by Oracle Corporation
[20:08:04] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[20:08:05] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/jacki/Downloads/mmc-stable-win32(1)/MultiMC/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[20:08:05] [main/INFO] [STDOUT/]: [net.creeperhost.traylauncher.ModLocatorHack:<init>:32]: Initializing launcher communication
[20:08:07] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:213]: Failed to start Minecraft:
[20:08:07] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: java.lang.reflect.InvocationTargetException
[20:08:07] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:08:07] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:08:07] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:08:07] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20:08:07] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[20:08:07] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[20:08:07] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[20:08:07] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[20:08:07] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: Caused by: java.lang.reflect.InvocationTargetException
[20:08:07] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:08:07] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:08:07] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:08:07] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20:08:07] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
[20:08:07] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	... 8 more
[20:08:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
[20:08:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[20:08:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[20:08:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[20:08:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[20:08:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[20:08:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.forName0(Native Method)
[20:08:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.forName(Unknown Source)
[20:08:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:57)
[20:08:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:71)
[20:08:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:60)
[20:08:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:197)
[20:08:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:190)
[20:08:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.initializeLaunch(MixinLaunchPlugin.java:196)
[20:08:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[20:08:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.HashMap.forEach(Unknown Source)
[20:08:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[20:08:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[20:08:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[20:08:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[20:08:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[20:08:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 13 more
[20:08:07] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 19 Sep 2022 20:11:04 -0700

### Steps to reproduce

Download direwolf20 on ftb app and import it to multimc then try to load it.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Forge 34.1.27 to 36.2.24 (Minecraft 1.16.3-1.16.5) are broken with Java 8 Update 321 or newer.
If you are on 1.16.5 try upgrading your instances Forge version. If this isn't an option for you, you need an older Java 8 version, e.g. 8u312 you can find downloads here <https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk>

the crash will contain this
```
Caused by: java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
```

**Comment by Slimesoldier** [comment]
Thanks this helped!
