### ISSUE TITLE
Exiting with code -1

### ISSUE THREAD

**Issue by jeniusgregic** [MultiMC/Launcher#4921]
### Operating System

_Windows 11_

### Description of bug

Everytime I try to launch any instance it gives a crash no matter the Java Version, Forge Version or minecraft version. I tried updating changing everything and it didn't work. In this crashlog I am trying to launch a mod pack called Cave Factory. What could it be

### Steps to reproduce

MultiMC version: 0.6.16-3431

Launched instance in online mode

authserver.mojang.com resolves to:
    [64:ff9b::12a1:c13a, 64:ff9b::12a1:c12c, 64:ff9b::12a1:c136, 64:ff9b::12a1:c128, 18.161.193.58, 18.161.193.44, 18.161.193.54, 18.161.193.40]

session.minecraft.net resolves to:
    [64:ff9b::6418:ac5f, 64:ff9b::22c7:ec9a, 64:ff9b::2399:99c8, 100.24.172.95, 34.199.236.154, 35.153.153.200]

textures.minecraft.net resolves to:
    [64:ff9b::1243:5e, 64:ff9b::1243:c, 64:ff9b::1243:3e, 64:ff9b::1243:42, 18.67.0.62, 18.67.0.66, 18.67.0.94, 18.67.0.12]

api.mojang.com resolves to:
    [64:ff9b::6c9e:7a22, 64:ff9b::6c9e:7a54, 64:ff9b::6c9e:7a67, 64:ff9b::6c9e:7a7a, 52.85.213.14, 52.85.213.97, 52.85.213.57, 52.85.213.79]

Minecraft folder is:
C:/Users/aiueo/Documents/MultiMC/instances/Cave Factory/minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 19, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/aiueo/Documents/MultiMC/instances/Cave Factory/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/aiueo/Documents/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/net/minecraftforge/forge/1.16.5-36.2.23/forge-1.16.5-36.2.23-launcher.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/cpw/mods/grossjava9hacks/1.3.3/grossjava9hacks-1.3.3.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/com/electronwill/night-config/core/3.6.3/core-3.6.3.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/com/electronwill/night-config/toml/3.6.3/toml-3.6.3.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/net/minecraftforge/nashorn-core-compat/15.1.1.1/nashorn-core-compat-15.1.1.1.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  C:/Users/aiueo/Documents/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/aiueo/Documents/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] absentbydesign-1.16.5-1.5.1
  [✔️] Apotheosis-1.16.5-4.8.4
  [✔️] appleskin-forge-mc1.16.x-2.3.0
  [✔️] architectury-1.28.48
  [✔️] AttributeFix-1.16.5-10.1.3
  [✔️] AutoRegLib-1.6-49
  [✔️] BloodMagic-1.16.4-3.1.7-27
  [✔️] Bookshelf-Forge-1.16.5-10.4.31
  [✔️] Botania-1.16.5-420.2
  [✔️] Bountiful Baubles FORGE-1.16.3-0.0.2
  [✔️] buildersaddition-1.16.5-20210807a
  [✔️] buildinggadgets-1.16.5-3.8.2
  [✔️] carryon-1.16.5-1.15.5.22
  [✔️] CBMultipart-1.16.5-3.0.4.123-universal
  [✔️] cfm-7.0.0pre22-1.16.3
  [✔️] Chisel-MC1.16.5-2.0.1-alpha.4
  [✔️] chiselsandbits-1.0.63
  [✔️] ClientTweaks_1.16.3-5.3.0
  [✔️] cloth-config-4.13.49-forge
  [✔️] Clumps-6.0.0.27
  [✔️] cobblegenrandomizer-1.16-5.1.2
  [✔️] CodeChickenLib-1.16.5-4.0.6.443-universal
  [✔️] compactmachines-4.0.0-beta.2
  [✔️] configured-1.5.1-1.16.5
  [✔️] constructionwand-1.16.5-2.6
  [✔️] Controlling-7.0.0.28
  [✔️] CookingForBlockheads_1.16.5-9.3.4
  [✔️] corail_woodcutter-1.16-2.0.1
  [✔️] CraftingTweaks_1.16.5-12.2.1
  [✔️] createaddition-1.16.5-20211215b
  [✔️] create-mc1.16.5_v0.3.2g
  [✔️] creativewirelesstransmitter-1.16x-1.12
  [✔️] CTM-MC1.16.1-1.1.2.6
  [✔️] Cucumber-1.16.5-4.1.12
  [✔️] curios-forge-1.16.5-4.0.8.0
  [✔️] dankstorage-3.19
  [✔️] DarkUtilities-1.16.5-8.0.10
  [✔️] decorative_blocks-1.16.4-1.7.2
  [✔️] Ding-1.16.5-1.3.0
  [✔️] elevatorid-1.16.5-1.7.13
  [✔️] emojiful-1.16.4-2.1.6
  [✔️] EnchantmentDescriptions-1.16.5-7.0.18
  [✔️] enderchests-1.16-1.7.9
  [✔️] endertanks-1.16-1.9.8
  [✔️] engineersdecor-1.16.5-1.1.16
  [✔️] envirocore-1.16.5-3.0.9.3
  [✔️] enviromats-1.16.5-2.0.9.0
  [✔️] envirotech-1.16.5-3.0.9.4
  [✔️] ExCompressum_1.16.5-4.0.5
  [✔️] ExtendedCrafting-1.16.5-3.1.11
  [✔️] extradisks-1.16.4-1.5.1
  [✔️] ExtraStorage-1.16.5-1.6.0
  [✔️] ExtremeReactors2-1.16.5-2.0.38
  [✔️] extremeSoundMuffler-3.17_1.16.5
  [✔️] FarmersDelight-1.16.5-0.5.4
  [✔️] FarmingForBlockheads_1.16.5-7.3.1
  [✔️] FastFurnace-1.16.5-4.5.0
  [✔️] FastWorkbench-1.16.5-4.6.1
  [✔️] ferritecore-2.1.0-forge
  [✔️] FluxNetworks-1.16.5-6.2.1.14
  [✔️] flywheel-1.16-0.2.5
  [✔️] FramedBlocks-2.12.0
  [✔️] framedcompactdrawers-1.16-2.2.1
  [✔️] ftb-backups-2.1.2.2
  [✔️] ftb-chunks-forge-1605.3.2-build.115
  [✔️] ftb-library-forge-1605.3.4-build.90
  [✔️] ftb-quests-forge-1605.3.6-build.76
  [✔️] ftb-teams-forge-1605.2.3-build.40
  [✔️] ftb-ultimine-forge-1605.3.1-build.45
  [✔️] globaldataandresourcepacks-1.16.5-1.10.2
  [✔️] ImmersiveEngineering-1.16.5-5.0.7-143
  [✔️] ImmersivePetroleum-1.16.5-3.3.0-11
  [✔️] Interactio-1.16.4-3.1.1
  [✔️] ironchest-1.16.5-11.2.21
  [✔️] ironfurnaces-1.16.5-2.7.7
  [✔️] IronJetpacks-1.16.5-4.2.3
  [✔️] itemcollectors-1.1.4-mc1.16
  [✔️] item-filters-forge-1605.2.5-build.9
  [✔️] jei-1.16.5-7.7.1.145
  [✔️] jeiintegration_1.16.5-7.0.1.15
  [✔️] JustEnoughCalculation-1.16.5-3.8.6
  [✔️] JustEnoughProfessions-1.16.5-1.2.2
  [✔️] JustEnoughResources-1.16.5-0.12.1.133
  [✔️] KleeSlabs_1.16.5-9.2.1
  [✔️] kotlinforforge-1.16.0-obf
  [✔️] kubejs-blood-magic-1605.1.1-build.3
  [✔️] kubejs-create-1605.1.4-build.12
  [✔️] kubejs-forge-1605.3.19-build.258
  [✔️] kubejs-immersive-engineering-1605.1.2-build.28
  [✔️] kubejs-ui-forge-1605.1.4-build.12
  [✔️] lemonlib-1.3.6
  [✔️] LibX-1.16.3-1.0.76
  [✔️] light-overlay-5.8.1
  [✔️] Lollipop-1.16.5-3.2.9
  [✔️] LostTrinkets-1.16.5-0.1.27
  [✔️] Mantle-1.16.5-1.6.152
  [✔️] mcjtylib-1.16-5.1.3
  [✔️] mcw-doors-1.0.5-mc1.16.5
  [✔️] mcw-trapdoors-1.0.4-mc1.16.5
  [✔️] mcw-windows-2.0.2-mc1.16.5
  [✔️] minecolonies-1.16.5-1.0.352-BETA
  [✔️] miniutilities-1.2.3
  [✔️] mob_grinding_utils-1.16.5-0.4.32
  [✔️] mobcatcher-1.16.4-3.2a
  [✔️] modnametooltip_1.16.2-1.15.0
  [✔️] Morpheus-1.16.5-4.2.70
  [✔️] MouseTweaks-2.14-mc1.16.2
  [✔️] NBT-Ingredient-Predicate-1.3
  [✔️] Neat 1.7-27
  [✔️] oauth-1.1.11-1.16
  [✔️] observable-0.2.1-forge
  [✔️] overloadedarmorbar-5.1.0
  [✔️] pamhc2crops-1.16.3-1.0.2
  [✔️] pamhc2foodcore-1.16.3-1.0.2
  [✔️] pamhc2foodextended-1.16.3-1.0.4
  [✔️] pamhc2trees-1.16.3-1.0.1
  [✔️] Patchouli-1.16.4-53.2
  [✔️] performant-1.16.2-5-3.84m
  [✔️] pipez-1.16.5-1.2.15
  [✔️] Placebo-1.16.5-4.6.1
  [✔️] pneumaticcraft-repressurized-1.16.5-2.15.1-297
  [✔️] polymorph-forge-1.16.5-0.39
  [✔️] ProjectRed-1.16.5-4.11.0-beta-6-core
  [✔️] ProjectRed-1.16.5-4.11.0-beta-6-illumination
  [✔️] ProjectRed-1.16.5-4.11.0-beta-6-integration
  [✔️] ProjectRed-1.16.5-4.11.0-beta-6-transmission
  [✔️] Quark-r2.4-321
  [✔️] randompatches-2.4.4-forge
  [✔️] refinedstorage-1.9.16
  [✔️] refinedstorageaddons-0.7.4
  [✔️] reliquary-1.16.5-1.3.5.1104
  [✔️] rftoolsbase-1.16-2.1.2
  [✔️] rftoolsbuilder-1.16-3.1.5
  [✔️] rftoolspower-1.16-3.0.13
  [✔️] rftoolsutility-1.16-3.1.9
  [✔️] rhino-forge-1605.1.5-build.75
  [✔️] rsgauges-1.16.5-1.2.13
  [✔️] RSLargePatterns-1.16.5-2.1.0.3
  [✔️] rsrequestify-1.16.5-2.1.6
  [✔️] Runelic-1.16.5-7.0.2
  [✔️] Scorge-3.1.3
  [✔️] selene-1.16.5-1.9.0
  [✔️] shetiphiancore-1.16-3.8.9
  [✔️] simplemagnets-1.1.4-mc1.16
  [✔️] SimpleStorageNetwork-1.16.5-1.5.1
  [✔️] SkyblockBuilder-1.16.4-1.6.13
  [✔️] snad-1.0.9-forge
  [✔️] SoL-Carrot-1.16.5-1.10.1
  [✔️] sophisticatedbackpacks-1.16.5-3.15.1.503
  [✔️] StorageDrawers-1.16.3-8.5.1
  [✔️] structurize-0.13.252-ALPHA-universal
  [✔️] supermartijn642configlib-1.0.9-mc1.16
  [✔️] supermartijn642corelib-1.0.16-mc1.16.5
  [✔️] supplementaries-1.16.5-0.18.2
  [✔️] tanknull-2.3-1.16.4
  [✔️] TConstruct-1.16.5-3.3.2.324
  [✔️] theoneprobe-1.16-3.1.4
  [✔️] Tiny-Coal-1.16.4-1.0.0
  [✔️] tombstone-6.7.1-1.16.5
  [✔️] topaddons-1.16.5-2.2.0-beta
  [✔️] torchmaster-2.3.8
  [✔️] toughnessbar-6.1
  [✔️] trashcans-1.0.12-mc1.16
  [✔️] TrashSlot_1.16.3-12.2.1
  [✔️] TravelAnchors-2.4
  [✔️] TwerkItMeal-1.3.9
  [✔️] twilightforest-1.16.5-4.0.870-universal
  [✔️] valkyrielib-1.16.5-3.0.9.5
  [✔️] xnet-1.16-3.0.16
  [✔️] ZeroCore2-1.16.5-2.1.9

Params:
  --username  --version 1.16.5 --gameDir C:/Users/aiueo/Documents/MultiMC/instances/Cave Factory/minecraft --assetsDir C:/Users/aiueo/Documents/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 36.2.23 --fml.mcVersion 1.16.5 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20210115.111550

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx2048m, -Duser.language=en]

Minecraft process ID: 14232

Using onesix launcher.

Checking: MC_SLIM
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: PATCHED
Checking: MC_SRG
2022-09-22 17:20:18,265 main WARN Advanced terminal features are not available in this environment
[17:20:18] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Juuuaan_, --version, 1.16.5, --gameDir, C:/Users/aiueo/Documents/MultiMC/instances/Cave Factory/minecraft, --assetsDir, C:/Users/aiueo/Documents/MultiMC/assets, --assetIndex, 1.16, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.23, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --width, 854, --height, 480]
[17:20:18] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 19 by Oracle Corporation
[17:20:18] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[17:20:18] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/aiueo/Documents/MultiMC/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[17:20:19] [Thread-1/INFO] [STDERR/]: [org.lwjgl.system.ThreadLocalUtil:<clinit>:135]: [LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
[17:20:21] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '~'
[17:20:22] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:213]: Failed to start Minecraft:
[17:20:22] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: java.lang.reflect.InvocationTargetException
[17:20:22] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
[17:20:22] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[17:20:22] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[17:20:22] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[17:20:22] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[17:20:22] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]: Caused by: java.lang.reflect.InvocationTargetException
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]: 	... 5 more
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: Caused by: java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at java.base/java.lang.Class.forName0(Native Method)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at java.base/java.lang.Class.forName(Class.java:495)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at java.base/java.lang.Class.forName(Class.java:474)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:67)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:70)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:59)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:196)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at java.base/java.util.HashMap.forEach(HashMap.java:1429)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[17:20:22] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	... 8 more
[17:20:22] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 22 Sep 2022 17:20:29 -0300

### Suspected cause

When changing java versions the error changes. previously I thought it was because it was on the program files folder but I moved to docs folder and nothing changed. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Forge 34.1.27 to 36.2.24 (Minecraft 1.16.3-1.16.5) are broken with Java 8 Update 321 or newer.
If you are on 1.16.5 try upgrading your instances Forge version. If this isn't an option for you, you need an older Java 8 version, e.g. 8u312 you can find downloads here <https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk>

the crash will contain this
```
Caused by: java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
```
