### ISSUE TITLE
Unable to launch any profile - MacOS 12.6, Java 19, MultiMC 5 v0.6.16-3433

### ISSUE THREAD

**Issue by juleklO** [MultiMC/Launcher#4940]
### Operating System

macOS

### Description of bug

I'm running a Macbook Air M2, with 8Gb RAM, 256Gb ROM.
I've installed java from https://www.oracle.com/java/technologies/downloads/#jdk19-mac.
MultiMC installation from https://multimc.org/#Download.

Whenever I try to launch minecraft with it, no matter if this is a preexisting profile zipped from my main PC, or a clean version install, I get the error below. Restarting the machine does not fix the issue.

```
MultiMC version: 0.6.16-3434


Launched instance in online mode

authserver.mojang.com resolves to:
    [18.66.119.38, 18.66.119.37, 18.66.119.42, 18.66.119.35]

session.minecraft.net resolves to:
    [35.153.153.200, 34.199.236.154, 100.24.172.95]

textures.minecraft.net resolves to:
    [13.32.99.35, 13.32.99.54, 13.32.99.32, 13.32.99.71]

api.mojang.com resolves to:
    [108.138.17.109, 108.138.17.100, 108.138.17.3, 108.138.17.41]


Minecraft folder is:
/Applications/MultiMC.app/Data/instances/1.191/.minecraft


Java path is:
/usr/bin/java


Checking Java version...
Java is version 19, using 32-bit architecture, from Oracle Corporation.


Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.


Main Class:
  net.minecraft.client.main.Main

Native path:
  /Applications/MultiMC.app/Data/instances/1.191/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /Applications/MultiMC.app/Data/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  /Applications/MultiMC.app/Data/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  /Applications/MultiMC.app/Data/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  /Applications/MultiMC.app/Data/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-common/4.1.77.Final/netty-common-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-buffer/4.1.77.Final/netty-buffer-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-codec/4.1.77.Final/netty-codec-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-handler/4.1.77.Final/netty-handler-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-resolver/4.1.77.Final/netty-resolver-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport/4.1.77.Final/netty-transport-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport-native-unix-common/4.1.77.Final/netty-transport-native-unix-common-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport-classes-epoll/4.1.77.Final/netty-transport-classes-epoll-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /Applications/MultiMC.app/Data/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /Applications/MultiMC.app/Data/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /Applications/MultiMC.app/Data/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar
  /Applications/MultiMC.app/Data/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/authlib/3.5.41/authlib-3.5.41.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /Applications/MultiMC.app/Data/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  /Applications/MultiMC.app/Data/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/text2speech/1.13.9/text2speech-1.13.9.jar
  /Applications/MultiMC.app/Data/libraries/ca/weblite/java-objc-bridge/1.1/java-objc-bridge-1.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/minecraft/1.19/minecraft-1.19-client.jar

Native libraries:
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-macos.jar

Params:
  --username  --version 1.19 --gameDir /Applications/MultiMC.app/Data/instances/1.191/.minecraft --assetsDir /Applications/MultiMC.app/Data/assets --assetIndex 1.19 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: 1.19", -XstartOnFirstThread, -Xms2048m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 1084


Using onesix launcher.

[11:20:34] [main/INFO]: Building optimized datafixer
[11:20:35] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[11:20:35] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[11:20:35] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[11:20:36] [Render thread/INFO]: [STDERR]: Failed to start Minecraft:
[11:20:36] [Render thread/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
[11:20:36] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
[11:20:36] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[11:20:36] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[11:20:36] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[11:20:36] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[11:20:36] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[11:20:36] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
[11:20:36] [Render thread/INFO]: [STDERR]: 	at ac.a(SourceFile:65)
[11:20:36] [Render thread/INFO]: [STDERR]: 	at eev.a(SourceFile:2306)
[11:20:36] [Render thread/INFO]: [STDERR]: 	at eev.a(SourceFile:2301)
[11:20:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:207)
[11:20:36] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[11:20:36] [Render thread/INFO]: [STDERR]: 	... 5 more
[11:20:36] [Render thread/INFO]: [STDERR]: Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.dylib [in thread "Render thread"]
[11:20:36] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:164)
[11:20:36] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:63)
[11:20:36] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.<clinit>(Library.java:51)
[11:20:36] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
[11:20:36] [Render thread/INFO]: [STDERR]: 	at dyq.<clinit>(SourceFile:8)
[11:20:36] [Render thread/INFO]: [STDERR]: 	at dzo.<init>(SourceFile:51)
[11:20:36] [Render thread/INFO]: [STDERR]: 	at dzv.<init>(SourceFile:19)
[11:20:36] [Render thread/INFO]: [STDERR]: 	at dzv.<init>(SourceFile:23)
[11:20:36] [Render thread/INFO]: [STDERR]: 	at dzv.<clinit>(SourceFile:11)
[11:20:36] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(SourceFile:46)
[11:20:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:195)
[11:20:36] [Render thread/INFO]: [STDERR]: 	... 6 more
[11:20:36] [Render thread/INFO]: [STDOUT]: Exiting with -1
Process exited with code 255 (0xff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 15 Oct 2022 11:20:39 +0200

```

I'll try to answer all questions and requests asap, thank you for your project and contributions to the community!

### Steps to reproduce

1. Buy an overpriced piece of hardware.
2. Download and install 'Arm 64 DMG Installer' from https://www.oracle.com/java/technologies/downloads/#jdk19-mac.
3. Restart the machine, just to be safe
4. Download and install MultiMC for Mac from https://multimc.org/#Download.
5. Launch MultiMC and create a profile, in my example this was 1.19(.0)
6. Launch the profile

### Suspected cause

ARM M2 architecture, maybe MacOS itself

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you need to download Java for x64, see the links in the windows section here https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by juleklO** [comment]
For any future Me-s, here's a quick [video ](https://youtu.be/iSjZLaE8hJU)tutorial I've put together, thank you for the support again!
