### ISSUE TITLE
Process exited with code 255 (0xff) when attempting to launch MultiMC on Mac M1.

### ISSUE THREAD

**Issue by AMR2586** [MultiMC/Launcher#4988]
### Operating System

macOS

### Description of bug

Hi. I'm getting the error "Process exited with code 255 (0xff)." I'm not sure how to fix it. I'm running MultiMC on a Mac M1 with macOS Ventura 13.0.1 (22A400).  I have JDK-19. I am able to launch MC via the native MC launcher, but not MultiMC. I have tried restarting as others with this error recommended, but it did not fix the problem. Here is the log:

MultiMC version: 0.6.16-3434

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.33.61.46, 13.33.61.64, 13.33.61.34, 13.33.61.44]

session.minecraft.net resolves to:
    [34.197.32.8, 35.153.153.200, 100.24.172.95]

textures.minecraft.net resolves to:
    [13.107.213.40, 13.107.246.40]

api.mojang.com resolves to:
    [108.139.47.60, 108.139.47.33, 108.139.47.94, 108.139.47.9]

Minecraft folder is:
/Applications/MultiMC.app/Data/instances/1.19.2/.minecraft

Java path is:
/Library/Java/JavaVirtualMachines/jdk-19.jdk/Contents/Home/bin/java

Checking Java version...
Java is version 19.0.1, using 32-bit architecture, from Oracle Corporation.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  net.minecraft.client.main.Main

Native path:
  /Applications/MultiMC.app/Data/instances/1.19.2/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /Applications/MultiMC.app/Data/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  /Applications/MultiMC.app/Data/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.0/log4j-slf4j18-impl-2.17.0.jar
  /Applications/MultiMC.app/Data/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  /Applications/MultiMC.app/Data/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-common/4.1.77.Final/netty-common-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-buffer/4.1.77.Final/netty-buffer-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-codec/4.1.77.Final/netty-codec-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-handler/4.1.77.Final/netty-handler-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-resolver/4.1.77.Final/netty-resolver-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport/4.1.77.Final/netty-transport-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport-native-unix-common/4.1.77.Final/netty-transport-native-unix-common-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport-classes-epoll/4.1.77.Final/netty-transport-classes-epoll-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /Applications/MultiMC.app/Data/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /Applications/MultiMC.app/Data/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /Applications/MultiMC.app/Data/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar
  /Applications/MultiMC.app/Data/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/authlib/3.11.49/authlib-3.11.49.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /Applications/MultiMC.app/Data/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  /Applications/MultiMC.app/Data/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-api/2.17.0/log4j-api-2.17.0.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-core/2.17.0/log4j-core-2.17.0.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/text2speech/1.13.9/text2speech-1.13.9.jar
  /Applications/MultiMC.app/Data/libraries/ca/weblite/java-objc-bridge/1.1/java-objc-bridge-1.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/minecraft/1.19.2/minecraft-1.19.2-client.jar

Native libraries:
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-macos.jar

Params:
  --username  --version 1.19.2 --gameDir /Applications/MultiMC.app/Data/instances/1.19.2/.minecraft --assetsDir /Applications/MultiMC.app/Data/assets --assetIndex 1.19 --uuid  --accessToken  --userType  --versionType release

Window size: max (if available)

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: 1.19.2", -XstartOnFirstThread, -Xms512m, -Xmx8000m, -Duser.language=en]

Minecraft process ID: 13039

Using onesix launcher.

[20:40:15] [main/INFO]: Building optimized datafixer
[20:40:17] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[20:40:17] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[20:40:17] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[20:40:18] [Render thread/INFO]: [STDERR]: Failed to start Minecraft:
[20:40:18] [Render thread/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
[20:40:18] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
[20:40:18] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[20:40:18] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[20:40:18] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[20:40:18] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[20:40:18] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[20:40:18] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
[20:40:18] [Render thread/INFO]: [STDERR]: 	at ac.a(SourceFile:66)
[20:40:18] [Render thread/INFO]: [STDERR]: 	at efu.a(SourceFile:2359)
[20:40:18] [Render thread/INFO]: [STDERR]: 	at efu.a(SourceFile:2354)
[20:40:18] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.a(SourceFile:214)
[20:40:18] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:51)
[20:40:18] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[20:40:18] [Render thread/INFO]: [STDERR]: 	... 5 more
[20:40:18] [Render thread/INFO]: [STDERR]: Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.dylib [in thread "Render thread"]
[20:40:18] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:164)
[20:40:18] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:63)
[20:40:18] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.<clinit>(Library.java:51)
[20:40:18] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
[20:40:18] [Render thread/INFO]: [STDERR]: 	at dzn.<clinit>(SourceFile:8)
[20:40:18] [Render thread/INFO]: [STDERR]: 	at eal.<init>(SourceFile:51)
[20:40:18] [Render thread/INFO]: [STDERR]: 	at eas.<init>(SourceFile:19)
[20:40:18] [Render thread/INFO]: [STDERR]: 	at eas.<init>(SourceFile:23)
[20:40:18] [Render thread/INFO]: [STDERR]: 	at eas.<clinit>(SourceFile:11)
[20:40:18] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(SourceFile:46)
[20:40:18] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.a(SourceFile:202)
[20:40:18] [Render thread/INFO]: [STDERR]: 	... 7 more
[20:40:18] [Render thread/INFO]: [STDOUT]: Exiting with -1
Process exited with code 255 (0xff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 23 Nov 2022 20:42:54 -0500
Clipboard copy at: 23 Nov 2022 20:42:54 -0500

### Steps to reproduce

Any attempt to launch MC via MultiMC.

### Suspected cause

No clue.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by AMR2586** [comment]
It is saying "Java is version 19.0.1, using 32-bit architecture, from Oracle Corporation.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version." However, I have the 64 version installed. I'm not sure how to fix this.

**Comment by phit** [comment]
you need to install Java for x86 and run the game through Rosetta, as MultiMC currently does not support native ARM

**Comment by Cat7373** [comment]
Working fix (tested): [Link Removed]

**Comment by TacoGS** [comment]
This should go without saying. Do not link in our issues to a page that tells them to not use MultiMC.
