### ISSUE TITLE
Process exited with code 1 (0x1)

### ISSUE THREAD

**Issue by mxumu** [MultiMC/Launcher#5035]
### Operating System

macOS

### Description of bug

I ran Minecraft but it failed and gave me error code 1. It was supposed to launch my game but didn't.

### Steps to reproduce

MultiMC version: 0.6.16-3434

Launched instance in online mode

authserver.mojang.com resolves to:
    [65.8.160.55, 65.8.160.42, 65.8.160.61, 65.8.160.40]

session.minecraft.net resolves to:
    [35.153.153.200, 34.197.32.8, 100.24.172.95]

textures.minecraft.net resolves to:
    [2620:1ec:4e:1::69, 2620:1ec:4f:1::69, 13.107.237.69, 13.107.238.69]

api.mojang.com resolves to:
    [65.8.158.94, 65.8.158.37, 65.8.158.22, 65.8.158.123]

Minecraft folder is:
/Applications/MultiMC.app/Data/instances/ANTI TI TI TI FRAGILE/.minecraft

Java path is:
/usr/bin/java

Checking Java version...
Java is version 17.0.5, using 32-bit architecture, from Oracle Corporation.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  /Applications/MultiMC.app/Data/instances/ANTI TI TI TI FRAGILE/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /Applications/MultiMC.app/Data/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  /Applications/MultiMC.app/Data/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.0/log4j-slf4j18-impl-2.17.0.jar
  /Applications/MultiMC.app/Data/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  /Applications/MultiMC.app/Data/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-common/4.1.77.Final/netty-common-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-buffer/4.1.77.Final/netty-buffer-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-codec/4.1.77.Final/netty-codec-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-handler/4.1.77.Final/netty-handler-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-resolver/4.1.77.Final/netty-resolver-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport/4.1.77.Final/netty-transport-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport-native-unix-common/4.1.77.Final/netty-transport-native-unix-common-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport-classes-epoll/4.1.77.Final/netty-transport-classes-epoll-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /Applications/MultiMC.app/Data/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /Applications/MultiMC.app/Data/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /Applications/MultiMC.app/Data/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar
  /Applications/MultiMC.app/Data/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/authlib/3.11.49/authlib-3.11.49.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /Applications/MultiMC.app/Data/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  /Applications/MultiMC.app/Data/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-api/2.17.0/log4j-api-2.17.0.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-core/2.17.0/log4j-core-2.17.0.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/text2speech/1.13.9/text2speech-1.13.9.jar
  /Applications/MultiMC.app/Data/libraries/ca/weblite/java-objc-bridge/1.1/java-objc-bridge-1.1.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/intermediary/1.19.2/intermediary-1.19.2.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm/9.4/asm-9.4.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-analysis/9.4/asm-analysis-9.4.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-commons/9.4/asm-commons-9.4.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-tree/9.4/asm-tree-9.4.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-util/9.4/asm-util-9.4.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/fabric-loader/0.14.12/fabric-loader-0.14.12.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/minecraft/1.19.2/minecraft-1.19.2-client.jar

Native libraries:
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-macos.jar

Mods:
  [✔️] 3dskinlayers-fabric-1.5.2-mc1.19.1
  [✔️] animatica-0.5+1.19
  [✔️] c2me-fabric-mc1.19.2-0.2.0+alpha.9.0
  [✔️] Capes-1.4.5+1.19
  [✔️] cem-0.7.1
  [✔️] CITResewn-1.1.2+1.19.2
  [✔️] colormatic-3.1.2+mc.1.19
  [✔️] continuity-2.0.1+1.19
  [✔️] enhancedblockentities-0.7.2+1.19.2
  [✔️] entity_texture_features_fabric_1.19.2-4.3.0
  [✔️] entityculling-fabric-1.5.2-mc1.19
  [✔️] exordium-fabric-1.0.2-mc1.19.2
  [✔️] fabric-api-0.71.0+1.19.2
  [✔️] fabric-language-kotlin-1.9.0+kotlin.1.8.0
  [✔️] fabricskyboxes-0.6.1+mc1.19.2
  [✔️] Fastload+1.19.2-2.6.10
  [✔️] ferritecore-5.0.3-fabric
  [✔️] fsb-interop-1.1.3+mc1.19.2-build.25
  [✔️] illuminations-1.10.11
  [✔️] ImmediatelyFast-1.1.5+1.19
  [✔️] indium-1.0.9+mc1.19.2
  [✔️] iris-mc1.19.2-1.4.3
  [✔️] lambdabettergrass-1.3.0+1.19
  [✔️] lambdynamiclights-2.2.0+1.19.2
  [✔️] lazydfu-0.1.3
  [✔️] lithium-fabric-mc1.19.2-0.10.4
  [✔️] memoryleakfix-1.19.1-0.7.0
  [✔️] modmenu-4.1.2
  [✔️] moreculling-1.19.1-0.12.4
  [✔️] puzzle-1.4.0-1.19
  [✔️] reeses_sodium_options-1.4.9+mc1.19.2-build.67
  [✔️] smoothboot-fabric-1.19-1.7.1
  [✔️] sodium-extra-0.4.16+mc1.19.2-build.90
  [✔️] sodium-fabric-mc1.19.2-0.4.4+build.18
  [✔️] starlight-1.1.1+fabric.ae22326
  [✔️] YetAnotherConfigLib-1.7.1
  [✔️] Zoomify-2.9.0

Params:
  --username  --version 1.19.2 --gameDir /Applications/MultiMC.app/Data/instances/ANTI TI TI TI FRAGILE/.minecraft --assetsDir /Applications/MultiMC.app/Data/assets --assetIndex 1.19 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: ANTI TI TI TI FRAGILE", -XstartOnFirstThread, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 13859

Using onesix launcher.

[13:03:06] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.12
[13:03:06] [main/WARN]: Warnings were found!
 - Mod 'Custom Entity Models' (cem) 0.7.1 recommends any version of completeconfig, which is missing!
	 - You should install any version of completeconfig for the optimal experience.
 - Mod 'Colormatic' (colormatic) 3.1.2+mc.1.19 recommends any version of quilt_loader, which is missing!
	 - You should install any version of quilt_loader for the optimal experience.
 - Mod 'Colormatic' (colormatic) 3.1.2+mc.1.19 recommends any version between 3.0.0 (inclusive) and 4- (exclusive) of mod 'Mod Menu' (modmenu), but only the wrong version is present: 4.1.2!
	 - You should install any version between 3.0.0 (inclusive) and 4- (exclusive) of mod 'Mod Menu' (modmenu) for the optimal experience.
[13:03:06] [main/INFO]: Loading 152 mods:
	- advanced_runtime_resource_pack 0.6.2 via enhancedblockentities
	- animatica 0.5+1.19
	- c2me 0.2.0+alpha.9.0
	- c2me-base 0.2.0+alpha.9.0 via c2me
	- c2me-client-uncapvd 0.2.0+alpha.9.0 via c2me
	- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.9.0 via c2me
	- c2me-fixes-general-threading-issues 0.2.0+alpha.9.0 via c2me
	- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.9.0 via c2me
	- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.9.0 via c2me
	- c2me-notickvd 0.2.0+alpha.9.0 via c2me
	- c2me-opts-allocs 0.2.0+alpha.9.0 via c2me
	- c2me-opts-chunk-access 0.2.0+alpha.9.0 via c2me
	- c2me-opts-chunkio 0.2.0+alpha.9.0 via c2me
	- c2me-opts-math 0.2.0+alpha.9.0 via c2me
	- c2me-opts-scheduling 0.2.0+alpha.9.0 via c2me
	- c2me-opts-worldgen-general 0.2.0+alpha.9.0 via c2me
	- c2me-opts-worldgen-vanilla 0.2.0+alpha.9.0 via c2me
	- c2me-rewrites-chunkio 0.2.0+alpha.9.0 via c2me
	- c2me-server-utils 0.2.0+alpha.9.0 via c2me
	- c2me-threading-chunkio 0.2.0+alpha.9.0 via c2me
	- c2me-threading-lighting 0.2.0+alpha.9.0 via c2me
	- c2me-threading-scheduling 0.2.0+alpha.9.0 via c2me
	- c2me-threading-worldgen 0.2.0+alpha.9.0 via c2me
	- caffeineconfig 1.0.0+1.17 via sodium-extra
	- capes 1.4.5+1.19
	- cem 0.7.1
	- citresewn 1.1.2+1.19.2
	- citresewn-defaults 1.1.2+1.19.2 via citresewn
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 7.0.74 via moreculling
	- colormatic 3.1.2+mc.1.19
	- com_electronwill_night-config_core 3.6.5 via c2me
	- com_electronwill_night-config_toml 3.6.5 via c2me
	- com_github_llamalad7_mixinextras 0.1.1 via immediatelyfast
	- com_ibm_async_asyncutil 0.1.0 via c2me
	- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
	- completeconfig-base 2.0.0-beta.3 via cem
	- completeconfig-gui-cloth 2.0.0-beta.3 via cem
	- conditional-mixin 0.3.0 via moreculling
	- continuity 2.0.1+1.19
	- dev_isxander_settxi_settxi-core 2.10.5 via zoomify
	- dev_isxander_settxi_settxi-gui 2.10.5 via zoomify
	- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.5 via zoomify
	- enhancedblockentities 0.7.2+1.19.2
	- entity_texture_features 4.3.0
	- entityculling 1.5.2-mc1.19
	- exordium 1.0.2-mc1.19.2
	- fabric-api 0.71.0+1.19.2
	- fabric-api-base 0.4.14+6e0787e690 via fabric-api
	- fabric-api-lookup-api-v1 1.6.13+93d8cb8290 via fabric-api
	- fabric-biome-api-v1 9.1.0+82db024a90 via fabric-api
	- fabric-block-api-v1 1.0.2+e415d50e90 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.23+c6af733c90 via fabric-api
	- fabric-client-tags-api-v1 1.0.4+b35fea8390 via fabric-api
	- fabric-command-api-v1 1.2.14+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.1.10+93d8cb8290 via fabric-api
	- fabric-commands-v0 0.2.31+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.40+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.5.0+7c6cd14d90 via fabric-api
	- fabric-convention-tags-v1 1.2.1+27265b3490 via fabric-api
	- fabric-crash-report-info-v1 0.2.8+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.3.5+2d2baf4b90 via fabric-api
	- fabric-dimensions-v1 2.1.34+0d0f210290 via fabric-api
	- fabric-entity-events-v1 1.5.3+9244241690 via fabric-api
	- fabric-events-interaction-v0 0.4.33+562bff6e90 via fabric-api
	- fabric-events-lifecycle-v0 0.2.33+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.24+b6b6abb490 via fabric-api
	- fabric-item-api-v1 1.6.3+9785ec3590 via fabric-api
	- fabric-item-groups-v0 0.3.37+9244241690 via fabric-api
	- fabric-key-binding-api-v1 1.0.25+5c4fce2890 via fabric-api
	- fabric-keybindings-v0 0.2.23+df3654b390 via fabric-api
	- fabric-language-kotlin 1.9.0+kotlin.1.8.0
	- fabric-lifecycle-events-v1 2.2.3+1b46dc7890 via fabric-api
	- fabric-loot-api-v2 1.1.11+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.14+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.6+93d8cb8290 via fabric-api
	- fabric-mining-level-api-v1 2.1.22+33fbc73890 via fabric-api
	- fabric-models-v0 0.3.20+c6af733c90 via fabric-api
	- fabric-networking-api-v1 1.2.10+10eb22f490 via fabric-api
	- fabric-networking-v0 0.3.27+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.1.5+9785ec3590 via fabric-api
	- fabric-particles-v1 1.0.13+4d0d570390 via fabric-api
	- fabric-registry-sync-v0 0.9.31+9244241690 via fabric-api
	- fabric-renderer-api-v1 1.2.0+2e5408b590 via fabric-api
	- fabric-renderer-indigo 0.7.0+2e5408b590 via fabric-api
	- fabric-renderer-registries-v1 3.2.23+df3654b390 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.18+6e0787e690 via fabric-api
	- fabric-rendering-fluids-v1 3.0.10+4d0d570390 via fabric-api
	- fabric-rendering-v0 1.1.26+df3654b390 via fabric-api
	- fabric-rendering-v1 1.12.0+08b73de490 via fabric-api
	- fabric-resource-conditions-api-v1 2.1.2+aae9039d90 via fabric-api
	- fabric-resource-loader-v0 0.8.3+251d254a90 via fabric-api
	- fabric-screen-api-v1 1.0.31+4d0d570390 via fabric-api
	- fabric-screen-handler-api-v1 1.3.6+1cc24b1b90 via fabric-api
	- fabric-sound-api-v1 1.0.2+c4f28df590 via fabric-api
	- fabric-textures-v0 1.0.23+aeb40ebe90 via fabric-api
	- fabric-transfer-api-v1 2.1.4+4d0d570390 via fabric-api
	- fabric-transitive-access-wideners-v1 1.3.3+08b73de490 via fabric-api
	- fabricloader 0.14.12
	- fabricskyboxes 0.6.1+mc1.19.2
	- fastload 2.6.10
	- ferritecore 5.0.3
	- fsb-interop 1.1.3+mc1.19.2-build.25
	- illuminations 1.10.11
	- immediatelyfast 1.1.5
	- indium 1.0.9+mc1.19.2
	- io_github_douira_glsl-transformer 1.0.1 via iris
	- iris 1.4.3
	- java 17
	- lambdabettergrass 1.3.0+1.19
	- lambdynlights 2.2.0+1.19.2
	- lazydfu 0.1.3
	- lithium 0.10.4
	- memoryleakfix 1.19.1-0.7.0
	- midnightlib 0.5.2 via puzzle
	- minecraft 1.19.2
	- modmenu 4.1.2
	- moreculling 1.19.1-0.12.4
	- net_objecthunter_exp4j 0.4.8 via c2me
	- omega-config 1.2.3-1.18.1 via capes
	- org_anarres_jcpp 1.4.14 via iris
	- org_antlr_antlr4-runtime 4.10.1 via iris
	- org_apache_httpcomponents_httpmime 4.5.10 via entity_texture_features
	- org_jetbrains_kotlin_kotlin-reflect 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.5 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
	- org_joml_joml 1.10.4 via sodium
	- org_threadly_threadly 7.0 via c2me
	- pride 1.1.2+1.19 via lambdynlights
	- puzzle 1.4.0-1.19
	- puzzle-base 1.4.0-1.19 via puzzle
	- puzzle-gui 1.4.0-1.19 via puzzle
	- puzzle-models 1.4.0-1.19 via puzzle
	- puzzle-splashscreen 1.4.0-1.19 via puzzle
	- reeses-sodium-options 1.4.9+mc1.19.2-build.67
	- settxi-gui-yacl 2.10.5 via zoomify
	- skinlayers 1.5.2-mc1.19.1
	- smoothboot 1.19-1.7.1
	- sodium 0.4.4+build.18
	- sodium-extra 0.4.16+mc1.19.2-build.90
	- spruceui 4.1.0+1.19.2 via lambdynlights
	- starlight 1.1.1+fabric.ae22326
	- yet-another-config-lib 1.7.1
	- zoomify 2.9.0
[13:03:06] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/Applications/MultiMC.app/Data/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[13:03:06] [main/INFO]: Compatibility level set to JAVA_16
[13:03:06] [main/INFO]: Compatibility level set to JAVA_17
[13:03:06] [main/INFO]: Initializing com.ishland.c2me.base.mixin
[13:03:06] [main/INFO]: Initializing com.ishland.c2me.client.uncapvd.mixin
[13:03:06] [main/INFO]: Disabling com.ishland.c2me.client.uncapvd.mixin
[13:03:06] [main/INFO]: Initializing com.ishland.c2me.fixes.chunkio.threading_issues.mixin
[13:03:06] [main/INFO]: Initializing com.ishland.c2me.fixes.general.threading_issues.mixin
[13:03:06] [main/INFO]: Initializing com.ishland.c2me.fixes.worldgen.threading_issues.mixin
[13:03:06] [main/INFO]: Initializing com.ishland.c2me.fixes.worldgen.vanilla_bugs.mixin
[13:03:06] [main/INFO]: Initializing com.ishland.c2me.notickvd.mixin
[13:03:06] [main/INFO]: Initializing com.ishland.c2me.opts.allocs.mixin
[13:03:06] [main/INFO]: Initializing com.ishland.c2me.opts.chunk_access.mixin
[13:03:06] [main/INFO]: Initializing com.ishland.c2me.opts.chunkio.mixin
[13:03:06] [main/INFO]: Initializing com.ishland.c2me.opts.math.mixin
[13:03:06] [main/INFO]: Initializing com.ishland.c2me.opts.scheduling.mixin
[13:03:06] [main/INFO]: Initializing com.ishland.c2me.opts.worldgen.general.mixin
[13:03:06] [main/INFO]: Initializing com.ishland.c2me.opts.worldgen.vanilla.mixin
[13:03:06] [main/INFO]: Initializing com.ishland.c2me.rewrites.chunkio.mixin
[13:03:06] [main/INFO]: Initializing com.ishland.c2me.server.utils.mixin
[13:03:06] [main/INFO]: Initializing com.ishland.c2me.threading.chunkio.mixin
[13:03:06] [main/INFO]: Initializing com.ishland.c2me.threading.lighting.mixin
[13:03:06] [main/INFO]: Initializing com.ishland.c2me.threading.scheduling.mixin
[13:03:06] [main/INFO]: Initializing com.ishland.c2me.threading.worldgen.mixin
[13:03:06] [main/INFO]: Loaded configuration file for Lithium: 106 options available, 2 override(s) found
[13:03:06] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 2 override(s) found
[13:03:06] [main/INFO]: Loaded configuration file for Sodium Extra: 28 options available, 0 override(s) found
[13:03:07] [main/WARN]: Mixin malte0811.ferritecore.mixin.threaddetec.PalettedContainerMixin is disabled automatically as lithium is installed
[13:03:07] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[13:03:07] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [c2me]) disables it and children
[13:03:07] [main/WARN]: Force-disabling mixin 'features.fast_biome_colors.MixinBackgroundRenderer' as rule 'mixin.features.fast_biome_colors' (added by mods [colormatic]) disables it and children
[13:03:07] [main/WARN]: Force-disabling mixin 'features.fast_biome_colors.MixinClientWorld' as rule 'mixin.features.fast_biome_colors' (added by mods [colormatic]) disables it and children
[13:03:07] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[13:03:07] [main/INFO]: I used the json to destroy the json
[13:03:07] [main/INFO]: Smooth Boot config initialized
[13:03:09] [main/INFO]: Building unoptimized datafixer
minecraft:empty task radius: -1 -> -1
minecraft:structure_starts task radius: 0 -> 0
minecraft:structure_references task radius: 8 -> 0
minecraft:biomes task radius: 8 -> 0
minecraft:noise task radius: 8 -> 0
minecraft:surface task radius: 8 -> 0
minecraft:carvers task radius: 8 -> 0
minecraft:liquid_carvers task radius: 8 -> 0
minecraft:features task radius: 8 -> 1
minecraft:light task radius: 1 -> 1
minecraft:spawn task radius: 0 -> 0
minecraft:heightmaps task radius: 0 -> 0
minecraft:full task radius: 0 -> 0
[13:03:10] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder from mod sodium, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[13:03:10] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[13:03:10] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[13:03:10] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[13:03:10] [Render thread/WARN]: Discarding @Unique public method getAnimatedSkin in 3dskinlayers.mixins.json:DonorAbstractClientPlayerMixin from mod skinlayers because it already exists in net.minecraft.class_742
[13:03:10] [Render thread/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at net.minecraft.class_6396.method_37123(class_6396.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_37274(class_310.java:2359) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_22681(class_310.java:2354) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:214) ~[minecraft-1.19.2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	... 10 more
Process exited with code 1 (0x1).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 09 Jan 2023 13:11:26 -0800

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

use x86 Java, ARM isn't supported in MultiMC currently
