### ISSUE TITLE
DireWolf20 1.16 wont start

### ISSUE THREAD

**Issue by RW2001** [MultiMC/Launcher#5077]
### Description of bug

Checking: MC_SLIM
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: PATCHED
Checking: MC_SRG
2023-02-14 03:59:42,615 main WARN Advanced terminal features are not available in this environment
[03:59:42] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, EndrBro, --version, 1.16.4, --gameDir, C:/Users/roy_wash/Desktop/MultiMC/instances/FTB Presents Direwolf20 1.16/.minecraft, --assetsDir, C:/Users/roy_wash/Desktop/MultiMC/assets, --assetIndex, 1.16, --uuid, <ID ПРОФИЛЯ>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 35.1.15, --fml.mcVersion, 1.16.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20201102.104115, --width, 854, --height, 480]
[03:59:42] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.6+85+master.325de55 starting: java version 19.0.2 by Oracle Corporation
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x67c27493) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x67c27493
	at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:41)
	at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
	at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:41)
	at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
	at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
	at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
	at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 8 more
Exiting with -1

tryed 19 java and 8, still wont start

### Steps to reproduce

/

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
nope you are using java 19, switch to java 8 in the settings

**Comment by RW2001** [comment]
> nope you are using java 19, switch to java 8 in the settings

[22:34:00] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.6+85+master.325de55 starting: java version 1.8.0_362 by Azul Systems, Inc.
[22:34:00] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[22:34:00] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/roy_wash/Desktop/MultiMC/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[22:34:00] [main/INFO] [STDOUT/]: [net.creeperhost.traylauncher.ModLocatorHack:<init>:32]: Initializing launcher communication
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:217]: Failed to start Minecraft:
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:249]: java.lang.reflect.InvocationTargetException
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:249]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:249]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:249]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:249]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:249]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:249]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:249]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:249]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:249]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:249]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:249]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:249]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:249]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:218]: Caused by: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:218]: 	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:218]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:218]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:218]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:218]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:218]: 	at java.lang.Class.forName0(Native Method)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:218]: 	at java.lang.Class.forName(Class.java:348)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:218]: 	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:57)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:218]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:71)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:218]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:60)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:218]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:197)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:218]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:190)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:218]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.initializeLaunch(MixinLaunchPlugin.java:196)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:218]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:218]: 	at java.util.HashMap.forEach(HashMap.java:1290)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:218]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:218]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:218]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:218]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:218]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[22:34:02] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:218]: 	... 13 more
[22:34:02] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1

**Comment by RW2001** [comment]
same results :(

**Comment by phit** [comment]
no different result

Forge 34.1.27 to 36.2.24 (Minecraft 1.16.3-1.16.5) are broken with Java 8 Update 321 or newer.
If you are on 1.16.5 try upgrading your instances Forge version. If this isn't an option for you, you need an older Java 8 version, e.g. 8u312 you can find downloads here <https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk>

the crash will contain this
```
Caused by: java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
```
