### ISSUE TITLE
Crash when opening a self made modpack

### ISSUE THREAD

**Issue by vixlaz** [MultiMC/Launcher#5128]
### Operating System

_Windows_

### Description of bug

It has crashed many times at random. Sometimes it self resolves but other times it's persistent... like now. Can someone help me?

Here's the crash report:

MultiMC version: 0.7.0-3739

Launched instance in online mode

authserver.mojang.com resolves to:
    [108.158.145.55, 108.158.145.36, 108.158.145.43, 108.158.145.65]

session.minecraft.net resolves to:
    [13.107.237.34, 13.107.238.34, 2620:1ec:4e:1::34, 2620:1ec:4f:1::34]

textures.minecraft.net resolves to:
    [13.107.237.33, 13.107.238.33, 2620:1ec:4f:1::33, 2620:1ec:4e:1::33]

api.mojang.com resolves to:
    [13.107.237.34, 13.107.238.34, 2620:1ec:4e:1::34, 2620:1ec:4f:1::34]

Minecraft folder is:
C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/instances/Mundo Quântico Novo/.minecraft

Java path is:
C:/Program Files/Java/jdk-17/bin/javaw.exe

Checking Java version...
Java is version 17.0.6, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/instances/Mundo Quântico Novo/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.0/log4j-slf4j18-impl-2.17.0.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/io/netty/netty-common/4.1.77.Final/netty-common-4.1.77.Final.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/io/netty/netty-buffer/4.1.77.Final/netty-buffer-4.1.77.Final.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/io/netty/netty-codec/4.1.77.Final/netty-codec-4.1.77.Final.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/io/netty/netty-handler/4.1.77.Final/netty-handler-4.1.77.Final.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/io/netty/netty-resolver/4.1.77.Final/netty-resolver-4.1.77.Final.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/io/netty/netty-transport/4.1.77.Final/netty-transport-4.1.77.Final.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/io/netty/netty-transport-native-unix-common/4.1.77.Final/netty-transport-native-unix-common-4.1.77.Final.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/io/netty/netty-transport-classes-epoll/4.1.77.Final/netty-transport-classes-epoll-4.1.77.Final.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/com/mojang/authlib/3.11.49/authlib-3.11.49.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.17.0/log4j-api-2.17.0.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.17.0/log4j-core-2.17.0.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/com/mojang/text2speech/1.13.9/text2speech-1.13.9.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/cpw/mods/securejarhandler/2.1.4/securejarhandler-2.1.4.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/net/minecraftforge/eventbus/6.0.3/eventbus-6.0.3.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/net/minecraftforge/forgespi/6.0.0/forgespi-6.0.0.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/cpw/mods/modlauncher/10.0.8/modlauncher-10.0.8.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/net/minecraftforge/JarJarSelector/0.3.16/JarJarSelector-0.3.16.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/net/minecraftforge/JarJarMetadata/0.3.16/JarJarMetadata-0.3.16.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/net/minecraftforge/JarJarFileSystems/0.3.16/JarJarFileSystems-0.3.16.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/net/minecraftforge/fmlloader/1.19.2-43.2.0/fmlloader-1.19.2-43.2.0.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/com/mojang/minecraft/1.19.2/minecraft-1.19.2-client.jar

Native libraries:
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-windows.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-windows.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-windows.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-windows.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-windows.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-windows.jar
  C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-windows.jar

Mods:
  [✔️] AI-Improvements-1.19.2-0.5.2.jar
  [✔️] architectury-6.3.49-forge.jar
  [✔️] ars_creo-1.19.2-3.1.0.jar
  [✔️] ars_nouveau-1.19.2-3.4.6.jar
  [✔️] BeaconOverhaul-1.7.3+1.19.2.jar
  [✔️] biggerreactors-1.19.2-0.6.0-beta.5.1.jar
  [✔️] blockui-1.19-0.0.64-ALPHA.jar
  [✔️] Bookshelf-Forge-1.19.2-16.1.11.jar
  [✔️] chunkloaders-1.2.2-forge-mc1.19.jar
  [✔️] cloth-config-8.2.88-forge.jar
  [✔️] CodeChickenLib-1.19.2-4.3.0.470-universal.jar
  [✔️] compactmachines-5.1.0.jar
  [❌] connectivity-1.19.2-3.4.jar.disabled (disabled)
  [✔️] create_crystal_clear-0.1e-1.19.2.jar
  [✔️] create_enchantment_industry-1.19.2-for-create-0.5.0.f-1.1.6.jar
  [✔️] create_misc_and_things_1.19.2_1.1B.jar
  [✔️] create-1.19.2-0.5.0.f.jar
  [✔️] createaddition-1.19.2-20221103a.jar
  [✔️] createchunkloading-1.3.0-forge.jar
  [✔️] curios-forge-1.19.2-5.1.1.0.jar
  [✔️] CyclopsCore-1.19.2-1.17.0.jar
  [✔️] DarkPaintings-Forge-1.19.2-13.1.2.jar
  [✔️] dynview-1.19.1-2.9.jar
  [✔️] EnchantingInfuser-v4.2.2-1.19.2-Forge.jar
  [✔️] EnderMail-1.19.2-1.2.6.jar
  [✔️] EnderStorage-1.19.2-2.10.1.181-universal.jar
  [✔️] entityculling-forge-1.5.2-mc1.19.1.jar
  [✔️] extendedflywheels-1.2.3-1.19.2-0.5.f.jar
  [❌] FallingTree-1.19.2-3.10.0.jar.disabled (disabled)
  [✔️] ferritecore-5.0.3-forge.jar
  [✔️] geckolib-forge-1.19-3.1.36.jar
  [✔️] ImmersiveEngineering-1.19.2-9.0.0-153.jar
  [✔️] industrial-foregoing-1.19.2-3.3.2.0-2.jar
  [✔️] jei-1.19.2-forge-11.4.0.285.jar
  [❌] jeimultiblocks-1.19.2-0.0.3.jar.disabled (disabled)
  [✔️] lazydfu-1.0-1.19+.jar
  [✔️] littlecontraptions-forge-1.19.2.0.jar
  [✔️] littlelogistics-mc1.19.2-v1.3.1.jar
  [✔️] Mekanism-1.19.2-10.3.5.473.jar
  [✔️] MekanismGenerators-1.19.2-10.3.5.473.jar
  [✔️] modonomicon-1.19.2-1.6.0.jar
  [✔️] MoreMekanismProcessing-1.19.2-3.0.jar
  [✔️] occultism-1.19.2-1.48.0.jar
  [❌] oculus-mc1.19.2-1.2.8.jar.disabled (disabled)
  [✔️] Patchouli-1.19.2-77.jar
  [✔️] phosphophyllite-1.19.2-0.6.0-beta.5.jar
  [❌] plantinajar-2.5.0.jar.disabled (disabled)
  [✔️] potionsmaster-0.6.0-1.19.2-43.1.1.jar
  [✔️] PuzzlesLib-v4.3.12-1.19.2-Forge.jar
  [✔️] quartz-1.19.2-0.1.0-beta.jar
  [❌] rubidium-0.6.2.jar.disabled (disabled)
  [✔️] ScalableCatsForce-2.13.10-build-10-with-library.jar
  [✔️] SimpleBackups-1.19.1-2.1.4.jar
  [✔️] starlight-1.1.1+forge.cf5b10b.jar
  [✔️] supermartijn642configlib-1.1.6b-forge-mc1.19.jar
  [✔️] supermartijn642corelib-1.0.19a-forge-mc1.19.jar
  [✔️] titanium-1.19.2-3.7.0-23.jar
  [✔️] toms_storage-1.19-1.3.9.jar
  [✔️] ZeroCore2-1.19-2.1.26.jar

Params:
  --username  --version 1.19.2 --gameDir C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/instances/Mundo Quântico Novo/.minecraft --assetsDir C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/assets --assetIndex 1.19 --uuid  --accessToken  --userType  --versionType release --launchTarget forgeclient --fml.forgeVersion 43.2.0 --fml.mcVersion 1.19.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20220805.130853

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms4096m, -Xmx8064m, -Duser.language=en]

Minecraft process ID: 15560

Using onesix launcher.

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2023-04-12 02:50:04,762 main WARN Advanced terminal features are not available in this environment
[02:50:04] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, VixGames, --version, 1.19.2, --gameDir, C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/instances/Mundo Quântico Novo/.minecraft, --assetsDir, C:/Users/vhlro/OneDrive/Área de Trabalho/MultiMC/MultiMC/assets, --assetIndex, 1.19, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 43.2.0, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853, --width, 854, --height, 480]
[02:50:04] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.6 by Oracle Corporation; OS Windows 11 arch amd64 version 10.0
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:234)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:269)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.IllegalArgumentException: 1.0-1.19+: Empty pre-release
	at java.base/java.lang.module.ModuleDescriptor$Version.<init>(ModuleDescriptor.java:1054)
	at java.base/java.lang.module.ModuleDescriptor$Version.parse(ModuleDescriptor.java:1090)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.JarMetadata.fromFileName(JarMetadata.java:82)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.JarMetadata.from(JarMetadata.java:44)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.lambda$from$0(SecureJar.java:50)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:143)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:70)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:66)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:50)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.0/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.visitFile(ModDirTransformerDiscoverer.java:61)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.0/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.scan(ModDirTransformerDiscoverer.java:50)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.0/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.candidates(ModDirTransformerDiscoverer.java:33)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.serviceapi.ITransformerDiscoveryService.candidates(ITransformerDiscoveryService.java:48)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.lambda$discoverServices$14(TransformationServicesHandler.java:125)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:127)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:86)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 13 more
Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
MultiMC: Log upload triggered at: 12 Apr 2023 02:50:12 -0300

### Steps to reproduce

I couldn't find a way to reproduce it consistenly 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
