### ISSUE TITLE
so confused

### ISSUE THREAD

**Issue by PaulOfall** [MultiMC/Launcher#5138]
### Description of bug

MultiMC version: 0.7.0-3739

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.154.101.93, 18.154.101.19, 18.154.101.47, 18.154.101.51]

session.minecraft.net resolves to:
    [2620:1ec:4f:1::66, 2620:1ec:4e:1::66, 13.107.238.66, 13.107.237.66]

textures.minecraft.net resolves to:
    [2620:1ec:4f:1::66, 2620:1ec:4e:1::66, 13.107.237.66, 13.107.238.66]

api.mojang.com resolves to:
    [2620:1ec:4f:1::66, 2620:1ec:4e:1::66, 13.107.238.66, 13.107.237.66]

Minecraft folder is:
C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/instances/1.19.4/.minecraft

Java path is:
C:/Program Files/Java/jdk-17/bin/javaw.exe

Checking Java version...
Java is version 17.0.7, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/instances/1.19.4/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/authlib/3.18.38/authlib-3.18.38.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/datafixerupper/6.0.6/datafixerupper-6.0.6.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/text2speech/1.16.7/text2speech-1.16.7.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/cpw/mods/securejarhandler/2.1.6/securejarhandler-2.1.6.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/minecraftforge/eventbus/6.0.3/eventbus-6.0.3.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/minecraftforge/forgespi/6.0.0/forgespi-6.0.0.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/cpw/mods/modlauncher/10.0.8/modlauncher-10.0.8.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/minecraftforge/JarJarSelector/0.3.19/JarJarSelector-0.3.19.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/minecraftforge/JarJarMetadata/0.3.19/JarJarMetadata-0.3.19.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/minecraftforge/JarJarFileSystems/0.3.19/JarJarFileSystems-0.3.19.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/minecraftforge/fmlloader/1.19.4-45.0.49/fmlloader-1.19.4-45.0.49.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/minecraft/1.19.4/minecraft-1.19.4-client.jar

Native libraries:
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-windows.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-windows.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-windows.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-windows.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-windows.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-windows.jar
  C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-windows.jar

Mods:
  [✔️] !mixinbooter-5.0.jar
  [✔️] aether-1.12.2-v1.5.3.2.jar
  [✔️] AppleCore-mc1.12.2-3.4.0.jar
  [✔️] Aquaculture-1.12.2-1.6.8.jar
  [✔️] Artifacts-1.12.2-1.2.3.jar
  [✔️] Atum-1.12.2-2.0.20.jar
  [✔️] AutoRegLib-1.3-32.jar
  [✔️] BattleTowers-1.12.2.jar
  [✔️] Baubles-1.12-1.5.2.jar
  [✔️] bettercaves-1.12.2-2.0.4.jar
  [✔️] BetterCombat-1.12.2-1.5.6.jar
  [✔️] BiblioCraft[v2.4.6][MC1.12.2].jar
  [✔️] BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar
  [✔️] BiomeSpecificDungeons-1.12.2-1.0.3.jar
  [✔️] blood particles.jar
  [✔️] Bookshelf-1.12.2-2.3.590.jar
  [✔️] Bountiful-2.2.2.jar
  [✔️] brvsb-1.0.2-mc1.19.2.jar
  [✔️] buildcraft-all-7.99.24.8.jar
  [✔️] canary-mc1.19.2-0.1.8.jar
  [✔️] candyworld-1.1.5.jar
  [✔️] car-1.12.2-2.0.1.jar
  [✔️] chickens-6.0.4.jar
  [✔️] Clumps-forge-1.19.2-9.0.0+14.jar
  [✔️] CodeChickenLib-1.12.2-3.2.3.358-universal.jar
  [✔️] collective-1.12.2-3.0.jar
  [✔️] CompatSkills-1.12.2-1.17.0.jar
  [✔️] controllable-0.17.0-1.19.2.jar
  [✔️] CraftTweaker2-1.12-4.1.20.681.jar
  [✔️] CreativeCore_v1.10.70_mc1.12.2.jar
  [✔️] CTM-MC1.12.2-1.0.2.31.jar
  [✔️] Cucumber-1.12.2-1.1.3.jar
  [✔️] CustomMobSpawner-3.11.5.jar
  [✔️] cxlibrary-1.12.1-1.6.1.jar
  [✔️] CyclopsCore-1.12.2-1.6.7.jar
  [✔️] Decocraft-2.6.3.7_1.12.2.jar
  [✔️] DimensionalDoors-1.12.2-3.0.12.jar
  [✔️] dimensionapocketsii-1.12.2-5.2.101-beta-clientonly.jar
  [✔️] EnderStorage-1.12.2-2.4.6.137-universal.jar
  [✔️] EndReborn [0.3.9].jar
  [✔️] EnhancedVisuals_v1.4.4_mc1.12.2.jar
  [✔️] entityculling-forge-1.5.2-mc1.19.1.jar
  [✔️] Erebus-1.0.32.jar
  [✔️] EvilCraft-1.12.2-0.10.78.jar
  [✔️] ExtendedCrafting-1.12.2-1.5.6.jar
  [✔️] FamiliarFauna-1.12.2-1.0.11.jar
  [✔️] farlanders-1.12.2-1.0.1.jar
  [✔️] Fastload-Reforged-2.6.9+1.19.2.jar
  [✔️] Forgelin-1.8.4.jar
  [✔️] ForgivingVoid_1.12.2-1.1.0.jar
  [✔️] FpsReducer-mc1.12.2-1.20.jar
  [✔️] furniture-6.3.2-1.12.2.jar
  [✔️] future-mc-0.2.11.jar
  [✔️] Galacticraft-1.12.2-4.0.4.jar
  [✔️] GrimoireOfGaia3-1.12.2-1.7.2.jar
  [✔️] Hats-1.12.2-7.1.1.jar
  [✔️] HatStand-1.12.2-7.1.0.jar
  [✔️] HeroesExpansion-1.12.2-1.3.5.jar
  [✔️] HungerInPeace-mc1.12-1.0.0.jar
  [✔️] Hwyla-1.8.26-B41_1.12.2.jar
  [✔️] iChunUtil-1.12.2-7.2.2.jar
  [✔️] ImprovedBackpacks-1.12.2-1.5.0.0.jar
  [✔️] inventorypets-1.12-2.0.15.jar
  [✔️] ironchest-1.12.2-7.0.72.847.jar
  [✔️] jei_1.12.2-4.16.1.301.jar
  [✔️] journeymap-1.12.2-5.7.1.jar
  [✔️] LibraryEx-1.12.2-1.2.2.jar
  [✔️] lozmod-4.0.0-pre7.jar
  [✔️] LucraftCore-1.12.2-2.4.17.jar
  [✔️] lumen-Beta 0.4.1.jar
  [✔️] MCA-1.12.2-6.1.0-universal.jar
  [✔️] MoreFurnaces-1.12.2-1.10.6.jar
  [✔️] More-Planets-1.12.2-2.2.4-GC284.jar
  [✔️] mOres-v2.0.jar
  [✔️] MoreSwordsLegacy-1.12.2-1.0.7.jar
  [✔️] Morph-1.12.2-7.2.1.jar
  [✔️] MouseTweaks-2.10-mc1.12.2.jar
  [✔️] mysticallib-1.12.2-1.13.0.jar
  [✔️] mysticalworld-1.12.2-1.11.0.jar
  [✔️] NetherEx-1.12.2-2.2.5.jar
  [✔️] OreLib-1.12.2-3.6.0.1.jar
  [✔️] Patchouli-1.0-23.6.jar
  [✔️] Peaceful+ Mod [v1.5.1].jar
  [✔️] pluto-mc1.19.2-0.0.7.jar
  [✔️] PortalGun-1.12.2-7.1.0.jar
  [✔️] PTRLib-1.0.5.jar
  [✔️] QuarkOddities-1.12.2.jar
  [✔️] Quark-r1.6-179.jar
  [✔️] RedstoneFlux-1.12-2.1.1.1-universal.jar
  [✔️] Reskillable-1.12.2-1.13.0.jar
  [✔️] Rex's-AdditionalStructures-1.12.x(v.2.5.0).jar
  [✔️] RikMuldsCore_1.3.3.jar
  [✔️] RITNN_Mc1.12.2_0.1.jar
  [✔️] RoguelikeDungeons-1.12.2-1.8.0.jar
  [✔️] rubidium_extras-1.19.2_v1.3.2.jar
  [✔️] rubidium-0.6.2.jar
  [✔️] RubidiumExtra-1.19.2-0.4.11.44.jar
  [✔️] saturn-mc1.19.2-0.0.1.jar
  [✔️] SereneSeasons-1.12.2-1.2.18-universal.jar
  [✔️] smoothboot(reloaded)-mc1.19.2-0.0.2.jar
  [✔️] starlight-1.1.1+forge.cf5b10b.jar
  [✔️] SteveKunG's-Lib-1.12.2-1.2.0.jar
  [✔️] stg-1.12.2-1.2.3.jar
  [✔️] Sync-1.12.2-7.1.0.jar
  [✔️] theaurorian-1.12.2-release-may3021.jar
  [✔️] TheCampingMod_2.4.3.jar
  [✔️] the-fifth-world-0.5.1.jar
  [✔️] torohealth-1.12.2-11.jar
  [✔️] ToughAsNails-1.12.2-3.1.0.139-universal.jar
  [✔️] treeharvester_1.12.2-4.0.jar
  [✔️] tropicraft-MC1.12.2-7.1.9.115.jar
  [✔️] twilightforest-1.12.2-3.11.1021-universal.jar
  [✔️] UndergroundBiomesConstructs-1.12-1.3.14.jar
  [✔️] Xp Ore 1.0 (v1.12.2).jar
  [✔️] xptome-1.12.2-v2.0.1.jar
  [✔️] zeherlib-1.12.2-7.2.05-universal.jar

Params:
  --username  --version 1.19.4 --gameDir C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/instances/1.19.4/.minecraft --assetsDir C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/assets --assetIndex 3 --uuid  --accessToken  --userType  --versionType release --launchTarget forgeclient --fml.forgeVersion 45.0.49 --fml.mcVersion 1.19.4 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20230314.122934

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 4552

Using onesix launcher.

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2023-04-27 00:18:00,254 main WARN Advanced terminal features are not available in this environment
[00:18:00] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, FreeOFallOPaul, --version, 1.19.4, --gameDir, C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/instances/1.19.4/.minecraft, --assetsDir, C:/Users/arago/Downloads/mmc-develop-win32 (1)/MultiMC/assets, --assetIndex, 3, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 45.0.49, --fml.mcVersion, 1.19.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230314.122934, --width, 854, --height, 480]
[00:18:00] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.7 by Oracle Corporation; OS Windows 11 arch amd64 version 10.0
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:234)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:269)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.IllegalArgumentException: ejektaflex.bountiful.api.enum: Invalid package name: 'enum' is not a Java identifier
	at java.base/jdk.internal.module.Checks.requireTypeName(Checks.java:161)
	at java.base/jdk.internal.module.Checks.requirePackageName(Checks.java:72)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.lang.module.ModuleDescriptor$Builder.packages(ModuleDescriptor.java:2026)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.SimpleJarMetadata.descriptor(SimpleJarMetadata.java:16)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.computeDescriptor(Jar.java:51)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar$JarModuleDataProvider.descriptor(Jar.java:276)
	at MC-BOOTSTRAP/fmlloader@1.19.4-45.0.49/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.visitFile(ModDirTransformerDiscoverer.java:62)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at MC-BOOTSTRAP/fmlloader@1.19.4-45.0.49/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.scan(ModDirTransformerDiscoverer.java:50)
	at MC-BOOTSTRAP/fmlloader@1.19.4-45.0.49/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.candidates(ModDirTransformerDiscoverer.java:33)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.serviceapi.ITransformerDiscoveryService.candidates(ITransformerDiscoveryService.java:48)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.lambda$discoverServices$14(TransformationServicesHandler.java:125)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:127)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:86)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 13 more
Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 27 Apr 2023 00:18:12 -0600
Clipboard copy at: 27 Apr 2023 00:21:44 -0600

### Steps to reproduce

just the mods i have

### Suspected cause

idk

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by PaulOfall** [comment]
pls hlp

**Comment by FeedTheChunk** [comment]
Looks like your mod pack needs more ram / memory: -Xms512m, -Xmx1024m,  512M typically isn't nearly enough memory for modded minecraft.  For modded minecraft I typically start around 2G of ram and go up from there depending on the pack.

**Comment by Heufneutje** [comment]
No the problem is that this is a Minecraft 1.19 instance with 1.12 mods in it. This is also not a bug. Please use the Discord for support.
