### ISSUE TITLE
-1 (0xffffffffffffffff).

### ISSUE THREAD

**Issue by Error9E** [MultiMC/Launcher#5141]
### Operating System

Windows

### Description of bug

opens Minecraft then instantly crashes then gives me this error code -1 (0xffffffffffffffff).

### Steps to reproduce

MultiMC version: 0.7.0-3739

Launched instance in online mode

authserver.mojang.com resolves to:
    [52.85.254.17, 52.85.254.80, 52.85.254.83, 52.85.254.54]

session.minecraft.net resolves to:
    [13.107.238.55, 13.107.237.55, 2620:1ec:4e:1::55, 2620:1ec:4f:1::55]

textures.minecraft.net resolves to:
    [13.107.238.55, 13.107.237.55, 2620:1ec:4e:1::55, 2620:1ec:4f:1::55]

api.mojang.com resolves to:
    [13.107.238.55, 13.107.237.55, 2620:1ec:4e:1::55, 2620:1ec:4f:1::55]

Minecraft folder is:
C:/Users/error/AppData/Roaming/.minecraft/MultiMC/instances/Create Above and Beyond Preformence Edition/.minecraft

Java path is:
C:/Program Files/Zulu/zulu-8-jre/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_372, using 64-bit architecture, from Azul Systems, Inc..

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/instances/Create Above and Beyond Preformence Edition/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/net/minecraftforge/forge/1.16.5-36.2.20/forge-1.16.5-36.2.20-launcher.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/cpw/mods/grossjava9hacks/1.3.3/grossjava9hacks-1.3.3.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/com/electronwill/night-config/core/3.6.3/core-3.6.3.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/com/electronwill/night-config/toml/3.6.3/toml-3.6.3.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/net/minecraftforge/nashorn-core-compat/15.1.1.1/nashorn-core-compat-15.1.1.1.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] _MixinBootstrap-1.1.0.jar
  [✔️] abnormals_core-1.16.5-3.3.0.jar
  [✔️] AdvancedRocketry-1.16.5-2.0.0-12-universal.jar
  [✔️] AI-Improvements-1.16.2-0.3.0.jar
  [✔️] antiqueatlas-6.0.1-forge-mc1.16.5.jar
  [✔️] appleskin-forge-mc1.16.x-2.2.0.jar
  [✔️] appliedenergistics2-8.4.4.jar
  [✔️] Aquaculture-1.16.5-2.1.21.jar
  [✔️] archers_paradox-1.16.5-1.4.0.1.jar
  [✔️] Architects-Palette-1.16.4-1.1.4.jar
  [✔️] architectury-1.24.35-forge.jar
  [✔️] BackTools-1.16.5-10.1.0.jar
  [✔️] BetterAdvancements-1.16.5-0.1.0.108.jar
  [✔️] betterbiomeblend-1.16.4-1.2.9-forge.jar
  [✔️] BetterBurning-1.16.5-6.0.6.jar
  [✔️] BiomesOPlenty-1.16.5-13.1.0.482-universal.jar
  [✔️] Buddycards-1.16.5-2.5.2.jar
  [✔️] bwncr-1.16.5-3.10.16.jar
  [✔️] catalogue-1.5.0-1.16.5.jar
  [✔️] cavebiomeapi-1.16.5-1.3.7.jar
  [✔️] CBMultipart-1.16.5-3.0.3.122-universal.jar
  [✔️] cc-tweaked-1.16.5-1.99.1.jar
  [✔️] Chisel-MC1.16.5-2.0.1-alpha.4.jar
  [✔️] chiselsandbits-1.0.43.jar
  [✔️] Chunk Pregenerator-V1.16-3.2.0.jar
  [✔️] ChunkNoGoByeBye-1.16.5-1.3.0.jar
  [✔️] cloth-config-4.12.41-forge.jar
  [✔️] Clumps-6.0.0.27.jar
  [✔️] cobblegenrandomizer-1.16-5.1.2.jar
  [✔️] CodeChickenLib-1.16.5-4.0.5.438-universal.jar
  [✔️] cofh_core-1.16.5-1.4.0.6.jar
  [✔️] configured-1.5.1-1.16.5.jar
  [✔️] connectivity-2.4-1.16.5.jar
  [✔️] constructionwand-1.16.5-2.6.jar
  [✔️] Controlling-7.0.0.28.jar
  [✔️] cookiecore-1.16.5-3.3.0-12106d2.jar
  [✔️] corpse-1.16.5-1.0.6.jar
  [✔️] CosmeticArmorReworked-1.16.5-v4a.jar
  [✔️] CraftingTweaks_1.16.5-12.2.1.jar
  [✔️] crashutilities-3.12.jar
  [✔️] create-mc1.16.5_v0.3.2g.jar
  [✔️] CTM-MC1.16.1-1.1.2.6.jar
  [✔️] culinaryconstruct-forge-1.16.5-4.0.0.6.jar
  [✔️] curios-forge-1.16.5-4.0.5.3.jar
  [✔️] darkerdepths-1.16.5-1.1.4.jar
  [✔️] decorative_blocks_abnormals-1.2.jar
  [✔️] decorative_blocks-1.16.4-1.7.2.jar
  [✔️] DefaultOptions_1.16.5-12.2.1.jar
  [✔️] Desolation 1.1.0-2 1.16.5.jar
  [✔️] Dice-1.16.5-1.2.0.jar
  [✔️] drinkbeer-1.16.5-2.3.5.jar
  [✔️] DungeonCrawl-1.16.5-2.3.2.jar
  [✔️] dynviewdist-2.0.jar
  [✔️] enchantedbookredesign-3.3-1.16.4.jar
  [✔️] endergetic-1.16.4-3.0.0.jar
  [✔️] EnderStorage-1.16.5-2.8.0.168-universal.jar
  [✔️] entityculling-forge-mc1.16.5-1.5.2.jar
  [✔️] Exchangers-1.16.5-3.0.2.jar
  [✔️] exoticbirds-1.16.4-1.3.0.jar
  [✔️] extcaves-2.4.jar
  [✔️] fairylights-4.0.5-1.16.5.jar
  [✔️] FarmersDelight-1.16.5-0.5.3.jar
  [✔️] fastfurnaceminusreplacement-1.1-1.16.3.jar
  [✔️] FastLeafDecay-v25.jar
  [✔️] FastWorkbench-1.16.4-4.5.1.jar
  [✔️] ferritecore-2.1.0-forge.jar
  [✔️] ferritecore-2.1.1-forge.jar
  [✔️] flywheel-1.16-0.2.5.jar
  [✔️] forbidden_arcanus-16.2.2.jar
  [✔️] ftb-backups-2.1.2.2.jar
  [✔️] ftb-chunks-forge-1605.3.2-build.83.jar
  [✔️] ftb-library-forge-1605.3.4-build.90.jar
  [✔️] ftb-quests-forge-1605.3.5-build.72.jar
  [✔️] ftb-teams-forge-1605.2.3-build.40.jar
  [✔️] getittogetherdrops-1.16.5-v1.2.jar
  [✔️] grapplemod-1.16.5-v12.jar
  [✔️] GunpowderLib-1.16.5-1.2.2.jar
  [✔️] iChunUtil-1.16.5-10.5.0.jar
  [✔️] ImprovedBackpacks-1.6.2.0.jar
  [✔️] inventorysorter-1.16.1-18.1.0.jar
  [✔️] item-filters-forge-1605.2.5-build.9.jar
  [✔️] Jade-1.16.4-2.8.0.jar
  [✔️] jei-1.16.5-7.7.1.137.jar
  [✔️] kubejs-create-1605.1.2-build.7.jar
  [✔️] kubejs-forge-1605.3.19-build.229.jar
  [✔️] kubejs-thermal-1605.1.4-build.3.jar
  [✔️] LibVulpes-1.16.5-1.0.2-25-universal.jar
  [✔️] lootr-1.16.5-0.0.9.30.jar
  [✔️] magicfeather-1.16.2-3.2.0.jar
  [✔️] Mantle-1.16.5-1.6.147.jar
  [✔️] metalbarrels-1.16.2-3.3b.jar
  [✔️] mightyarchitect-mc1.16.3_v0.5.jar
  [✔️] moreminecarts-1.3.12.jar
  [✔️] MoreObservers-1.4.1-MC1.16-Forge.jar
  [✔️] Morpheus-1.16.5-4.2.70.jar
  [✔️] MouseTweaks-2.14-mc1.16.2.jar
  [✔️] NaturesCompass-1.16.5-1.9.1-forge.jar
  [✔️] nolakes-0.1-1.16.4.jar
  [✔️] occultism-1.16.5-1.20.1.jar
  [✔️] OpenLoader-1.16.5-9.0.3.jar
  [✔️] orcinusscaves-1.3.jar
  [✔️] OreTweaker-1.16.5-2.6.0.jar
  [✔️] paintings-1.16.4-7.0.0.1.jar
  [✔️] Patchouli-1.16.4-53.2.jar
  [✔️] PathToDirt-1.2.0-mc1.16.x.jar
  [✔️] pipez-1.16.5-1.2.13.jar
  [✔️] Placebo-1.16.5-4.6.0.jar
  [✔️] ponderjs-1.16.5-1.0.3d.jar
  [✔️] portable_stonecutter-1.16.5-1.3.5.jar
  [✔️] portality-1.16.5-3.2.5.jar
  [✔️] PrettyPipes-1.9.5.jar
  [✔️] ProjectRed-1.16.5-4.11.0-beta-6-core.jar
  [✔️] ProjectRed-1.16.5-4.11.0-beta-6-illumination.jar
  [✔️] ProjectRed-1.16.5-4.11.0-beta-6-integration.jar
  [✔️] ProjectRed-1.16.5-4.11.0-beta-6-transmission.jar
  [✔️] randomium-1.16.5-1.7.jar
  [✔️] ravencoffee-1.16.5-beta_01.jar
  [✔️] reliquary-1.16.5-1.3.5.1100.jar
  [✔️] repurposed_structures_forge-3.4.4+1.16.5.jar
  [✔️] rhino-forge-1605.1.5-build.75.jar
  [✔️] RoadRunner-mc1.16.5-1.4.1.jar
  [✔️] Rubber_Duck-1.16.5-1.2.0.jar
  [✔️] rubidium-0.2.11 (1).jar
  [✔️] rubidium-extra-0.4.18+mc1.16.5-build.75.jar
  [✔️] Scorge-3.1.3.jar
  [✔️] selene-1.16.5-1.9.0.jar
  [✔️] shutupexperimentalsettings-1.0.3.jar
  [✔️] smoothboot-forge-1.16.4-1.2.2.jar
  [✔️] SoundFilters-0.14_for_1.16.2.jar
  [✔️] spark-forge.jar
  [✔️] SpawnerFix-1.16.2-1.0.0.2.jar
  [✔️] StorageDrawers-1.16.3-8.3.0.jar
  [✔️] strawgolem-1.16-1.9.jar
  [✔️] structurescompass-1.16.5-1.2.0.jar
  [✔️] supplementaries-1.16.5-0.17.12b.jar
  [✔️] TConstruct-1.16.5-3.3.0.308.jar
  [✔️] TextruesRubidiumOptions-1.0.4-mc1.16.5.jar
  [✔️] thermal_expansion-1.16.5-1.4.1.3.jar
  [✔️] thermal_foundation-1.16.5-1.4.1.7.jar
  [✔️] thermal_innovation-1.16.5-1.4.1.3.jar
  [✔️] thermal_locomotion-1.16.5-1.4.1.2.jar
  [✔️] titanium-1.16.5-3.2.8.7-22.jar
  [✔️] torchmaster-2.3.8.jar
  [✔️] valhelsia_core-16.0.13a.jar
  [✔️] WaterStrainer-1.16.3-10.0.0.jar
  [✔️] worldshape-1.0.jar
  [✔️] xkdeco_0.2.4.jar

Params:
  --username  --version 1.16.5 --gameDir C:/Users/error/AppData/Roaming/.minecraft/MultiMC/instances/Create Above and Beyond Preformence Edition/.minecraft --assetsDir C:/Users/error/AppData/Roaming/.minecraft/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 36.2.20 --fml.mcVersion 1.16.5 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20210115.111550

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx2048m, -Duser.language=en]

Minecraft process ID: 8820

Using onesix launcher.

Checking: MC_SLIM
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: PATCHED
Checking: MC_SRG
2023-04-29 12:23:25,196 main WARN Advanced terminal features are not available in this environment
[12:23:25] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Error9E, --version, 1.16.5, --gameDir, C:/Users/error/AppData/Roaming/.minecraft/MultiMC/instances/Create Above and Beyond Preformence Edition/.minecraft, --assetsDir, C:/Users/error/AppData/Roaming/.minecraft/MultiMC/assets, --assetIndex, 1.16, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.20, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --width, 854, --height, 480]
[12:23:25] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_372 by Azul Systems, Inc.
[12:23:26] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[12:23:26] [main/INFO] [MixinBootstrap Launch/]: MixinBootstrap v1.1.0
[12:23:26] [main/INFO] [MixinBootstrap Launch/]: Mixin v0.8.4
[12:23:26] [main/INFO] [MixinBootstrap Launch/]: ModLauncher v8.0.9+86+master.3cf110c (7.0)
[12:23:26] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/error/AppData/Roaming/.minecraft/MultiMC/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[12:23:33] [main/ERROR] [mixin/]: Mixin config antiqueatlas.mixins.json does not specify "minVersion" property
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:237]: Failed to start Minecraft:
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:269]: java.lang.reflect.InvocationTargetException
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:269]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:269]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:269]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:269]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:269]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:269]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:269]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:269]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:269]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:269]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:234)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:269]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:269)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:269]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:269]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: Caused by: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: 	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: 	at java.lang.Class.forName0(Native Method)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: 	at java.lang.Class.forName(Class.java:348)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: 	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:67)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:70)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:59)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:196)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: 	at java.util.HashMap.forEach(HashMap.java:1290)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[12:23:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:238]: 	... 13 more
[12:23:34] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

Don't know why this is happening.
using java 8, even tried java 17 nothing worked.

### Suspected cause

no idea XD

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Forge 34.1.27 to 36.2.24 (Minecraft 1.16.3-1.16.5) are broken with Java 8 Update 321 or newer.
If you are on 1.16.5 try upgrading your instances Forge version. If this isn't an option for you, you need an older Java 8 version, e.g. 8u312 you can find downloads here <https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk>

the crash will contain this
```
Caused by: java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
```
