### ISSUE TITLE
Error V1.19.2 (Java 17 & 20)(MacOs ventura 13.3.1)

### ISSUE THREAD

**Issue by Antxis77** [MultiMC/Launcher#5143]
### Operating System

macOS

### Description of bug

Hello

I have a problem to launch minecraft 1.19.2 on MultiMC (Work on Minecraft Launcher)

I have MacOs version of MultiMc 0.7.0-3736.

Thanks for your help

### Steps to reproduce

Launch Minecraft 1.19.2 with Java 17.0.7

### Suspected cause

Error output

MultiMC version: 0.7.0-3736

Launched instance in online mode

authserver.mojang.com resolves to:
    [52.222.174.86, 52.222.174.120, 52.222.174.32, 52.222.174.63]

session.minecraft.net resolves to:
    [2620:1ec:4f:1::42, 2620:1ec:4e:1::42, 13.107.238.42, 13.107.237.42]

textures.minecraft.net resolves to:
    [2620:1ec:4f:1::42, 2620:1ec:4e:1::42, 13.107.238.42, 13.107.237.42]

api.mojang.com resolves to:
    [2620:1ec:4f:1::42, 2620:1ec:4e:1::42, 13.107.238.42, 13.107.237.42]

Minecraft folder is:
/Applications/MultiMC.app/Data/instances/1.19.2/.minecraft

Java path is:
/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/java

Checking Java version...
Java is version 17.0.7, using 32-bit architecture, from Oracle Corporation.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  /Applications/MultiMC.app/Data/instances/1.19.2/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /Applications/MultiMC.app/Data/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  /Applications/MultiMC.app/Data/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.0/log4j-slf4j18-impl-2.17.0.jar
  /Applications/MultiMC.app/Data/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  /Applications/MultiMC.app/Data/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-common/4.1.77.Final/netty-common-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-buffer/4.1.77.Final/netty-buffer-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-codec/4.1.77.Final/netty-codec-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-handler/4.1.77.Final/netty-handler-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-resolver/4.1.77.Final/netty-resolver-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport/4.1.77.Final/netty-transport-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport-native-unix-common/4.1.77.Final/netty-transport-native-unix-common-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport-classes-epoll/4.1.77.Final/netty-transport-classes-epoll-4.1.77.Final.jar
  /Applications/MultiMC.app/Data/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /Applications/MultiMC.app/Data/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /Applications/MultiMC.app/Data/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /Applications/MultiMC.app/Data/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar
  /Applications/MultiMC.app/Data/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/authlib/3.11.49/authlib-3.11.49.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /Applications/MultiMC.app/Data/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  /Applications/MultiMC.app/Data/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-api/2.17.0/log4j-api-2.17.0.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-core/2.17.0/log4j-core-2.17.0.jar
  /Applications/MultiMC.app/Data/libraries/ca/weblite/java-objc-bridge/1.1/java-objc-bridge-1.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/text2speech/1.16.7/text2speech-1.16.7.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/intermediary/1.19.2/intermediary-1.19.2.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm/9.4/asm-9.4.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-analysis/9.4/asm-analysis-9.4.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-commons/9.4/asm-commons-9.4.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-tree/9.4/asm-tree-9.4.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-util/9.4/asm-util-9.4.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/fabric-loader/0.14.19/fabric-loader-0.14.19.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/minecraft/1.19.2/minecraft-1.19.2-client.jar

Native libraries:
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-macos.jar

Params:
  --username  --version 1.19.2 --gameDir /Applications/MultiMC.app/Data/instances/1.19.2/.minecraft --assetsDir /Applications/MultiMC.app/Data/assets --assetIndex 1.19 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: 1.19.2", -XstartOnFirstThread, -Xms512m, -Xmx2048m, -Duser.language=en]

Minecraft process ID: 2020

Using onesix launcher.

[13:27:15] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.19
[13:27:15] [main/INFO]: Loading 3 mods:
	- fabricloader 0.14.19
	- java 17
	- minecraft 1.19.2
[13:27:15] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/Applications/MultiMC.app/Data/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[13:27:17] [main/INFO]: Building optimized datafixer
[13:27:18] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[13:27:18] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[13:27:18] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[13:27:19] [Render thread/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:464) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.19.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:234) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:269) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at net.minecraft.class_6396.method_37123(class_6396.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_37274(class_310.java:2359) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_22681(class_310.java:2354) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:214) ~[minecraft-1.19.2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	... 10 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.dylib [in thread "Render thread"]
	at org.lwjgl.system.Library.loadSystem(Library.java:164) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.system.Library.loadSystem(Library.java:63) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.system.Library.<clinit>(Library.java:51) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100) ~[lwjgl-3.3.1.jar:?]
	at net.minecraft.class_311.<clinit>(class_311.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_287.<init>(class_287.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_289.<init>(class_289.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_289.<init>(class_289.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_289.<clinit>(class_289.java:11) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(RenderSystem.java:46) ~[minecraft-1.19.2-client.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:202) ~[minecraft-1.19.2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	... 10 more
Le processus s'est arrêté avec le code de sortie 1 (0x1).
Veuillez noter que généralement ni le code de sortie, ni sa description ne suffisent pour diagnostiquer les problèmes !
Téléchargez toujours le journal complet et pas seulement le code de sortie.
Clipboard copy at: 01 May 2023 13:27:24 +0200

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java make sure to read the note about x64

**Comment by Antxis77** [comment]
Yes i test with zulu-17.jdk and it doesn't work

**Comment by phit** [comment]
but your log isn't using x64 Java as mentioned in the wiki
