### ISSUE TITLE
I received unexpected error when I play MultiMC today

### ISSUE THREAD

**Issue by Caseypiano360** [MultiMC/Launcher#5144]
Hi MultiMC,

I tried to play MultiMC but I received this error below:

[20:18:57] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShutdownPatcher (mcef-1.12.2-1.11-coremod.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 5/5/23 8:18 PM
Description: Unexpected error

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 188 path $[3].text
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492)
	at net.minecraft.util.JsonUtils.func_188176_a(SourceFile:517)
	at net.minecraft.util.text.ITextComponent$Serializer.func_150699_a(ITextComponent.java:271)
	at org.musiccraft.ClientTickHandler.checkForUpdate(ClientTickHandler.java:411)
	at org.musiccraft.ClientTickHandler.onClientTick(ClientTickHandler.java:341)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_136_ClientTickHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 188 path $[3].text
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:731)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 20 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492)
	at net.minecraft.util.JsonUtils.func_188176_a(SourceFile:517)
	at net.minecraft.util.text.ITextComponent$Serializer.func_150699_a(ITextComponent.java:271)
	at org.musiccraft.ClientTickHandler.checkForUpdate(ClientTickHandler.java:411)
	at org.musiccraft.ClientTickHandler.onClientTick(ClientTickHandler.java:341)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_136_ClientTickHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Casey360'/345, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['Casey360'/345, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1559405576 bytes (1487 MB) / 3068657664 bytes (2926 MB) up to 4898947072 bytes (4672 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms128m -Xmx5256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2814 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                                  | Signature                                |
	|:------ |:------------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2       | minecraft.jar                           | None                                     |
	| LCHIJA | mcp                 | 9.42         | minecraft.jar                           | None                                     |
	| LCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2814-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2814 | forge-1.12.2-14.23.5.2814-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | architecturecraft   | @VERSION@    | ArchitectureCraft-Mod-1.12.2 (1).jar    | None                                     |
	| LCHIJA | buildcraftlib       | 7.99.24.6    | buildcraft-all-7.99.24.6.jar            | None                                     |
	| LCHIJA | buildcraftcore      | 7.99.24.6    | buildcraft-all-7.99.24.6.jar            | None                                     |
	| LCHIJA | buildcraftbuilders  | 7.99.24.6    | buildcraft-all-7.99.24.6.jar            | None                                     |
	| LCHIJA | buildcrafttransport | 7.99.24.6    | buildcraft-all-7.99.24.6.jar            | None                                     |
	| LCHIJA | buildcraftsilicon   | 7.99.24.6    | buildcraft-all-7.99.24.6.jar            | None                                     |
	| LCHIJA | buildcraftcompat    | 7.99.24.6    | buildcraft-all-7.99.24.6.jar            | None                                     |
	| LCHIJA | buildcraftenergy    | 7.99.24.6    | buildcraft-all-7.99.24.6.jar            | None                                     |
	| LCHIJA | buildcraftfactory   | 7.99.24.6    | buildcraft-all-7.99.24.6.jar            | None                                     |
	| LCHIJA | buildcraftrobotics  | 7.99.24.6    | buildcraft-all-7.99.24.6.jar            | None                                     |
	| LCHIJA | casinocraft         | v11          | CasinoCraft_1.12.2_v11.jar              | None                                     |
	| LCHIJA | cdm                 | 0.4.1        | cdm-0.4.1-mc1.12.2.jar                  | None                                     |
	| LCHIJA | customnpcs          | 1.12         | CustomNPCs_1.12.2-(01Oct19).jar         | None                                     |
	| LCHIJA | ptrmodellib         | 1.0.4        | PTRLib-1.0.4.jar                        | None                                     |
	| LCHIJA | props               | 2.6.2        | Decocraft-2.6.2_1.12.2.jar              | None                                     |
	| LCHIJA | cfm                 | 6.3.1        | furniture-6.3.1-1.12.2.jar              | None                                     |
	| LCHIJA | mcef                | 1.11         | mcef-1.12.2-1.11.jar                    | None                                     |
	| LCHIJA | musiccraft          | 3.2.3        | MusicCraft-3.2.3.jar                    | None                                     |
	| LCHIJA | railcraft           | 12.0.0       | railcraft-12.0.0.jar                    | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | redstonepaste       | 1.7.5        | redstonepaste-mc1.12-1.7.5.jar          | None                                     |
	| LCHIJA | webdisplays         | 1.1          | webdisplays-1.12.2-1.1.jar              | None                                     |

	Loaded coremods (and transformers): 
ShutdownPatcher (mcef-1.12.2-1.11-coremod.jar)
  net.montoyo.mcef.coremod.ShutdownPatcher
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 512.36' Renderer: 'NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2'
	Launched Version: 
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 4.6.0 NVIDIA 512.36, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
[20:18:57] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\casey\Documents\MultiMC\MultiMC\instances\custom npc\.minecraft\crash-reports\crash-2023-05-05_20.18.57-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.

How to fix it?

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
