### ISSUE TITLE
launcher crashes with this message

### ISSUE THREAD

**Issue by sambonusg** [MultiMC/Launcher#5192]
### Description of bug

Keeps crashing with this message, I'm unsure why.

### Steps to reproduce

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: Civ", -XstartOnFirstThread, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 97144

Using onesix launcher.

[21:14:32] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[21:14:32] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[21:14:32] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[21:14:33] [Render thread/INFO]: [STDERR]: Failed to start Minecraft:
[21:14:33] [Render thread/INFO]: [STDERR]: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
[21:14:33] [Render thread/INFO]: [STDERR]: 	at ac.a(SourceFile:65)
[21:14:33] [Render thread/INFO]: [STDERR]: 	at dyr.a(SourceFile:2394)
[21:14:33] [Render thread/INFO]: [STDERR]: 	at dyr.a(SourceFile:2389)
[21:14:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:206)
[21:14:33] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:14:33] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[21:14:33] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:14:33] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[21:14:33] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
[21:14:33] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
[21:14:33] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[21:14:33] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[21:14:33] [Render thread/INFO]: [STDERR]: Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.dylib [in thread "Render thread"]
[21:14:33] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:147)
[21:14:33] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:67)
[21:14:33] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.<clinit>(Library.java:50)
[21:14:33] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:97)
[21:14:33] [Render thread/INFO]: [STDERR]: 	at dsk.<clinit>(SourceFile:8)
[21:14:33] [Render thread/INFO]: [STDERR]: 	at dth.<init>(SourceFile:56)
[21:14:33] [Render thread/INFO]: [STDERR]: 	at dto.<init>(SourceFile:19)
[21:14:33] [Render thread/INFO]: [STDERR]: 	at dto.<init>(SourceFile:23)
[21:14:33] [Render thread/INFO]: [STDERR]: 	at dto.<clinit>(SourceFile:11)
[21:14:33] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(SourceFile:46)
[21:14:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:194)
[21:14:33] [Render thread/INFO]: [STDERR]: 	... 8 more
[21:14:33] [Render thread/INFO]: [STDOUT]: Exiting with -1
Process exited with exit code 255 (0xff).

### Suspected cause

unsure

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
