### ISSUE TITLE
Process exited with exit code 127

### ISSUE THREAD

**Issue by ghost** [MultiMC/Launcher#5220]
### Operating System

Linux

### Description of bug

i am trying to run minecraft 1.1.0 on Linux Manjaro but it gives me this error and there is nothing i could find about the error. please help.

MultiMC version: 0.7.0-3772

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.225.239.19, 13.225.239.10, 13.225.239.81, 13.225.239.14]

session.minecraft.net resolves to:
    [2620:1ec:46::67, 2620:1ec:bdf::67, 13.107.213.67, 13.107.246.67]

textures.minecraft.net resolves to:
    [2620:1ec:bdf::67, 2620:1ec:46::67, 13.107.246.67, 13.107.213.67]

api.mojang.com resolves to:
    [2620:1ec:bdf::67, 2620:1ec:46::67, 13.107.213.67, 13.107.246.67]

Minecraft folder is:
/home/zacki/.local/share/multimc/instances/1.1/.minecraft

Java path is:
/usr/bin/java

Checking Java version...
Java is version 20.0.1, using 64-bit architecture, from N/A.

11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
NVIDIA Corporation GA106 [GeForce RTX 3060 Lite Hash Rate] (rev a1)

Subsystem: NVIDIA Corporation GA106 [GeForce RTX 3060 Lite Hash Rate]

Kernel driver in use: nvidia

OpenGL version string: 4.6.0 NVIDIA 535.54.03

Main Class:
  

Native path:
  /home/zacki/.local/share/multimc/instances/1.1/natives

Traits:
traits legacyLaunch
traits texturepacks

Libraries:
  /home/zacki/.local/share/multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/zacki/.local/share/multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/zacki/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/zacki/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/zacki/.local/share/multimc/libraries/com/mojang/minecraft/1.1/minecraft-1.1-client.jar

Native libraries:
  /home/zacki/.local/share/multimc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/zacki/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar

Params:
  

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 19705

Using onesix launcher.

Launching with applet wrapper...
27 achievements
174 recipes
Setting user: ZackOsh, token:<ACCESS TOKEN>:<PROFILE ID>
Inconsistency detected by ld.so: dl-lookup.c: 107: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
Process exited with exit code 127 (0x7f).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 22 Jul 2023 02:47:28 +0200
Clipboard copy at: 22 Jul 2023 02:47:29 +0200
Clipboard copy at: 22 Jul 2023 02:47:29 +0200

### Steps to reproduce

booting 1.1.0 on linux manjaro

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
your java version is broken install a proper java package https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by ghost** [comment]
> your java version is broken install a proper java package https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

i reinstalled jre17-openjdk and now there is a different error

MultiMC version: 0.7.0-3772


Launched instance in online mode

authserver.mojang.com resolves to:
    [13.225.239.19, 13.225.239.14, 13.225.239.81, 13.225.239.10]

session.minecraft.net resolves to:
    [2620:1ec:bdf::67, 2620:1ec:46::67, 13.107.246.67, 13.107.213.67]

textures.minecraft.net resolves to:
    [2620:1ec:46::67, 2620:1ec:bdf::67, 13.107.213.67, 13.107.246.67]

api.mojang.com resolves to:
    [2620:1ec:bdf::67, 2620:1ec:46::67, 13.107.246.67, 13.107.213.67]


Minecraft folder is:
/home/zacki/.local/share/multimc/instances/1.1/.minecraft


Java path is:
/usr/bin/java


Checking Java version...
Java is version 1.8.0_372, using 64-bit architecture, from Oracle Corporation.


11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
NVIDIA Corporation GA106 [GeForce RTX 3060 Lite Hash Rate] (rev a1)

Subsystem: NVIDIA Corporation GA106 [GeForce RTX 3060 Lite Hash Rate]

Kernel driver in use: nvidia

OpenGL version string: 4.6.0 NVIDIA 535.54.03

Main Class:
  

Native path:
  /home/zacki/.local/share/multimc/instances/1.1/natives

Traits:
traits legacyLaunch
traits texturepacks

Libraries:
  /home/zacki/.local/share/multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/zacki/.local/share/multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/zacki/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/zacki/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/zacki/.local/share/multimc/libraries/com/mojang/minecraft/1.1/minecraft-1.1-client.jar

Native libraries:
  /home/zacki/.local/share/multimc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/zacki/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar

Params:
  

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 2043


Using onesix launcher.

Launching with applet wrapper...
Exception in thread "main" java.lang.UnsatisfiedLinkError: no atk-wrapper in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:843)
	at java.lang.System.loadLibrary(System.java:1136)
	at org.GNOME.Accessibility.AtkWrapper.initAtk(AtkWrapper.java:36)
	at org.GNOME.Accessibility.AtkWrapper.<clinit>(AtkWrapper.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:805)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
	at java.awt.Window.getToolkit(Window.java:1358)
	at java.awt.Window.init(Window.java:506)
	at java.awt.Window.<init>(Window.java:537)
	at java.awt.Frame.<init>(Frame.java:420)
	at org.multimc.LegacyFrame.<init>(LegacyFrame.java:38)
	at org.multimc.onesix.OneSixLauncher.legacyLaunch(OneSixLauncher.java:146)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:273)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Process exited with exit code 1 (0x1).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 22 Jul 2023 20:14:38 +0200

**Comment by ghost** [comment]
i could only find stuff about error code -1

**Comment by phit** [comment]
you installed a headless java now, you need the full jre

**Comment by ghost** [comment]
fixed it thx for the help
