### ISSUE TITLE
Forge 1.8.9 Crash (java.lang.ClassCastException)

### ISSUE THREAD

**Issue by IxGamerXL** [MultiMC/Launcher#5246]
### Operating System

Windows

### Description of bug

Have tested with and without mods, the crash still appears.

```
MultiMC version: 0.7.0-3775


Launched instance in online mode

authserver.mojang.com resolves to:
    [18.172.122.24, 18.172.122.34, 18.172.122.31, 18.172.122.90]

session.minecraft.net resolves to:
    [13.107.213.51, 13.107.246.51]

textures.minecraft.net resolves to:
    [13.107.213.51, 13.107.246.51]

api.mojang.com resolves to:
    [13.107.246.51, 13.107.213.51]


Minecraft folder is:
C:/Users/USERNAME/MultiMC/instances/F1.8.9 - SkyblockAddons/.minecraft


Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe


Checking Java version...
Java is version 18.0.1.1, using 64-bit architecture, from Oracle Corporation.


Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/USERNAME/MultiMC/instances/F1.8.9 - SkyblockAddons/natives

Libraries:
  C:/Users/USERNAME/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/USERNAME/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/USERNAME/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/USERNAME/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-2015020
9.jar
  C:/Users/USERNAME/MultiMC/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  C:/Users/USERNAME/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/USERNAME/MultiMC/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  C:/Users/USERNAME/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/USERNAME/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/USERNAME/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  C:/Users/USERNAME/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/USERNAME/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/USERNAME/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/USERNAME/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/USERNAME/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/USERNAME/MultiMC/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  C:/Users/USERNAME/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/USERNAME/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/USERNAME/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/USERNAME/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/USERNAME/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/USERNAME/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/USERNAME/MultiMC/libraries/com/mojang/realms/1.7.59/realms-1.7.59.jar
  C:/Users/USERNAME/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/USERNAME/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/USERNAME/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/USERNAME/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/USERNAME/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  C:/Users/USERNAME/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar

  C:/Users/USERNAME/MultiMC/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar
  C:/Users/USERNAME/MultiMC/libraries/net/minecraftforge/forge/1.8.9-11.15.1.2318-1.8.9/forge-1.8.9-11.15.1.2318-1.8.9-u
niversal.jar
  C:/Users/USERNAME/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/USERNAME/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/USERNAME/MultiMC/libraries/jline/jline/2.13/jline-2.13.jar
  C:/Users/USERNAME/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/USERNAME/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/USERNAME/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0
.jar
  C:/Users/USERNAME/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/USERNAME/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-
library_2.11-1.0.2.jar
  C:/Users/USERNAME/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations
-plugin_2.11.1-1.0.2.jar
  C:/Users/USERNAME/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/USERNAME/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1
.0.1.jar
  C:/Users/USERNAME/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/USERNAME/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/USERNAME/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/USERNAME/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/USERNAME/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/USERNAME/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/USERNAME/MultiMC/libraries/com/mojang/minecraft/1.8.9/minecraft-1.8.9-client.jar

Native libraries:
  C:/Users/USERNAME/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/USERNAME/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly
-20150209-natives-windows.jar
  C:/Users/USERNAME/MultiMC/libraries/tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-windows-64.jar
  C:/Users/USERNAME/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-window
s-64.jar

Mods:
  [??] OptiFine_1.8.9_HD_U_M5.jar
  [??] SkyblockAddons-1.6.1-for-MC-1.8.9.jar

Params:
  --username IxGamerXL --version 1.8.9 --gameDir C:/Users/USERNAME/MultiMC/instances/F1.8.9 - SkyblockAddons/.minecraft
--assetsDir C:/Users/USERNAME/MultiMC/assets --assetIndex 1.8 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userPro
perties {} --userType msa --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.l
anguage=en]


Minecraft process ID: 11880


Using onesix launcher.

Failed to start Minecraft:
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URL
ClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of load
er 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
        at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
        at org.multimc.EntryPoint.listen(EntryPoint.java:143)
        at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

```

### Steps to reproduce

* Create a new 1.8.9 profile
* Install forge (11.15.1.2318)
* Run profile (online)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
Wrong java version.

/usr/lib/jvm/java-11-openjdk-amd64/bin/java

There's a nice convenient Wiki just for things like this: [Using the right Java](https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java)

**Comment by IxGamerXL** [comment]
> Wrong java version.
> 
> /usr/lib/jvm/java-11-openjdk-amd64/bin/java
> 
> There's a nice convenient Wiki just for things like this: [Using the right Java](https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java)

Thankfully that was just the fix I needed. Linked the java runtime to Java 8 from Eclipse Temurin and it ran flawlessly.
