### ISSUE TITLE
1.7.10 install forge in clean installation

### ISSUE THREAD

**Issue by DonKolia** [MultiMC/Launcher#5248]
### Operating System

Windows

### Description of bug

1.7.10 install forge in clean installation
![image](https://github.com/MultiMC/Launcher/assets/55564649/7bba4abc-9ee8-4971-91bd-87c3c4416d7d)

MultiMC version: 0.7.0-3775

Launched instance in online mode

authserver.mojang.com resolves to:
    [54.192.95.78, 54.192.95.17, 54.192.95.51, 54.192.95.102]

session.minecraft.net resolves to:
    [13.107.213.43, 13.107.246.43]

textures.minecraft.net resolves to:
    [13.107.213.43, 13.107.246.43]

api.mojang.com resolves to:
    [13.107.213.43, 13.107.246.43]

Minecraft folder is:
C:/Program Files (x86)/MultiMC/instances/1.7.10/.minecraft

Java path is:
C:/Program Files/Java/jdk-17/bin/javaw.exe

Checking Java version...
Java is version 17, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Program Files (x86)/MultiMC/instances/1.7.10/natives

Libraries:
  C:/Program Files (x86)/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Program Files (x86)/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Program Files (x86)/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Program Files (x86)/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Program Files (x86)/MultiMC/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  C:/Program Files (x86)/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Program Files (x86)/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Program Files (x86)/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Program Files (x86)/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Program Files (x86)/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Program Files (x86)/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Program Files (x86)/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Program Files (x86)/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Program Files (x86)/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Program Files (x86)/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Program Files (x86)/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Program Files (x86)/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Program Files (x86)/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Program Files (x86)/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Program Files (x86)/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Program Files (x86)/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Program Files (x86)/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Program Files (x86)/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Program Files (x86)/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Program Files (x86)/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Program Files (x86)/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Program Files (x86)/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  C:/Program Files (x86)/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  C:/Program Files (x86)/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Program Files (x86)/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
  C:/Program Files (x86)/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Program Files (x86)/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Program Files (x86)/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Program Files (x86)/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Program Files (x86)/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Program Files (x86)/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Program Files (x86)/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Program Files (x86)/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Program Files (x86)/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Program Files (x86)/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Program Files (x86)/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Program Files (x86)/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Program Files (x86)/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Program Files (x86)/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Program Files (x86)/MultiMC/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  C:/Program Files (x86)/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Program Files (x86)/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Program Files (x86)/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar
  C:/Program Files (x86)/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Params:
  --username DonKolia --version 1.7.10 --gameDir C:/Program Files (x86)/MultiMC/instances/1.7.10/.minecraft --assetsDir C:/Program Files (x86)/MultiMC/assets --assetIndex 1.7.10 --uuid <ID DEL PERFIL> --accessToken <TOKEN DE ACCESO> --userProperties {} --userType msa --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx20976m, -Duser.language=en]

Minecraft process ID: 9848

Using onesix launcher.

Failed to start Minecraft:
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with exit code -1 (0xffffffffffffffff).
¡Por favor, ten en cuenta que normalmente ni el código de salida ni su descripción son suficientes para diagnosticar problemas!
Sube siempre el registro entero y no solo el código de salida.
MultiMC: Log upload triggered at: 27 Aug 2023 01:02:46 +0200

### Steps to reproduce

Install 1.7.10 and install forge. New installation.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DonKolia** [comment]
Sorry, my bad. It was the Java version. My default Java version is 17 and 1.17.10 works in other java version.
**-- Delete this issue --**
