### ISSUE TITLE
Apple M2 Macbook Air not being able to launch any version

### ISSUE THREAD

**Issue by 0rangy** [MultiMC/Launcher#5258]
### Operating System

macOS

### Description of bug

When I launch it gives me an error

Full log:

MultiMC version: 0.7.0-3814

Launched instance in online mode

authserver.mojang.com resolves to:
    [3.162.3.13, 3.162.3.54, 3.162.3.92, 3.162.3.93]

session.minecraft.net resolves to:
    [13.107.246.36, 13.107.213.36, 2620:1ec:46::36, 2620:1ec:bdf::36]

textures.minecraft.net resolves to:
    [13.107.246.36, 13.107.213.36, 2620:1ec:46::36, 2620:1ec:bdf::36]

api.mojang.com resolves to:
    [13.107.213.36, 13.107.246.36, 2620:1ec:bdf::36, 2620:1ec:46::36]

Minecraft folder is:
/Applications/MultiMC.app/Data/instances/1.19.3/.minecraft

Java path is:
/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java

Checking Java version...
Java is version 17.0.8, using 32-bit architecture, from Eclipse Adoptium.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  net.minecraft.client.main.Main

Native path:
  /Applications/MultiMC.app/Data/instances/1.19.3/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/ca/weblite/java-objc-bridge/1.1/java-objc-bridge-1.1.jar
  /Applications/MultiMC.app/Data/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
  /Applications/MultiMC.app/Data/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
  /Applications/MultiMC.app/Data/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /Applications/MultiMC.app/Data/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
  /Applications/MultiMC.app/Data/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/authlib/3.16.29/authlib-3.16.29.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/javabridge/2.0.25/javabridge-2.0.25.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/text2speech/1.16.7/text2speech-1.16.7.jar
  /Applications/MultiMC.app/Data/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /Applications/MultiMC.app/Data/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /Applications/MultiMC.app/Data/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
  /Applications/MultiMC.app/Data/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
  /Applications/MultiMC.app/Data/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  /Applications/MultiMC.app/Data/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  /Applications/MultiMC.app/Data/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/minecraft/1.19.3/minecraft-1.19.3-client.jar

Native libraries:
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-macos.jar

Params:
  --username 0rangy --version 1.19.3 --gameDir /Applications/MultiMC.app/Data/instances/1.19.3/.minecraft --assetsDir /Applications/MultiMC.app/Data/assets --assetIndex 2 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType msa --versionType release

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: 1.19.3", -XstartOnFirstThread, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 48170

Using onesix launcher.

[11:36:20] [main/INFO]: Building optimized datafixer
[11:36:21] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[11:36:21] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[11:36:21] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[11:36:21] [Render thread/INFO]: [STDERR]: Failed to start Minecraft:
[11:36:21] [Render thread/INFO]: [STDERR]: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
[11:36:21] [Render thread/INFO]: [STDERR]: 	at z.a(SourceFile:66)
[11:36:21] [Render thread/INFO]: [STDERR]: 	at ejf.a(SourceFile:2408)
[11:36:21] [Render thread/INFO]: [STDERR]: 	at ejf.a(SourceFile:2403)
[11:36:21] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.a(SourceFile:214)
[11:36:21] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:51)
[11:36:21] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:36:21] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[11:36:21] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:36:21] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[11:36:21] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
[11:36:21] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
[11:36:21] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[11:36:21] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[11:36:21] [Render thread/INFO]: [STDERR]: Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.dylib [in thread "Render thread"]
[11:36:21] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:164)
[11:36:21] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:63)
[11:36:21] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.<clinit>(Library.java:51)
[11:36:21] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
[11:36:21] [Render thread/INFO]: [STDERR]: 	at edb.<clinit>(SourceFile:8)
[11:36:21] [Render thread/INFO]: [STDERR]: 	at edy.<init>(SourceFile:51)
[11:36:21] [Render thread/INFO]: [STDERR]: 	at eef.<init>(SourceFile:19)
[11:36:21] [Render thread/INFO]: [STDERR]: 	at eef.<init>(SourceFile:23)
[11:36:21] [Render thread/INFO]: [STDERR]: 	at eef.<clinit>(SourceFile:11)
[11:36:21] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(SourceFile:46)
[11:36:21] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.a(SourceFile:202)
[11:36:21] [Render thread/INFO]: [STDERR]: 	... 9 more
[11:36:21] [Render thread/INFO]: [STDOUT]: Exiting with -1
Process exited with exit code 255 (0xff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

### Steps to reproduce

Launch Minecraft

### Suspected cause

Weird natives but I can't find teh folder to replace them

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
I'm no Apple expert so take it with a grain of salt, if that's ARM processor MultiMC doesn't support ARM.  Else the error log tells you "Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version."

https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
