### ISSUE TITLE
Error minecraft 1.18.2 launching: exit code 255 (0xff)

### ISSUE THREAD

**Issue by PabloMakesStuff** [MultiMC/Launcher#5265]
### Operating System

Linux

### Description of bug

This is the error message when launching 1.18.2 forge:

MultiMC version: 0.7.0-3809

Launched instance in online mode

authserver.mojang.com resolves to:
    [52.84.106.97, 52.84.106.46, 52.84.106.12, 52.84.106.101]

session.minecraft.net resolves to:
    [13.107.213.67, 13.107.246.67, 2620:1ec:bdf::67, 2620:1ec:46::67]

textures.minecraft.net resolves to:
    [13.107.246.67, 13.107.213.67, 2620:1ec:46::67, 2620:1ec:bdf::67]

api.mojang.com resolves to:
    [13.107.246.67, 13.107.213.67, 2620:1ec:46::67, 2620:1ec:bdf::67]

Minecraft folder is:
/home/pablo_h0t/.local/share/multimc/instances/1.18.2/.minecraft

Java path is:
/home/pablo_h0t/Documents/jdk-17.0.8/bin/java

Checking Java version...
Java is version 17.0.8, using 64-bit architecture, from Oracle Corporation.

Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz
Advanced Micro Devices, Inc. [AMD/ATI] Lexa PRO [Radeon 540/540X/550/550X / RX 540X/550/550X] (rev c7)

Subsystem: Sapphire Technology Limited Lexa PRO [Radeon RX 550]

Kernel driver in use: amdgpu

OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  /home/pablo_h0t/.local/share/multimc/instances/1.18.2/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  /home/pablo_h0t/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  /home/pablo_h0t/.local/share/multimc/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  /home/pablo_h0t/.local/share/multimc/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /home/pablo_h0t/.local/share/multimc/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /home/pablo_h0t/.local/share/multimc/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  /home/pablo_h0t/.local/share/multimc/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  /home/pablo_h0t/.local/share/multimc/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.0/log4j-slf4j18-impl-2.17.0.jar
  /home/pablo_h0t/.local/share/multimc/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  /home/pablo_h0t/.local/share/multimc/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  /home/pablo_h0t/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/pablo_h0t/.local/share/multimc/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
  /home/pablo_h0t/.local/share/multimc/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/pablo_h0t/.local/share/multimc/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /home/pablo_h0t/.local/share/multimc/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /home/pablo_h0t/.local/share/multimc/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /home/pablo_h0t/.local/share/multimc/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  /home/pablo_h0t/.local/share/multimc/libraries/com/mojang/datafixerupper/4.1.27/datafixerupper-4.1.27.jar
  /home/pablo_h0t/.local/share/multimc/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  /home/pablo_h0t/.local/share/multimc/libraries/com/mojang/authlib/3.3.39/authlib-3.3.39.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/pablo_h0t/.local/share/multimc/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  /home/pablo_h0t/.local/share/multimc/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.17.0/log4j-api-2.17.0.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.17.0/log4j-core-2.17.0.jar
  /home/pablo_h0t/.local/share/multimc/libraries/com/mojang/text2speech/1.12.4/text2speech-1.12.4.jar
  /home/pablo_h0t/.local/share/multimc/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  /home/pablo_h0t/.local/share/multimc/libraries/cpw/mods/securejarhandler/1.0.8/securejarhandler-1.0.8.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar
  /home/pablo_h0t/.local/share/multimc/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  /home/pablo_h0t/.local/share/multimc/libraries/net/minecraftforge/eventbus/5.0.3/eventbus-5.0.3.jar
  /home/pablo_h0t/.local/share/multimc/libraries/net/minecraftforge/forgespi/4.0.15-4.x/forgespi-4.0.15-4.x.jar
  /home/pablo_h0t/.local/share/multimc/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar
  /home/pablo_h0t/.local/share/multimc/libraries/cpw/mods/modlauncher/9.1.3/modlauncher-9.1.3.jar
  /home/pablo_h0t/.local/share/multimc/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  /home/pablo_h0t/.local/share/multimc/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  /home/pablo_h0t/.local/share/multimc/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  /home/pablo_h0t/.local/share/multimc/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  /home/pablo_h0t/.local/share/multimc/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  /home/pablo_h0t/.local/share/multimc/libraries/net/minecraftforge/JarJarSelector/0.3.19/JarJarSelector-0.3.19.jar
  /home/pablo_h0t/.local/share/multimc/libraries/net/minecraftforge/JarJarMetadata/0.3.19/JarJarMetadata-0.3.19.jar
  /home/pablo_h0t/.local/share/multimc/libraries/cpw/mods/bootstraplauncher/1.0.0/bootstraplauncher-1.0.0.jar
  /home/pablo_h0t/.local/share/multimc/libraries/net/minecraftforge/JarJarFileSystems/0.3.19/JarJarFileSystems-0.3.19.jar
  /home/pablo_h0t/.local/share/multimc/libraries/net/minecraftforge/fmlloader/1.18.2-40.2.10/fmlloader-1.18.2-40.2.10.jar
  /home/pablo_h0t/.local/share/multimc/libraries/com/mojang/minecraft/1.18.2/minecraft-1.18.2-client.jar

Native libraries:
  /home/pablo_h0t/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-linux.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-linux.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-linux.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-linux.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-linux.jar
  /home/pablo_h0t/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-linux.jar
  /home/pablo_h0t/.local/share/multimc/libraries/com/mojang/text2speech/1.12.4/text2speech-1.12.4-natives-linux.jar

Mods:
  [✔️] alchemistry-1.18.2-2.2.2.jar
  [✔️] alchemylib-1.18.2-1.0.22.jar
  [✔️] Apotheosis-1.18.2-5.8.1.jar
  [✔️] appliedenergistics2-forge-11.7.6.jar
  [✔️] architectury-4.11.93-forge.jar
  [✔️] ars_nouveau-1.18.2-2.9.0.jar
  [✔️] artifacts-1.18.2-4.2.2.jar
  [✔️] balm-3.2.6.jar
  [✔️] Bookshelf-Forge-1.18.2-13.3.56.jar
  [✔️] BrandonsCore-1.18.2-3.1.9.280-universal.jar
  [✔️] camera-1.18.2-1.0.6.jar
  [✔️] carryon-1.18.2-1.17.1.12.jar
  [✔️] chemlib-1.18.2-2.0.16.jar
  [✔️] citadel-1.11.3-1.18.2.jar
  [✔️] CodeChickenLib-1.18.2-4.1.4.488-universal.jar
  [✔️] cofh_core-1.18.2-9.2.2.44.jar
  [✔️] constructionwand-1.18.2-2.9.jar
  [✔️] create-1.18.2-0.5.1.c.jar
  [✔️] create-confectionery1.18.2_v1.0.9.jar
  [✔️] curios-forge-1.18.2-5.0.9.1.jar
  [✔️] Draconic-Evolution-1.18.2-3.0.29.524-universal.jar
  [✔️] dreadsteel-1.18.2-1.1.6.jar
  [✔️] DungeonCrawl-1.18.2-2.3.14.jar
  [✔️] EnchantmentDescriptions-Forge-1.18.2-10.0.12.jar
  [✔️] ensorcellation-1.18.2-3.2.1.17.jar
  [✔️] expandability-6.0.0.jar
  [✔️] ExplorersCompass-1.18.2-1.3.0-forge.jar
  [✔️] geckolib-forge-1.18-3.0.57.jar
  [✔️] hexcasting-forge-1.18.2-0.9.6.jar
  [✔️] iceandfire-2.1.12-1.18.2.jar
  [✔️] ironchest-1.18.2-13.2.11.jar
  [✔️] jei-1.18.2-forge-10.2.1.1005.jar
  [✔️] journeymap-1.18.2-5.9.7-forge.jar
  [✔️] Kobolds-2.9.3-1.18.2-final.jar
  [✔️] kotlinforforge-3.12.0-all.jar
  [✔️] Mantle-1.18.2-1.9.45.jar
  [✔️] MaxHealthFix-Forge-1.18.2-5.0.4.jar
  [✔️] memoryleakfix-forge-1.17+-1.0.0.jar
  [✔️] minecraft-comes-alive-7.4.9+1.18.2-universal.jar
  [✔️] NaturesCompass-1.18.2-1.9.7-forge.jar
  [✔️] OreExcavation-1.10.162.jar
  [✔️] Patchouli-1.18.2-71.1.jar
  [✔️] paucal-forge-1.18.2-0.4.7.jar
  [✔️] pipez-1.18.2-1.1.5.jar
  [✔️] Placebo-1.18.2-6.6.7.jar
  [✔️] simplyswords-forge-1.40-1.18.2.jar
  [✔️] Steam_Rails-1.4.4+forge-mc1.18.2-build.12.jar
  [✔️] supermartijn642configlib-1.1.8-forge-mc1.18.jar
  [✔️] supermartijn642corelib-1.1.12-forge-mc1.18.jar
  [✔️] TConstruct-1.18.2-3.6.4.113.jar
  [✔️] TravelersBackpack-1.18.2-7.1.41.jar
  [✔️] unusualprehistory-1.1.2.jar
  [✔️] waystones-forge-1.18.2-10.2.1.jar
  [✔️] wormhole-1.1.15-forge-mc1.18.jar

Params:
  --username RollinsHoe --version 1.18.2 --gameDir /home/pablo_h0t/.local/share/multimc/instances/1.18.2/.minecraft --assetsDir /home/pablo_h0t/.local/share/multimc/assets --assetIndex 1.18 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType msa --versionType release --launchTarget forgeclient --fml.forgeVersion 40.2.10 --fml.mcVersion 1.18.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20220404.173914

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx2400m, -Duser.language=en]

Minecraft process ID: 2974

Using onesix launcher.

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2023-09-23 23:07:51,139 main WARN Advanced terminal features are not available in this environment
[23:07:51] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, RollinsHoe, --version, 1.18.2, --gameDir, /home/pablo_h0t/.local/share/multimc/instances/1.18.2/.minecraft, --assetsDir, /home/pablo_h0t/.local/share/multimc/assets, --assetIndex, 1.18, --uuid, <PROFILE ID>, --accessToken, ❄❄❄❄❄❄❄❄, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 40.2.10, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914, --width, 854, --height, 480]
[23:07:51] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.8 by Oracle Corporation
[23:07:51] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/pablo_h0t/.local/share/multimc/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2348!/ Service=ModLauncher Env=CLIENT
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: com.electronwill.nightconfig.core.io.WritingException: An I/O error occured
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:222)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.WriteAsyncFileConfig.load(WriteAsyncFileConfig.java:138)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.10/net.minecraftforge.fml.loading.moddiscovery.ModFileParser.modsTomlParser(ModFileParser.java:44)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.10/net.minecraftforge.fml.loading.moddiscovery.ModFileParser.readModList(ModFileParser.java:31)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.10/net.minecraftforge.fml.loading.moddiscovery.ModFile.<init>(ModFile.java:79)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.10/net.minecraftforge.fml.loading.moddiscovery.ModFile.<init>(ModFile.java:68)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.10/net.minecraftforge.fml.loading.moddiscovery.AbstractModLocator.createMod(AbstractModLocator.java:49)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.10/net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModLocator.lambda$scanMods$0(AbstractJarFileModLocator.java:23)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.10/net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModLocator.scanMods(AbstractJarFileModLocator.java:26)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.10/net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:59)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.10/net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:166)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.10/net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55)
Exiting with -1
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:87)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
	... 13 more
Caused by: java.util.zip.ZipException: R0
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$Entry.readLocEXTT(ZipFileSystem.java:3239)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$Entry.readExtra(ZipFileSystem.java:3173)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$Entry.readCEN(ZipFileSystem.java:2850)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$Entry.<init>(ZipFileSystem.java:2786)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.getEntry(ZipFileSystem.java:1980)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.newByteChannel(ZipFileSystem.java:982)
	at jdk.zipfs/jdk.nio.zipfs.ZipPath.newByteChannel(ZipPath.java:864)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newByteChannel(ZipFileSystemProvider.java:255)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at cpw.mods.securejarhandler@1.0.8/cpw.mods.niofs.union.UnionFileSystem.byteChannel(UnionFileSystem.java:316)
	at java.base/java.util.Optional.map(Optional.java:260)
	at cpw.mods.securejarhandler@1.0.8/cpw.mods.niofs.union.UnionFileSystem.newReadByteChannel(UnionFileSystem.java:307)
	at cpw.mods.securejarhandler@1.0.8/cpw.mods.niofs.union.UnionFileSystemProvider.newByteChannel(UnionFileSystemProvider.java:149)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:218)
	... 52 more
Process exited with exit code 255 (0xff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

### Steps to reproduce

Make a new instance with Java 17, Multimc 5 and 1.18.2 forge, launch the game with 42 mods.

### Suspected cause

Java something error, i have no idea

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
Wrong Java version.  Java 17, and 1.18.2 forge 

https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by phit** [comment]
they are already using the right java, there's just a bad file somewhere in their pack

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by FeedTheChunk** [comment]
Sorry I miss read it as 1.8.2.
