### ISSUE TITLE
Crash at launch: Failed to locate library: liblwjgl.so

### ISSUE THREAD

**Issue by distinctjuggle** [MultiMC/Launcher#5271]
### Operating System

Linux

### Description of bug

Attempting to launch a fresh instance of 1.20.2 with zero special configuration other than specifying a java path, I am met with a crash and the following logs:

```MultiMC version: 0.6.14-custom


Launched instance in online mode

authserver.mojang.com resolves to:
    [IPs]

session.minecraft.net resolves to:
    [IPs]

textures.minecraft.net resolves to:
    [IPs]

api.mojang.com resolves to:
    [IPs]


Minecraft folder is:
/home/user/.local/share/multimc/instances/1.20.2/.minecraft


Java path is:
/usr/lib/jvm/java-21-openjdk/bin/java


Checking Java version...
Java is version 21, using 64-bit architecture, from N/A.


Modern functional CPU
Modern funcitonal GPU

Kernel driver in use: nvidia

OpenGL version string: 4.6.0 NVIDIA 535.113.01

Main Class:
  net.minecraft.client.main.Main

Native path:
  /home/user/.local/share/multimc/instances/1.20.2/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  /home/user/.local/share/multimc/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar
  /home/user/.local/share/multimc/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  /home/user/.local/share/multimc/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/user/.local/share/multimc/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  /home/user/.local/share/multimc/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  /home/user/.local/share/multimc/libraries/com/mojang/authlib/5.0.47/authlib-5.0.47.jar
  /home/user/.local/share/multimc/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /home/user/.local/share/multimc/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar
  /home/user/.local/share/multimc/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  /home/user/.local/share/multimc/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  /home/user/.local/share/multimc/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /home/user/.local/share/multimc/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  /home/user/.local/share/multimc/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  /home/user/.local/share/multimc/libraries/commons-io/commons-io/2.13.0/commons-io-2.13.0.jar
  /home/user/.local/share/multimc/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/user/.local/share/multimc/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  /home/user/.local/share/multimc/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  /home/user/.local/share/multimc/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  /home/user/.local/share/multimc/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  /home/user/.local/share/multimc/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  /home/user/.local/share/multimc/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  /home/user/.local/share/multimc/libraries/io/netty/netty-transport-native-epoll/4.1.97.Final/netty-transport-native-epoll-4.1.97.Final-linux-aarch_64.jar
  /home/user/.local/share/multimc/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  /home/user/.local/share/multimc/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  /home/user/.local/share/multimc/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  /home/user/.local/share/multimc/libraries/net/java/dev/jna/jna-platform/5.13.0/jna-platform-5.13.0.jar
  /home/user/.local/share/multimc/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar
  /home/user/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/user/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.22/commons-compress-1.22.jar
  /home/user/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.13.0/commons-lang3-3.13.0.jar
  /home/user/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/user/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  /home/user/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  /home/user/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  /home/user/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  /home/user/.local/share/multimc/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  /home/user/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar
  /home/user/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar
  /home/user/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar
  /home/user/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar
  /home/user/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar
  /home/user/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar
  /home/user/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar
  /home/user/.local/share/multimc/libraries/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar
  /home/user/.local/share/multimc/libraries/com/mojang/minecraft/1.20.2/minecraft-1.20.2-client.jar

Native libraries:

Params:
  --username  --version MultiMC5 --gameDir /home/user/.local/share/multimc/instances/1.20.2/.minecraft --assetsDir /home/user/.local/share/multimc/assets --assetIndex 8 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 35652


Using onesix launcher.

[14:45:58] [Datafixer Bootstrap/INFO]: 192 Datafixer optimizations took 93 milliseconds
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[14:45:58] [Render thread/INFO]: [STDERR]: Failed to start Minecraft:
[14:45:58] [Render thread/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
[14:45:58] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
[14:45:58] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[14:45:58] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[14:45:58] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[14:45:58] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[14:45:58] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[14:45:58] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
[14:45:58] [Render thread/INFO]: [STDERR]: 	at ab.a(SourceFile:66)
[14:45:58] [Render thread/INFO]: [STDERR]: 	at eqv.a(SourceFile:2500)
[14:45:58] [Render thread/INFO]: [STDERR]: 	at eqv.a(SourceFile:2494)
[14:45:58] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:223)
[14:45:58] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[14:45:58] [Render thread/INFO]: [STDERR]: 	... 5 more
[14:45:58] [Render thread/INFO]: [STDERR]: Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.so [in thread "Render thread"]
[14:45:58] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:174)
[14:45:58] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:64)
[14:45:58] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.<clinit>(Library.java:52)
[14:45:58] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
[14:45:58] [Render thread/INFO]: [STDERR]: 	at ekn.<clinit>(SourceFile:8)
[14:45:58] [Render thread/INFO]: [STDERR]: 	at elk.<init>(SourceFile:48)
[14:45:58] [Render thread/INFO]: [STDERR]: 	at elr.<init>(SourceFile:19)
[14:45:58] [Render thread/INFO]: [STDERR]: 	at elr.<init>(SourceFile:23)
[14:45:58] [Render thread/INFO]: [STDERR]: 	at elr.<clinit>(SourceFile:11)
[14:45:58] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(SourceFile:50)
[14:45:58] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:211)
[14:45:58] [Render thread/INFO]: [STDERR]: 	... 6 more
[14:45:58] [Render thread/INFO]: [STDOUT]: Exiting with -1
Process exited with code 255.```

I noticed that there seems to be [a change with LWJGL](https://old.reddit.com/r/MultiMC/comments/16ooum3/lwjgl_isnt_on_the_version_list/), and I presume this is related to the cause.  

I couldn't find any previous reports matching this.  

### Steps to reproduce

Install and attempt to launch 1.20.2 on a fresh instance.

### Suspected cause

Possibly a problem with java-21-openjdk jre?  I don't have another supported version of Java installed to compare with, and 21 has worked fine for all previous versions with Multimc.  

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
looks like you aren't using multimc, or you need to update it

**Comment by distinctjuggle** [comment]
Ah, thanks!  It looks like the repo I was using was no longer supported, I swapped repos and seems to launch now.

**Comment by phit** [comment]
the only official repo is https://github.com/MultiMC/multimc-pkgbuild
for debian & co there's the deb on the website, everything else needs to use the tar

anything outside of that is not multimc and just abusing the trademark

**Comment by distinctjuggle** [comment]
I'm referring to a system repo package, not anything else.  Moreover, Multi-MC follows the Apache 2 license, so I'm a bit confused why you would imply that FOSS doing FOSS things would be, "trademark abuse."

**Comment by phit** [comment]
the launcher itself is Apache 2 and MSPL, the name, logo etc are not

see https://github.com/MultiMC/Launcher#forkingredistributingcustom-builds-policy

**Comment by distinctjuggle** [comment]
I fail to see your point.  This doesn't change any stated facts, nor does it mean a system repo is in violation of any intellectual property.  The implication otherwise would be stating that there are quite literally millions of IP violations touching nearly every single aspect of software, which surely you can see is ludicrous.  

Thanks again for the help.

**Comment by phit** [comment]
A repos distributing something called MultiMC using the MultiMC logo are in violation of a registered trademark, this has nothing to do with FOSS and the license of the "Launcher" source code.

**Comment by distinctjuggle** [comment]
Great, take them to court if you believe there's a violation of IP.  Let me know how that turns out.  

In the meantime I have better things to do than try to convince you of the fundamentals of IP law, backed by decades of examples and real case law.  Thank you again for the help, have a nice day.

**Comment by phit** [comment]
You are confusing copyright and IP law

**Comment by distinctjuggle** [comment]
> You are confusing copyright and IP law

Literally two seconds of an internet search would inform you that a copyright (as well as a trademark) is a type of IP, but thanks for proving my point.  : )  I'm out.

**Comment by phit** [comment]
exactly, FOSS is about copyright, you can be violating a trademark, without violating copyright

**Comment by Xtore14** [comment]
I have PrismLauncher and it gives me the same error. I went to the folder that was supposed to contain iblwjgl.so, but it didn't exist.

`java.lang.UnsatisfiedLinkError: /home/username/.local/share/PrismLauncher/instances/1.12/natives/liblwjgl.so: libawt_xawt.so: impossibile aprire il file oggetto condiviso: File o directory non esistente (Possible cause: architecture word width mismatch)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1850)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.lwjgl.Sys$1.run(Sys.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:96)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at bhz.I(SourceFile:2825)
	at net.minecraft.client.main.Main.main(SourceFile:38)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Exiting with ERROR
`
