### ISSUE TITLE
Process exited with exit code -1 (0xffffffffffffffff). 

### ISSUE THREAD

**Issue by Orion-Netix** [MultiMC/Launcher#5277]
### Operating System

Windows 11

### Description of bug

Updated MultiMC and created new instance for minecraft and this happens.
I don't know much so any help is appreciated.

MultiMC version: 0.7.0-3775

Launched instance in online mode

authserver.mojang.com resolves to:
    [52.222.174.86, 52.222.174.63, 52.222.174.32, 52.222.174.120]

session.minecraft.net resolves to:
    [2620:1ec:46::42, 2620:1ec:bdf::42, 13.107.213.42, 13.107.246.42]

textures.minecraft.net resolves to:
    [2620:1ec:46::42, 2620:1ec:bdf::42, 13.107.213.42, 13.107.246.42]

api.mojang.com resolves to:
    [2620:1ec:46::42, 2620:1ec:bdf::42, 13.107.213.42, 13.107.246.42]

Minecraft folder is:
E:/MultiMC/instances/1.20.2/.minecraft

Java path is:
C:/Program Files/Java/jdk-19/bin/java.exe

Checking Java version...
Java is version 19.0.2, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.client.main.Main

Native path:
  E:/MultiMC/instances/1.20.2/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  E:/MultiMC/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar
  E:/MultiMC/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  E:/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  E:/MultiMC/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  E:/MultiMC/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  E:/MultiMC/libraries/com/mojang/authlib/5.0.47/authlib-5.0.47.jar
  E:/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  E:/MultiMC/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar
  E:/MultiMC/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  E:/MultiMC/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  E:/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  E:/MultiMC/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  E:/MultiMC/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  E:/MultiMC/libraries/commons-io/commons-io/2.13.0/commons-io-2.13.0.jar
  E:/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  E:/MultiMC/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  E:/MultiMC/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  E:/MultiMC/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  E:/MultiMC/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  E:/MultiMC/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  E:/MultiMC/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  E:/MultiMC/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  E:/MultiMC/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  E:/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  E:/MultiMC/libraries/net/java/dev/jna/jna-platform/5.13.0/jna-platform-5.13.0.jar
  E:/MultiMC/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar
  E:/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  E:/MultiMC/libraries/org/apache/commons/commons-compress/1.22/commons-compress-1.22.jar
  E:/MultiMC/libraries/org/apache/commons/commons-lang3/3.13.0/commons-lang3-3.13.0.jar
  E:/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  E:/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  E:/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  E:/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  E:/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  E:/MultiMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar
  E:/MultiMC/libraries/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar
  E:/MultiMC/libraries/com/mojang/minecraft/1.20.2/minecraft-1.20.2-client.jar

Native libraries:

Params:
  --username EU_Orion_Netix --version 1.20.2 --gameDir E:/MultiMC/instances/1.20.2/.minecraft --assetsDir E:/MultiMC/assets --assetIndex 8 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType msa --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 8352

Using onesix launcher.

[17:55:54] [Datafixer Bootstrap/INFO]: 192 Datafixer optimizations took 91 milliseconds
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[17:55:55] [Render thread/INFO]: [STDERR]: Failed to start Minecraft:
[17:55:55] [Render thread/INFO]: [STDERR]: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
[17:55:55] [Render thread/INFO]: [STDERR]: 	at ab.a(SourceFile:66)
[17:55:55] [Render thread/INFO]: [STDERR]: 	at eqv.a(SourceFile:2500)
[17:55:55] [Render thread/INFO]: [STDERR]: 	at eqv.a(SourceFile:2494)
[17:55:55] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:223)
[17:55:55] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[17:55:55] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[17:55:55] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
[17:55:55] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
[17:55:55] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[17:55:55] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[17:55:55] [Render thread/INFO]: [STDERR]: Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll [in thread "Render thread"]
[17:55:55] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:174)
[17:55:55] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:64)
[17:55:55] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.<clinit>(Library.java:52)
[17:55:55] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
[17:55:55] [Render thread/INFO]: [STDERR]: 	at ekn.<clinit>(SourceFile:8)
[17:55:55] [Render thread/INFO]: [STDERR]: 	at elk.<init>(SourceFile:48)
[17:55:55] [Render thread/INFO]: [STDERR]: 	at elr.<init>(SourceFile:19)
[17:55:55] [Render thread/INFO]: [STDERR]: 	at elr.<init>(SourceFile:23)
[17:55:55] [Render thread/INFO]: [STDERR]: 	at elr.<clinit>(SourceFile:11)
[17:55:55] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(SourceFile:50)
[17:55:55] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:211)
[17:55:55] [Render thread/INFO]: [STDERR]: 	... 6 more
[17:55:55] [Render thread/INFO]: [STDOUT]: Exiting with -1
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 14 Oct 2023 17:56:19 +0200
Clipboard copy at: 14 Oct 2023 17:56:59 +0200

### Steps to reproduce

pressing the cat button does help, but not the problem, only my mood. 

no idea what to say here, it worked with the previous instance.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
update multimc

**Comment by Orion-Netix** [comment]
> update multimc

huh, though i had already done that, fixed it, thanks

**Comment by Derp33** [comment]
Had the exact same problem lol. For those wondering you have to update multiple times in a row. Dunno why
