### ISSUE TITLE
Can't run minecraft

### ISSUE THREAD

**Issue by KornineQ** [MultiMC/Launcher#5368]
### Operating System

Linux

### Description of bug

MultiMC version: 0.7.0-stable-3673

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.44, 13.107.213.44, 2620:1ec:46::44, 2620:1ec:bdf::44]

textures.minecraft.net resolves to:
    [13.107.246.44, 13.107.213.44, 2620:1ec:bdf::44, 2620:1ec:46::44]

api.mojang.com resolves to:
    [13.107.246.44, 13.107.213.44, 2620:1ec:46::44, 2620:1ec:bdf::44]

Minecraft folder is:
/home/kornineq/.local/share/multimc/instances/1.20.4/.minecraft

Java path is:
/usr/bin/java

Checking Java version...
Java is version 21.0.2, using 64-bit architecture, from N/A.

AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx
NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] (rev a1)

Subsystem: ASUSTeK Computer Inc. TU117M [GeForce GTX 1650 Mobile / Max-Q]

Kernel driver in use: nvidia

Advanced Micro Devices, Inc. [AMD/ATI] Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] (rev c1)

Subsystem: ASUSTeK Computer Inc. Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series]

Kernel driver in use: amdgpu

OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.0.3-arch1.1

Main Class:
  net.minecraft.client.main.Main

Native path:
  /home/kornineq/.local/share/multimc/instances/1.20.4/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  /home/kornineq/.local/share/multimc/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar
  /home/kornineq/.local/share/multimc/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  /home/kornineq/.local/share/multimc/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/kornineq/.local/share/multimc/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  /home/kornineq/.local/share/multimc/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  /home/kornineq/.local/share/multimc/libraries/com/mojang/authlib/6.0.52/authlib-6.0.52.jar
  /home/kornineq/.local/share/multimc/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /home/kornineq/.local/share/multimc/libraries/com/mojang/brigadier/1.2.9/brigadier-1.2.9.jar
  /home/kornineq/.local/share/multimc/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  /home/kornineq/.local/share/multimc/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  /home/kornineq/.local/share/multimc/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /home/kornineq/.local/share/multimc/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  /home/kornineq/.local/share/multimc/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  /home/kornineq/.local/share/multimc/libraries/commons-io/commons-io/2.13.0/commons-io-2.13.0.jar
  /home/kornineq/.local/share/multimc/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/kornineq/.local/share/multimc/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  /home/kornineq/.local/share/multimc/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  /home/kornineq/.local/share/multimc/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  /home/kornineq/.local/share/multimc/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  /home/kornineq/.local/share/multimc/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  /home/kornineq/.local/share/multimc/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  /home/kornineq/.local/share/multimc/libraries/io/netty/netty-transport-native-epoll/4.1.97.Final/netty-transport-native-epoll-4.1.97.Final-linux-aarch_64.jar
  /home/kornineq/.local/share/multimc/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  /home/kornineq/.local/share/multimc/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  /home/kornineq/.local/share/multimc/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  /home/kornineq/.local/share/multimc/libraries/net/java/dev/jna/jna-platform/5.13.0/jna-platform-5.13.0.jar
  /home/kornineq/.local/share/multimc/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar
  /home/kornineq/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/kornineq/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.22/commons-compress-1.22.jar
  /home/kornineq/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.13.0/commons-lang3-3.13.0.jar
  /home/kornineq/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/kornineq/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  /home/kornineq/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  /home/kornineq/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  /home/kornineq/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  /home/kornineq/.local/share/multimc/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  /home/kornineq/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar
  /home/kornineq/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar
  /home/kornineq/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar
  /home/kornineq/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar
  /home/kornineq/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar
  /home/kornineq/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar
  /home/kornineq/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar
  /home/kornineq/.local/share/multimc/libraries/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar
  /home/kornineq/.local/share/multimc/libraries/com/mojang/minecraft/1.20.4/minecraft-1.20.4-client.jar

Native libraries:

Params:
  --username  --version 1.20.4 --gameDir /home/kornineq/.local/share/multimc/instances/1.20.4/.minecraft --assetsDir /home/kornineq/.local/share/multimc/assets --assetIndex 12 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 6980

Using onesix launcher.

[18:26:23] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 171 milliseconds
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[18:26:25] [Render thread/INFO]: [STDERR]: Failed to start Minecraft:
[18:26:25] [Render thread/INFO]: [STDERR]: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
[18:26:25] [Render thread/INFO]: [STDERR]: 	at ab.a(SourceFile:66)
[18:26:25] [Render thread/INFO]: [STDERR]: 	at evi.a(SourceFile:2605)
[18:26:25] [Render thread/INFO]: [STDERR]: 	at evi.a(SourceFile:2580)
[18:26:25] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:233)
[18:26:25] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:26:25] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[18:26:25] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
[18:26:25] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
[18:26:25] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[18:26:25] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[18:26:25] [Render thread/INFO]: [STDERR]: Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.so [in thread "Render thread"]
[18:26:25] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:174)
[18:26:25] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:64)
[18:26:25] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.<clinit>(Library.java:52)
[18:26:25] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
[18:26:25] [Render thread/INFO]: [STDERR]: 	at eoz.<clinit>(SourceFile:8)
[18:26:25] [Render thread/INFO]: [STDERR]: 	at epw.<init>(SourceFile:49)
[18:26:25] [Render thread/INFO]: [STDERR]: 	at eqd.<init>(SourceFile:33)
[18:26:25] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(SourceFile:51)
[18:26:25] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:220)
[18:26:25] [Render thread/INFO]: [STDERR]: 	... 6 more
[18:26:25] [Render thread/INFO]: [STDOUT]: Exiting with -1
Process exited with code 255 (0xff).
Należy pamiętać, że do debugowania problemów zwykle nie wystarczy podać tylko kod wyjścia lub jego opis!
Zawsze przesyłaj cały log, a nie tylko kod wyjścia.

### Steps to reproduce

Arch Linux
Kde

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Zetabite** [comment]
Update your multimc. Also, use java 17
