### ISSUE TITLE
Minecraft 1.20.2+ crashing on launch MacOS 12.7 with Java 22.0.1

### ISSUE THREAD

**Issue by joenfriberg** [MultiMC/Launcher#5390]
### Description of bug

So i've tried launching minecraft but the only version working is 1.20.1. I've updated Java SDK to 22.0.1 and made sure to use the same Java path on both the instance and the launcher. I also allocated 4096 mb of ram to the instance. 

Here is the bugreport. 

Cheers

### Steps to reproduce

MultiMC version: 0.6.12-custom

Minecraft folder is:
/Applications/MultiMC.app/Contents/MacOS/instances/1.20.41/.minecraft

Java path is:
/usr/bin/java

Checking Java version...
Java is version 22.0.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.client.main.Main

Native path:
  /Applications/MultiMC.app/Contents/MacOS/instances/1.20.41/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/ca/weblite/java-objc-bridge/1.1/java-objc-bridge-1.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/authlib/6.0.52/authlib-6.0.52.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/brigadier/1.2.9/brigadier-1.2.9.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-io/commons-io/2.13.0/commons-io-2.13.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/jna-platform/5.13.0/jna-platform-5.13.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-compress/1.22/commons-compress-1.22.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-lang3/3.13.0/commons-lang3-3.13.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/minecraft/1.20.4/minecraft-1.20.4-client.jar

Native libraries:

Params:
  --username  --version MultiMC5 --gameDir /Applications/MultiMC.app/Contents/MacOS/instances/1.20.41/.minecraft --assetsDir /Applications/MultiMC.app/Contents/MacOS/assets --assetIndex 12 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: 1.20.4", -XstartOnFirstThread, -Xms204m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 8966

Using onesix launcher.

[10:50:48] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 261 milliseconds
[10:50:49] [main/WARN]: Unrecognized user type: 
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[10:50:50] [Render thread/INFO]: [STDERR]: Failed to start Minecraft:
[10:50:50] [Render thread/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
[10:50:50] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
[10:50:50] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[10:50:50] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[10:50:50] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[10:50:50] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[10:50:50] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[10:50:50] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
[10:50:50] [Render thread/INFO]: [STDERR]: 	at ab.a(SourceFile:66)
[10:50:50] [Render thread/INFO]: [STDERR]: 	at evi.a(SourceFile:2605)
[10:50:50] [Render thread/INFO]: [STDERR]: 	at evi.a(SourceFile:2580)
[10:50:50] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:233)
[10:50:50] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[10:50:50] [Render thread/INFO]: [STDERR]: 	... 5 more
[10:50:50] [Render thread/INFO]: [STDERR]: Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.dylib [in thread "Render thread"]
[10:50:50] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:174)
[10:50:50] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:64)
[10:50:50] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.Library.<clinit>(Library.java:52)
[10:50:50] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
[10:50:50] [Render thread/INFO]: [STDERR]: 	at eoz.<clinit>(SourceFile:8)
[10:50:50] [Render thread/INFO]: [STDERR]: 	at epw.<init>(SourceFile:49)
[10:50:50] [Render thread/INFO]: [STDERR]: 	at eqd.<init>(SourceFile:33)
[10:50:50] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(SourceFile:51)
[10:50:50] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:220)
[10:50:50] [Render thread/INFO]: [STDERR]: 	... 6 more
[10:50:50] [Render thread/INFO]: [STDOUT]: Exiting with -1
Process exited with code 255.
MultiMC: Log upload triggered at: 17 Apr 2024 10:52:14 +0200

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you aren't using multimc
