### ISSUE TITLE
has been compiled by a more recent version of the Java Runtime (with latest version of Java installed)

### ISSUE THREAD

**Issue by Moltresrider** [MultiMC/Launcher#5401]
### Description of bug

Launching a 1.20.5 instance of Minecraft with the latest April 2024 version of Java always causes crash with the following log message "has been compiled by a more recent version of the Java Runtime"

```MultiMC version: 0.7.0-3857


Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [2620:1ec:46::51, 2620:1ec:bdf::51, 13.107.213.51, 13.107.246.51]

textures.minecraft.net resolves to:
    [2620:1ec:bdf::51, 2620:1ec:46::51, 13.107.213.51, 13.107.246.51]

api.mojang.com resolves to:
    [2620:1ec:46::51, 2620:1ec:bdf::51, 13.107.246.51, 13.107.213.51]


Minecraft folder is:
C:/Standalone EXEs/MultiMC/instances/1.19.3/.minecraft


Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe


Checking Java version...
Java is version 17.0.6, using 64-bit architecture, from Oracle Corporation.


Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Standalone EXEs/MultiMC/instances/1.19.3/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Standalone EXEs/MultiMC/libraries/com/github/oshi/oshi-core/6.4.10/oshi-core-6.4.10.jar
  C:/Standalone EXEs/MultiMC/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  C:/Standalone EXEs/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Standalone EXEs/MultiMC/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  C:/Standalone EXEs/MultiMC/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  C:/Standalone EXEs/MultiMC/libraries/com/mojang/authlib/6.0.54/authlib-6.0.54.jar
  C:/Standalone EXEs/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Standalone EXEs/MultiMC/libraries/com/mojang/brigadier/1.2.9/brigadier-1.2.9.jar
  C:/Standalone EXEs/MultiMC/libraries/com/mojang/datafixerupper/7.0.14/datafixerupper-7.0.14.jar
  C:/Standalone EXEs/MultiMC/libraries/com/mojang/logging/1.2.7/logging-1.2.7.jar
  C:/Standalone EXEs/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Standalone EXEs/MultiMC/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  C:/Standalone EXEs/MultiMC/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  C:/Standalone EXEs/MultiMC/libraries/commons-io/commons-io/2.15.1/commons-io-2.15.1.jar
  C:/Standalone EXEs/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Standalone EXEs/MultiMC/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  C:/Standalone EXEs/MultiMC/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  C:/Standalone EXEs/MultiMC/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  C:/Standalone EXEs/MultiMC/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  C:/Standalone EXEs/MultiMC/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  C:/Standalone EXEs/MultiMC/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  C:/Standalone EXEs/MultiMC/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  C:/Standalone EXEs/MultiMC/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  C:/Standalone EXEs/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  C:/Standalone EXEs/MultiMC/libraries/net/java/dev/jna/jna-platform/5.14.0/jna-platform-5.14.0.jar
  C:/Standalone EXEs/MultiMC/libraries/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar
  C:/Standalone EXEs/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Standalone EXEs/MultiMC/libraries/org/apache/commons/commons-compress/1.26.0/commons-compress-1.26.0.jar
  C:/Standalone EXEs/MultiMC/libraries/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar
  C:/Standalone EXEs/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Standalone EXEs/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  C:/Standalone EXEs/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.22.1/log4j-api-2.22.1.jar
  C:/Standalone EXEs/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.22.1/log4j-core-2.22.1.jar
  C:/Standalone EXEs/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.22.1/log4j-slf4j2-impl-2.22.1.jar
  C:/Standalone EXEs/MultiMC/libraries/org/jcraft/jorbis/0.0.17/jorbis-0.0.17.jar
  C:/Standalone EXEs/MultiMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3-natives-windows.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3-natives-windows-arm64.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3-natives-windows-x86.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3-natives-windows.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3-natives-windows-arm64.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3-natives-windows-x86.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3-natives-windows.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3-natives-windows-arm64.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3-natives-windows-x86.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3-natives-windows.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3-natives-windows-arm64.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3-natives-windows-x86.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3-natives-windows.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3-natives-windows-arm64.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3-natives-windows-x86.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3-natives-windows.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3-natives-windows-arm64.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3-natives-windows-x86.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3-natives-windows.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3-natives-windows-arm64.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3-natives-windows-x86.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3-natives-windows.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3-natives-windows-arm64.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3-natives-windows-x86.jar
  C:/Standalone EXEs/MultiMC/libraries/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar
  C:/Standalone EXEs/MultiMC/libraries/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar
  C:/Standalone EXEs/MultiMC/libraries/com/mojang/minecraft/1.20.5/minecraft-1.20.5-client.jar

Native libraries:

Params:
  --username MoltresRider --version 1.20.5 --gameDir C:/Standalone EXEs/MultiMC/instances/1.19.3/.minecraft --assetsDir C:/Standalone EXEs/MultiMC/assets --assetIndex 16 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType msa --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 14508


Using onesix launcher.

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:217)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Process exited with exit code 1 (0x1).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 28 Apr 2024 12:11:33 -0400```

### Steps to reproduce

Update my instance to 1.20.5
install the library files
meet crash
Get error 
```Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0```
Download and install the latest version of Java: released April 16, 2024.
launch instance again
meet same crash
try again
repeat indefinitely with same crash

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
You're using the wrong Java version to launch Minecraft.


https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by Moltresrider** [comment]
I just updated to the one here: https://www.java.com/en/download/windows_offline.jsp

This is the latest and I meet the error

**Comment by FeedTheChunk** [comment]
You're still launching the game with version 17. You need to goto setting and select version 21

Checking Java version...
Java is version 17.0.6, using 64-bit architecture, from Oracle Corporation.

**Comment by Moltresrider** [comment]
There is no option to select what version of java in settings, there is only a checkmark "Java installation" but no other options.

**Comment by phit** [comment]
click auto detect

**Comment by FeedTheChunk** [comment]
Edit the instance and go to setting.  There's a Java section there.  Read the wiki it'll hold your hand through the process

**Comment by Moltresrider** [comment]
But 21 is not listed despite installing the latest version

**Comment by Moltresrider** [comment]
I also tried installing the one at the link you gave. Still no 21 option
