### ISSUE TITLE
1.16.5 Minecraft Controllable Mod Issues

### ISSUE THREAD

**Issue by DMagV** [MultiMC/Launcher#5409]
### Operating System

Windows

### Description of bug

I'm trying play Minecraft in split screen mode via Nucleus and MultiMC. I get Minecraft to run without any mods but I need the Controllable mod (added along with OptiFine). Tried all kinds of versions but it never works. Java is up to date. Any suggestions? See for the log below:

### Steps to reproduce

MultiMC version: 0.7.0-3857

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.38, 13.107.213.38, 2620:1ec:46::38, 2620:1ec:bdf::38]

textures.minecraft.net resolves to:
    [13.107.246.38, 13.107.213.38, 2620:1ec:46::38, 2620:1ec:bdf::38]

api.mojang.com resolves to:
    [13.107.246.38, 13.107.213.38, 2620:1ec:46::38, 2620:1ec:bdf::38]

Minecraft folder is:
C:/MultiMC/instances/1.16.5/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/java8path/javaw.exe

Checking Java version...
Java is version 1.8.0_411, using 32-bit architecture, from Oracle Corporation.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/MultiMC/instances/1.16.5/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/MultiMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  C:/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc5/ForgeWrapper-mmc5.jar
  C:/MultiMC/libraries/net/minecraftforge/forge/1.16.5-36.2.0/forge-1.16.5-36.2.0-launcher.jar
  C:/MultiMC/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  C:/MultiMC/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  C:/MultiMC/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  C:/MultiMC/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  C:/MultiMC/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  C:/MultiMC/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar
  C:/MultiMC/libraries/cpw/mods/grossjava9hacks/1.3.3/grossjava9hacks-1.3.3.jar
  C:/MultiMC/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  C:/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/MultiMC/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  C:/MultiMC/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  C:/MultiMC/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar
  C:/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/MultiMC/libraries/com/electronwill/night-config/core/3.6.3/core-3.6.3.jar
  C:/MultiMC/libraries/com/electronwill/night-config/toml/3.6.3/toml-3.6.3.jar
  C:/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  C:/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  C:/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/MultiMC/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar
  C:/MultiMC/libraries/net/minecraftforge/nashorn-core-compat/15.1.1.1/nashorn-core-compat-15.1.1.1.jar
  C:/MultiMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  C:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] controllable-0.16.5-1.16.5.jar
  [✔️] OptiFine_1.16.5_HD_U_G8.jar

Params:
  --username DMagV --version 1.16.5 --gameDir C:/MultiMC/instances/1.16.5/.minecraft --assetsDir C:/MultiMC/assets --assetIndex 1.16 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType msa --versionType release --launchTarget fmlclient --fml.forgeVersion 36.2.0 --fml.mcVersion 1.16.5 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20210115.111550

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 15932

Using onesix launcher.

Checking: MC_SLIM
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: PATCHED
Checking: MC_SRG
2024-05-03 20:20:57,615 main WARN Advanced terminal features are not available in this environment
[20:20:57] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, DMagV, --version, 1.16.5, --gameDir, C:/MultiMC/instances/1.16.5/.minecraft, --assetsDir, C:/MultiMC/assets, --assetIndex, 1.16, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.0, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --width, 854, --height, 480]
[20:20:57] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_411 by Oracle Corporation
[20:20:57] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[20:20:57] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file: C:\MultiMC\instances\1.16.5\.minecraft\mods\OptiFine_1.16.5_HD_U_G8.jar
[20:20:57] [main/INFO] [op.OptiFineTransformer/]: Target.PRE_CLASS is available
[20:20:58] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[20:20:58] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/MultiMC/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[20:20:58] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[20:20:59] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.transformers
[20:20:59] [main/INFO] [op.OptiFineTransformer/]: Targets: 311
[20:20:59] [main/INFO] [op.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
[20:20:59] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.16.5, --gameDir, C:\MultiMC\instances\1.16.5\.minecraft, --assetsDir, C:\MultiMC\assets, --uuid, <PROFILE ID>, --username, DMagV, --assetIndex, 1.16, --accessToken, ????????, --userType, msa, --versionType, release, --width, 854, --height, 480]
[20:20:59] [main/ERROR] [mixin/]: Error loading companion plugin class [com.mrcrayfish.controllable.mixin.ControllableMixinPlugin] for mixin config [controllable.mixins.json]. The plugin may be out of date: NoSuchMethodError:sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_411] {}
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_411] {}
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_411] {}
	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:66) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.PluginHandle.<init>(PluginHandle.java:96) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:596) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:475) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:437) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.0.9.jar:8.0.9+86+master.3cf110c] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_411] {}
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_411] {}
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_411] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.0-launcher.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_411] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_411] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_411] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_411] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-mmc5.jar:mmc5] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_411] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_411] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_411] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_411] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
[20:21:00] [main/WARN] [mixin/]: Error loading class: mezz/jei/input/MouseUtil (java.lang.ClassNotFoundException: null)
[20:21:00] [main/WARN] [mixin/]: Error loading class: mezz/jei/gui/overlay/IngredientListOverlay (java.lang.ClassNotFoundException: null)
[20:21:00] [main/WARN] [mixin/]: Error loading class: mezz/jei/gui/overlay/IngredientGridWithNavigation (java.lang.ClassNotFoundException: null)
[20:21:00] [main/WARN] [mixin/]: Error loading class: mezz/jei/gui/overlay/IngredientGrid (java.lang.ClassNotFoundException: null)
[20:21:00] [main/WARN] [mixin/]: Error loading class: mezz/jei/gui/PageNavigation (java.lang.ClassNotFoundException: null)
[20:21:00] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:246]: Failed to start Minecraft:
[20:21:00] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:278]: java.lang.reflect.InvocationTargetException
[20:21:00] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:21:00] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:21:00] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:21:00] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20:21:00] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
[20:21:00] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:21:00] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:21:00] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:21:00] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20:21:00] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
[20:21:00] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
[20:21:00] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[20:21:00] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[20:21:00] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[20:21:00] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[20:21:00] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[20:21:00] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[20:21:00] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[20:21:00] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[20:21:00] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	... 13 more
[20:21:00] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.reflect.InvocationTargetException
[20:21:00] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:21:00] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:21:00] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:21:00] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20:21:00] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[20:21:00] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[20:21:00] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 17 more
[20:21:00] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
[20:21:00] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[20:21:00] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[20:21:00] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[20:21:00] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[20:21:00] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[20:21:00] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.math.MathHelper.<clinit>(MathHelper.java:20)
[20:21:00] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.Util.func_240979_a_(Util.java:109)
[20:21:00] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.Util.<clinit>(Util.java:65)
[20:21:00] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.client.main.Main.main(Main.java:63)
[20:21:00] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 23 more
[20:21:00] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
MultiMC: Log upload triggered at: 03 May 2024 20:21:16 -0500

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
