### ISSUE TITLE
whenever I try to launch mods like "farplane2" in multimc 1.12.2, it just straight up crashes. I'm think I am doing everything right, but it is still not working. Can someone help me?

### ISSUE THREAD

**Issue by gamermkrasap** [MultiMC/Launcher#5410]
### Operating System

Windows

### Description of bug

Whenever I launch into the game with farplane2 on forge installed, it shows this log error Mods:
  [❌] C.M.A_Transport_Pack+_v.2.5-1.12.2.jar.disabled (disabled)
  [✔️] fp2-0.0.1.612-1.12.2.jar
  [✔️] GoldenAerotransport+3.3.1+hot+fix.jar
  [✔️] Immersive Vehicles-1.12.2-22.10.0.jar
  [✔️] UNU+Parts+Pack+[MTS]+1.12.2-22.10.0-6.2.1.jar

Params:
  --username Thatguyplayer_YT --version 1.12.2 --gameDir C:/Users/jangi/Downloads/mmc-develop-win32/MultiMC/instances/1.12.2/.minecraft --assetsDir C:/Users/jangi/Downloads/mmc-develop-win32/MultiMC/assets --assetIndex 1.12 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType msa --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1664m, -Xmx3200m, -Duser.language=en]

Minecraft process ID: 61300

Using onesix launcher.

[21:16:29] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:16:29] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:16:29] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[21:16:29] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2859 for Minecraft 1.12.2 loading
[21:16:29] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_392-392, running on Windows 11:amd64:10.0, installed at C:\Program Files\OpenLogic\jdk-8.0.392.08-hotspot\jre
[21:16:29] [main/INFO] [FML]: Searching C:\Users\jangi\Downloads\mmc-develop-win32\MultiMC\instances\1.12.2\.minecraft\mods for mods
[21:16:29] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from fp2-0.0.1.612-1.12.2.jar
[21:16:29] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:16:29] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[21:16:29] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_392-392]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_392-392]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_392-392]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_392-392]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_392-392]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_392-392]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_392-392]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_392-392]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_392-392]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_392-392]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_392-392]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_392-392]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[21:16:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:246]: Failed to start Minecraft:
[21:16:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:278]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[21:16:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[21:16:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[21:16:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at java.lang.Runtime.exit(Runtime.java:101)
[21:16:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at java.lang.System.exit(System.java:987)
[21:16:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[21:16:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:16:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:16:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:16:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:16:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:16:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
[21:16:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
[21:16:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[21:16:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:278]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[21:16:29] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[21:16:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[21:16:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[21:16:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[21:16:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:101)
[21:16:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:987)
[21:16:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
Process exited with exit code 1 (0x1).

### Steps to reproduce

I put the file "farplane2" 
I had forge already installed, ver: 14.23.5.2859
Launch into the game with all my other mods with aircraft stuff
then it tries to launch, but it shows the log above

### Suspected cause

no idea

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
Try updating Immersive Vehicles.  That version is dated.

https://github.com/SpongePowered/Mixin/issues/211

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
