### ISSUE TITLE
I can't play the mod

### ISSUE THREAD

**Issue by miketangoo14** [MultiMC/Launcher#5428]
### Operating System
Windows 11
MultiMC Version : 0.7.0-3857 on win32

### Description of bug

So, I'm donwload the "Another RPG Pack [FABRIC] 4.0.6" mod. When i want to run it, it can't. I can't play the mod. I check the log but i can't understand it. 

The log says : 
Failed to find Minecraft main class:
java.lang.ClassNotFoundException: net.fabricmc.loader.impl.launch.knot.KnotClient
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:217)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
MultiMC: Log upload triggered at: 28 May 2024 13:33:59 +0700

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Wolf68k** [comment]
That's a mod pack not a mod. Since it's listed on Modrinth you can easily download it in MMC->Add Instance->Modrinth and search for Another RPG Pack and it should be listed.

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
