### ISSUE TITLE
Unable to open version 1.18.2

### ISSUE THREAD

**Issue by liberteryen** [MultiMC/Launcher#5439]
### Operating System

Fedora GNU/Linux

### Description of bug

Java 17 version published by more than one provider (azul zulu, openjdk, adoptium) works in official minecraft launcher but does not work in multimc.

### Steps to reproduce

Add support for 1.18.2.

### Suspected cause

```bash
MultiMC version: 0.7.0-3860


Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.45, 2620:1ec:bdf::45]

textures.minecraft.net resolves to:
    [13.107.246.44, 2620:1ec:bdf::44]

api.mojang.com resolves to:
    [13.107.246.60, 2620:1ec:bdf::60]


Minecraft folder is:
/home/h/İndirilenler/MultiMC/instances/1.18.2/.minecraft


Java path is:
/usr/lib/jvm/java-21-openjdk-21.0.3.0.9-1.fc40.x86_64/bin/java


Checking Java version...
Java is version 21.0.3, using 64-bit architecture, from Red Hat, Inc..


12th Gen Intel(R) Core(TM) i7-12650H
Intel Corporation Alder Lake-P GT1 [UHD Graphics] (rev 0c)

DeviceName: Onboard - Video

Subsystem: QUANTA Computer Inc Device 1384

NVIDIA Corporation GA107M [GeForce RTX 3050 Mobile] (rev a1)

Subsystem: QUANTA Computer Inc Device 1386

Kernel driver in use: nvidia

OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.0.8

Main Class:
  net.minecraft.client.main.Main

Native path:
  /home/h/İndirilenler/MultiMC/instances/1.18.2/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  /home/h/İndirilenler/MultiMC/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  /home/h/İndirilenler/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /home/h/İndirilenler/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /home/h/İndirilenler/MultiMC/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  /home/h/İndirilenler/MultiMC/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  /home/h/İndirilenler/MultiMC/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  /home/h/İndirilenler/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /home/h/İndirilenler/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.0/log4j-slf4j18-impl-2.17.0.jar
  /home/h/İndirilenler/MultiMC/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  /home/h/İndirilenler/MultiMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  /home/h/İndirilenler/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/h/İndirilenler/MultiMC/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
  /home/h/İndirilenler/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/h/İndirilenler/MultiMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  /home/h/İndirilenler/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /home/h/İndirilenler/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /home/h/İndirilenler/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /home/h/İndirilenler/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  /home/h/İndirilenler/MultiMC/libraries/com/mojang/datafixerupper/4.1.27/datafixerupper-4.1.27.jar
  /home/h/İndirilenler/MultiMC/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  /home/h/İndirilenler/MultiMC/libraries/com/mojang/authlib/3.3.39/authlib-3.3.39.jar
  /home/h/İndirilenler/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /home/h/İndirilenler/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/h/İndirilenler/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/h/İndirilenler/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  /home/h/İndirilenler/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  /home/h/İndirilenler/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.17.0/log4j-api-2.17.0.jar
  /home/h/İndirilenler/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.17.0/log4j-core-2.17.0.jar
  /home/h/İndirilenler/MultiMC/libraries/com/mojang/text2speech/1.12.4/text2speech-1.12.4.jar
  /home/h/İndirilenler/MultiMC/libraries/com/mojang/minecraft/1.18.2/minecraft-1.18.2-client.jar

Native libraries:
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-linux.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-linux.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-linux.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-linux.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-linux.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-linux.jar
  /home/h/İndirilenler/MultiMC/libraries/com/mojang/text2speech/1.12.4/text2speech-1.12.4-natives-linux.jar

Params:
  --username SUBMITTER_19 --version 1.18.2 --gameDir /home/h/İndirilenler/MultiMC/instances/1.18.2/.minecraft --assetsDir /home/h/İndirilenler/MultiMC/assets --assetIndex 1.18 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType msa --versionType release

Window size: 854 x 480

Java Arguments:
[-Xms20000m, -Xmx20000m, -Duser.language=en]


Minecraft process ID: 9490


Using onesix launcher.

[17:56:23] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:56:24] [Render thread/INFO]: Setting user: SUBMITTER_19
---- Minecraft Crash Report ----
// Sorry :(

Time: 6/7/24, 5:56 PM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at dyv.<init>(SourceFile:165)
	at dyr.<init>(SourceFile:454)
	at net.minecraft.client.main.Main.main(SourceFile:197)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Failed to dynamically load library: /home/h/İndirilenler/MultiMC/instances/1.18.2/natives/libglfw.so(error = /home/h/0ndirilenler/MultiMC/instances/1.18.2/natives/libglfw.so: paylaÅÄ±mlÄ± nesne dosyasÄ± aÃ§Ä±lamÄ±yor: BÃ¶yle bir dosya ya da dizin yok)
	at dsh.<clinit>(SourceFile:46)
	... 9 more
Caused by: java.lang.UnsatisfiedLinkError: Failed to dynamically load library: /home/h/İndirilenler/MultiMC/instances/1.18.2/natives/libglfw.so(error = /home/h/0ndirilenler/MultiMC/instances/1.18.2/natives/libglfw.so: paylaÅÄ±mlÄ± nesne dosyasÄ± aÃ§Ä±lamÄ±yor: BÃ¶yle bir dosya ya da dizin yok)
	at org.lwjgl.system.linux.LinuxLibrary.loadLibrary(LinuxLibrary.java:32)
	at org.lwjgl.system.linux.LinuxLibrary.<init>(LinuxLibrary.java:19)
	at org.lwjgl.system.APIUtil.apiCreateLibrary(APIUtil.java:123)
	at org.lwjgl.system.Library.loadNative(Library.java:335)
	at org.lwjgl.system.Library.loadNative(Library.java:281)
	at org.lwjgl.system.Library.loadNative(Library.java:205)
	at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:674)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/java.lang.invoke.DirectMethodHandle.checkInitialized(DirectMethodHandle.java:383)
	at java.base/java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:371)
	at java.base/java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:393)
	at dsh.<clinit>(SourceFile:43)
	... 9 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dyv.<init>(SourceFile:165)
	at dyr.<init>(SourceFile:454)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:197)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 6.8.11-300.fc40.x86_64
	Java Version: 21.0.3, Red Hat, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Red Hat, Inc.
	Memory: 18973541568 bytes (18094 MiB) / 20971520000 bytes (20000 MiB) up to 20971520000 bytes (20000 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i7-12650H
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 16
	Graphics card #0 name: Alder Lake-P GT1 [UHD Graphics]
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x46a3
	Graphics card #0 versionInfo: unknown
	Graphics card #1 name: GA107M [GeForce RTX 3050 Mobile]
	Graphics card #1 vendor: NVIDIA Corporation (0x10de)
	Graphics card #1 VRAM (MB): 4128.00
	Graphics card #1 deviceId: 0x25a2
	Graphics card #1 versionInfo: unknown
	Virtual memory max (MB): 24106.01
	Virtual memory used (MB): 16119.14
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms20000m -Xmx20000m
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /home/h/İndirilenler/MultiMC/instances/1.18.2/.minecraft/crash-reports/crash-2024-06-07_17.56.24-client.txt
İşlem, 255 kodu ile sonlandı (0xff).
Lütfen ne çıkış kodunun ne de açıklamasının hataları tanımlamada genellikle yeterli olmadığını not edin!
Her zaman bütün günlük kayıtları yükle, sadece çıkış kodunu değil.
[translation:The transaction ended with code 255 (0xff).
Please note that neither the exit code nor its description is often sufficient to identify errors!
Always upload all logs, not just the exit code.]

File : /home/h/İndirilenler/MultiMC/instances/1.18.2/.minecraft/crash-reports/crash-2024-06-07_17.56.24-client.txt

---- Minecraft Crash Report ----
// Why did you do that?

Time: 6/7/24, 5:56 PM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at dyv.<init>(SourceFile:165)
	at dyr.<init>(SourceFile:454)
	at net.minecraft.client.main.Main.main(SourceFile:197)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Failed to dynamically load library: /home/h/İndirilenler/MultiMC/instances/1.18.2/natives/libglfw.so(error = /home/h/0ndirilenler/MultiMC/instances/1.18.2/natives/libglfw.so: paylaÅ%    
```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
Wrong Java version.  Go to Wiki above and read using the right Java.  Id post a link but on my phone atm

**Comment by FeedTheChunk** [comment]
Here's the link: https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by liberteryen** [comment]
Already im using version 17? Its working with official launcher

**Comment by FeedTheChunk** [comment]
No your not.  Read the log, read the Wiki.   you're using v 21.

**Comment by FeedTheChunk** [comment]
Java path is:
/usr/lib/jvm/java-21-openjdk-21.0.3.0.9-1.fc40.x86_64/bin/java

**Comment by liberteryen** [comment]
Version 17 is active in MultiMC settings. Same with profile setting. Why would it still use version 21?

**Comment by FeedTheChunk** [comment]
Because you don't have the instance setting set correctly. Read the wiki it explains how to properly configure the correct Java version.

**Comment by liberteryen** [comment]
![resim](https://github.com/MultiMC/Launcher/assets/84645312/0322ec93-ec9d-4af3-bdbb-13267689aa40)
İs it wrong java path?

**Comment by FeedTheChunk** [comment]
Are you certain that you uploaded the correct log?  The log you uploaded clearly shows that your running Version 21.

`Java path is:
/usr/lib/jvm/java-21-openjdk-21.0.3.0.9-1.fc40.x86_64/bin/java

Checking Java version...
Java is version 21.0.3, using 64-bit architecture, from Red Hat, Inc..
`

**Comment by liberteryen** [comment]
```bash
MultiMC version: 0.7.0-3860


Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.44, 2620:1ec:bdf::44]

textures.minecraft.net resolves to:
    [13.107.246.44, 2620:1ec:bdf::44]

api.mojang.com resolves to:
    [13.107.246.40, 2620:1ec:bdf::40]


Minecraft folder is:
/home/h/İndirilenler/MultiMC/instances/1.18.2/.minecraft


Java path is:
/usr/lib/jvm/java-17-zulu-openjdk-jre/bin/java


Checking Java version...
Java is version 17.0.11, using 64-bit architecture, from Azul Systems, Inc..


12th Gen Intel(R) Core(TM) i7-12650H
Intel Corporation Alder Lake-P GT1 [UHD Graphics] (rev 0c)

DeviceName: Onboard - Video

Subsystem: QUANTA Computer Inc Device 1384

NVIDIA Corporation GA107M [GeForce RTX 3050 Mobile] (rev a1)

Subsystem: QUANTA Computer Inc Device 1386

Kernel driver in use: nvidia

OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.0.8

Main Class:
  net.minecraft.client.main.Main

Native path:
  /home/h/İndirilenler/MultiMC/instances/1.18.2/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  /home/h/İndirilenler/MultiMC/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  /home/h/İndirilenler/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /home/h/İndirilenler/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /home/h/İndirilenler/MultiMC/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  /home/h/İndirilenler/MultiMC/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  /home/h/İndirilenler/MultiMC/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  /home/h/İndirilenler/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /home/h/İndirilenler/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.0/log4j-slf4j18-impl-2.17.0.jar
  /home/h/İndirilenler/MultiMC/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  /home/h/İndirilenler/MultiMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  /home/h/İndirilenler/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/h/İndirilenler/MultiMC/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
  /home/h/İndirilenler/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/h/İndirilenler/MultiMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  /home/h/İndirilenler/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /home/h/İndirilenler/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /home/h/İndirilenler/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /home/h/İndirilenler/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  /home/h/İndirilenler/MultiMC/libraries/com/mojang/datafixerupper/4.1.27/datafixerupper-4.1.27.jar
  /home/h/İndirilenler/MultiMC/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  /home/h/İndirilenler/MultiMC/libraries/com/mojang/authlib/3.3.39/authlib-3.3.39.jar
  /home/h/İndirilenler/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /home/h/İndirilenler/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/h/İndirilenler/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/h/İndirilenler/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  /home/h/İndirilenler/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  /home/h/İndirilenler/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.17.0/log4j-api-2.17.0.jar
  /home/h/İndirilenler/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.17.0/log4j-core-2.17.0.jar
  /home/h/İndirilenler/MultiMC/libraries/com/mojang/text2speech/1.12.4/text2speech-1.12.4.jar
  /home/h/İndirilenler/MultiMC/libraries/com/mojang/minecraft/1.18.2/minecraft-1.18.2-client.jar

Native libraries:
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-linux.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-linux.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-linux.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-linux.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-linux.jar
  /home/h/İndirilenler/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-linux.jar
  /home/h/İndirilenler/MultiMC/libraries/com/mojang/text2speech/1.12.4/text2speech-1.12.4-natives-linux.jar

Params:
  --username SUBMITTER_19 --version 1.18.2 --gameDir /home/h/İndirilenler/MultiMC/instances/1.18.2/.minecraft --assetsDir /home/h/İndirilenler/MultiMC/assets --assetIndex 1.18 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType msa --versionType release

Window size: 854 x 480

Java Arguments:
[-Xms20000m, -Xmx20000m, -Duser.language=en]


Minecraft process ID: 6676


Using onesix launcher.

[21:40:39] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[21:40:39] [Render thread/INFO]: Setting user: SUBMITTER_19
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 6/7/24, 9:40 PM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at dyv.<init>(SourceFile:165)
	at dyr.<init>(SourceFile:454)
	at net.minecraft.client.main.Main.main(SourceFile:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Failed to dynamically load library: /home/h/İndirilenler/MultiMC/instances/1.18.2/natives/libglfw.so(error = /home/h/0ndirilenler/MultiMC/instances/1.18.2/natives/libglfw.so: paylaÅÄ±mlÄ± nesne dosyasÄ± aÃ§Ä±lamÄ±yor: BÃ¶yle bir dosya ya da dizin yok)
	at dsh.<clinit>(SourceFile:46)
	... 11 more
Caused by: java.lang.UnsatisfiedLinkError: Failed to dynamically load library: /home/h/İndirilenler/MultiMC/instances/1.18.2/natives/libglfw.so(error = /home/h/0ndirilenler/MultiMC/instances/1.18.2/natives/libglfw.so: paylaÅÄ±mlÄ± nesne dosyasÄ± aÃ§Ä±lamÄ±yor: BÃ¶yle bir dosya ya da dizin yok)
	at org.lwjgl.system.linux.LinuxLibrary.loadLibrary(LinuxLibrary.java:32)
	at org.lwjgl.system.linux.LinuxLibrary.<init>(LinuxLibrary.java:19)
	at org.lwjgl.system.APIUtil.apiCreateLibrary(APIUtil.java:123)
	at org.lwjgl.system.Library.loadNative(Library.java:335)
	at org.lwjgl.system.Library.loadNative(Library.java:281)
	at org.lwjgl.system.Library.loadNative(Library.java:205)
	at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:674)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unknown Source)
	at java.base/java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(Unknown Source)
	at java.base/java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(Unknown Source)
	at java.base/java.lang.ClassValue.getFromHashMap(Unknown Source)
	at java.base/java.lang.ClassValue.getFromBackup(Unknown Source)
	at java.base/java.lang.ClassValue.get(Unknown Source)
	at java.base/java.lang.invoke.DirectMethodHandle.checkInitialized(Unknown Source)
	at java.base/java.lang.invoke.DirectMethodHandle.ensureInitialized(Unknown Source)
	at java.base/java.lang.invoke.DirectMethodHandle.ensureInitialized(Unknown Source)
	at dsh.<clinit>(SourceFile:43)
	... 11 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dyv.<init>(SourceFile:165)
	at dyr.<init>(SourceFile:454)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 6.8.11-300.fc40.x86_64
	Java Version: 17.0.11, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 14117805704 bytes (13463 MiB) / 20971520000 bytes (20000 MiB) up to 20971520000 bytes (20000 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i7-12650H
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 16
	Graphics card #0 name: Alder Lake-P GT1 [UHD Graphics]
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x46a3
	Graphics card #0 versionInfo: unknown
	Graphics card #1 name: GA107M [GeForce RTX 3050 Mobile]
	Graphics card #1 vendor: NVIDIA Corporation (0x10de)
	Graphics card #1 VRAM (MB): 4128.00
	Graphics card #1 deviceId: 0x25a2
	Graphics card #1 versionInfo: unknown
	Virtual memory max (MB): 24106.00
	Virtual memory used (MB): 11731.43
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms20000m -Xmx20000m
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /home/h/İndirilenler/MultiMC/instances/1.18.2/.minecraft/crash-reports/crash-2024-06-07_21.40.39-client.txt
İşlem, 255 kodu ile sonlandı (0xff).
Lütfen ne çıkış kodunun ne de açıklamasının hataları tanımlamada genellikle yeterli olmadığını not edin!
Her zaman bütün günlük kayıtları yükle, sadece çıkış kodunu değil.```

When I restart MulTiMC, I can actually change the java path. But it still gives an error. With OpenJDK and with azul zulu in the log.

**Comment by liberteryen** [comment]
When I restart MulTiMC, I can actually change the java path. But it still gives an error. With OpenJDK and with azul zulu in the log.

**Comment by FeedTheChunk** [comment]
Can you select a non zulu version of Java?  I'm not familiar with the version of java.  I use the open java installed from apt.  Your screenshot shows that you have a non Zulu version of java installed.  I would try and use that one.  At this point I've done all that I can do.  You'll have to wait on feedback from the devs unless you can get it running.  But it doesn't look an issue with MMc.  It sure looks like something to do with Java.
