### ISSUE TITLE
Won't launch any version above 1.20.1

### ISSUE THREAD

**Issue by SaltyLemonado** [MultiMC/Launcher#5442]
### Operating System

Windows

### Description of bug

 Basically it wont launch any minecraft version above 1.20.1. When i tried to launch, it gives me this error:

```Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
at org.multimc.EntryPoint.listen(EntryPoint.java:143)
at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: 
at java.base/java.util.UUID.fromString1(UUID.java:286)
at java.base/java.util.UUID.fromString(UUID.java:264)
at com.mojang.util.UndashedUuid.fromStringLenient(UndashedUuid.java:14)
at net.minecraft.client.main.Main.main(SourceFile:151)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
... 5 more
Exiting with -1
Process exited with code -1.```



### Steps to reproduce

-     When i tried to launch into any version below 1.20.1, it launches without any error
-     Im currently using Java Zulu 22.0.1 64-bits (Azul Systems)
-    I am using no mods or shaders whatsoever. Tried to create a new instance, but no luck
-     Tried another version of Java for the same OS and the same architecture, it just returns with version errors
-     Something funky happens when i change versions into Edit Instance: When i select any versions equal or below 1.20.1, a ticked box shows up spelling "LWJGL 3" above the version. This box is absent when the version selected is above 1.20.1.

![Captura de tela 2024-06-11 234259](https://github.com/MultiMC/Launcher/assets/50812143/d8694e02-88cb-478c-b0bf-62e287107dca)
![Captura de tela 2024-06-11 234349](https://github.com/MultiMC/Launcher/assets/50812143/a6166351-c52d-4a04-b34c-c86a1fc23138)
![Captura de tela 2024-06-11 234406](https://github.com/MultiMC/Launcher/assets/50812143/d7978910-b7ad-4281-bd7a-20791420d74b)


### Suspected cause

I have little expertise with troubleshooting this issue, but i have a hunch that might me something related to the Libraries and whatever LWJGL is. 

Sorry if its a simple issue. Tried to talk via Discord but the link is dead

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you arent using multimc
