### ISSUE TITLE
Direwolf20 1.7.10 Process exited with code

### ISSUE THREAD

**Issue by Bitware41** [MultiMC/Launcher#5448]
### Operating System

Windows

### Description of bug

Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:452)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

### Steps to reproduce

[crash-2024-06-23_16.28.02-client.txt](https://github.com/user-attachments/files/15944808/crash-2024-06-23_16.28.02-client.txt)
[DxDiag.txt](https://github.com/user-attachments/files/15944812/DxDiag.txt)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
configure your graphics card to be used with the game https://i.imgur.com/TH7lPhr.png

**Comment by Bitware41** [comment]
it didn't work. ı can't find java in there

**Comment by phit** [comment]
then use the browse button to select it manually

**Comment by Bitware41** [comment]
ı cant open any minecraft version vanilla too
