### ISSUE TITLE
Launcher didn't even start the modpack

### ISSUE THREAD

**Issue by GuilhermeCAT05** [MultiMC/Launcher#5472]
### Operating System

Windows

### Description of bug

The modpack "FTB Golem Factory" was supposed to start, but it didn't. It gave me a Log:

MultiMC version: 0.7.0-3863

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [2620:1ec:bdf::33, 13.107.246.33]

textures.minecraft.net resolves to:
    [2620:1ec:bdf::33, 13.107.246.33]

api.mojang.com resolves to:
    [2620:1ec:bdf::33, 13.107.246.33]

Minecraft folder is:
C:/Users/User/Desktop/Gui/MultiMC/instances/Hardcore Testing Mode- Golem Factory/.minecraft

Java path is:
C:/Program Files/Java/jre-1.8/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_401, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/User/Desktop/Gui/MultiMC/instances/Hardcore Testing Mode- Golem Factory/natives

Libraries:
  C:/Users/User/Desktop/Gui/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/argo/argo/2.25_fixed/argo-2.25_fixed.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/com/google/guava/guava/14.0/guava-14.0.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/com/google/code/gson/gson/2.2.2/gson-2.2.2.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/net/minecraftforge/forge/1.6.4-9.11.1.965/forge-1.6.4-9.11.1.965-universal.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/net/minecraft/launchwrapper/1.8/launchwrapper-1.8.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/org/ow2/asm/asm-all/4.1/asm-all-4.1.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/org/scala-lang/scala-library/2.10.2/scala-library-2.10.2.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/org/scala-lang/scala-compiler/2.10.2/scala-compiler-2.10.2.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/com/mojang/minecraft/1.6.4/minecraft-1.6.4-client.jar

Native libraries:
  C:/Users/User/Desktop/Gui/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/User/Desktop/Gui/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Mods:
  [📁] 1.6.4 (folder)
  [✔️] CodeChickenCore-1.6.4-0.9.0.9-universal.jar
  [✔️] CoFHCore-2.0.0.5.jar
  [✔️] extrautils-1.0.3c.zip
  [✔️] HQM-The Journey (4.0.6).jar
  [✔️] Lockdown-universal-1.6.4-1.0.0.0.jar
  [✔️] NotEnoughItems-1.6.4-1.6.1.9-universal.jar
  [✔️] Thaumcraft4.1.0g.zip
  [✔️] ThermalExpansion-3.0.0.7.jar

Params:
  --username UTK110205 --session token:<TOKEN DE ACESSO>:<ID DO PERFIL> --version 1.6.4 --gameDir C:/Users/User/Desktop/Gui/MultiMC/instances/Hardcore Testing Mode- Golem Factory/.minecraft --assetsDir C:/Users/User/Desktop/Gui/MultiMC/assets/virtual/legacy --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 29704

Using onesix launcher.

Jul 18, 2024 6:59:23 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
Jul 18, 2024 6:59:23 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
Jul 18, 2024 6:59:23 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
2024-07-18 18:59:23 [INFO] [ForgeModLoader] Forge Mod Loader version 6.4.49.965 for Minecraft 1.6.4 loading
2024-07-18 18:59:23 [INFO] [ForgeModLoader] Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_401, running on Windows 11:amd64:10.0, installed at C:\Program Files\Java\jre-1.8
2024-07-18 18:59:23 [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2024-07-18 18:59:23 [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2024-07-18 18:59:23 [WARNING] [ForgeModLoader] The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2024-07-18 18:59:23 [WARNING] [ForgeModLoader] The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2024-07-18 18:59:23 [INFO] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
2024-07-18 18:59:23 [INFO] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
2024-07-18 18:59:23 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
2024-07-18 18:59:23 [SEVERE] [ForgeModLoader] Unable to launch
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.remove(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

### Steps to reproduce

Install the mod in the Third Party tab using "capitalism" as the code.
Next, you try to enter the modpack.

### Suspected cause

Some mods may don't be compatible with others

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
your java version is too new for 1.6.4, you can find an older version that should work on this wiki page https://github.com/MultiMC/Launcher/wiki/Unsupported-Intel-GPUs
