### ISSUE TITLE
Game crashes when trying to join MCC Island

### ISSUE THREAD

**Issue by ADPlayz19** [MultiMC/Launcher#5483]
### Description of bug

When I try to join MCC Island (server) the game automatically crashes saying the resource pack could not be downloaded. When i removed all of the resource packs and mods (disabled). It still didn't work but it didn't crash. I tried on the normal Minecraft Launcher in 1.21 and it worked perfectly. This is weird since it used to work in 1.20.6 but no longer works.

Crash log:
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-08-04 16:36:40
Description: Encountered exception while building chunk meshes

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_8532()" because "client.field_1687" is null
	at com.modrinth.methane.client.BrightnessUtil.calculateBrightnessScale(BrightnessUtil.java:27)
	at net.minecraft.class_638.handler$bhm001$methane$MethaneSetCustomLightLevel(class_638.java:2103)
	at net.minecraft.class_638.method_24852(class_638.java)
	at me.jellysquid.mods.sodium.client.world.WorldSlice.method_24852(WorldSlice.java:254)
	at me.jellysquid.mods.sodium.client.model.light.smooth.SmoothLightPipeline.applySidedBrightness(SmoothLightPipeline.java:218)
	at me.jellysquid.mods.sodium.client.model.light.smooth.SmoothLightPipeline.calculate(SmoothLightPipeline.java:90)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderer.getVertexLight(BlockRenderer.java:120)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderer.renderQuadList(BlockRenderer.java:105)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderer.renderModel(BlockRenderer.java:82)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$bgl000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:545)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:1570)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.modrinth.methane.client.BrightnessUtil.calculateBrightnessScale(BrightnessUtil.java:27)
	at net.minecraft.class_638.handler$bhm001$methane$MethaneSetCustomLightLevel(class_638.java:2103)

-- Block being rendered --
Details:
	Block: Block{minecraft:cobblestone_slab}[type=top,waterlogged=false]
	Block location: World: (402,32,550), Section: (at 2,0,6 in 25,2,34; chunk contains blocks 400,-64,544 to 415,319,559), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,-64,512 to 511,319,1023)
	Chunk section: RenderSection at chunk (25, 2, 34) from (400, 32, 544) to (415, 47, 559)
	Render context volume: class_3341{minX=398, minY=30, minZ=542, maxX=417, maxY=49, maxZ=561}
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:1570)

-- Uptime --
Details:
	JVM uptime: 100.768s
	Wall uptime: 74.452s
	High-res time: 67.428s
	Client ticks: 1229 ticks / 61.450s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 4
	Reload reason: manual
	Finished: No
	Packs: vanilla, fabric, carpet, cloth-config, continuity, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, indium, libmcdev-fabric, logical_zoom, methane, modmenu, shulkerboxtooltip, sodium, voicechat, worldedit

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 22.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 328470896 bytes (313 MiB) / 725614592 bytes (692 MiB) up to 1073741824 bytes (1024 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 7520U with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 160 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 2.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 512.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.12024.9004
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 5.50
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 5.50
	Memory slot #1 type: Unknown
	Virtual memory max (MiB): 28405.25
	Virtual memory used (MiB): 14322.06
	Swap memory total (MiB): 12800.00
	Swap memory used (MiB): 147.80
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 316287.69, total: 487085.00
	Space in storage for workdir (MiB): available: 316287.69, total: 487085.00
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	Fabric Mods: 
		audioplayer: AudioPlayer 1.21-1.10.2
			admiral: Admiral 0.4.4+1.20.5
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.27+6a6dfa1990
		carpet: Carpet Mod 1.4.147+v240613
		cloth-config: Cloth Config v15 15.0.127
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.5+1.21
		fabric-api: Fabric API 0.100.4+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28+6fc22b99d1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.48+f71b366fd1
			fabric-commands-v0: Fabric Commands (v0) 0.2.65+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.14+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.15+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.3.2+78017270d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.24+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.9+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.52+6573ed8cd1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.2+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.11+6573ed8cd1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.12+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.23+78017270d1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0+0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.67+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.70+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.4+5a8c785ed1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.5+78017270d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.80+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		indium: Indium 1.0.34+mc1.21
		java: Java HotSpot(TM) 64-Bit Server VM 22
		logical_zoom: Logical Zoom 0.0.25
		methane: Methane 3.8.2
			libmcdev-fabric: libmcdev-fabric 1.4.2
		minecraft: Minecraft 1.21
		modmenu: Mod Menu 11.0.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		shulkerboxtooltip: Shulker Box Tooltip 5.0.2+1.21
		sodium: Sodium 0.5.11+mc1.21
		voicechat: Simple Voice Chat 1.21-2.5.17
		worldedit: WorldEdit 7.3.4-beta-01+0452ca2
	Launched Version: 1.21
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: AMD Radeon(TM) Graphics GL version 3.2.0 Core Profile Context 22.20.24.09.231220, ATI Technologies Inc.
	Window size: 1920x991
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fast
	Render Distance: 9/12 chunks
	Resource Packs: vanilla, fabric, carpet, cloth-config, continuity, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, indium, libmcdev-fabric, logical_zoom, methane, modmenu, shulkerboxtooltip, sodium, voicechat, worldedit (incompatible)
	Current Language: en_us
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 8x AMD Ryzen 5 7520U with Radeon Graphics 

### Steps to reproduce

Go to servers, add the mcc island server (ip: play.mccisland.net), join.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by ApplecakeYT** [comment]
# Further Clarification
This issue is due to the particular Minecraft server (MCCisland) utilizing a compression method on their server resource pack. This causes the server resource pack to corrupt, which likely means MultiMC cannot properly read the pack. This error also is replicable with any server resource pack utilizing similar compression methods.
___
_Example Log taken on Vanilla 1.20.6 Instance running on MultiMC 5 - Version 0.7.0-4064 on win32_
```markdown
[13:03:48] [Render thread/ERROR]: Failed to open pack <REDACTED>\MultiMC\instances\1.20.6\.minecraft\downloads\5b39d78a-025c-4fe5-9f43-80326cc333f0\132cc9e0b1781d9601aaeef43a7114b85af49dc9
java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra len size)
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1848) ~[?:?]
	at java.base/java.util.zip.ZipFile$Source.checkAndAddEntry(ZipFile.java:1260) ~[?:?]
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1787) ~[?:?]
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1782) ~[?:?]
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1562) ~[?:?]
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1525) ~[?:?]
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:744) ~[?:?]
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:254) ~[?:?]
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:181) ~[?:?]
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:195) ~[?:?]
	at asy$b.a(SourceFile:172) ~[minecraft-1.20.6-client.jar:?]
	at asy.b(SourceFile:61) ~[minecraft-1.20.6-client.jar:?]
	at asy.a(SourceFile:43) ~[minecraft-1.20.6-client.jar:?]
	at ass.a(SourceFile:28) ~[minecraft-1.20.6-client.jar:?]
	at atx.a(SourceFile:55) ~[minecraft-1.20.6-client.jar:?]
	at grr.a(SourceFile:270) ~[minecraft-1.20.6-client.jar:?]
	at grr.a(SourceFile:296) ~[minecraft-1.20.6-client.jar:?]
	at grv.i(SourceFile:365) ~[minecraft-1.20.6-client.jar:?]
	at grv.e(SourceFile:241) ~[minecraft-1.20.6-client.jar:?]
	at grr$5.a(SourceFile:241) ~[minecraft-1.20.6-client.jar:?]
	at bpm.d(SourceFile:162) [minecraft-1.20.6-client.jar:?]
	at bpq.d(SourceFile:23) [minecraft-1.20.6-client.jar:?]
	at bpm.A(SourceFile:136) [minecraft-1.20.6-client.jar:?]
	at bpm.bA(SourceFile:121) [minecraft-1.20.6-client.jar:?]
	at ffh.c(SourceFile:1275) [minecraft-1.20.6-client.jar:?]
	at ffh.f(SourceFile:888) [minecraft-1.20.6-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:265) [minecraft-1.20.6-client.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by phit** [comment]
1. multimc doesnt read resource packs
2. your log is completely different from the original issue
3. most likely you can delete that file and it will be redownloaded properly
