### ISSUE TITLE
Not loading world after win update

### ISSUE THREAD

**Issue by Triliton** [MultiMC/Launcher#5519]
### Operating System

Windows

### Description of bug

Hello,

It was fine yesterday. Today i had a windows update.
When i launched Multimc it crashed with exit code -1.
I installed an older RTX 3060driver. The game loaded. But when i enter any world, the game crashes with this report:

--- Minecraft Crash Report ----

WARNING: coremods are present:
  Plugin (NotEnoughIDs-1.5.4.4.jar)
  RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.5-1.12.2-anarchy.jar)
  LoadingPlugin (replaymod-1.12.2-2.1.4.jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 10/12/24 2:44 PM
Description: Exception in server tick loop

java.lang.NumberFormatException: For input string: "false"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at drzhark.customspawner.environment.EnvironmentSettings.processEntityConfig(EnvironmentSettings.java:463)
	at drzhark.customspawner.environment.EnvironmentSettings.registerEntity(EnvironmentSettings.java:344)
	at drzhark.customspawner.environment.EnvironmentSettings.initializeEntities(EnvironmentSettings.java:212)
	at drzhark.customspawner.utils.CMSUtils.addWorldEnvironment(CMSUtils.java:143)
	at drzhark.customspawner.EventHooks.onWorldLoad(EventHooks.java:171)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_335_EventHooks_onWorldLoad_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.call(Reflector.java:976)
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1251)
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1237)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:151)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:233)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_401, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1756155368 bytes (1674 MB) / 3999793152 bytes (3814 MB) up to 3999793152 bytes (3814 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 Optifine OptiFine_1.12.2_HD_U_G5 87 mods loaded, 87 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                      | Version                      | Source                                                     | Signature                                |
	|:------- |:----------------------- |:---------------------------- |:---------------------------------------------------------- |:---------------------------------------- |
	| UCHIJAA | minecraft               | 1.12.2                       | minecraft.jar                                              | None                                     |
	| UCHIJAA | mcp                     | 9.42                         | minecraft.jar                                              | None                                     |
	| UCHIJAA | FML                     | 8.0.99.99                    | forge-1.12.2-14.23.4.2705-universal.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | forge                   | 14.23.4.2705                 | forge-1.12.2-14.23.4.2705-universal.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | creativecoredummy       | 1.0.0                        | minecraft.jar                                              | None                                     |
	| UCHIJAA | foamfixcore             | 7.7.4                        | minecraft.jar                                              | None                                     |
	| UCHIJAA | passableleavescore      | 1.0.0                        | minecraft.jar                                              | None                                     |
	| UCHIJAA | replaymod-compat        | 1.12.2-2.1.4                 | replaymod-1.12.2-2.1.4.jar                                 | None                                     |
	| UCHIJAA | replaymod               | 1.12.2-2.1.4                 | replaymod-1.12.2-2.1.4.jar                                 | None                                     |
	| UCHIJAA | replaymod-editor        | 1.12.2-2.1.4                 | replaymod-1.12.2-2.1.4.jar                                 | None                                     |
	| UCHIJAA | replaymod-extras        | 1.12.2-2.1.4                 | replaymod-1.12.2-2.1.4.jar                                 | None                                     |
	| UCHIJAA | replaymod-online        | 1.12.2-2.1.4                 | replaymod-1.12.2-2.1.4.jar                                 | None                                     |
	| UCHIJAA | replaymod-recording     | 1.12.2-2.1.4                 | replaymod-1.12.2-2.1.4.jar                                 | None                                     |
	| UCHIJAA | replaymod-render        | 1.12.2-2.1.4                 | replaymod-1.12.2-2.1.4.jar                                 | None                                     |
	| UCHIJAA | replaymod-replay        | 1.12.2-2.1.4                 | replaymod-1.12.2-2.1.4.jar                                 | None                                     |
	| UCHIJAA | replaymod-simplepathing | 1.12.2-2.1.4                 | replaymod-1.12.2-2.1.4.jar                                 | None                                     |
	| UCHIJAA | creativecore            | 1.10.0                       | CreativeCore_v1.10.16_mc1.12.2.jar                         | None                                     |
	| UCHIJAA | ambientsounds           | 3.0                          | AmbientSounds_v3.1.7_mc1.12.2.jar                          | None                                     |
	| UCHIJAA | aquaculture             | 1.6.8                        | Aquaculture-1.12.2-1.6.8.jar                               | None                                     |
	| UCHIJAA | askir                   | 1.0                          | Askir-1.0-Final.jar                                        | None                                     |
	| UCHIJAA | astikoor                | 1.1.1                        | astikoor_horse-carts-1.1.1.jar                             | None                                     |
	| UCHIJAA | athenaeum               | 1.12.2-1.19.5                | athenaeum-1.12.2-1.19.5.jar                                | None                                     |
	| UCHIJAA | autoplant               | 1.12-1.0.0                   | autoplant-1.12-1.0.0.jar                                   | None                                     |
	| UCHIJAA | backpack                | 3.0.2                        | backpack-3.0.2-1.12.2.jar                                  | None                                     |
	| UCHIJAA | ichunutil               | 7.0.2                        | iChunUtil-1.12.2-7.0.2.jar                                 | None                                     |
	| UCHIJAA | backtools               | 7.0.0                        | BackTools-1.12.2-7.0.0.jar                                 | None                                     |
	| UCHIJAA | baubles                 | 1.5.2                        | Baubles-1.12-1.5.2.jar                                     | None                                     |
	| UCHIJAA | betteranimalsplus       | 7.0.2                        | betteranimalsplus-1.12.2-7.0.2.jar                         | None                                     |
	| UCHIJAA | betterbuilderswands     | 0.11.1                       | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar            | None                                     |
	| UCHIJAA | betterfoliage           | 2.1.10                       | BetterFoliage-MC1.12-2.1.10.jar                            | None                                     |
	| UCHIJAA | bibliocraft             | 2.4.5                        | BiblioCraft[v2.4.5][MC1.12.2].jar                          | None                                     |
	| UCHIJAA | biomesoplenty           | 7.0.1.2418                   | BiomesOPlenty-1.12.2-7.0.1.2418-universal.jar              | None                                     |
	| UCHIJAA | zawa                    | 1.12.2-1.6.0                 | zawa+-+1.6.0+(1.12.2).jar                                  | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| UCHIJAA | bookworm                | 1.12.2-2.2.0                 | bookworm+-+2.2.0+(1.12.2).jar                              | None                                     |
	| UCHIJAA | butterflies             | 1.12.2-1.0.3                 | butterflies-1.12.2-1.0.3.jar                               | None                                     |
	| UCHIJAA | campfire                | 1.2                          | campfire-1.12-v1.2.jar                                     | None                                     |
	| UCHIJAA | chopdownupdated         | 1.12.2-1.2.4                 | chopdownupdated-1.12.2-1.2.4.jar                           | None                                     |
	| UCHIJAA | collective              | 3.0                          | collective-1.12.2-3.0.jar                                  | None                                     |
	| UCHIJAA | conquest                | 3.0.2                        | ConquestReforged-3.0.2-mc1.12.2.jar                        | None                                     |
	| UCHIJAA | blockpalette            | 1.5.0                        | ConquestReforged-3.0.2-mc1.12.2.jar                        | None                                     |
	| UCHIJAA | connect                 | 1.0.3-mc1.12.2-SNAPSHOT      | ConquestReforged-3.0.2-mc1.12.2.jar                        | None                                     |
	| UCHIJAA | craftablesaddles        | 1.3                          | Craftable+Saddles[1.12]-1.3.jar                            | None                                     |
	| UCHIJAA | craftingstation         | @VERSION@                    | craftingstation-0.1.8a.jar                                 | None                                     |
	| UCHIJAA | customspawner           | 3.11.4                       | CustomMobSpawner-3.11.4.jar                                | None                                     |
	| UCHIJAA | customnpcs              | 1.12                         | CustomNPCs_1.12.2(30Jan19).jar                             | None                                     |
	| UCHIJAA | dmp                     | 1.12.0                       | Decoration-Mega-Pack-Mod-1.12.2.jar                        | None                                     |
	| UCHIJAA | durabilityshow          | 5.0.0                        | Durability+Show-1.12-5.0.0.jar                             | None                                     |
	| UCHIJAA | familiarfauna           | 1.0.8                        | FamiliarFauna-1.12.2-1.0.8.jar                             | None                                     |
	| UCHIJAA | fbp                     | 2.4.1                        | FancyBlockParticles-1.12.x-2.4.1.jar                       | None                                     |
	| UCHIJAA | fenceoverhaul           | 1.3.4                        | FenceOverhaul-1.3.4.jar                                    | None                                     |
	| UCHIJAA | foamfix                 | 0.9.5-1.12.2                 | foamfix-0.9.5-1.12.2-anarchy.jar                           | None                                     |
	| UCHIJAA | foodexpansion           | 1.3                          | FoodExpansion1.3.3-1.12.2.jar                              | None                                     |
	| UCHIJAA | fw                      | 1.6.0                        | FullscreenWindowed-1.12-1.6.0.jar                          | None                                     |
	| UCHIJAA | goldinthemtharhills     | 1.0.2                        | goldinthemtharhills-1.0.2.jar                              | None                                     |
	| UCHIJAA | gravestone              | 1.3.1                        | GraveStone-1.12.2-Graves-1.3.1.jar                         | None                                     |
	| UCHIJAA | harvest                 | 1.12-1.2.8-25                | Harvest-1.12-1.2.8-25.jar                                  | None                                     |
	| UCHIJAA | hiddenrecipebook        | 2.0                          | hiddenrecipebook_1.12.2-2.0.jar                            | None                                     |
	| UCHIJAA | llibrary                | 1.7.14                       | llibrary-1.7.14-1.12.2.jar                                 | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJAA | iceandfire              | 1.6.1                        | iceandfire-1.6.1-1.12.2.jar                                | None                                     |
	| UCHIJAA | inventorytweaks         | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar                               | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAA | ironchest               | 1.12.2-7.0.67.844            | ironchest-1.12.2-7.0.72.847.jar                            | None                                     |
	| UCHIJAA | journeymap              | 1.12.2-5.5.2                 | journeymap-1.12.2-5.5.2.jar                                | None                                     |
	| UCHIJAA | jaff                    | 1.7_for_1.12                 | Just-a-Few-Fish-Mod-1.12.jar                               | None                                     |
	| UCHIJAA | mocreatures             | 12.0.5                       | Mo-Creatures-Mod-1.12.2.jar                                | None                                     |
	| UCHIJAA | mobends                 | 1.2.1                        | MoBends_1.12.2-1.2.1-19.12.21.jar                          | None                                     |
	| UCHIJAA | moreplayermodels        | 1.12.2                       | MorePlayerModels_1.12.2(18jan18).jar                       | None                                     |
	| UCHIJAA | nosquid                 | 1.0.0                        | noSquid_1.0.0_1.12.2.jar                                   | None                                     |
	| UCHIJAA | neid                    | 1.5.4.4                      | NotEnoughIDs-1.5.4.4.jar                                   | None                                     |
	| UCHIJAA | paragonia               | 0.40                         | Paragonia-Mod-1.12.2.jar                                   | None                                     |
	| UCHIJAA | quickhotbar             | 1.05                         | quickhotbar_112_1.05.jar                                   | None                                     |
	| UCHIJAA | rustic                  | 1.1.1                        | rustic.jar                                                 | None                                     |
	| UCHIJAA | saltmod                 | 1.12_f                       | SaltyMod_1.12.2_f_.jar                                     | None                                     |
	| UCHIJAA | serverredirect          | 1.3.7                        | ServerRedirect-Forge-MC1.12.2-1.3.7.jar                    | None                                     |
	| UCHIJAA | simplecore              | 1.7.3.4                      | simplecore-1.12.2-1.7.3.4.jar                              | None                                     |
	| UCHIJAA | simpleores              | 1.11.2.0                     | simpleores-1.12.2-1.11.2.0.jar                             | None                                     |
	| UCHIJAA | thaumcraft              | 6.1.BETA23                   | Thaumcraft-1.12.2-6.1.BETA23.jar                           | None                                     |
	| UCHIJAA | variedcommodities       | 1.12.2                       | VariedCommodities_1.12.2(15may18.jar                       | None                                     |
	| UCHIJAA | veining                 | 1.3.1                        | veining-1.3.1-1.12.x.jar                                   | None                                     |
	| UCHIJAA | vomir                   | 1.0.0                        | Vomir.jar                                                  | None                                     |
	| UCHIJAA | watercan                | 1.12.2-1.1.3                 | watercan-1.12.2-1.1.3.jar                                  | None                                     |
	| UCHIJAA | worldedit               | 6.1.10-SNAPSHOT              | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar          | None                                     |
	| UCHIJAA | worldeditcuife2         | 2.1.2-mf-1.12.2-14.23.5.2768 | WorldEditCUIForgeEdition2-2.1.2-mf-1.12.2-14.23.5.2768.jar | None                                     |
	| UCHIJAA | modwinder               | 1.1                          | Ladylib-2.3.jar                                            | None                                     |
	| UCHIJAA | ladylib                 | 2.3                          | Ladylib-2.3.jar                                            | None                                     |
	| UCHIJAA | lumen                   | 0.4.1                        | lumen-Beta+0.4.2.jar                                       | None                                     |
	| UCHIJAA | passableleaves          | 2.0.0                        | PassableLeaves-1.12.2-2.0.0.jar                            | None                                     |
	| UCHIJAA | gravelores              | 1.8                          | gravelores-1.8.jar                                         | None                                     |

	Loaded coremods (and transformers): 
Plugin (NotEnoughIDs-1.5.4.4.jar)
  ru.fewizz.neid.asm.Transformer
RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  pw.prok.realbench.asm.RBTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.5-1.12.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LoadingPlugin (replaymod-1.12.2-2.1.4.jar)
  
llibrary (llibrary-core-1.0.6-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  teamrtg.passableleaves.asm.PassableLeavesTransformer
CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
  
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.0 NVIDIA 561.09
	OpenGlRenderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

### Steps to reproduce

Multimc version 0.7.0

### Suspected cause

Ive disabled dynamic surroundings mod.
Ive tested, but to no prevail. Could the windows update be the root of the cause?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Triliton** [comment]
Windows update log:


OS-bygg 19044.5011 og 19045.5011 Solving security issues

**Comment by Triliton** [comment]
Resolved.
