### ISSUE TITLE
Invalid registry value type detected for PerfOS counters

### ISSUE THREAD

**Issue by CasualFan99** [MultiMC/Launcher#5536]
### Operating System

_Windows 11_

### Description of bug

Instance won't start.

Minecraft v1.20.1

MultiMC v0.7.0-3863 (current as of 12-1-2024

Using Java 17 like the FAQ says to for this version

Running Windows 11

MultiMC version: 0.7.0-3863

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.66]

textures.minecraft.net resolves to:
    [13.107.246.66]

api.mojang.com resolves to:
    [13.107.246.66]

Minecraft folder is:
D:/MultiMC/instances/1.21.3/.minecraft

Java path is:
C:/Users/mcent/AppData/Local/Programs/Eclipse Adoptium/jre-17.0.13.11-hotspot/bin/javaw.exe

Checking Java version...
Java is version 17.0.13, using 64-bit architecture, from Eclipse Adoptium.

Main Class:
  net.minecraft.client.main.Main

Native path:
  D:/MultiMC/instances/1.21.3/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  D:/MultiMC/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
  D:/MultiMC/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
  D:/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  D:/MultiMC/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
  D:/MultiMC/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar
  D:/MultiMC/libraries/com/mojang/authlib/4.0.43/authlib-4.0.43.jar
  D:/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  D:/MultiMC/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar
  D:/MultiMC/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  D:/MultiMC/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  D:/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  D:/MultiMC/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  D:/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  D:/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  D:/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  D:/MultiMC/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
  D:/MultiMC/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
  D:/MultiMC/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
  D:/MultiMC/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
  D:/MultiMC/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
  D:/MultiMC/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
  D:/MultiMC/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
  D:/MultiMC/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
  D:/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
  D:/MultiMC/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
  D:/MultiMC/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
  D:/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  D:/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  D:/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  D:/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  D:/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
  D:/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  D:/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  D:/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  D:/MultiMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  D:/MultiMC/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
  D:/MultiMC/libraries/com/mojang/minecraft/1.20.1/minecraft-1.20.1-client.jar

Native libraries:

Mods:
  [❌] controllable-forge-1.20.1-0.20.3.jar.disabled (disabled)
  [❌] doom-neo-1.20.1-7.0.13.jar.disabled (disabled)
  [❌] mcdoomfix-1.0.jar.disabled (disabled)
  [❌] OptiFine_1.20.1_HD_U_I6.jar.disabled (disabled)

Params:
  --username AlexMcEntire --version 1.20.1 --gameDir D:/MultiMC/instances/1.21.3/.minecraft --assetsDir D:/MultiMC/assets --assetIndex 5 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType msa --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 12140

Using onesix launcher.

[15:37:59] [main/WARN]: Invalid registry value type detected for PerfOS counters. Should be REG_DWORD. Ignoring: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance\Disable Performance Counters.
[15:38:01] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 124 milliseconds
[15:38:02] [Render thread/INFO]: [STDERR]: Failed to start Minecraft:
[15:38:02] [Render thread/INFO]: [STDERR]: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
[15:38:02] [Render thread/INFO]: [STDERR]: 	at ab.a(SourceFile:66)
[15:38:02] [Render thread/INFO]: [STDERR]: 	at enn.a(SourceFile:2424)
[15:38:02] [Render thread/INFO]: [STDERR]: 	at enn.a(SourceFile:2419)
[15:38:02] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:220)
[15:38:02] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:38:02] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:38:02] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:38:02] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[15:38:02] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
[15:38:02] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
[15:38:02] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[15:38:02] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[15:38:02] [Render thread/INFO]: [STDERR]: Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: org/lwjgl/system/MemoryUtil [in thread "Render thread"]
[15:38:02] [Render thread/INFO]: [STDERR]: 	at ehh.<clinit>(SourceFile:8)
[15:38:02] [Render thread/INFO]: [STDERR]: 	at eie.<init>(SourceFile:48)
[15:38:02] [Render thread/INFO]: [STDERR]: 	at eil.<init>(SourceFile:19)
[15:38:02] [Render thread/INFO]: [STDERR]: 	at eil.<init>(SourceFile:23)
[15:38:02] [Render thread/INFO]: [STDERR]: 	at eil.<clinit>(SourceFile:11)
[15:38:02] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(SourceFile:50)
[15:38:02] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:208)
[15:38:02] [Render thread/INFO]: [STDERR]: 	... 8 more
[15:38:02] [Render thread/INFO]: [STDOUT]: Exiting with -1
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 01 Dec 2024 15:38:06 -0700

### Steps to reproduce

Launch instance under the above circumstances.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
Try giving in more RAM and see if that helps.

**Comment by phit** [comment]
remake that instance or change its mc version to something else and then back, it was created with an older version of multimc or another launcher
