### ISSUE TITLE
instance doenst want to open

### ISSUE THREAD

**Issue by git-user69** [MultiMC/Launcher#5542]
im new to MultiMc and i might of messed anything up. so if any of you might be kind enough to help thanks. im using only one mod which should support this version. but if you want to ask me about anything. feel free.

MultiMC version: 0.7.0-3863

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.45]

textures.minecraft.net resolves to:
    [13.107.246.45]

api.mojang.com resolves to:
    [13.107.246.45]

Minecraft folder is:
F:/gmaes/mmc-develop-win32/MultiMC/instances/1.19.2/.minecraft

Java path is:
C:/Program Files/Java/jdk-23/bin/javaw.exe

Checking Java version...
Java is version 23.0.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  F:/gmaes/mmc-develop-win32/MultiMC/instances/1.19.2/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.0/log4j-slf4j18-impl-2.17.0.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/io/netty/netty-common/4.1.77.Final/netty-common-4.1.77.Final.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/io/netty/netty-buffer/4.1.77.Final/netty-buffer-4.1.77.Final.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/io/netty/netty-codec/4.1.77.Final/netty-codec-4.1.77.Final.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/io/netty/netty-handler/4.1.77.Final/netty-handler-4.1.77.Final.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/io/netty/netty-resolver/4.1.77.Final/netty-resolver-4.1.77.Final.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/io/netty/netty-transport/4.1.77.Final/netty-transport-4.1.77.Final.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/io/netty/netty-transport-native-unix-common/4.1.77.Final/netty-transport-native-unix-common-4.1.77.Final.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/io/netty/netty-transport-classes-epoll/4.1.77.Final/netty-transport-classes-epoll-4.1.77.Final.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/com/mojang/authlib/3.11.49/authlib-3.11.49.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.17.0/log4j-api-2.17.0.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.17.0/log4j-core-2.17.0.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/com/mojang/text2speech/1.16.7/text2speech-1.16.7.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc5/ForgeWrapper-mmc5.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/cpw/mods/securejarhandler/2.1.4/securejarhandler-2.1.4.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/net/minecraftforge/eventbus/6.0.3/eventbus-6.0.3.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/net/minecraftforge/forgespi/6.0.0/forgespi-6.0.0.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/cpw/mods/modlauncher/10.0.8/modlauncher-10.0.8.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/net/minecraftforge/JarJarSelector/0.3.16/JarJarSelector-0.3.16.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/net/minecraftforge/JarJarMetadata/0.3.16/JarJarMetadata-0.3.16.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/net/minecraftforge/JarJarFileSystems/0.3.16/JarJarFileSystems-0.3.16.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/net/minecraftforge/fmlloader/1.19.2-43.3.5/fmlloader-1.19.2-43.3.5.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/com/mojang/minecraft/1.19.2/minecraft-1.19.2-client.jar

Native libraries:
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-windows.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-windows.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-windows.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-windows.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-windows.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-windows.jar
  F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-windows.jar

Mods:
  [✔️] EMC.jar

Params:
  --username _Noob_Player_ --version 1.19.2 --gameDir F:/gmaes/mmc-develop-win32/MultiMC/instances/1.19.2/.minecraft --assetsDir F:/gmaes/mmc-develop-win32/MultiMC/assets --assetIndex 1.19 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType msa --versionType release --launchTarget forgeclient --fml.forgeVersion 43.3.5 --fml.mcVersion 1.19.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20220805.130853

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms410m, -Xmx4100m, -Duser.language=en]

Minecraft process ID: 13988

Using onesix launcher.

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2024-12-11 15:18:04,811 main WARN Advanced terminal features are not available in this environment
[15:18:04] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, _Noob_Player_, --version, 1.19.2, --gameDir, F:/gmaes/mmc-develop-win32/MultiMC/instances/1.19.2/.minecraft, --assetsDir, F:/gmaes/mmc-develop-win32/MultiMC/assets, --assetIndex, 1.19, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 43.3.5, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853, --width, 854, --height, 480]
[15:18:04] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 23.0.1 by Oracle Corporation; OS Windows 11 arch amd64 version 10.0
[15:18:05] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/F:/gmaes/mmc-develop-win32/MultiMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23118!/ Service=ModLauncher Env=CLIENT
[15:18:05] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file F:\gmaes\mmc-develop-win32\MultiMC\libraries\net\minecraftforge\fmlcore\1.19.2-43.3.5\fmlcore-1.19.2-43.3.5.jar is missing mods.toml file
[15:18:05] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file F:\gmaes\mmc-develop-win32\MultiMC\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.3.5\javafmllanguage-1.19.2-43.3.5.jar is missing mods.toml file
[15:18:05] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file F:\gmaes\mmc-develop-win32\MultiMC\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.3.5\lowcodelanguage-1.19.2-43.3.5.jar is missing mods.toml file
[15:18:05] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file F:\gmaes\mmc-develop-win32\MultiMC\libraries\net\minecraftforge\mclanguage\1.19.2-43.3.5\mclanguage-1.19.2-43.3.5.jar is missing mods.toml file
[15:18:05] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
[15:18:06] [main/ERROR] [mixin/]: Mixin config mixins.emc.json does not specify "minVersion" property
[15:18:06] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [me.deftware.launch.MixinConnector]
[15:18:06] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.19.2, --gameDir, F:\gmaes\mmc-develop-win32\MultiMC\instances\1.19.2\.minecraft, --assetsDir, F:\gmaes\mmc-develop-win32\MultiMC\assets, --uuid, <PROFILE ID>, --username, _Noob_Player_, --assetIndex, 1.19, --accessToken, ????????, --userType, msa, --versionType, release, --width, 854, --height, 480]
[15:18:06] [main/WARN] [mixin/]: Error loading class: net/minecraft/world/item/ItemStack (java.lang.IllegalArgumentException: Unsupported class file major version 67)
[15:18:06] [main/WARN] [mixin/]: @Mixin target net.minecraft.world.item.ItemStack was not found mixins.emc.json:item.MixinItemStack
[15:18:06] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 67)
[15:18:06] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 67)
[15:18:06] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 67)
[15:18:06] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 67)
[15:18:06] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 67)
[15:18:06] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 67)
[15:18:06] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 67)
[15:18:06] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 67)
[15:18:06] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 67)
[15:18:06] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 67)
[15:18:06] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 67)
[15:18:06] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 67)
[15:18:06] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 67)
[15:18:06] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 67)
[15:18:06] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 67)
[15:18:06] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 67)
[15:18:06] [main/WARN] [mixin/]: Error loading class: java/lang/Boolean (java.lang.IllegalArgumentException: Unsupported class file major version 67)
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.3.5/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	... 16 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.chat.MutableComponent.m_237204_(MutableComponent.java:29)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.chat.Component.m_237113_(Component.java:436)
	at TRANSFORMER/emc@0.0NONE/me.deftware.client.framework.message.Message.<clinit>(Message.java:17)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.chat.Component.m_237115_(Component.java:440)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.commands.BrigadierExceptions.<clinit>(BrigadierExceptions.java:24)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.SharedConstants.<clinit>(SharedConstants.java:217)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:55)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 19 more
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: java.lang.Boolean
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:754)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:739)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:310)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 41 more
Exiting with -1
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
MultiMC: Log upload triggered at: 11 Dec 2024 15:22:09 +0100

**Comment by phit** [comment]
hi please refer to https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
