### ISSUE TITLE
Minecraft exited with exitcode 0

### ISSUE THREAD

**Issue by Ripperino** [MultiMC/Launcher#652]
Will not load ever since I installed the latest forge.

```
MultiMC version: 0.4.5

Minecraft folder is:
C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/instances/RPG/minecraft

Java path is:
C:/Program Files/Java/jre7/bin/javaw.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2048m, -Xmx4096m, -XX:PermSize=254m, -Duser.language=en, -jar, C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/jars/NewLaunch.jar]

Using onesix launcher.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/instances/RPG/natives

Traits:
  []

Libraries:
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.2.1240/forge-1.7.10-10.13.2.1240-universal.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/net/minecraft/launchwrapper/1.11/launchwrapper-1.11.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/com/google/guava/guava/16.0/guava-16.0.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/org/apache/commons/commons-lang3/3.2.1/commons-lang3-3.2.1.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/com/mojang/authlib/1.5.16/authlib-1.5.16.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/versions/1.7.10/1.7.10.jar

Params:
  [--username, <PROFILE NAME>, --version, 1.7.10, --gameDir, C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/instances/RPG/minecraft, --assetsDir, C:/Users/Pedro/Desktop/Minecraft Items/MultiMC/assets, --assetIndex, 1.7.10, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {}, --userType, mojang, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]

Window size: 854 x 480

Preparing native libraries...
Extracting twitch-platform-5.16-natives-windows-64.jar
Extracting twitch-external-platform-4.5-natives-windows-64.jar
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

[17:51:42] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[17:51:42] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: cpw.mods.fml.common.launcher.FMLTweaker
    at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_67]
    at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_67]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_67]
    at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_67]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_67]
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.7.0_67]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_67]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_67]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_67]
    at java.lang.Class.forName0(Native Method) ~[?:1.7.0_67]
    at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_67]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_67]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_67]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_67]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_67]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Minecraft exited with exitcode 0.
```

**Comment by Josifekjj** [comment]
i have the same issue

**Comment by Josifekjj** [comment]
but forge change doesnt work

**Comment by Josifekjj** [comment]
log : https://paste.ee/p/Y3slx
